Common Alogrithm: HashTable Class Reference
HashTable Class Reference
#include <hash_table.h>
Public Member Functions
void Add (HashObject *object)
Brief function description here.
bool Exists (const std::string key)
Brief function description here.
const std::string Get (const std::string key)
Brief function description here.
HashTable (const HashObject &)
HashTable (const int size)
Brief function description here.
HashTable & operator= (const HashTable &)
void PringDebug ()
void Remove (const std::string key)
Brief function description here.
virtual ~HashTable ()
Private Member Functions
int Hash (const std::string key)
Brief function description here.
Private Attributes
HashObject * data_
int size_
Detailed Description
Definition at line 9 of file hash_table.h.
Constructor & Destructor Documentation
HashTable() [1/2]
HashTable (const int size) explicit
Brief function description here.
Detailed description
Parameters
size Parameter description
Returns
Return parameter description
Definition at line 13 of file hash_table.cc.
{
     size_ = size;
     data_ = new HashObject[size];
     assert(data_ != nullptr);
     for (int i = 0; i < size; ++i) {
         data_[i].SetKey(HashObject::GetNullKey());
     }
 }
References HashTable::data_, HashObject::GetNullKey(), HashObject::SetKey(), and HashTable::size_.
HashTable() [2/2]
HashTable (const HashObject &)
Definition at line 19 of file hash_table.h.
 {};
~HashTable()
~HashTable () virtual
Definition at line 23 of file hash_table.cc.
 {delete[] data_;};
References HashTable::data_.
Member Function Documentation
Add()
void Add (HashObject * object)
Brief function description here.
Detailed description
Returns
Return parameter description
Definition at line 31 of file hash_table.cc.
{
     int index = Hash(object->Getkey());
     int original_index = index;
     int dummyIndex = -1;
     bool found = false;
     while (data_[index].Getkey() != HashObject::GetNullKey()) {
         if (data_[index].Getkey() == object->Getkey()) {
             found = true;
             break;
         } else if (data_[index].Getkey() == HashObject::GetDummyKey()) {
             dummyIndex = index;
         }
         index = (index + 1) % size_;
         if (index == original_index) {
             return;
         }
     }
     if (!found && dummyIndex != -1) {
         index = dummyIndex;
     }
     data_[index].SetKey(object->Getkey());
     data_[index].SetValue(object->GetValue());
 }
References HashTable::data_, HashObject::GetDummyKey(), HashObject::Getkey(), HashObject::GetNullKey(), HashObject::GetValue(), HashTable::Hash(), HashObject::SetKey(), HashObject::SetValue(), and HashTable::size_.
Referenced by test_add_exists(), test_get(), test_probing(), and test_remove().
Exists()
bool Exists (const std::string key)
Brief function description here.
Detailed description
Returns
Return parameter description
Definition at line 84 of file hash_table.cc.
{
     int index = Hash(key);
     int original_index = index;
     bool found = false;
     while (data_[index].Getkey() != HashObject::GetNullKey()) {
         if (data_[index].Getkey() == key) {
             found = true;
             break;
         }
         index = (index + 1) % size_;
         // break out of while loop while traveling one cycle
         if (index == original_index) {
             break;
         }
     }
     return found;
 }
References HashTable::data_, HashObject::GetNullKey(), HashTable::Hash(), and HashTable::size_.
Referenced by test_add_exists(), test_probing(), and test_remove().
Get()
const std::string Get (const std::string key)
Brief function description here.
Detailed description
Returns
Return parameter description
Definition at line 111 of file hash_table.cc.
{
     int index = Hash(key);
     int original_index = index;
     while (data_[index].Getkey() != HashObject::GetNullKey()) {
         if (data_[index].Getkey() == key) {
             return data_[index].GetValue();
         }
         index = (index + 1) % size_;
         if (index == original_index) {
             break;
         }
     }
     return NULL;
 }
References HashTable::data_, HashObject::GetNullKey(), HashObject::GetValue(), HashTable::Hash(), and HashTable::size_.
Referenced by test_get().
Hash()
int Hash (const std::string key) private
Brief function description here.
Detailed description
Returns
Return parameter description
Definition at line 67 of file hash_table.cc.
{
     int hash = 0;
     int key_length = static_cast<int>(key.length());
     for (int i = 0; i < key_length; ++i) {
         hash = hash * 31 + key[i];
     }
     return abs(hash % size_);
 }
References string::length(), and HashTable::size_.
Referenced by HashTable::Add(), HashTable::Exists(), HashTable::Get(), and HashTable::Remove().
operator=()
HashTable& operator= (const HashTable &)
PringDebug()
void PringDebug ()
Definition at line 155 of file hash_table.cc.
{
     for (int i = 0; i < size_; ++i) {
         std::cout << i << ": " << data_[i].Getkey() << ": " << data_[i].GetValue() << std::endl;
     }
     std::cout << "-----------------------------\n" << std::endl;
 }
References HashTable::data_, std::endl(), HashObject::Getkey(), HashObject::GetValue(), and HashTable::size_.
Referenced by test_probing(), and test_remove().
Remove()
void Remove (const std::string key)
Brief function description here.
Detailed description
Returns
Return parameter description
Definition at line 136 of file hash_table.cc.
{
     int index = Hash(key);
     int original_index = index;
     while (data_[index].Getkey() != HashObject::GetNullKey()) {
         if (data_[index].Getkey() == key) {
             data_[index].SetKey(HashObject::GetDummyKey());
             data_[index].SetValue("");
             break;
         }
         index = (index + 1) % size_;
         if (index == original_index) {
             break;
         }
     }
 }
References HashTable::data_, HashObject::GetDummyKey(), HashObject::GetNullKey(), HashTable::Hash(), HashObject::SetKey(), HashObject::SetValue(), and HashTable::size_.
Referenced by test_remove().
Member Data Documentation
data_
HashObject* data_ private
Definition at line 13 of file hash_table.h.
Referenced by HashTable::Add(), HashTable::Exists(), HashTable::Get(), HashTable::HashTable(), HashTable::PringDebug(), HashTable::Remove(), and HashTable::~HashTable().
size_
int size_ private
Definition at line 12 of file hash_table.h.
Referenced by HashTable::Add(), HashTable::Exists(), HashTable::Get(), HashTable::Hash(), HashTable::HashTable(), HashTable::PringDebug(), and HashTable::Remove().