Common Alogrithm: GraphRepresentation Class Reference
GraphRepresentation Class Reference
#include <graph_representation.h>
Public Member Functions
virtual void AddEdge (const int source, const int destination)
virtual void BFS ()
virtual bool ContainsCycle ()
virtual void DFS ()
GraphRepresentation ()
GraphRepresentation (const GraphRepresentation &)
GraphRepresentation (const string graph_type)
virtual void PrintDebug ()
virtual ~GraphRepresentation ()
Static Public Member Functions
static unique_ptr< common::GraphRepresentation > GetRepresentation (const string representation_type, const string graph_type)
Public Attributes
string type
int vertices
Static Public Attributes
static const string kGraphTypeDirected
static const string kGraphTypeUndirected
static const string kRepresentationTypeList
static const string kRepresentationTypeMatrix
Detailed Description
Constructor & Destructor Documentation
GraphRepresentation() [1/3]
GraphRepresentation ()
 {};
GraphRepresentation() [2/3]
GraphRepresentation (const string graph_type)
{
     vertices = 0;
     if (graph_type == kGraphTypeDirected) {
         type = kGraphTypeDirected;
     } else if (graph_type == kGraphTypeDirected) {
         type = kGraphTypeUndirected;
     }
 }
GraphRepresentation() [3/3]
GraphRepresentation (const GraphRepresentation &)
 {};
~GraphRepresentation()
virtual ~GraphRepresentation () virtual
 {};
Member Function Documentation
AddEdge()
virtual void AddEdge (const int source, const int destination) virtual
Reimplemented in GraphRepresentationList.
 {};
Referenced by GraphDirected::AddEdge().
BFS()
virtual void BFS () virtual
Reimplemented in GraphRepresentationList.
 {};
Referenced by GraphDirected::BFS().
ContainsCycle()
virtual bool ContainsCycle () virtual
Reimplemented in GraphRepresentationList.
 { return 0; } ;
DFS()
virtual void DFS () virtual
Reimplemented in GraphRepresentationList.
 {};
Referenced by GraphDirected::DFS().
GetRepresentation()
unique_ptr< GraphRepresentation > GetRepresentation (const string representation_type, const string graph_type) static
{
     if (representation_type == kRepresentationTypeList) {
         return unique_ptr<GraphRepresentation>(new GraphRepresentationList(graph_type));
     } else {
         std::cout << "Graph Representation type not supported." << std::endl;
         exit(EXIT_FAILURE);
     }
 }
References std::endl(), and std::exit().
Referenced by GraphDirected::GraphDirected().
PrintDebug()
virtual void PrintDebug () virtual
Reimplemented in GraphRepresentationList.
 {};
Referenced by GraphDirected::PrintDebug().
Member Data Documentation
kGraphTypeDirected
const string kGraphTypeDirected static
Referenced by GraphDirected::GraphDirected().
kGraphTypeUndirected
const string kGraphTypeUndirected static
kRepresentationTypeList
const string kRepresentationTypeList static
Referenced by main().
kRepresentationTypeMatrix
const string kRepresentationTypeMatrix static
type
string type
vertices
int vertices
Referenced by GraphDirected::GetVertexCount().