Common Alogrithm: common::GraphRepresentation::GetRepresentation
GetRepresentation()
unique_ptr< GraphRepresentation > GetRepresentation (const string representation_type, const string graph_type) static inherited
{
     if (representation_type == kRepresentationTypeList) {
         return unique_ptr<GraphRepresentation>(new GraphRepresentationList(graph_type));
     } else {
         std::cout << "Graph Representation type not supported." << std::endl;
         exit(EXIT_FAILURE);
     }
 }
References std::endl(), and std::exit().
Referenced by GraphDirected::GraphDirected().