Common Alogrithm: common::HashTable::Remove
Remove()
void Remove (const std::string key)
Brief function description here.
Detailed description
Returns
Return parameter description
{
     int index = Hash(key);
     int original_index = index;
     while (data_[index].Getkey() != HashObject::GetNullKey()) {
         if (data_[index].Getkey() == key) {
             data_[index].SetKey(HashObject::GetDummyKey());
             data_[index].SetValue("");
             break;
         }
         index = (index + 1) % size_;
         if (index == original_index) {
             break;
         }
     }
 }
References HashTable::data_, HashObject::GetDummyKey(), HashObject::GetNullKey(), HashTable::Hash(), HashObject::SetKey(), HashObject::SetValue(), and HashTable::size_.
Referenced by test_remove().