Common Alogrithm: common::HashTable::PringDebug
PringDebug()
void PringDebug ()
{
     for (int i = 0; i < size_; ++i) {
         std::cout << i << ": " << data_[i].Getkey() << ": " << data_[i].GetValue() << std::endl;
     }
     std::cout << "-----------------------------\n" << std::endl;
 }
References HashTable::data_, std::endl(), HashObject::Getkey(), HashObject::GetValue(), and HashTable::size_.
Referenced by test_probing(), and test_remove().