Common Alogrithm: common::HashTable::Exists
Exists()
bool Exists (const std::string key)
Brief function description here.
Detailed description
Returns
Return parameter description
{
     int index = Hash(key);
     int original_index = index;
     bool found = false;
     while (data_[index].Getkey() != HashObject::GetNullKey()) {
         if (data_[index].Getkey() == key) {
             found = true;
             break;
         }
         index = (index + 1) % size_;
         // break out of while loop while traveling one cycle
         if (index == original_index) {
             break;
         }
     }
     return found;
 }
References HashTable::data_, HashObject::GetNullKey(), HashTable::Hash(), and HashTable::size_.
Referenced by test_add_exists(), test_probing(), and test_remove().