Common Alogrithm: common::HashTable::Add
Add()
void Add (HashObject * object)
Brief function description here.
Detailed description
Returns
Return parameter description
{
     int index = Hash(object->Getkey());
     int original_index = index;
     int dummyIndex = -1;
     bool found = false;
     while (data_[index].Getkey() != HashObject::GetNullKey()) {
         if (data_[index].Getkey() == object->Getkey()) {
             found = true;
             break;
         } else if (data_[index].Getkey() == HashObject::GetDummyKey()) {
             dummyIndex = index;
         }
         index = (index + 1) % size_;
         if (index == original_index) {
             return;
         }
     }
     if (!found && dummyIndex != -1) {
         index = dummyIndex;
     }
     data_[index].SetKey(object->Getkey());
     data_[index].SetValue(object->GetValue());
 }
References HashTable::data_, HashObject::GetDummyKey(), HashObject::Getkey(), HashObject::GetNullKey(), HashObject::GetValue(), HashTable::Hash(), HashObject::SetKey(), HashObject::SetValue(), and HashTable::size_.
Referenced by test_add_exists(), test_get(), test_probing(), and test_remove().