Common Alogrithm: lib/googletest/test/gtest_throw_on_failure_test_.cc File Reference
gtest_throw_on_failure_test_.cc File Reference
(d4ab02d08ceed19dab4276c86042b1520529304b)
#include "gtest/gtest.h"
#include <stdio.h>
#include <stdlib.h>
#include <exception>
Functions
int main (int argc, char **argv)
void TerminateHandler ()
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 53 of file gtest_throw_on_failure_test_.cc.
{
 #if GTEST_HAS_EXCEPTIONS
   std::set_terminate(&TerminateHandler);
 #endif
   testing::InitGoogleTest(&argc, argv);
   // We want to ensure that people can use Google Test assertions in
   // other testing frameworks, as long as they initialize Google Test
   // properly and set the throw-on-failure mode.  Therefore, we don't
   // use Google Test's constructs for defining and running tests
   // (e.g. TEST and RUN_ALL_TESTS) here.
   // In the throw-on-failure mode with exceptions disabled, this
   // assertion will cause the program to exit with a non-zero code.
   EXPECT_EQ(2, 3);
   // When not in the throw-on-failure mode, the control will reach
   // here.
   return 0;
 }
References EXPECT_EQ, testing::InitGoogleTest(), std::set_terminate(), and TerminateHandler().
TerminateHandler()
void TerminateHandler ()
Definition at line 47 of file gtest_throw_on_failure_test_.cc.
{
   fprintf(stderr, "%s\n", "Unhandled C++ exception terminating the program.");
   fflush(NULL);
   exit(1);
 }
Referenced by main().