Common Alogrithm: ElectricKettle Class Reference
ElectricKettle Class Reference
Public Member Functions
void boil ()
void plugIn (USASocketInterface *supply)
Private Attributes
USASocketInterface * power
Detailed Description
Definition at line 70 of file main.cc.
Member Function Documentation
boil()
void boil ()
Definition at line 80 of file main.cc.
         {
             if (power->voltage() > 110)
             {
                 std::cout << "Kettle is on fire!" << std::endl;
                 return;
             }
             if (power->live() == 1 && power->neutral() == -1)
             {
                 std::cout << "Coffee time!" << std::endl;
             }
         }
References std::endl(), USASocketInterface::live(), USASocketInterface::neutral(), power, and USASocketInterface::voltage().
Referenced by main().
plugIn()
void plugIn (USASocketInterface * supply)
Definition at line 75 of file main.cc.
         {
             power = supply;
         }
References power.
Referenced by main().
Member Data Documentation
power
USASocketInterface* power private
Definition at line 72 of file main.cc.
Referenced by boil(), and plugIn().