Common Alogrithm: testing::anonymous_namespace{gtest.cc}::IsSubstringImpl
IsSubstringImpl()
AssertionResult testing::anonymous_namespace{gtest.cc}::IsSubstringImpl (bool expected_to_be_substring, const char * needle_expr, const char * haystack_expr, const StringType & needle, const StringType & haystack)
{
   if (IsSubstringPred(needle, haystack) == expected_to_be_substring)
     return AssertionSuccess();
   const bool is_wide_string = sizeof(needle[0]) > 1;
   const char* const begin_string_quote = is_wide_string ? "L\"" : "\"";
   return AssertionFailure()
       << "Value of: " << needle_expr << "\n"
       << "  Actual: " << begin_string_quote << needle << "\"\n"
       << "Expected: " << (expected_to_be_substring ? "" : "not ")
       << "a substring of " << haystack_expr << "\n"
       << "Which is: " << begin_string_quote << haystack << "\"";
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), and testing::anonymous_namespace{gtest.cc}::IsSubstringPred().
Referenced by testing::IsNotSubstring(), and testing::IsSubstring().