Common Alogrithm: GraphRepresentationList Class Reference
GraphRepresentationList Class Reference
Brief class description.
#include <graph_representation.h>
Public Member Functions
void AddEdge (const int source, const int destination)
void BFS ()
Brief function description here.
bool ContainsCycle ()
void DFS ()
Brief function description here.
GraphRepresentationList (const string graph_type)
void PrintDebug ()
virtual ~GraphRepresentationList ()
Static Public Member Functions
static unique_ptr< common::GraphRepresentation > GetRepresentation (const string representation_type, const string graph_type)
Public Attributes
vector< vector< int > > adjust_list
string type
int vertices
Static Public Attributes
static const string kGraphTypeDirected
static const string kGraphTypeUndirected
static const string kRepresentationTypeList
static const string kRepresentationTypeMatrix
Detailed Description
Brief class description.
Detailed description
Definition at line 47 of file graph_representation.h.
Constructor & Destructor Documentation
GraphRepresentationList()
GraphRepresentationList (const string graph_type)
Definition at line 50 of file graph_representation.h.
 : GraphRepresentation(graph_type) {};
~GraphRepresentationList()
virtual ~GraphRepresentationList () virtual
Definition at line 51 of file graph_representation.h.
 {};
Member Function Documentation
AddEdge()
void AddEdge (const int source, const int destination) virtual
Reimplemented from GraphRepresentation.
Definition at line 34 of file graph_representation.cc.
{
     /* static_cast can be used to convert from an int to a char. However, the resulting char may not have enough bits to hold the entire int vaule */
     unsigned long source_index = static_cast<unsigned long>(source);
     int size_required = max(source, destination) + 1;
     while (adjust_list.size() < size_required) {
         adjust_list.push_back(vector<int>());
     }
     /* Operator[] does not do range checking. Accessing element not presenting in vector silently leads to undefined behaviors; .ar() member function does range checking and throws an expception when you are tring to access nonexisting element.*/
     auto adjacent_vertices = adjust_list.at(source_index);
     std::vector<int>::iterator it = find(adjacent_vertices.begin(), adjacent_vertices.end(), destination);
     if (it == adjacent_vertices.end()) {
         adjust_list.at(source_index).push_back(destination);
     }
     vertices = static_cast<int>(adjust_list.size());
 }
References vector< T >::end(), std::find(), and std::max().
BFS()
void BFS () virtual
Brief function description here.
Detailed description: Breadth First Search is traversing algorithm where you should start traversing from a selected node (source or parent node) and traverse the graph layerwise thus exploring the neighbour nodes. refer to https://www.hackerearth.com/practice/algorithms/graphs/breadth-first-search/practice-problems/
Returns
Return parameter description
Reimplemented from GraphRepresentation.
Definition at line 64 of file graph_representation.cc.
{
     std::vector<int> components;
     const int NULL_PARENT = -1;
     // creates an array on the heap that has a lifetime for as long as you need it
     int *parents = new int [vertices];
     assert(parents);
     /* Assigns vaule to the frist n elements of sequence pointed by first */
     fill_n(parents, vertices, NULL_PARENT);
     std::cout << "\n----------------\nBFS: " << std::endl;
     for (unsigned long i = 0; i < adjust_list.size(); ++i) {
         if (parents[i] == NULL_PARENT) {
             components.push_back(i);
         }
         std::queue<int> to_visit;
         to_visit.push(i);
         while(!to_visit.empty()){
             int vertex = to_visit.front();
             to_visit.pop();
             std::cout << vertex << " ";
             for (unsigned long n = 0; n < adjust_list[vertex].size(); ++n) {
                 int neighbor = adjust_list[vertex].at(n);
                 if (parents[neighbor] == NULL_PARENT) {
                     parents[neighbor] = vertex;
                     to_visit.push(neighbor);
                 }
             }
         }
     }
     std::cout << "\n\n Parents: "<< std::endl;
     for (int i = 0; i < vertices; ++i) {
         std::cout << i << " : " << parents[i] << std::endl;
     }
     std::cout << "\n Components: " << components.size() << std::endl;
     for (auto it = components.begin();  it != components.end() ; ++it) {
         std::cout << *it << std::endl;
     }
     std::cout << std::endl;
     delete [] parents;
 }
References vector< T >::begin(), queue< T >::empty(), vector< T >::end(), std::endl(), std::fill_n(), queue< T >::front(), testing::internal::posix::n, queue< T >::pop(), queue< T >::push(), vector< T >::push_back(), and vector< T >::size().
ContainsCycle()
bool ContainsCycle () virtual
Reimplemented from GraphRepresentation.
Definition at line 174 of file graph_representation.cc.
{
     bool contains_cycle = false;
     const int STATUS_NEW = 0;
     const int STATUS_STARTED = 1;
     const int STATUS_FINISHED = 2;
     for (unsigned long i = 0; i < adjust_list.size(); ++i) {
         int * nodes = new int [vertices]();
         assert(nodes);
         fill_n(nodes, vertices, STATUS_NEW);
         std::stack<int> to_visit; // LIFO
         to_visit.push(i);
         while (!(to_visit.empty() || contains_cycle)) {
             int vertex = to_visit.top();
             to_visit.pop();
             if (nodes[vertex] == STATUS_STARTED) {
                 nodes[vertex] = STATUS_FINISHED;
                 continue;
             }
             nodes[vertex] = STATUS_STARTED;
             // push back onto stack so we can tell when vertex is finished.
             to_visit.push(vertex);
             for (unsigned long n = 0; n < adjust_list[vertex].size(); ++n) {
                 int neighbor = adjust_list[vertex].at(n);
                 if (nodes[neighbor] == STATUS_NEW) {
                     to_visit.push(neighbor);
                 } else if (nodes[neighbor] == STATUS_STARTED) {
                     contains_cycle = true;
                     break;
                 } else if (nodes[neighbor] == STATUS_FINISHED) {
                     // skip, already seen
                 }
             }
         }
         delete[] nodes;
     }
     return contains_cycle;
 }
References stack< T >::empty(), std::fill_n(), testing::internal::posix::n, stack< T >::pop(), stack< T >::push(), and stack< T >::top().
DFS()
void DFS () virtual
Brief function description here.
Detailed description: Depth First Search is a recursive algorithm that uses the idea of backtracking. It involves searches of all the nodes by going ahead if possible, else by backtracking. refer to https://www.hackerearth.com/practice/algorithms/graphs/depth-first-search/tutorial/
Returns
Return parameter description
Reimplemented from GraphRepresentation.
Definition at line 123 of file graph_representation.cc.
{
     std::vector<int> components;
     const int NULL_PARENT = -1;
     int *parents = new int [vertices]();
     assert(parents);
     fill_n(parents, vertices, NULL_PARENT);
     std::cout << "\n----------------\nDFS: " << std::endl;
     for (unsigned long i = 0; i < adjust_list.size(); ++i) {
         if (parents[i] == NULL_PARENT) {
             components.push_back(i);
         }
         std::stack<int> to_visit;
         to_visit.push(i);
         while (!to_visit.empty()) {
             int vertex = to_visit.top();
             to_visit.pop();
             std::cout << vertex << " ";
             for (unsigned long n = 0; n < adjust_list[vertex].size(); n++) {
                 int neighbor = adjust_list[vertex].at(n);
                 if (parents[neighbor] == NULL_PARENT) {
                     parents[neighbor] = vertex;
                     to_visit.push(neighbor);
                 }
             }
         }
     }
     std::cout << "\n\nParents: " << std::endl;
     for (int i = 0; i < vertices; ++i) {
         std::cout << i << " : " << parents[i] << std::endl;
     }
     std::cout << "\n Components: " << components.size() << std::endl;
     for (auto it = components.begin();  it != components.end() ; ++it) {
         std::cout << *it << std::endl;
     }
     std::cout << std::endl;
     delete [] parents;
 }
References vector< T >::begin(), stack< T >::empty(), vector< T >::end(), std::endl(), std::fill_n(), testing::internal::posix::n, stack< T >::pop(), stack< T >::push(), vector< T >::push_back(), vector< T >::size(), and stack< T >::top().
GetRepresentation()
unique_ptr< GraphRepresentation > GetRepresentation (const string representation_type, const string graph_type) static inherited
Definition at line 15 of file graph_representation.cc.
{
     if (representation_type == kRepresentationTypeList) {
         return unique_ptr<GraphRepresentation>(new GraphRepresentationList(graph_type));
     } else {
         std::cout << "Graph Representation type not supported." << std::endl;
         exit(EXIT_FAILURE);
     }
 }
References std::endl(), and std::exit().
Referenced by GraphDirected::GraphDirected().
PrintDebug()
void PrintDebug () virtual
Reimplemented from GraphRepresentation.
Definition at line 221 of file graph_representation.cc.
{
     std::cout << "Adjacency List:" << std::endl;
     std::cout << "Vertices: " << vertices << std::endl;
     for (unsigned long i = 0;  i < adjust_list.size(); ++ i) {
         std::cout << i << ":"  << std::endl;
         for (unsigned long j = 0; j < adjust_list[i].size(); ++j) {
             std::cout << " " << adjust_list[i].at(j) << std::endl;
         }
         std::cout << std::endl;
     }
 }
References std::endl().
Member Data Documentation
adjust_list
vector<vector<int> > adjust_list
Definition at line 59 of file graph_representation.h.
kGraphTypeDirected
const string kGraphTypeDirected static inherited
Definition at line 26 of file graph_representation.h.
Referenced by GraphDirected::GraphDirected().
kGraphTypeUndirected
const string kGraphTypeUndirected static inherited
Definition at line 27 of file graph_representation.h.
kRepresentationTypeList
const string kRepresentationTypeList static inherited
Definition at line 24 of file graph_representation.h.
Referenced by main().
kRepresentationTypeMatrix
const string kRepresentationTypeMatrix static inherited
Definition at line 25 of file graph_representation.h.
type
string type inherited
Definition at line 37 of file graph_representation.h.
vertices
int vertices inherited
Definition at line 38 of file graph_representation.h.
Referenced by GraphDirected::GetVertexCount().