Common Alogrithm: testing::Message Class Reference
testing::Message Class Reference
#include <gtest-message.h>
Public Member Functions
std::string GetString () const
Message ()
Message (const char *str)
Message (const Message &msg)
Message & operator<< (BasicNarrowIoManip val)
Message & operator<< (bool b)
template<typename T >
Message & operator<< (const T &val)
Message & operator<< (const wchar_t *wide_c_str)
template<typename T >
Message & operator<< (T *const &pointer)
Message & operator<< (wchar_t *wide_c_str)
Package Functions
void operator= (const Message &)
Package Attributes
__pad0__:scoped_ptr< ::std::stringstream> ss_
Private Types
typedef std::ostream &(* BasicNarrowIoManip) (std::ostream &)
Detailed Description
Member Typedef Documentation
BasicNarrowIoManip
typedef std::ostream&(* testing::Message::BasicNarrowIoManip) (std::ostream &) private
Constructor & Destructor Documentation
Message() [1/3]
testing::Message::Message ()
                  : ss_(new ::std::stringstream) {
   // By default, we want there to be enough precision when printing
   // a double to a Message.
   *ss_ << std::setprecision(std::numeric_limits<double>::digits10 + 2);
 }
References std::setprecision().
Message() [2/3]
testing::Message::Message (const Message & msg)
                               : ss_(new ::std::stringstream) {  // NOLINT
     *ss_ << msg.GetString();
   }
References GetString().
Message() [3/3]
testing::Message::Message (const char * str) explicit
                                     : ss_(new ::std::stringstream) {
     *ss_ << str;
   }
Member Function Documentation
GetString()
std::string testing::Message::GetString () const
{
   return internal::StringStreamToString(ss_.get());
 }
References testing::internal::StringStreamToString().
Referenced by testing::UnitTest::AddTestPartResult(), testing::AssertionResult::AppendMessage(), testing::internal::AppendUserMessage(), testing::internal::XmlUnitTestResultPrinter::EscapeXml(), testing::internal::FlagToEnvVar(), testing::FormatWordList(), testing::internal::GetBoolAssertionFailureMessage(), Message(), testing::operator<<(), testing::internal::ParseInt32(), testing::Test::RecordProperty(), testing::internal::ShouldShard(), and testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
operator<<() [1/6]
Message& testing::Message::operator<< (BasicNarrowIoManip val)
{
     *ss_ << val;
     return *this;
   }
operator<<() [2/6]
Message& testing::Message::operator<< (bool b)
{
     return *this << (b ? "true" : "false");
   }
operator<<() [3/6]
template<typename T > Message& testing::Message::operator<< (const T & val)
{
     // Some libraries overload << for STL containers.  These
     // overloads are defined in the global namespace instead of ::std.
     //
     // C++'s symbol lookup rule (i.e. Koenig lookup) says that these
     // overloads are visible in either the std namespace or the global
     // namespace, but not other namespaces, including the testing
     // namespace which Google Test's Message class is in.
     //
     // To allow STL containers (and other types that has a << operator
     // defined in the global namespace) to be used in Google Test
     // assertions, testing::Message must access the custom << operator
     // from the global namespace.  With this using declaration,
     // overloads of << defined in the global namespace and those
     // visible via Koenig lookup are both exposed in this function.
     using ::operator <<;
     *ss_ << val;
     return *this;
   }
operator<<() [4/6]
Message & testing::Message::operator<< (const wchar_t * wide_c_str)
{
   return *this << internal::String::ShowWideCString(wide_c_str);
 }
References testing::internal::String::ShowWideCString().
operator<<() [5/6]
template<typename T > Message& testing::Message::operator<< (T *const & pointer)
                                                  {  // NOLINT
     if (pointer == NULL) {
       *ss_ << "(null)";
     } else {
       *ss_ << pointer;
     }
     return *this;
   }
operator<<() [6/6]
Message & testing::Message::operator<< (wchar_t * wide_c_str)
{
   return *this << internal::String::ShowWideCString(wide_c_str);
 }
References testing::internal::String::ShowWideCString().
operator=()
void testing::Message::operator= (const Message &) package
Member Data Documentation
__pad0__
testing::Message::__pad0__ package