Common Alogrithm: priority_queue/main.cc File Reference
main.cc File Reference
(d27395f313f54f5e8c11541cc0295a12a238d400)
#include <iostream>
#include "./priority_queue.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 4 of file main.cc.
 {
     common::PriorityQueue priorityqueue(10);
     assert (priorityqueue.IsEmpty());
     assert (priorityqueue.GetSize() == 0);
     priorityqueue.Insert(10,"Hello");
     priorityqueue.Insert(300,"c++");
     priorityqueue.Insert(444,"Taiwan");
     common::PQElement* maxqueue = priorityqueue.ExtractMax();
     std::cout << "First priority: " << maxqueue->key << " : value: " << maxqueue->value << std::endl;
     std::cout <<  "======================" << std::endl;
     priorityqueue.PrintDebug();
     std::cout <<  "======================" << std::endl;
     int to_sort[10] = {613, 55, 8721, 472, 94, 72, 74, 8, 61, 356};
     common::heapify(to_sort, 10);
     common::print_heap(to_sort, 10);
     return 0;
 }
References std::endl(), PriorityQueue::ExtractMax(), PriorityQueue::GetSize(), common::heapify(), PriorityQueue::Insert(), PriorityQueue::IsEmpty(), PriorityQueueElement::key, common::print_heap(), PriorityQueue::PrintDebug(), and PriorityQueueElement::value.