Common Alogrithm: QueueLinkedList< T > Class Template Reference
QueueLinkedList< T > Class Template Reference
#include <queue_linked_list.h>
Public Member Functions
const T Dequeue ()
bool Empty () const
void Enqueue (T value)
QueueLinkedList & operator= (const QueueLinkedList &)=delete
void PrintDebug () const
QueueLinkedList ()
QueueLinkedList (const QueueLinkedList &)=delete
virtual ~QueueLinkedList ()
Private Attributes
ListElement< T > * head
ListElement< T > * tail
Detailed Description
template<class T>
class common::QueueLinkedList< T >
Definition at line 10 of file queue_linked_list.h.
Constructor & Destructor Documentation
QueueLinkedList() [1/2]
QueueLinkedList ()
Definition at line 17 of file queue_linked_list.h.
 : head(nullptr), tail(nullptr) {} ;
QueueLinkedList() [2/2]
QueueLinkedList (const QueueLinkedList< T > &) delete
~QueueLinkedList()
~QueueLinkedList virtual
Definition at line 9 of file queue_linked_list.cc.
 {
     ListElement<T>* current = head;
     ListElement<T>* temp = nullptr;
     while (current) {
         temp = current;
         current = current->GetNext();
         delete temp;
     }
 };
References ListElement< T >::GetNext().
Member Function Documentation
Dequeue()
const T Dequeue
Definition at line 42 of file queue_linked_list.cc.
 {
     if(Empty()) {
         std::cerr << "Queue is empty. Cannot dequeue." << std::endl;
         exit(EXIT_FAILURE);
     }
     T value = head->GetData();
     ListElement<T>* temp = head;
     if (head == tail)
         tail = head->GetNext();
     head = head->GetNext();
     delete temp;
     return value;
 }
References std::endl(), and ListElement< T >::GetNext().
Referenced by googletest::TEST_F().
Empty()
bool Empty
Definition at line 66 of file queue_linked_list.cc.
 {
     return head == nullptr;
 }
Referenced by googletest::TEST_F().
Enqueue()
void Enqueue (T value)
Definition at line 25 of file queue_linked_list.cc.
 {
     auto * p = new ListElement<T>(value);
     p->SetData(value);
     p->SetNext(nullptr);
     if(Empty()) {
         head = tail = p;
     } else {
         head->SetNext(p);
         tail = p;
     }
 }
Referenced by googletest::TEST_F().
operator=()
QueueLinkedList& operator= (const QueueLinkedList< T > &) delete
PrintDebug()
void PrintDebug
Definition at line 72 of file queue_linked_list.cc.
 {
     ListElement<T>* current = head;
     std::cout << "Queue elements: " << std::endl;
     while (current) {
         std::cout << current->GetData() << " < ";
         current = current->GetNext();
     }
     std::cout << "" << std::endl;
 }
References std::endl(), ListElement< T >::GetData(), and ListElement< T >::GetNext().
Member Data Documentation
head
ListElement<T>* head private
Definition at line 13 of file queue_linked_list.h.
tail
ListElement<T>* tail private
Definition at line 14 of file queue_linked_list.h.