# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.6/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shi-rongliu/Documents/GitHub/cplusplus_practice-/practice_common_alogrithm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shi-rongliu/Documents/GitHub/cplusplus_practice-/practice_common_alogrithm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shi-rongliu/Documents/GitHub/cplusplus_practice-/practice_common_alogrithm/CMakeFiles /Users/shi-rongliu/Documents/GitHub/cplusplus_practice-/practice_common_alogrithm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shi-rongliu/Documents/GitHub/cplusplus_practice-/practice_common_alogrithm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named binary_search

# Build rule for target.
binary_search: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary_search
.PHONY : binary_search

# fast build rule for target.
binary_search/fast:
	$(MAKE) $(MAKESILENT) -f binary_search/CMakeFiles/binary_search.dir/build.make binary_search/CMakeFiles/binary_search.dir/build
.PHONY : binary_search/fast

#=============================================================================
# Target rules for targets named graphs

# Build rule for target.
graphs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphs
.PHONY : graphs

# fast build rule for target.
graphs/fast:
	$(MAKE) $(MAKESILENT) -f graphs/CMakeFiles/graphs.dir/build.make graphs/CMakeFiles/graphs.dir/build
.PHONY : graphs/fast

#=============================================================================
# Target rules for targets named graphs_lib

# Build rule for target.
graphs_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphs_lib
.PHONY : graphs_lib

# fast build rule for target.
graphs_lib/fast:
	$(MAKE) $(MAKESILENT) -f graphs/src/CMakeFiles/graphs_lib.dir/build.make graphs/src/CMakeFiles/graphs_lib.dir/build
.PHONY : graphs_lib/fast

#=============================================================================
# Target rules for targets named hash_table

# Build rule for target.
hash_table: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hash_table
.PHONY : hash_table

# fast build rule for target.
hash_table/fast:
	$(MAKE) $(MAKESILENT) -f hash_table/CMakeFiles/hash_table.dir/build.make hash_table/CMakeFiles/hash_table.dir/build
.PHONY : hash_table/fast

#=============================================================================
# Target rules for targets named array

# Build rule for target.
array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 array
.PHONY : array

# fast build rule for target.
array/fast:
	$(MAKE) $(MAKESILENT) -f array/CMakeFiles/array.dir/build.make array/CMakeFiles/array.dir/build
.PHONY : array/fast

#=============================================================================
# Target rules for targets named facade_pattern

# Build rule for target.
facade_pattern: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 facade_pattern
.PHONY : facade_pattern

# fast build rule for target.
facade_pattern/fast:
	$(MAKE) $(MAKESILENT) -f design_pattern/facade_pattern/CMakeFiles/facade_pattern.dir/build.make design_pattern/facade_pattern/CMakeFiles/facade_pattern.dir/build
.PHONY : facade_pattern/fast

#=============================================================================
# Target rules for targets named adapter_pattern

# Build rule for target.
adapter_pattern: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 adapter_pattern
.PHONY : adapter_pattern

# fast build rule for target.
adapter_pattern/fast:
	$(MAKE) $(MAKESILENT) -f design_pattern/adapter_pattern/CMakeFiles/adapter_pattern.dir/build.make design_pattern/adapter_pattern/CMakeFiles/adapter_pattern.dir/build
.PHONY : adapter_pattern/fast

#=============================================================================
# Target rules for targets named bridge_pattern

# Build rule for target.
bridge_pattern: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bridge_pattern
.PHONY : bridge_pattern

# fast build rule for target.
bridge_pattern/fast:
	$(MAKE) $(MAKESILENT) -f design_pattern/bridge_pattern/CMakeFiles/bridge_pattern.dir/build.make design_pattern/bridge_pattern/CMakeFiles/bridge_pattern.dir/build
.PHONY : bridge_pattern/fast

#=============================================================================
# Target rules for targets named strategy_pattern

# Build rule for target.
strategy_pattern: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strategy_pattern
.PHONY : strategy_pattern

# fast build rule for target.
strategy_pattern/fast:
	$(MAKE) $(MAKESILENT) -f design_pattern/strategy_pattern/CMakeFiles/strategy_pattern.dir/build.make design_pattern/strategy_pattern/CMakeFiles/strategy_pattern.dir/build
.PHONY : strategy_pattern/fast

#=============================================================================
# Target rules for targets named singleton_pattern

# Build rule for target.
singleton_pattern: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 singleton_pattern
.PHONY : singleton_pattern

# fast build rule for target.
singleton_pattern/fast:
	$(MAKE) $(MAKESILENT) -f design_pattern/singleton_pattern/CMakeFiles/singleton_pattern.dir/build.make design_pattern/singleton_pattern/CMakeFiles/singleton_pattern.dir/build
.PHONY : singleton_pattern/fast

#=============================================================================
# Target rules for targets named linkedlists_run

# Build rule for target.
linkedlists_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linkedlists_run
.PHONY : linkedlists_run

# fast build rule for target.
linkedlists_run/fast:
	$(MAKE) $(MAKESILENT) -f linked_list/CMakeFiles/linkedlists_run.dir/build.make linked_list/CMakeFiles/linkedlists_run.dir/build
.PHONY : linkedlists_run/fast

#=============================================================================
# Target rules for targets named linkedlists_lib

# Build rule for target.
linkedlists_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linkedlists_lib
.PHONY : linkedlists_lib

# fast build rule for target.
linkedlists_lib/fast:
	$(MAKE) $(MAKESILENT) -f linked_list/src/CMakeFiles/linkedlists_lib.dir/build.make linked_list/src/CMakeFiles/linkedlists_lib.dir/build
.PHONY : linkedlists_lib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... adapter_pattern"
	@echo "... array"
	@echo "... binary_search"
	@echo "... bridge_pattern"
	@echo "... facade_pattern"
	@echo "... graphs"
	@echo "... graphs_lib"
	@echo "... hash_table"
	@echo "... linkedlists_lib"
	@echo "... linkedlists_run"
	@echo "... singleton_pattern"
	@echo "... strategy_pattern"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

