Common Alogrithm: lib/googletest/test/gtest-param-test_test.cc File Reference
gtest-param-test_test.cc File Reference
(d4ab02d08ceed19dab4276c86042b1520529304b)
#include "gtest/gtest.h"
Functions
int main (int argc, char **argv)
TEST (CompileTest, CombineIsDefinedOnlyWhenGtestHasParamTestIsDefined)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 1036 of file gtest-param-test_test.cc.
{
 #if GTEST_HAS_PARAM_TEST
   // Used in TestGenerationTest test case.
   AddGlobalTestEnvironment(TestGenerationTest::Environment::Instance());
   // Used in GeneratorEvaluationTest test case. Tests that the updated value
   // will be picked up for instantiating tests in GeneratorEvaluationTest.
   GeneratorEvaluationTest::set_param_value(1);
 #endif  // GTEST_HAS_PARAM_TEST
   ::testing::InitGoogleTest(&argc, argv);
 #if GTEST_HAS_PARAM_TEST
   // Used in GeneratorEvaluationTest test case. Tests that value updated
   // here will NOT be used for instantiating tests in
   // GeneratorEvaluationTest.
   GeneratorEvaluationTest::set_param_value(2);
 #endif  // GTEST_HAS_PARAM_TEST
   return RUN_ALL_TESTS();
 }
References testing::AddGlobalTestEnvironment(), testing::InitGoogleTest(), and RUN_ALL_TESTS().
TEST()
TEST (CompileTest , CombineIsDefinedOnlyWhenGtestHasParamTestIsDefined)
Definition at line 1030 of file gtest-param-test_test.cc.
{
 #if GTEST_HAS_COMBINE && !GTEST_HAS_PARAM_TEST
   FAIL() << "GTEST_HAS_COMBINE is defined while GTEST_HAS_PARAM_TEST is not\n"
 #endif
 }
References FAIL.