Common Alogrithm: GraphDirected Class Reference
GraphDirected Class Reference
#include <graph_directed.h>
Public Member Functions
void AddEdge (const int source, const int destination)
void BFS ()
bool ContainsCycle ()
void DFS ()
const int GetVertexCount ()
GraphDirected ()
GraphDirected (const string)
void PrintDebug ()
virtual ~GraphDirected ()
Public Attributes
unique_ptr< common::GraphRepresentation > representation
int vertices
Detailed Description
Definition at line 10 of file graph_directed.h.
Constructor & Destructor Documentation
GraphDirected() [1/2]
GraphDirected ()
Definition at line 15 of file graph_directed.h.
 {};
GraphDirected() [2/2]
GraphDirected (const string representation_type)
Definition at line 6 of file graph_directed.cc.
{
     representation = GraphRepresentation::GetRepresentation(representation_type, GraphRepresentation::kGraphTypeDirected);
 }
References GraphRepresentation::GetRepresentation(), GraphRepresentation::kGraphTypeDirected, and Graph::representation.
~GraphDirected()
virtual ~GraphDirected () virtual
Definition at line 17 of file graph_directed.h.
 {};
Member Function Documentation
AddEdge()
void AddEdge (const int source, const int destination) virtual
Reimplemented from Graph.
Definition at line 18 of file graph_directed.cc.
{
     representation->AddEdge(source, destination);
 }
References GraphRepresentation::AddEdge(), and Graph::representation.
BFS()
void BFS () virtual
Reimplemented from Graph.
Definition at line 10 of file graph_directed.cc.
{
    representation->BFS();
 }
References GraphRepresentation::BFS(), and Graph::representation.
ContainsCycle()
bool ContainsCycle ()
Definition at line 23 of file graph_directed.h.
 { return 0;};
DFS()
void DFS () virtual
Reimplemented from Graph.
Definition at line 14 of file graph_directed.cc.
{
     representation->DFS();
 }
References GraphRepresentation::DFS(), and Graph::representation.
GetVertexCount()
const int GetVertexCount ()
Definition at line 26 of file graph_directed.cc.
{
     return representation->vertices;
 }
References Graph::representation, and GraphRepresentation::vertices.
PrintDebug()
void PrintDebug () virtual
Reimplemented from Graph.
Definition at line 22 of file graph_directed.cc.
{
     representation->PrintDebug();
 }
References GraphRepresentation::PrintDebug(), and Graph::representation.
Member Data Documentation
representation
unique_ptr<common::GraphRepresentation> representation inherited
Definition at line 26 of file graph.h.
Referenced by GraphDirected::AddEdge(), GraphDirected::BFS(), GraphDirected::DFS(), GraphDirected::GetVertexCount(), GraphDirected::GraphDirected(), and GraphDirected::PrintDebug().
vertices
int vertices inherited
Definition at line 27 of file graph.h.