Common Alogrithm: BinarySearch Class Reference
BinarySearch Class Reference
#include <binary_search.h>
Public Member Functions
BinarySearch ()
BSTNode * BinarySearchGetNewNode (int value)
void DeleteTree (BSTNode *node)
BSTNode * DeleteValue (BSTNode *node, int value)
int GetHeight (BSTNode *node)
Maximum Depth of Binary tree.
int GetMax (BSTNode *node)
BSTNode * GetMaxNode (BSTNode *node)
int GetMin (BSTNode *node)
BSTNode * GetMinNode (BSTNode *node)
BSTNode * GetNewNode (int value)
BSTNode * Insert (BSTNode *node, int value)
bool IsBetween (BSTNode *node, int min, int max)
bool IsBinarySearchTree (BSTNode *node)
void PrintBFS (BSTNode *node)
void PrintInOrder (BSTNode *node)
bool Search (BSTNode *node, int value)
virtual ~BinarySearch ()
Detailed Description
Definition at line 17 of file binary_search.h.
Constructor & Destructor Documentation
BinarySearch()
BinarySearch ()
Definition at line 23 of file binary_search.h.
 {};
~BinarySearch()
virtual ~BinarySearch () virtual
Definition at line 24 of file binary_search.h.
 {};
Member Function Documentation
BinarySearchGetNewNode()
BSTNode* BinarySearchGetNewNode (int value)
DeleteTree()
void DeleteTree (BSTNode * node)
Definition at line 106 of file binary_search.cc.
{
     if (node == nullptr) return;
     if (node->left != nullptr) DeleteTree(node->left);
     if (node->right != nullptr) DeleteTree(node->right);
     delete node;
 }
References BSTNode::left, and BSTNode::right.
DeleteValue()
BSTNode * DeleteValue (BSTNode * node, int value)
Definition at line 115 of file binary_search.cc.
{
     if (node == nullptr) return nullptr;
     if (value < node->data)
         node->left = DeleteValue(node->left, value);
     else if (value > node->data)
         node->right = DeleteValue(node->right, value);
     else {
         // Delete the matching value
         if (node->left == nullptr && node->right == nullptr) {
             delete node;
             node = nullptr;
         } else if (node->left == nullptr) {
             BSTNode* temp = node;
             node = node->right;
             delete temp;
         } else if (node->right == nullptr) {
             BSTNode* temp = node;
             node = node->left;
             delete temp;
         } else {
             BSTNode* temp = GetMinNode(node->right);
             node->data = temp->data; // replace min data in the right node with deleted value
             node->right = DeleteValue(node->right, temp->data); // reconstruct binary tree
         }
     }
     return node;
 }
References BSTNode::data, BinarySearch::GetMinNode(), BSTNode::left, and BSTNode::right.
GetHeight()
int GetHeight (BSTNode * node)
Maximum Depth of Binary tree.
Given the root of a binary tree, return its maximum depth. A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.
Returns
maximum depth
Definition at line 100 of file binary_search.cc.
{
     if (node == nullptr) return 0;
     return 1 + std::max(GetHeight(node->left), GetHeight(node->right));
 }
References BSTNode::left, std::max(), and BSTNode::right.
GetMax()
int GetMax (BSTNode * node)
Definition at line 84 of file binary_search.cc.
{
     if (node == nullptr) return -1;
     if (node->right == nullptr)
         return node->data;
     return GetMax(node->right);
 }
References BSTNode::data, and BSTNode::right.
GetMaxNode()
BSTNode * GetMaxNode (BSTNode * node)
Definition at line 75 of file binary_search.cc.
{
     if (node == nullptr) return nullptr;
     if (node->right == nullptr)
         return node;
     return GetMaxNode(node->right);
 }
References BSTNode::right.
GetMin()
int GetMin (BSTNode * node)
Definition at line 66 of file binary_search.cc.
{
     if (node == nullptr) return -1;
     if (node->left == nullptr)
         return node->data;
     return GetMin(node->left);
 }
References BSTNode::data, and BSTNode::left.
GetMinNode()
BSTNode * GetMinNode (BSTNode * node)
Definition at line 57 of file binary_search.cc.
{
     if (node == nullptr) return nullptr;
     if(node->left == nullptr)
         return node;
     return GetMinNode(node->left);
 }
References BSTNode::left.
Referenced by BinarySearch::DeleteValue().
GetNewNode()
BSTNode * GetNewNode (int value)
Definition at line 5 of file binary_search.cc.
{
     BSTNode* node = new BSTNode;
     node->data = value;
     node->left = nullptr;
     node->right = nullptr;
     return node;
 }
References BSTNode::data, BSTNode::left, and BSTNode::right.
Referenced by BinarySearch::Insert().
Insert()
BSTNode * Insert (BSTNode * node, int value)
Definition at line 14 of file binary_search.cc.
{
     // First Node
     if (node == nullptr) {
         node = GetNewNode(value);
         return node;
     }
     if (value < node->data) {
         node->left = Insert(node->left, value);
     } else if (value > node->data) {
         node->right = Insert(node->right, value);
     }
     return node;
 }
References BSTNode::data, BinarySearch::GetNewNode(), BSTNode::left, and BSTNode::right.
IsBetween()
bool IsBetween (BSTNode * node, int min, int max)
Definition at line 46 of file binary_search.cc.
{
     if (node == nullptr) return true;
     if (node->data > min && node->data < max &&
         IsBetween(node->left, min, node->data) &&
         IsBetween(node->right, node->data, max))
         return true;
     else
         return false;
 }
References BSTNode::data, BSTNode::left, and BSTNode::right.
Referenced by BinarySearch::IsBinarySearchTree().
IsBinarySearchTree()
bool IsBinarySearchTree (BSTNode * node)
Definition at line 42 of file binary_search.cc.
{
     return IsBetween(node, INT_MIN, INT_MAX);
 }
References BinarySearch::IsBetween().
PrintBFS()
void PrintBFS (BSTNode * node)
Definition at line 145 of file binary_search.cc.
{
     std::queue<BSTNode*> node_queue;
     BSTNode* current;
     node_queue.push(node);
     while (! node_queue.empty()) {
         current = node_queue.front();
         node_queue.pop();
         if (current != nullptr) {
             std::cout << current->data << " ";
             if (current->left != nullptr) node_queue.push(current->left);
             if (current->right != nullptr) node_queue.push(current->right);
         }
     }
 }
References BSTNode::data, queue< T >::empty(), queue< T >::front(), BSTNode::left, queue< T >::pop(), queue< T >::push(), and BSTNode::right.
PrintInOrder()
void PrintInOrder (BSTNode * node)
Definition at line 163 of file binary_search.cc.
{
     if (node == nullptr) return;
     if (node->left != nullptr) PrintInOrder(node->left);
     std::cout << node->data << " ";
     if (node->right != nullptr) PrintInOrder(node->right);
 }
References BSTNode::data, BSTNode::left, and BSTNode::right.
Search()
bool Search (BSTNode * node, int value)
Definition at line 30 of file binary_search.cc.
{
     if (node == nullptr) return false;
     if (value < node->data) {
         return Search(node->left, value);
     } else if (value > node->data) {
         return Search(node->right, value);
     } else {
         return true;
     }
 }
References BSTNode::data, BSTNode::left, and BSTNode::right.