Common Alogrithm: common::GraphRepresentationList::ContainsCycle
ContainsCycle()
bool ContainsCycle () virtual
Reimplemented from GraphRepresentation.
{
     bool contains_cycle = false;
     const int STATUS_NEW = 0;
     const int STATUS_STARTED = 1;
     const int STATUS_FINISHED = 2;
     for (unsigned long i = 0; i < adjust_list.size(); ++i) {
         int * nodes = new int [vertices]();
         assert(nodes);
         fill_n(nodes, vertices, STATUS_NEW);
         std::stack<int> to_visit; // LIFO
         to_visit.push(i);
         while (!(to_visit.empty() || contains_cycle)) {
             int vertex = to_visit.top();
             to_visit.pop();
             if (nodes[vertex] == STATUS_STARTED) {
                 nodes[vertex] = STATUS_FINISHED;
                 continue;
             }
             nodes[vertex] = STATUS_STARTED;
             // push back onto stack so we can tell when vertex is finished.
             to_visit.push(vertex);
             for (unsigned long n = 0; n < adjust_list[vertex].size(); ++n) {
                 int neighbor = adjust_list[vertex].at(n);
                 if (nodes[neighbor] == STATUS_NEW) {
                     to_visit.push(neighbor);
                 } else if (nodes[neighbor] == STATUS_STARTED) {
                     contains_cycle = true;
                     break;
                 } else if (nodes[neighbor] == STATUS_FINISHED) {
                     // skip, already seen
                 }
             }
         }
         delete[] nodes;
     }
     return contains_cycle;
 }
References stack< T >::empty(), std::fill_n(), stack< T >::pop(), stack< T >::push(), and stack< T >::top().