Common Alogrithm: common::GraphRepresentationList::DFS
DFS()
void DFS () virtual
Brief function description here.
Detailed description: Depth First Search is a recursive algorithm that uses the idea of backtracking. It involves searches of all the nodes by going ahead if possible, else by backtracking. refer to https://www.hackerearth.com/practice/algorithms/graphs/depth-first-search/tutorial/
Returns
Return parameter description
Reimplemented from GraphRepresentation.
{
     std::vector<int> components;
     const int NULL_PARENT = -1;
     int *parents = new int [vertices]();
     assert(parents);
     fill_n(parents, vertices, NULL_PARENT);
     std::cout << "\n----------------\nDFS: " << std::endl;
     for (unsigned long i = 0; i < adjust_list.size(); ++i) {
         if (parents[i] == NULL_PARENT) {
             components.push_back(i);
         }
         std::stack<int> to_visit;
         to_visit.push(i);
         while (!to_visit.empty()) {
             int vertex = to_visit.top();
             to_visit.pop();
             std::cout << vertex << " ";
             for (unsigned long n = 0; n < adjust_list[vertex].size(); n++) {
                 int neighbor = adjust_list[vertex].at(n);
                 if (parents[neighbor] == NULL_PARENT) {
                     parents[neighbor] = vertex;
                     to_visit.push(neighbor);
                 }
             }
         }
     }
     std::cout << "\n\nParents: " << std::endl;
     for (int i = 0; i < vertices; ++i) {
         std::cout << i << " : " << parents[i] << std::endl;
     }
     std::cout << "\n Components: " << components.size() << std::endl;
     for (auto it = components.begin();  it != components.end() ; ++it) {
         std::cout << *it << std::endl;
     }
     std::cout << std::endl;
     delete [] parents;
 }
References vector< T >::begin(), stack< T >::empty(), vector< T >::end(), std::endl(), std::fill_n(), stack< T >::pop(), stack< T >::push(), vector< T >::push_back(), vector< T >::size(), and stack< T >::top().