Common Alogrithm: common::GraphRepresentationList::BFS
BFS()
void BFS () virtual
Brief function description here.
Detailed description: Breadth First Search is traversing algorithm where you should start traversing from a selected node (source or parent node) and traverse the graph layerwise thus exploring the neighbour nodes. refer to https://www.hackerearth.com/practice/algorithms/graphs/breadth-first-search/practice-problems/
Returns
Return parameter description
Reimplemented from GraphRepresentation.
{
     std::vector<int> components;
     const int NULL_PARENT = -1;
     // creates an array on the heap that has a lifetime for as long as you need it
     int *parents = new int [vertices];
     assert(parents);
     /* Assigns vaule to the frist n elements of sequence pointed by first */
     fill_n(parents, vertices, NULL_PARENT);
     std::cout << "\n----------------\nBFS: " << std::endl;
     for (unsigned long i = 0; i < adjust_list.size(); ++i) {
         if (parents[i] == NULL_PARENT) {
             components.push_back(i);
         }
         std::queue<int> to_visit;
         to_visit.push(i);
         while(!to_visit.empty()){
             int vertex = to_visit.front();
             to_visit.pop();
             std::cout << vertex << " ";
             for (unsigned long n = 0; n < adjust_list[vertex].size(); ++n) {
                 int neighbor = adjust_list[vertex].at(n);
                 if (parents[neighbor] == NULL_PARENT) {
                     parents[neighbor] = vertex;
                     to_visit.push(neighbor);
                 }
             }
         }
     }
     std::cout << "\n\n Parents: "<< std::endl;
     for (int i = 0; i < vertices; ++i) {
         std::cout << i << " : " << parents[i] << std::endl;
     }
     std::cout << "\n Components: " << components.size() << std::endl;
     for (auto it = components.begin();  it != components.end() ; ++it) {
         std::cout << *it << std::endl;
     }
     std::cout << std::endl;
     delete [] parents;
 }
References vector< T >::begin(), queue< T >::empty(), vector< T >::end(), std::endl(), std::fill_n(), queue< T >::front(), queue< T >::pop(), queue< T >::push(), vector< T >::push_back(), and vector< T >::size().