Common Alogrithm: common::GraphRepresentationList::AddEdge
AddEdge()
void AddEdge (const int source, const int destination) virtual
Reimplemented from GraphRepresentation.
{
     /* static_cast can be used to convert from an int to a char. However, the resulting char may not have enough bits to hold the entire int vaule */
     unsigned long source_index = static_cast<unsigned long>(source);
     int size_required = max(source, destination) + 1;
     while (adjust_list.size() < size_required) {
         adjust_list.push_back(vector<int>());
     }
     /* Operator[] does not do range checking. Accessing element not presenting in vector silently leads to undefined behaviors; .ar() member function does range checking and throws an expception when you are tring to access nonexisting element.*/
     auto adjacent_vertices = adjust_list.at(source_index);
     std::vector<int>::iterator it = find(adjacent_vertices.begin(), adjacent_vertices.end(), destination);
     if (it == adjacent_vertices.end()) {
         adjust_list.at(source_index).push_back(destination);
     }
     vertices = static_cast<int>(adjust_list.size());
 }
References vector< T >::end(), std::find(), and std::max().