Common Alogrithm: lib/googletest/test/gtest_pred_impl_unittest.cc File Reference
gtest_pred_impl_unittest.cc File Reference
(d4ab02d08ceed19dab4276c86042b1520529304b)
#include <iostream>
#include "gtest/gtest.h"
#include "gtest/gtest-spi.h"
Classes
struct PredFormatFunctor5
class Predicate5Test
Typedefs
typedef Predicate1Test ASSERT_PRED1Test
typedef Predicate2Test ASSERT_PRED2Test
typedef Predicate3Test ASSERT_PRED3Test
typedef Predicate4Test ASSERT_PRED4Test
typedef Predicate5Test ASSERT_PRED5Test
typedef Predicate1Test ASSERT_PRED_FORMAT1Test
typedef Predicate2Test ASSERT_PRED_FORMAT2Test
typedef Predicate3Test ASSERT_PRED_FORMAT3Test
typedef Predicate4Test ASSERT_PRED_FORMAT4Test
typedef Predicate5Test ASSERT_PRED_FORMAT5Test
typedef Predicate1Test EXPECT_PRED1Test
typedef Predicate2Test EXPECT_PRED2Test
typedef Predicate3Test EXPECT_PRED3Test
typedef Predicate4Test EXPECT_PRED4Test
typedef Predicate5Test EXPECT_PRED5Test
typedef Predicate1Test EXPECT_PRED_FORMAT1Test
typedef Predicate2Test EXPECT_PRED_FORMAT2Test
typedef Predicate3Test EXPECT_PRED_FORMAT3Test
typedef Predicate4Test EXPECT_PRED_FORMAT4Test
typedef Predicate5Test EXPECT_PRED_FORMAT5Test
Functions
std::ostream & operator<< (std::ostream &os, const Bool &x)
template<typename T1 >
testing::AssertionResult PredFormatFunction1 (const char *e1, const T1 &v1)
template<typename T1 , typename T2 >
testing::AssertionResult PredFormatFunction2 (const char *e1, const char *e2, const T1 &v1, const T2 &v2)
template<typename T1 , typename T2 , typename T3 >
testing::AssertionResult PredFormatFunction3 (const char *e1, const char *e2, const char *e3, const T1 &v1, const T2 &v2, const T3 &v3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
testing::AssertionResult PredFormatFunction4 (const char *e1, const char *e2, const char *e3, const char *e4, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
testing::AssertionResult PredFormatFunction5 (const char *e1, const char *e2, const char *e3, const char *e4, const char *e5, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5)
template<typename T1 >
bool PredFunction1 (T1 v1)
bool PredFunction1Bool (Bool v1)
bool PredFunction1Int (int v1)
template<typename T1 , typename T2 >
bool PredFunction2 (T1 v1, T2 v2)
bool PredFunction2Bool (Bool v1, Bool v2)
bool PredFunction2Int (int v1, int v2)
template<typename T1 , typename T2 , typename T3 >
bool PredFunction3 (T1 v1, T2 v2, T3 v3)
bool PredFunction3Bool (Bool v1, Bool v2, Bool v3)
bool PredFunction3Int (int v1, int v2, int v3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
bool PredFunction4 (T1 v1, T2 v2, T3 v3, T4 v4)
bool PredFunction4Bool (Bool v1, Bool v2, Bool v3, Bool v4)
bool PredFunction4Int (int v1, int v2, int v3, int v4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
bool PredFunction5 (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5)
bool PredFunction5Bool (Bool v1, Bool v2, Bool v3, Bool v4, Bool v5)
bool PredFunction5Int (int v1, int v2, int v3, int v4, int v5)
TEST_F (EXPECT_PRED1Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED1Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED1Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED1Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED1Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED1Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED1Test, FunctorOnUserTypeFailure)
TEST_F (EXPECT_PRED1Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED2Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED2Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED2Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED2Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED2Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED2Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED2Test, FunctorOnUserTypeFailure)
TEST_F (EXPECT_PRED2Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED3Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED3Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED3Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED3Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED3Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED3Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED3Test, FunctorOnUserTypeFailure)
TEST_F (EXPECT_PRED3Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED4Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED4Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED4Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED4Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED4Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED4Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED4Test, FunctorOnUserTypeFailure)
TEST_F (EXPECT_PRED4Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED5Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED5Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED5Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED5Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED5Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED5Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED5Test, FunctorOnUserTypeFailure)
TEST_F (EXPECT_PRED5Test, FunctorOnUserTypeSuccess)
Typedef Documentation
ASSERT_PRED1Test
typedef Predicate1Test ASSERT_PRED1Test
Definition at line 163 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED2Test
typedef Predicate2Test ASSERT_PRED2Test
Definition at line 560 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED3Test
typedef Predicate3Test ASSERT_PRED3Test
Definition at line 999 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED4Test
typedef Predicate4Test ASSERT_PRED4Test
Definition at line 1480 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED5Test
typedef Predicate5Test ASSERT_PRED5Test
Definition at line 2003 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED_FORMAT1Test
typedef Predicate1Test ASSERT_PRED_FORMAT1Test
Definition at line 161 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED_FORMAT2Test
typedef Predicate2Test ASSERT_PRED_FORMAT2Test
Definition at line 558 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED_FORMAT3Test
typedef Predicate3Test ASSERT_PRED_FORMAT3Test
Definition at line 997 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED_FORMAT4Test
typedef Predicate4Test ASSERT_PRED_FORMAT4Test
Definition at line 1478 of file gtest_pred_impl_unittest.cc.
ASSERT_PRED_FORMAT5Test
typedef Predicate5Test ASSERT_PRED_FORMAT5Test
Definition at line 2001 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED1Test
typedef Predicate1Test EXPECT_PRED1Test
Definition at line 162 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED2Test
typedef Predicate2Test EXPECT_PRED2Test
Definition at line 559 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED3Test
typedef Predicate3Test EXPECT_PRED3Test
Definition at line 998 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED4Test
typedef Predicate4Test EXPECT_PRED4Test
Definition at line 1479 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED5Test
typedef Predicate5Test EXPECT_PRED5Test
Definition at line 2002 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED_FORMAT1Test
typedef Predicate1Test EXPECT_PRED_FORMAT1Test
Definition at line 160 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED_FORMAT2Test
typedef Predicate2Test EXPECT_PRED_FORMAT2Test
Definition at line 557 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED_FORMAT3Test
typedef Predicate3Test EXPECT_PRED_FORMAT3Test
Definition at line 996 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED_FORMAT4Test
typedef Predicate4Test EXPECT_PRED_FORMAT4Test
Definition at line 1477 of file gtest_pred_impl_unittest.cc.
EXPECT_PRED_FORMAT5Test
typedef Predicate5Test EXPECT_PRED_FORMAT5Test
Definition at line 2000 of file gtest_pred_impl_unittest.cc.
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & os, const Bool & x)
Definition at line 69 of file gtest_pred_impl_unittest.cc.
{
   return os << (x.value ? "true" : "false");
 }
References Bool::value.
PredFormatFunction1()
testing::AssertionResult PredFormatFunction1 (const char * e1, const T1 & v1)
Definition at line 101 of file gtest_pred_impl_unittest.cc.
{
   if (PredFunction1(v1))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1
       << " is expected to be positive, but evaluates to "
       << v1 << ".";
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction1().
Referenced by PredFormatFunctor1::operator()().
PredFormatFunction2()
testing::AssertionResult PredFormatFunction2 (const char * e1, const char * e2, const T1 & v1, const T2 & v2)
Definition at line 489 of file gtest_pred_impl_unittest.cc.
{
   if (PredFunction2(v1, v2))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2
       << " is expected to be positive, but evaluates to "
       << v1 + v2 << ".";
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction2().
Referenced by PredFormatFunctor2::operator()().
PredFormatFunction3()
testing::AssertionResult PredFormatFunction3 (const char * e1, const char * e2, const char * e3, const T1 & v1, const T2 & v2, const T3 & v3)
Definition at line 919 of file gtest_pred_impl_unittest.cc.
{
   if (PredFunction3(v1, v2, v3))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2 << " + " << e3
       << " is expected to be positive, but evaluates to "
       << v1 + v2 + v3 << ".";
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction3().
Referenced by PredFormatFunctor3::operator()().
PredFormatFunction4()
testing::AssertionResult PredFormatFunction4 (const char * e1, const char * e2, const char * e3, const char * e4, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4)
Definition at line 1391 of file gtest_pred_impl_unittest.cc.
{
   if (PredFunction4(v1, v2, v3, v4))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2 << " + " << e3 << " + " << e4
       << " is expected to be positive, but evaluates to "
       << v1 + v2 + v3 + v4 << ".";
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction4().
Referenced by PredFormatFunctor4::operator()().
PredFormatFunction5()
testing::AssertionResult PredFormatFunction5 (const char * e1, const char * e2, const char * e3, const char * e4, const char * e5, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5)
Definition at line 1905 of file gtest_pred_impl_unittest.cc.
{
   if (PredFunction5(v1, v2, v3, v4, v5))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2 << " + " << e3 << " + " << e4 << " + " << e5
       << " is expected to be positive, but evaluates to "
       << v1 + v2 + v3 + v4 + v5 << ".";
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction5().
Referenced by PredFormatFunctor5::operator()().
PredFunction1()
bool PredFunction1 (T1 v1)
Definition at line 77 of file gtest_pred_impl_unittest.cc.
{
   return v1 > 0;
 }
Referenced by PredFormatFunction1().
PredFunction1Bool()
bool PredFunction1Bool (Bool v1)
Definition at line 87 of file gtest_pred_impl_unittest.cc.
{
   return v1 > 0;
 }
Referenced by TEST_F().
PredFunction1Int()
bool PredFunction1Int (int v1)
Definition at line 84 of file gtest_pred_impl_unittest.cc.
{
   return v1 > 0;
 }
Referenced by TEST_F().
PredFunction2()
bool PredFunction2 (T1 v1, T2 v2)
Definition at line 464 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 > 0;
 }
Referenced by PredFormatFunction2().
PredFunction2Bool()
bool PredFunction2Bool (Bool v1, Bool v2)
Definition at line 474 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 > 0;
 }
Referenced by TEST_F().
PredFunction2Int()
bool PredFunction2Int (int v1, int v2)
Definition at line 471 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 > 0;
 }
Referenced by TEST_F().
PredFunction3()
bool PredFunction3 (T1 v1, T2 v2, T3 v3)
Definition at line 893 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 > 0;
 }
Referenced by PredFormatFunction3().
PredFunction3Bool()
bool PredFunction3Bool (Bool v1, Bool v2, Bool v3)
Definition at line 903 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 > 0;
 }
Referenced by TEST_F().
PredFunction3Int()
bool PredFunction3Int (int v1, int v2, int v3)
Definition at line 900 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 > 0;
 }
Referenced by TEST_F().
PredFunction4()
bool PredFunction4 (T1 v1, T2 v2, T3 v3, T4 v4)
Definition at line 1364 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 > 0;
 }
Referenced by PredFormatFunction4().
PredFunction4Bool()
bool PredFunction4Bool (Bool v1, Bool v2, Bool v3, Bool v4)
Definition at line 1374 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 > 0;
 }
Referenced by TEST_F().
PredFunction4Int()
bool PredFunction4Int (int v1, int v2, int v3, int v4)
Definition at line 1371 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 > 0;
 }
Referenced by TEST_F().
PredFunction5()
bool PredFunction5 (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5)
Definition at line 1877 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 + v5 > 0;
 }
Referenced by PredFormatFunction5().
PredFunction5Bool()
bool PredFunction5Bool (Bool v1, Bool v2, Bool v3, Bool v4, Bool v5)
Definition at line 1887 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 + v5 > 0;
 }
Referenced by TEST_F().
PredFunction5Int()
bool PredFunction5Int (int v1, int v2, int v3, int v4, int v5)
Definition at line 1884 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 + v5 > 0;
 }
Referenced by TEST_F().
TEST_F() [1/40]
TEST_F (EXPECT_PRED1Test , FunctionOnBuiltInTypeFailure)
Definition at line 199 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED1(PredFunction1Int,
                  n1_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, and PredFunction1Int().
TEST_F() [2/40]
TEST_F (EXPECT_PRED1Test , FunctionOnBuiltInTypeSuccess)
Definition at line 167 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED1(PredFunction1Int,
                ++n1_);
   finished_ = true;
 }
References EXPECT_PRED1, and PredFunction1Int().
TEST_F() [3/40]
TEST_F (EXPECT_PRED1Test , FunctionOnUserTypeFailure)
Definition at line 209 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED1(PredFunction1Bool,
                  Bool(n1_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, and PredFunction1Bool().
TEST_F() [4/40]
TEST_F (EXPECT_PRED1Test , FunctionOnUserTypeSuccess)
Definition at line 175 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED1(PredFunction1Bool,
                Bool(++n1_));
   finished_ = true;
 }
References EXPECT_PRED1, and PredFunction1Bool().
TEST_F() [5/40]
TEST_F (EXPECT_PRED1Test , FunctorOnBuiltInTypeFailure)
Definition at line 219 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED1(PredFunctor1(),
                  n1_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED1.
TEST_F() [6/40]
TEST_F (EXPECT_PRED1Test , FunctorOnBuiltInTypeSuccess)
Definition at line 183 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED1(PredFunctor1(),
                ++n1_);
   finished_ = true;
 }
References EXPECT_PRED1.
TEST_F() [7/40]
TEST_F (EXPECT_PRED1Test , FunctorOnUserTypeFailure)
Definition at line 229 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED1(PredFunctor1(),
                  Bool(n1_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED1.
TEST_F() [8/40]
TEST_F (EXPECT_PRED1Test , FunctorOnUserTypeSuccess)
Definition at line 191 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED1(PredFunctor1(),
                Bool(++n1_));
   finished_ = true;
 }
References EXPECT_PRED1.
TEST_F() [9/40]
TEST_F (EXPECT_PRED2Test , FunctionOnBuiltInTypeFailure)
Definition at line 600 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED2(PredFunction2Int,
                  n1_++,
                  n2_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED2, and PredFunction2Int().
TEST_F() [10/40]
TEST_F (EXPECT_PRED2Test , FunctionOnBuiltInTypeSuccess)
Definition at line 564 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED2(PredFunction2Int,
                ++n1_,
                ++n2_);
   finished_ = true;
 }
References EXPECT_PRED2, and PredFunction2Int().
TEST_F() [11/40]
TEST_F (EXPECT_PRED2Test , FunctionOnUserTypeFailure)
Definition at line 611 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED2(PredFunction2Bool,
                  Bool(n1_++),
                  Bool(n2_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED2, and PredFunction2Bool().
TEST_F() [12/40]
TEST_F (EXPECT_PRED2Test , FunctionOnUserTypeSuccess)
Definition at line 573 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED2(PredFunction2Bool,
                Bool(++n1_),
                Bool(++n2_));
   finished_ = true;
 }
References EXPECT_PRED2, and PredFunction2Bool().
TEST_F() [13/40]
TEST_F (EXPECT_PRED2Test , FunctorOnBuiltInTypeFailure)
Definition at line 622 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED2(PredFunctor2(),
                  n1_++,
                  n2_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED2.
TEST_F() [14/40]
TEST_F (EXPECT_PRED2Test , FunctorOnBuiltInTypeSuccess)
Definition at line 582 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED2(PredFunctor2(),
                ++n1_,
                ++n2_);
   finished_ = true;
 }
References EXPECT_PRED2.
TEST_F() [15/40]
TEST_F (EXPECT_PRED2Test , FunctorOnUserTypeFailure)
Definition at line 633 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED2(PredFunctor2(),
                  Bool(n1_++),
                  Bool(n2_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED2.
TEST_F() [16/40]
TEST_F (EXPECT_PRED2Test , FunctorOnUserTypeSuccess)
Definition at line 591 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED2(PredFunctor2(),
                Bool(++n1_),
                Bool(++n2_));
   finished_ = true;
 }
References EXPECT_PRED2.
TEST_F() [17/40]
TEST_F (EXPECT_PRED3Test , FunctionOnBuiltInTypeFailure)
Definition at line 1043 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunction3Int,
                  n1_++,
                  n2_++,
                  n3_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED3, and PredFunction3Int().
TEST_F() [18/40]
TEST_F (EXPECT_PRED3Test , FunctionOnBuiltInTypeSuccess)
Definition at line 1003 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED3(PredFunction3Int,
                ++n1_,
                ++n2_,
                ++n3_);
   finished_ = true;
 }
References EXPECT_PRED3, and PredFunction3Int().
TEST_F() [19/40]
TEST_F (EXPECT_PRED3Test , FunctionOnUserTypeFailure)
Definition at line 1055 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunction3Bool,
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED3, and PredFunction3Bool().
TEST_F() [20/40]
TEST_F (EXPECT_PRED3Test , FunctionOnUserTypeSuccess)
Definition at line 1013 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED3(PredFunction3Bool,
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_));
   finished_ = true;
 }
References EXPECT_PRED3, and PredFunction3Bool().
TEST_F() [21/40]
TEST_F (EXPECT_PRED3Test , FunctorOnBuiltInTypeFailure)
Definition at line 1067 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunctor3(),
                  n1_++,
                  n2_++,
                  n3_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED3.
TEST_F() [22/40]
TEST_F (EXPECT_PRED3Test , FunctorOnBuiltInTypeSuccess)
Definition at line 1023 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED3(PredFunctor3(),
                ++n1_,
                ++n2_,
                ++n3_);
   finished_ = true;
 }
References EXPECT_PRED3.
TEST_F() [23/40]
TEST_F (EXPECT_PRED3Test , FunctorOnUserTypeFailure)
Definition at line 1079 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunctor3(),
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED3.
TEST_F() [24/40]
TEST_F (EXPECT_PRED3Test , FunctorOnUserTypeSuccess)
Definition at line 1033 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED3(PredFunctor3(),
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_));
   finished_ = true;
 }
References EXPECT_PRED3.
TEST_F() [25/40]
TEST_F (EXPECT_PRED4Test , FunctionOnBuiltInTypeFailure)
Definition at line 1528 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED4(PredFunction4Int,
                  n1_++,
                  n2_++,
                  n3_++,
                  n4_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED4, and PredFunction4Int().
TEST_F() [26/40]
TEST_F (EXPECT_PRED4Test , FunctionOnBuiltInTypeSuccess)
Definition at line 1484 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED4(PredFunction4Int,
                ++n1_,
                ++n2_,
                ++n3_,
                ++n4_);
   finished_ = true;
 }
References EXPECT_PRED4, and PredFunction4Int().
TEST_F() [27/40]
TEST_F (EXPECT_PRED4Test , FunctionOnUserTypeFailure)
Definition at line 1541 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED4(PredFunction4Bool,
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED4, and PredFunction4Bool().
TEST_F() [28/40]
TEST_F (EXPECT_PRED4Test , FunctionOnUserTypeSuccess)
Definition at line 1495 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED4(PredFunction4Bool,
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_),
                Bool(++n4_));
   finished_ = true;
 }
References EXPECT_PRED4, and PredFunction4Bool().
TEST_F() [29/40]
TEST_F (EXPECT_PRED4Test , FunctorOnBuiltInTypeFailure)
Definition at line 1554 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED4(PredFunctor4(),
                  n1_++,
                  n2_++,
                  n3_++,
                  n4_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED4.
TEST_F() [30/40]
TEST_F (EXPECT_PRED4Test , FunctorOnBuiltInTypeSuccess)
Definition at line 1506 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED4(PredFunctor4(),
                ++n1_,
                ++n2_,
                ++n3_,
                ++n4_);
   finished_ = true;
 }
References EXPECT_PRED4.
TEST_F() [31/40]
TEST_F (EXPECT_PRED4Test , FunctorOnUserTypeFailure)
Definition at line 1567 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED4(PredFunctor4(),
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED4.
TEST_F() [32/40]
TEST_F (EXPECT_PRED4Test , FunctorOnUserTypeSuccess)
Definition at line 1517 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED4(PredFunctor4(),
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_),
                Bool(++n4_));
   finished_ = true;
 }
References EXPECT_PRED4.
TEST_F() [33/40]
TEST_F (EXPECT_PRED5Test , FunctionOnBuiltInTypeFailure)
Definition at line 2055 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunction5Int,
                  n1_++,
                  n2_++,
                  n3_++,
                  n4_++,
                  n5_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED5, and PredFunction5Int().
TEST_F() [34/40]
TEST_F (EXPECT_PRED5Test , FunctionOnBuiltInTypeSuccess)
Definition at line 2007 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED5(PredFunction5Int,
                ++n1_,
                ++n2_,
                ++n3_,
                ++n4_,
                ++n5_);
   finished_ = true;
 }
References EXPECT_PRED5, and PredFunction5Int().
TEST_F() [35/40]
TEST_F (EXPECT_PRED5Test , FunctionOnUserTypeFailure)
Definition at line 2069 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunction5Bool,
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++),
                  Bool(n5_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED5, and PredFunction5Bool().
TEST_F() [36/40]
TEST_F (EXPECT_PRED5Test , FunctionOnUserTypeSuccess)
Definition at line 2019 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED5(PredFunction5Bool,
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_),
                Bool(++n4_),
                Bool(++n5_));
   finished_ = true;
 }
References EXPECT_PRED5, and PredFunction5Bool().
TEST_F() [37/40]
TEST_F (EXPECT_PRED5Test , FunctorOnBuiltInTypeFailure)
Definition at line 2083 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunctor5(),
                  n1_++,
                  n2_++,
                  n3_++,
                  n4_++,
                  n5_++);
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED5.
TEST_F() [38/40]
TEST_F (EXPECT_PRED5Test , FunctorOnBuiltInTypeSuccess)
Definition at line 2031 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED5(PredFunctor5(),
                ++n1_,
                ++n2_,
                ++n3_,
                ++n4_,
                ++n5_);
   finished_ = true;
 }
References EXPECT_PRED5.
TEST_F() [39/40]
TEST_F (EXPECT_PRED5Test , FunctorOnUserTypeFailure)
Definition at line 2097 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunctor5(),
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++),
                  Bool(n5_++));
     finished_ = true;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED5.
TEST_F() [40/40]
TEST_F (EXPECT_PRED5Test , FunctorOnUserTypeSuccess)
Definition at line 2043 of file gtest_pred_impl_unittest.cc.
{
   EXPECT_PRED5(PredFunctor5(),
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_),
                Bool(++n4_),
                Bool(++n5_));
   finished_ = true;
 }
References EXPECT_PRED5.