Common Alogrithm: ElectricKettle Class Reference
ElectricKettle Class Reference
Public Member Functions
void boil ()
void plugIn (USASocketInterface *supply)
Private Attributes
USASocketInterface * power
Detailed Description
Member Function Documentation
boil()
void ElectricKettle::boil ()
         {
             if (power->voltage() > 110)
             {
                 std::cout << "Kettle is on fire!" << std::endl;
                 return;
             }
             if (power->live() == 1 && power->neutral() == -1)
             {
                 std::cout << "Coffee time!" << std::endl;
             }
         }
References std::endl(), USASocketInterface::live(), USASocketInterface::neutral(), power, and USASocketInterface::voltage().
Referenced by main().
plugIn()
void ElectricKettle::plugIn (USASocketInterface * supply)
         {
             power = supply;
         }
References power.
Referenced by main().
Member Data Documentation
power
USASocketInterface* ElectricKettle::power private
Referenced by boil(), and plugIn().