Common Alogrithm: TestEventListeners Class Reference
TestEventListeners Class Reference
#include <gtest.h>
Public Member Functions
void Append (TestEventListener *listener)
TestEventListener * default_result_printer () const
TestEventListener * default_xml_generator () const
TestEventListener * Release (TestEventListener *listener)
TestEventListeners ()
~TestEventListeners ()
Private Member Functions
bool EventForwardingEnabled () const
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventListeners)
TestEventListener * repeater ()
void SetDefaultResultPrinter (TestEventListener *listener)
void SetDefaultXmlGenerator (TestEventListener *listener)
void SuppressEventForwarding ()
Private Attributes
TestEventListener * default_result_printer_
TestEventListener * default_xml_generator_
internal::TestEventRepeater * repeater_
Friends
class internal::DefaultGlobalTestPartResultReporter
class internal::NoExecDeathTest
class internal::TestEventListenersAccessor
class internal::UnitTestImpl
class TestCase
class TestInfo
Detailed Description
Definition at line 1064 of file gtest.h.
Constructor & Destructor Documentation
TestEventListeners()
TestEventListeners ()
Definition at line 3890 of file gtest.cc.
     : repeater_(new internal::TestEventRepeater()),
       default_result_printer_(NULL),
       default_xml_generator_(NULL) {
 }
~TestEventListeners()
~TestEventListeners ()
Definition at line 3896 of file gtest.cc.
 { delete repeater_; }
References TestEventListeners::repeater_.
Member Function Documentation
Append()
void Append (TestEventListener * listener)
Definition at line 3902 of file gtest.cc.
{
   repeater_->Append(listener);
 }
References TestEventRepeater::Append(), and TestEventListeners::repeater_.
Referenced by UnitTestImpl::PostFlagParsingInit(), TestEventListeners::SetDefaultResultPrinter(), and TestEventListeners::SetDefaultXmlGenerator().
default_result_printer()
TestEventListener* default_result_printer () const
Definition at line 1084 of file gtest.h.
{
     return default_result_printer_;
   }
default_xml_generator()
TestEventListener* default_xml_generator () const
Definition at line 1095 of file gtest.h.
{
     return default_xml_generator_;
   }
EventForwardingEnabled()
bool EventForwardingEnabled () const private
Definition at line 3955 of file gtest.cc.
{
   return repeater_->forwarding_enabled();
 }
References TestEventRepeater::forwarding_enabled(), and TestEventListeners::repeater_.
GTEST_DISALLOW_COPY_AND_ASSIGN_()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventListeners) private
Release()
TestEventListener * Release (TestEventListener * listener)
Definition at line 3909 of file gtest.cc.
{
   if (listener == default_result_printer_)
     default_result_printer_ = NULL;
   else if (listener == default_xml_generator_)
     default_xml_generator_ = NULL;
   return repeater_->Release(listener);
 }
References TestEventListeners::default_result_printer_, TestEventListeners::default_xml_generator_, TestEventRepeater::Release(), and TestEventListeners::repeater_.
Referenced by TestEventListeners::SetDefaultResultPrinter(), and TestEventListeners::SetDefaultXmlGenerator().
repeater()
TestEventListener * repeater () private
Definition at line 3919 of file gtest.cc.
 { return repeater_; }
References TestEventListeners::repeater_.
Referenced by DefaultGlobalTestPartResultReporter::ReportTestPartResult(), TestInfo::Run(), TestCase::Run(), and UnitTestImpl::RunAllTests().
SetDefaultResultPrinter()
void SetDefaultResultPrinter (TestEventListener * listener) private
Definition at line 3926 of file gtest.cc.
{
   if (default_result_printer_ != listener) {
     // It is an error to pass this method a listener that is already in the
     // list.
     delete Release(default_result_printer_);
     default_result_printer_ = listener;
     if (listener != NULL)
       Append(listener);
   }
 }
References TestEventListeners::Append(), TestEventListeners::default_result_printer_, and TestEventListeners::Release().
Referenced by UnitTestImpl::UnitTestImpl().
SetDefaultXmlGenerator()
void SetDefaultXmlGenerator (TestEventListener * listener) private
Definition at line 3942 of file gtest.cc.
{
   if (default_xml_generator_ != listener) {
     // It is an error to pass this method a listener that is already in the
     // list.
     delete Release(default_xml_generator_);
     default_xml_generator_ = listener;
     if (listener != NULL)
       Append(listener);
   }
 }
References TestEventListeners::Append(), TestEventListeners::default_xml_generator_, and TestEventListeners::Release().
Referenced by UnitTestImpl::ConfigureXmlOutput().
SuppressEventForwarding()
void SuppressEventForwarding () private
Definition at line 3959 of file gtest.cc.
{
   repeater_->set_forwarding_enabled(false);
 }
References TestEventListeners::repeater_, and TestEventRepeater::set_forwarding_enabled().
Friends And Related Function Documentation
internal::DefaultGlobalTestPartResultReporter
friend class internal::DefaultGlobalTestPartResultReporter friend
Definition at line 1102 of file gtest.h.
internal::NoExecDeathTest
friend class internal::NoExecDeathTest friend
Definition at line 1103 of file gtest.h.
internal::TestEventListenersAccessor
friend class internal::TestEventListenersAccessor friend
Definition at line 1104 of file gtest.h.
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
Definition at line 1105 of file gtest.h.
TestCase
friend class TestCase friend
Definition at line 1100 of file gtest.h.
TestInfo
friend class TestInfo friend
Definition at line 1101 of file gtest.h.
Member Data Documentation
default_result_printer_
TestEventListener* default_result_printer_ private
Definition at line 1133 of file gtest.h.
Referenced by TestEventListeners::Release(), and TestEventListeners::SetDefaultResultPrinter().
default_xml_generator_
TestEventListener* default_xml_generator_ private
Definition at line 1135 of file gtest.h.
Referenced by TestEventListeners::Release(), and TestEventListeners::SetDefaultXmlGenerator().
repeater_
internal::TestEventRepeater* repeater_ private
Definition at line 1131 of file gtest.h.
Referenced by TestEventListeners::Append(), TestEventListeners::EventForwardingEnabled(), TestEventListeners::Release(), TestEventListeners::repeater(), TestEventListeners::SuppressEventForwarding(), and TestEventListeners::~TestEventListeners().