Common Alogrithm: AssertionResult Class Reference
AssertionResult Class Reference
#include <gtest.h>
Public Member Functions
AssertionResult (const AssertionResult &other)
template<typename T >
AssertionResult (const T &success, typename internal::EnableIf< !internal::ImplicitlyConvertible< T, AssertionResult >::value >::type *=NULL)
const char * failure_message () const
const char * message () const
operator bool () const
AssertionResult operator! () const
AssertionResult & operator<< (::std::ostream &(*basic_manipulator)(::std::ostream &stream))
template<typename T >
AssertionResult & operator<< (const T &value)
AssertionResult & operator= (AssertionResult other)
Private Member Functions
void AppendMessage (const Message &a_message)
void swap (AssertionResult &other)
Private Attributes
internal::scoped_ptr< ::std::string > message_
bool success_
Detailed Description
Constructor & Destructor Documentation
AssertionResult() [1/2]
AssertionResult (const AssertionResult & other)
     : success_(other.success_),
       message_(other.message_.get() != NULL ?
                new ::std::string(*other.message_) :
                static_cast< ::std::string*>(NULL)) {
 }
AssertionResult() [2/2]
AssertionResult (const T & success, typename internal::EnableIf< !internal::ImplicitlyConvertible< T, AssertionResult >::value >::type * = NULL) explicit
       : success_(success) {}
Member Function Documentation
AppendMessage()
void AppendMessage (const Message & a_message) private
{
     if (message_.get() == NULL)
       message_.reset(new ::std::string);
     message_->append(a_message.GetString().c_str());
   }
References string::c_str(), and Message::GetString().
failure_message()
const char* failure_message () const
 { return message(); }
message()
const char* message () const
{
     return message_.get() != NULL ?  message_->c_str() : "";
   }
Referenced by testing::internal::GetBoolAssertionFailureMessage().
operator bool()
operator bool () const
 { return success_; }  // NOLINT
operator!()
AssertionResult operator! () const
{
   AssertionResult negation(!success_);
   if (message_.get() != NULL)
     negation << *message_;
   return negation;
 }
References AssertionResult::message_, and AssertionResult::success_.
operator<<() [1/2]
AssertionResult& operator<< (::std::ostream &(*)(::std::ostream &stream) basic_manipulator)
{
     AppendMessage(Message() << basic_manipulator);
     return *this;
   }
operator<<() [2/2]
AssertionResult& operator<< (const T & value)
{
     AppendMessage(Message() << value);
     return *this;
   }
operator=()
AssertionResult& operator= (AssertionResult other)
{
     swap(other);
     return *this;
   }
swap()
void swap (AssertionResult & other) private
{
   using std::swap;
   swap(success_, other.success_);
   swap(message_, other.message_);
 }
References AssertionResult::message_, AssertionResult::success_, and std::swap().
Member Data Documentation
message_
internal::scoped_ptr< ::std::string> message_ private
Referenced by AssertionResult::operator!(), and AssertionResult::swap().
success_
bool success_ private
Referenced by AssertionResult::operator!(), and AssertionResult::swap().