Common Alogrithm: HashObject Class Reference
HashObject Class Reference
#include <hash_object.h>
Public Member Functions
std::string & Getkey ()
std::string & GetValue ()
HashObject ()
HashObject (const HashObject &)
HashObject & operator= (const HashObject &)
void SetAsDummy ()
void SetKey (const std::string key)
void SetValue (const std::string value)
virtual ~HashObject ()
Static Public Member Functions
static const std::string GetDummyKey ()
static const std::string GetNullKey ()
Private Attributes
std::string key_
std::string value_
Detailed Description
Definition at line 7 of file hash_object.h.
Constructor & Destructor Documentation
HashObject() [1/2]
HashObject ()
Definition at line 14 of file hash_object.h.
 {};
HashObject() [2/2]
HashObject (const HashObject &)
Definition at line 15 of file hash_object.h.
 {};
~HashObject()
virtual ~HashObject () virtual
Definition at line 17 of file hash_object.h.
 {};
Member Function Documentation
GetDummyKey()
static const std::string GetDummyKey () static
Definition at line 25 of file hash_object.h.
 { return "<Dummy>"; };
Referenced by HashTable::Add(), HashTable::Remove(), and HashObject::SetAsDummy().
Getkey()
std::string& Getkey ()
Definition at line 19 of file hash_object.h.
 { return key_; };
References HashObject::key_.
Referenced by HashTable::Add(), and HashTable::PringDebug().
GetNullKey()
static const std::string GetNullKey () static
Definition at line 26 of file hash_object.h.
 { return "<NULL>";};
Referenced by HashTable::Add(), HashTable::Exists(), HashTable::Get(), HashTable::HashTable(), and HashTable::Remove().
GetValue()
std::string& GetValue ()
Definition at line 20 of file hash_object.h.
 { return value_; };
References HashObject::value_.
Referenced by HashTable::Add(), HashTable::Get(), and HashTable::PringDebug().
operator=()
HashObject& operator= (const HashObject &)
SetAsDummy()
void SetAsDummy ()
Definition at line 28 of file hash_object.h.
                       {
         key_ = GetDummyKey();
         value_ = "";
     }
References HashObject::GetDummyKey(), HashObject::key_, and HashObject::value_.
SetKey()
void SetKey (const std::string key)
Definition at line 22 of file hash_object.h.
 { key_ = key;};
References HashObject::key_.
Referenced by HashTable::Add(), HashTable::HashTable(), HashTable::Remove(), test_add_exists(), test_get(), test_probing(), and test_remove().
SetValue()
void SetValue (const std::string value)
Definition at line 23 of file hash_object.h.
 { value_ = value;};
References HashObject::value_.
Referenced by HashTable::Add(), HashTable::Remove(), test_add_exists(), test_get(), test_probing(), and test_remove().
Member Data Documentation
key_
std::string key_ private
Definition at line 10 of file hash_object.h.
Referenced by HashObject::Getkey(), HashObject::SetAsDummy(), and HashObject::SetKey().
value_
std::string value_ private
Definition at line 11 of file hash_object.h.
Referenced by HashObject::GetValue(), HashObject::SetAsDummy(), and HashObject::SetValue().