Common Alogrithm: TestPartResult Class Reference
TestPartResult Class Reference
#include <gtest-test-part.h>
Public Types
enum Type { kSuccess , kNonFatalFailure , kFatalFailure }
Public Member Functions
bool failed () const
bool fatally_failed () const
const char * file_name () const
int line_number () const
const char * message () const
bool nonfatally_failed () const
bool passed () const
const char * summary () const
TestPartResult (Type a_type, const char *a_file_name, int a_line_number, const char *a_message)
Type type () const
Static Private Member Functions
static std::string ExtractSummary (const char *message)
Private Attributes
std::string file_name_
int line_number_
std::string message_
std::string summary_
Type type_
Detailed Description
Definition at line 47 of file gtest-test-part.h.
Member Enumeration Documentation
Type
enum Type
Enumerator
kSuccess
kNonFatalFailure
kFatalFailure
Definition at line 51 of file gtest-test-part.h.
             {
     kSuccess,          // Succeeded.
     kNonFatalFailure,  // Failed but the test can continue.
     kFatalFailure      // Failed and the test should be terminated.
   };
Constructor & Destructor Documentation
TestPartResult()
TestPartResult (Type a_type, const char * a_file_name, int a_line_number, const char * a_message)
Definition at line 60 of file gtest-test-part.h.
       : type_(a_type),
         file_name_(a_file_name == NULL ? "" : a_file_name),
         line_number_(a_line_number),
         summary_(ExtractSummary(a_message)),
         message_(a_message) {
   }
Member Function Documentation
ExtractSummary()
std::string ExtractSummary (const char * message) static private
Definition at line 51 of file gtest-test-part.cc.
{
   const char* const stack_trace = strstr(message, internal::kStackTraceMarker);
   return stack_trace == NULL ? message :
       std::string(message, stack_trace);
 }
References testing::internal::kStackTraceMarker, and TestPartResult::message().
failed()
bool failed () const
Definition at line 94 of file gtest-test-part.h.
 { return type_ != kSuccess; }
Referenced by TestResult::Failed(), and XmlUnitTestResultPrinter::OutputXmlTestInfo().
fatally_failed()
bool fatally_failed () const
Definition at line 100 of file gtest-test-part.h.
 { return type_ == kFatalFailure; }
Referenced by HasNewFatalFailureHelper::ReportTestPartResult(), and testing::TestPartFatallyFailed().
file_name()
const char* file_name () const
Definition at line 76 of file gtest-test-part.h.
{
     return file_name_.empty() ? NULL : file_name_.c_str();
   }
Referenced by testing::operator<<(), XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PrintTestPartResultToString().
line_number()
int line_number () const
Definition at line 82 of file gtest-test-part.h.
 { return line_number_; }
Referenced by testing::operator<<(), XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PrintTestPartResultToString().
message()
const char* message () const
Definition at line 88 of file gtest-test-part.h.
 { return message_.c_str(); }
Referenced by TestPartResult::ExtractSummary(), testing::internal::HasOneFailure(), testing::operator<<(), XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PrintTestPartResultToString().
nonfatally_failed()
bool nonfatally_failed () const
Definition at line 97 of file gtest-test-part.h.
 { return type_ == kNonFatalFailure; }
Referenced by testing::TestPartNonfatallyFailed().
passed()
bool passed () const
Definition at line 91 of file gtest-test-part.h.
 { return type_ == kSuccess; }
summary()
const char* summary () const
Definition at line 85 of file gtest-test-part.h.
 { return summary_.c_str(); }
Referenced by XmlUnitTestResultPrinter::OutputXmlTestInfo().
type()
Type type () const
Definition at line 72 of file gtest-test-part.h.
 { return type_; }
Referenced by testing::internal::HasOneFailure(), PrettyUnitTestResultPrinter::OnTestPartResult(), testing::operator<<(), and testing::internal::PrintTestPartResultToString().
Member Data Documentation
file_name_
std::string file_name_ private
Definition at line 111 of file gtest-test-part.h.
line_number_
int line_number_ private
Definition at line 114 of file gtest-test-part.h.
message_
std::string message_ private
Definition at line 116 of file gtest-test-part.h.
summary_
std::string summary_ private
Definition at line 115 of file gtest-test-part.h.
type_
Type type_ private
Definition at line 103 of file gtest-test-part.h.