Common Alogrithm: Singleton Class Reference
Singleton Class Reference
Static Public Member Functions
static Singleton * getInstance ()
Private Member Functions
Singleton ()
Static Private Attributes
static Singleton * instance = 0
Detailed Description
Definition at line 18 of file main.cc.
Constructor & Destructor Documentation
Singleton()
Singleton () private
Definition at line 44 of file main.cc.
 {}
Referenced by getInstance().
Member Function Documentation
getInstance()
Singleton * getInstance () static
Definition at line 34 of file main.cc.
 {
     if (instance == 0)
     {
         instance = new Singleton();
     }
     return instance;
 }
References instance, and Singleton().
Referenced by main().
Member Data Documentation
instance
Singleton * instance = 0 static private
Definition at line 22 of file main.cc.
Referenced by getInstance().