Common Alogrithm: testing Namespace Reference
testing Namespace Reference
Namespaces
anonymous_namespace{gtest-printers.cc}
anonymous_namespace{gtest.cc}
internal
internal2
Classes
class AssertionResult
class EmptyTestEventListener
class Environment
class Message
class ScopedFakeTestPartResultReporter
class Test
class TestCase
class TestEventListener
class TestEventListeners
class TestInfo
class TestPartResult
class TestPartResultArray
class TestPartResultReporterInterface
class TestProperty
class TestResult
class UnitTest
Functions
Environment * AddGlobalTestEnvironment (Environment *env)
template<int kSize>
std::vector< std::string > ArrayAsVector (const char *const (&array)[kSize])
AssertionResult AssertionFailure ()
AssertionResult AssertionFailure (const Message &message)
AssertionResult AssertionSuccess ()
AssertionResult DoubleLE (const char *expr1, const char *expr2, double val1, double val2)
AssertionResult FloatLE (const char *expr1, const char *expr2, float val1, float val2)
static std::string FormatCountableNoun (int count, const char *singular_form, const char *plural_form)
static std::string FormatTestCaseCount (int test_case_count)
static std::string FormatTestCount (int test_count)
static std::string FormatWordList (const std::vector< std::string > &words)
static const char * GetDefaultFilter ()
static std::vector< std::string > GetReservedAttributesForElement (const std::string &xml_element)
GTEST_DECLARE_bool_ (also_run_disabled_tests)
GTEST_DECLARE_bool_ (break_on_failure)
GTEST_DECLARE_bool_ (catch_exceptions)
GTEST_DECLARE_bool_ (death_test_use_fork)
GTEST_DECLARE_bool_ (list_tests)
GTEST_DECLARE_bool_ (print_time)
GTEST_DECLARE_bool_ (show_internal_stack_frames)
GTEST_DECLARE_bool_ (shuffle)
GTEST_DECLARE_bool_ (throw_on_failure)
GTEST_DECLARE_int32_ (random_seed)
GTEST_DECLARE_int32_ (repeat)
GTEST_DECLARE_int32_ (stack_trace_depth)
GTEST_DECLARE_string_ (color)
GTEST_DECLARE_string_ (death_test_style)
GTEST_DECLARE_string_ (filter)
GTEST_DECLARE_string_ (output)
GTEST_DECLARE_string_ (stream_result_to)
GTEST_DEFINE_bool_ (also_run_disabled_tests, internal::BoolFromGTestEnv("also_run_disabled_tests", false), "Run disabled tests too, in addition to the tests normally being run.")
GTEST_DEFINE_bool_ (break_on_failure, internal::BoolFromGTestEnv("break_on_failure", false), "True iff a failed assertion should be a debugger break-point.")
GTEST_DEFINE_bool_ (catch_exceptions, internal::BoolFromGTestEnv("catch_exceptions", true), "True iff " GTEST_NAME_ " should catch exceptions and treat them as test failures.")
GTEST_DEFINE_bool_ (death_test_use_fork, internal::BoolFromGTestEnv("death_test_use_fork", false), "Instructs to use fork()/_exit() instead of clone() in death tests. " "Ignored and always uses fork() on POSIX systems where clone() is not " "implemented. Useful when running under valgrind or similar tools if " "those do not support clone(). Valgrind 3.3.1 will just fail if " "it sees an unsupported combination of clone() flags. " "It is not recommended to use this flag w/o valgrind though it will " "work in 99% of the cases. Once valgrind is fixed, this flag will " "most likely be removed.")
GTEST_DEFINE_bool_ (list_tests, false, "List all tests without running them.")
GTEST_DEFINE_bool_ (print_time, internal::BoolFromGTestEnv("print_time", true), "True iff " GTEST_NAME_ " should display elapsed time in text output.")
GTEST_DEFINE_bool_ (show_internal_stack_frames, false, "True iff " GTEST_NAME_ " should include internal stack frames when " "printing test failure stack traces.")
GTEST_DEFINE_bool_ (shuffle, internal::BoolFromGTestEnv("shuffle", false), "True iff " GTEST_NAME_ " should randomize tests' order on every run.")
GTEST_DEFINE_bool_ (throw_on_failure, internal::BoolFromGTestEnv("throw_on_failure", false), "When this flag is specified, a failed assertion will throw an exception " "if exceptions are enabled or exit the program with a non-zero code " "otherwise.")
GTEST_DEFINE_int32_ (random_seed, internal::Int32FromGTestEnv("random_seed", 0), "Random number seed to use when shuffling test orders. Must be in range " "[1, 99999], or 0 to use a seed based on the current time.")
GTEST_DEFINE_int32_ (repeat, internal::Int32FromGTestEnv("repeat", 1), "How many times to repeat each test. Specify a negative number " "for repeating forever. Useful for shaking out flaky tests.")
GTEST_DEFINE_int32_ (stack_trace_depth, internal::Int32FromGTestEnv("stack_trace_depth", kMaxStackTraceDepth), "The maximum number of stack frames to print when an " "assertion fails. The valid range is 0 through 100, inclusive.")
GTEST_DEFINE_string_ (color, internal::StringFromGTestEnv("color", "auto"), "Whether to use colors in the output. Valid values: yes, no, " "and auto. 'auto' means to use colors if the output is " "being sent to a terminal and the TERM environment variable " "is set to a terminal type that supports colors.")
GTEST_DEFINE_string_ (death_test_style, internal::StringFromGTestEnv("death_test_style", kDefaultDeathTestStyle), "Indicates how to run a death test in a forked child process: " "\"threadsafe\" (child process re-executes the test binary " "from the beginning, running only the specific death test) or " "\"fast\" (child process runs the death test immediately " "after forking).")
GTEST_DEFINE_string_ (filter, internal::StringFromGTestEnv("filter", GetDefaultFilter()), "A colon-separated list of glob (not regex) patterns " "for filtering the tests to run, optionally followed by a " "'-' and a : separated list of negative patterns (tests to " "exclude). A test is run if it matches one of the positive " "patterns and does not match any of the negative patterns.")
GTEST_DEFINE_string_ (output, internal::StringFromGTestEnv("output", ""), "A format (currently must be \"xml\"), optionally followed " "by a colon and an output file name or directory. A directory " "is indicated by a trailing pathname separator. " "Examples: \"xml:filename.xml\", \"xml::directoryname/\". " "If a directory is specified, output files will be created " "within that directory, with file-names based on the test " "executable's name and, if necessary, made unique by adding " "digits.")
GTEST_DEFINE_string_ (stream_result_to, internal::StringFromGTestEnv("stream_result_to", ""), "This flag specifies the host name and the port number on which to stream " "test results. Example: \"localhost:555\". The flag is effective only on " "Linux.")
void InitGoogleTest (int *argc, char **argv)
void InitGoogleTest (int *argc, wchar_t **argv)
AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const ::std::string &needle, const ::std::string &haystack)
AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const ::std::string &needle, const ::std::string &haystack)
AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
std::ostream & operator<< (std::ostream &os, const Message &sb)
std::ostream & operator<< (std::ostream &os, const TestPartResult &result)
template<typename T >
::std::string PrintToString (const T &value)
template<typename T1 , typename T2 >
bool StaticAssertTypeEq ()
static bool TestPartFatallyFailed (const TestPartResult &result)
static bool TestPartNonfatallyFailed (const TestPartResult &result)
static const char * TestPartResultTypeToString (TestPartResult::Type type)
bool ValidateTestPropertyName (const std::string &property_name, const std::vector< std::string > &reserved_names)
Constants
__pad0__
static const char kDeathTestCaseFilter [] = "*DeathTest:*DeathTest/*"
static const char kDefaultDeathTestStyle [] = "fast"
static const char kDefaultOutputFile [] = "test_detail.xml"
static const char kDisableTestFilter [] = "DISABLED_*:*/DISABLED_*"
const int kMaxStackTraceDepth = 100
static const char *const kReservedTestCaseAttributes []
static const char *const kReservedTestSuiteAttributes []
static const char *const kReservedTestSuitesAttributes []
static const char kTestShardIndex [] = "GTEST_SHARD_INDEX"
static const char kTestShardStatusFile [] = "GTEST_SHARD_STATUS_FILE"
static const char kTestTotalShards [] = "GTEST_TOTAL_SHARDS"
static const char kUniversalFilter [] = "*"
Function Documentation
AddGlobalTestEnvironment()
Environment* testing::AddGlobalTestEnvironment (Environment * env) package
Definition at line 1350 of file gtest.h.
{
   return UnitTest::GetInstance()->AddEnvironment(env);
 }
ArrayAsVector()
std::vector<std::string> testing::ArrayAsVector (const char *const (&) array[kSize])
Definition at line 2108 of file gtest.cc.
{
   return std::vector<std::string>(array, array + kSize);
 }
Referenced by GetReservedAttributesForElement().
AssertionFailure() [1/2]
GTEST_API_ AssertionResult AssertionFailure ()
Definition at line 1015 of file gtest.cc.
{
   return AssertionResult(false);
 }
Referenced by AssertionFailure(), AssertPred1Helper(), AssertPred2Helper(), AssertPred3Helper(), AssertPred4Helper(), AssertPred5Helper(), testing::internal::CmpHelperOpFailure(), testing::internal::CmpHelperSTRNE(), testing::internal::DoubleNearPredFormat(), testing::internal::EqFailure(), testing::internal::FloatingPointLE(), testing::internal::HasOneFailure(), and testing::anonymous_namespace{gtest.cc}::IsSubstringImpl().
AssertionFailure() [2/2]
GTEST_API_ AssertionResult AssertionFailure (const Message & message)
Definition at line 1021 of file gtest.cc.
{
   return AssertionFailure() << message;
 }
References AssertionFailure().
AssertionSuccess()
GTEST_API_ AssertionResult AssertionSuccess ()
Definition at line 1010 of file gtest.cc.
{
   return AssertionResult(true);
 }
Referenced by AssertPred1Helper(), AssertPred2Helper(), AssertPred3Helper(), AssertPred4Helper(), AssertPred5Helper(), testing::internal::CmpHelperEQ(), testing::internal::CmpHelperFloatingPointEQ(), testing::internal::CmpHelperSTREQ(), testing::internal::CmpHelperSTRNE(), testing::internal::DoubleNearPredFormat(), testing::internal::FloatingPointLE(), testing::internal::GTEST_IMPL_CMP_HELPER_(), testing::internal::HasOneFailure(), and testing::anonymous_namespace{gtest.cc}::IsSubstringImpl().
DoubleLE()
GTEST_API_ AssertionResult DoubleLE (const char * expr1, const char * expr2, double val1, double val2)
Definition at line 1428 of file gtest.cc.
{
   return internal::FloatingPointLE<double>(expr1, expr2, val1, val2);
 }
FloatLE()
GTEST_API_ AssertionResult FloatLE (const char * expr1, const char * expr2, float val1, float val2)
Definition at line 1421 of file gtest.cc.
{
   return internal::FloatingPointLE<float>(expr1, expr2, val1, val2);
 }
FormatCountableNoun()
static std::string testing::FormatCountableNoun (int count, const char * singular_form, const char * plural_form) static
Definition at line 2809 of file gtest.cc.
{
   return internal::StreamableToString(count) + " " +
       (count == 1 ? singular_form : plural_form);
 }
References testing::internal::StreamableToString().
Referenced by FormatTestCaseCount(), FormatTestCount(), PrettyUnitTestResultPrinter::OnTestCaseEnd(), and PrettyUnitTestResultPrinter::OnTestCaseStart().
FormatTestCaseCount()
static std::string testing::FormatTestCaseCount (int test_case_count) static
Definition at line 2822 of file gtest.cc.
{
   return FormatCountableNoun(test_case_count, "test case", "test cases");
 }
References FormatCountableNoun().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd(), and PrettyUnitTestResultPrinter::OnTestIterationStart().
FormatTestCount()
static std::string testing::FormatTestCount (int test_count) static
Definition at line 2817 of file gtest.cc.
{
   return FormatCountableNoun(test_count, "test", "tests");
 }
References FormatCountableNoun().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd(), and PrettyUnitTestResultPrinter::OnTestIterationStart().
FormatWordList()
static std::string testing::FormatWordList (const std::vector< std::string > & words) static
Definition at line 2127 of file gtest.cc.
{
   Message word_list;
   for (size_t i = 0; i < words.size(); ++i) {
     if (i > 0 && words.size() > 2) {
       word_list << ", ";
     }
     if (i == words.size() - 1) {
       word_list << "and ";
     }
     word_list << "'" << words[i] << "'";
   }
   return word_list.GetString();
 }
References Message::GetString(), and vector< T >::size().
Referenced by ValidateTestPropertyName().
GetDefaultFilter()
static const char* testing::GetDefaultFilter () static
Definition at line 192 of file gtest.cc.
{
 #ifdef GTEST_TEST_FILTER_ENV_VAR_
   const char* const testbridge_test_only = getenv(GTEST_TEST_FILTER_ENV_VAR_);
   if (testbridge_test_only != NULL) {
     return testbridge_test_only;
   }
 #endif  // GTEST_TEST_FILTER_ENV_VAR_
   return kUniversalFilter;
 }
References kUniversalFilter.
GetReservedAttributesForElement()
static std::vector<std::string> testing::GetReservedAttributesForElement (const std::string & xml_element) static
Definition at line 2112 of file gtest.cc.
{
   if (xml_element == "testsuites") {
     return ArrayAsVector(kReservedTestSuitesAttributes);
   } else if (xml_element == "testsuite") {
     return ArrayAsVector(kReservedTestSuiteAttributes);
   } else if (xml_element == "testcase") {
     return ArrayAsVector(kReservedTestCaseAttributes);
   } else {
     GTEST_CHECK_(false) << "Unrecognized xml_element provided: " << xml_element;
   }
   // This code is unreachable but some compilers may not realizes that.
   return std::vector<std::string>();
 }
References ArrayAsVector(), GTEST_CHECK_, kReservedTestCaseAttributes, kReservedTestSuiteAttributes, and kReservedTestSuitesAttributes.
Referenced by XmlUnitTestResultPrinter::OutputXmlAttribute(), and TestResult::ValidateTestProperty().
GTEST_DECLARE_bool_() [1/9]
testing::GTEST_DECLARE_bool_ (also_run_disabled_tests)
GTEST_DECLARE_bool_() [2/9]
testing::GTEST_DECLARE_bool_ (break_on_failure)
GTEST_DECLARE_bool_() [3/9]
testing::GTEST_DECLARE_bool_ (catch_exceptions)
GTEST_DECLARE_bool_() [4/9]
testing::GTEST_DECLARE_bool_ (death_test_use_fork)
GTEST_DECLARE_bool_() [5/9]
testing::GTEST_DECLARE_bool_ (list_tests)
GTEST_DECLARE_bool_() [6/9]
testing::GTEST_DECLARE_bool_ (print_time)
GTEST_DECLARE_bool_() [7/9]
testing::GTEST_DECLARE_bool_ (show_internal_stack_frames)
GTEST_DECLARE_bool_() [8/9]
testing::GTEST_DECLARE_bool_ (shuffle)
GTEST_DECLARE_bool_() [9/9]
testing::GTEST_DECLARE_bool_ (throw_on_failure)
GTEST_DECLARE_int32_() [1/3]
testing::GTEST_DECLARE_int32_ (random_seed)
GTEST_DECLARE_int32_() [2/3]
testing::GTEST_DECLARE_int32_ (repeat)
GTEST_DECLARE_int32_() [3/3]
testing::GTEST_DECLARE_int32_ (stack_trace_depth)
GTEST_DECLARE_string_() [1/5]
testing::GTEST_DECLARE_string_ (color)
GTEST_DECLARE_string_() [2/5]
testing::GTEST_DECLARE_string_ (death_test_style)
GTEST_DECLARE_string_() [3/5]
testing::GTEST_DECLARE_string_ (filter)
GTEST_DECLARE_string_() [4/5]
testing::GTEST_DECLARE_string_ (output)
GTEST_DECLARE_string_() [5/5]
testing::GTEST_DECLARE_string_ (stream_result_to)
GTEST_DEFINE_bool_() [1/9]
testing::GTEST_DEFINE_bool_ (also_run_disabled_tests , internal::BoolFromGTestEnv("also_run_disabled_tests", false) , "Run disabled tests too, in addition to the tests normally being run.")
GTEST_DEFINE_bool_() [2/9]
testing::GTEST_DEFINE_bool_ (break_on_failure , internal::BoolFromGTestEnv("break_on_failure", false) , "True iff a failed assertion should be a debugger break-point.")
GTEST_DEFINE_bool_() [3/9]
testing::GTEST_DEFINE_bool_ (catch_exceptions , internal::BoolFromGTestEnv("catch_exceptions", true) , "True iff " GTEST_NAME_ " should catch exceptions and treat them as test failures.")
GTEST_DEFINE_bool_() [4/9]
testing::GTEST_DEFINE_bool_ (death_test_use_fork , internal::BoolFromGTestEnv("death_test_use_fork", false) , "Instructs to use fork()/_exit() instead of clone() in death tests. " "Ignored and always uses fork() on POSIX systems where clone() is not " "implemented. Useful when running under valgrind or similar tools if " "those do not support clone(). Valgrind 3.3.1 will just fail if " "it sees an unsupported combination of clone() flags. " "It is not recommended to use this flag w/o valgrind though it will " "work in 99% of the cases. Once valgrind is fixed, this flag will " "most likely be removed.")
GTEST_DEFINE_bool_() [5/9]
testing::GTEST_DEFINE_bool_ (list_tests , false , "List all tests without running them.")
GTEST_DEFINE_bool_() [6/9]
testing::GTEST_DEFINE_bool_ (print_time , internal::BoolFromGTestEnv("print_time", true) , "True iff " GTEST_NAME_ " should display elapsed time in text output.")
GTEST_DEFINE_bool_() [7/9]
testing::GTEST_DEFINE_bool_ (show_internal_stack_frames , false , "True iff " GTEST_NAME_ " should include internal stack frames when " "printing test failure stack traces.")
GTEST_DEFINE_bool_() [8/9]
testing::GTEST_DEFINE_bool_ (shuffle , internal::BoolFromGTestEnv("shuffle", false) , "True iff " GTEST_NAME_ " should randomize tests' order on every run.")
GTEST_DEFINE_bool_() [9/9]
testing::GTEST_DEFINE_bool_ (throw_on_failure , internal::BoolFromGTestEnv("throw_on_failure", false) , "When this flag is specified, a failed assertion will throw an exception " "if exceptions are enabled or exit the program with a non-zero code " "otherwise.")
GTEST_DEFINE_int32_() [1/3]
testing::GTEST_DEFINE_int32_ (random_seed , internal::Int32FromGTestEnv("random_seed", 0) , "Random number seed to use when shuffling test orders. Must be in range " " [1, 99999], or 0 to use a seed based on the current time.")
GTEST_DEFINE_int32_() [2/3]
testing::GTEST_DEFINE_int32_ (repeat , internal::Int32FromGTestEnv("repeat", 1) , "How many times to repeat each test. Specify a negative number " "for repeating forever. Useful for shaking out flaky tests.")
GTEST_DEFINE_int32_() [3/3]
testing::GTEST_DEFINE_int32_ (stack_trace_depth , internal::Int32FromGTestEnv("stack_trace_depth", kMaxStackTraceDepth) , "The maximum number of stack frames to print when an " "assertion fails. The valid range is 0 through 100, inclusive.")
GTEST_DEFINE_string_() [1/5]
testing::GTEST_DEFINE_string_ (color , internal::StringFromGTestEnv("color", "auto") , "Whether to use colors in the output. Valid values: yes, no , " "and auto. 'auto' means to use colors if the output is " "being sent to a terminal and the TERM environment variable " "is set to a terminal type that supports colors.")
GTEST_DEFINE_string_() [2/5]
testing::GTEST_DEFINE_string_ (death_test_style , internal::StringFromGTestEnv("death_test_style", kDefaultDeathTestStyle) , "Indicates how to run a death test in a forked child process: " "\"threadsafe\" (child process re-executes the test binary " "from the beginning, running only the specific death test) or " "\"fast\" (child process runs the death test immediately " "after forking).")
GTEST_DEFINE_string_() [3/5]
testing::GTEST_DEFINE_string_ (filter , internal::StringFromGTestEnv("filter", GetDefaultFilter()) , "A colon-separated list of glob (not regex) patterns " "for filtering the tests to run, optionally followed by a " "'-' and a :separated list of negative patterns(tests to " "exclude). A test is run if it matches one of the positive " "patterns and does not match any of the negative patterns.")
GTEST_DEFINE_string_() [4/5]
testing::GTEST_DEFINE_string_ (output , internal::StringFromGTestEnv("output", "") , "A format currently must be \"xml\", optionally followed " "by a colon and an output file name or directory. A directory " "is indicated by a trailing pathname separator. " "Examples:\"xml:filename.xml\" , \"xml::directoryname/\". " "If a directory is specified, output files will be created " "within that directory, with file-names based on the test " "executable 's name and, if necessary, made unique by adding " "digits.")
GTEST_DEFINE_string_() [5/5]
testing::GTEST_DEFINE_string_ (stream_result_to , internal::StringFromGTestEnv("stream_result_to", "") , "This flag specifies the host name and the port number on which to stream " "test results. Example: \"localhost:555\". The flag is effective only on " "Linux.")
InitGoogleTest() [1/2]
GTEST_API_ void InitGoogleTest (int * argc, char ** argv)
Definition at line 5370 of file gtest.cc.
{
 #if defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
   GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_(argc, argv);
 #else  // defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
   internal::InitGoogleTestImpl(argc, argv);
 #endif  // defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
 }
References testing::internal::InitGoogleTestImpl().
Referenced by main().
InitGoogleTest() [2/2]
GTEST_API_ void InitGoogleTest (int * argc, wchar_t ** argv)
Definition at line 5380 of file gtest.cc.
{
 #if defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
   GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_(argc, argv);
 #else  // defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
   internal::InitGoogleTestImpl(argc, argv);
 #endif  // defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
 }
References testing::internal::InitGoogleTestImpl().
IsNotSubstring() [1/3]
GTEST_API_ AssertionResult IsNotSubstring (const char * needle_expr, const char * haystack_expr, const ::std::string & needle, const ::std::string & haystack)
Definition at line 1636 of file gtest.cc.
{
   return IsSubstringImpl(false, needle_expr, haystack_expr, needle, haystack);
 }
References testing::anonymous_namespace{gtest.cc}::IsSubstringImpl().
IsNotSubstring() [2/3]
GTEST_API_ AssertionResult IsNotSubstring (const char * needle_expr, const char * haystack_expr, const char * needle, const char * haystack)
Definition at line 1618 of file gtest.cc.
{
   return IsSubstringImpl(false, needle_expr, haystack_expr, needle, haystack);
 }
References testing::anonymous_namespace{gtest.cc}::IsSubstringImpl().
IsNotSubstring() [3/3]
GTEST_API_ AssertionResult IsNotSubstring (const char * needle_expr, const char * haystack_expr, const wchar_t * needle, const wchar_t * haystack)
Definition at line 1624 of file gtest.cc.
{
   return IsSubstringImpl(false, needle_expr, haystack_expr, needle, haystack);
 }
References testing::anonymous_namespace{gtest.cc}::IsSubstringImpl().
IsSubstring() [1/3]
GTEST_API_ AssertionResult IsSubstring (const char * needle_expr, const char * haystack_expr, const ::std::string & needle, const ::std::string & haystack)
Definition at line 1630 of file gtest.cc.
{
   return IsSubstringImpl(true, needle_expr, haystack_expr, needle, haystack);
 }
References testing::anonymous_namespace{gtest.cc}::IsSubstringImpl().
IsSubstring() [2/3]
GTEST_API_ AssertionResult IsSubstring (const char * needle_expr, const char * haystack_expr, const char * needle, const char * haystack)
Definition at line 1606 of file gtest.cc.
{
   return IsSubstringImpl(true, needle_expr, haystack_expr, needle, haystack);
 }
References testing::anonymous_namespace{gtest.cc}::IsSubstringImpl().
IsSubstring() [3/3]
GTEST_API_ AssertionResult IsSubstring (const char * needle_expr, const char * haystack_expr, const wchar_t * needle, const wchar_t * haystack)
Definition at line 1612 of file gtest.cc.
{
   return IsSubstringImpl(true, needle_expr, haystack_expr, needle, haystack);
 }
References testing::anonymous_namespace{gtest.cc}::IsSubstringImpl().
operator<<() [1/2]
std::ostream& testing::operator<< (std::ostream & os, const Message & sb)
Definition at line 232 of file gtest-message.h.
{
   return os << sb.GetString();
 }
References Message::GetString().
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const TestPartResult & result)
Definition at line 58 of file gtest-test-part.cc.
{
   return os
       << result.file_name() << ":" << result.line_number() << ": "
       << (result.type() == TestPartResult::kSuccess ? "Success" :
           result.type() == TestPartResult::kFatalFailure ? "Fatal failure" :
           "Non-fatal failure") << ":\n"
       << result.message() << std::endl;
 }
References std::endl(), TestPartResult::file_name(), TestPartResult::kFatalFailure, TestPartResult::kSuccess, TestPartResult::line_number(), TestPartResult::message(), and TestPartResult::type().
PrintToString()
::std::string testing::PrintToString (const T & value)
Definition at line 980 of file gtest-printers.h.
{
   ::std::stringstream ss;
   internal::UniversalTersePrinter<T>::Print(value, &ss);
   return ss.str();
 }
References UniversalTersePrinter< T >::Print(), and stringstream::str().
Referenced by testing::internal::CmpHelperSTREQ(), testing::internal::CmpHelperSTRNE(), FormatForComparison< ToPrint, OtherOperand >::Format(), and testing::internal::GTEST_IMPL_CMP_HELPER_().
StaticAssertTypeEq()
bool testing::StaticAssertTypeEq () package
Definition at line 2150 of file gtest.h.
{
   (void)internal::StaticAssertTypeEqHelper<T1, T2>();
   return true;
 }
TestPartFatallyFailed()
static bool testing::TestPartFatallyFailed (const TestPartResult & result) static
Definition at line 2179 of file gtest.cc.
{
   return result.fatally_failed();
 }
References TestPartResult::fatally_failed().
Referenced by TestResult::HasFatalFailure().
TestPartNonfatallyFailed()
static bool testing::TestPartNonfatallyFailed (const TestPartResult & result) static
Definition at line 2189 of file gtest.cc.
{
   return result.nonfatally_failed();
 }
References TestPartResult::nonfatally_failed().
Referenced by TestResult::HasNonfatalFailure().
TestPartResultTypeToString()
static const char* testing::TestPartResultTypeToString (TestPartResult::Type type) static
Definition at line 2830 of file gtest.cc.
{
   switch (type) {
     case TestPartResult::kSuccess:
       return "Success";
     case TestPartResult::kNonFatalFailure:
     case TestPartResult::kFatalFailure:
 #ifdef _MSC_VER
       return "error: ";
 #else
       return "Failure\n";
 #endif
     default:
       return "Unknown result type";
   }
 }
References TestPartResult::kFatalFailure, TestPartResult::kNonFatalFailure, and TestPartResult::kSuccess.
Referenced by testing::internal::PrintTestPartResultToString().
ValidateTestPropertyName()
bool testing::ValidateTestPropertyName (const std::string & property_name, const std::vector< std::string > & reserved_names)
Definition at line 2141 of file gtest.cc.
{
   if (std::find(reserved_names.begin(), reserved_names.end(), property_name) !=
           reserved_names.end()) {
     ADD_FAILURE() << "Reserved key used in RecordProperty(): " << property_name
                   << " (" << FormatWordList(reserved_names)
                   << " are reserved by " << GTEST_NAME_ << ")";
     return false;
   }
   return true;
 }
References ADD_FAILURE, vector< T >::begin(), vector< T >::end(), std::find(), FormatWordList(), and GTEST_NAME_.
Referenced by TestResult::ValidateTestProperty().
Constant Documentation
__pad0__
__pad0__ package
Definition at line 480 of file gtest.h.
kDeathTestCaseFilter
const char kDeathTestCaseFilter[] = "*DeathTest:*DeathTest/*" static
Definition at line 165 of file gtest.cc.
Referenced by UnitTestImpl::GetTestCase().
kDefaultDeathTestStyle
const char kDefaultDeathTestStyle[] = "fast" static
Definition at line 84 of file gtest-death-test.cc.
kDefaultOutputFile
const char kDefaultOutputFile[] = "test_detail.xml" static
Definition at line 171 of file gtest.cc.
Referenced by UnitTestOptions::GetAbsolutePathToOutputFile().
kDisableTestFilter
const char kDisableTestFilter[] = "DISABLED_*:*/DISABLED_*" static
Definition at line 160 of file gtest.cc.
Referenced by UnitTestImpl::FilterTests().
kMaxStackTraceDepth
const int kMaxStackTraceDepth = 100
Definition at line 147 of file gtest.h.
kReservedTestCaseAttributes
const char* const kReservedTestCaseAttributes[] static
Initial value:
= {
  "classname",
  "name",
  "status",
  "time",
  "type_param",
  "value_param"
}
Definition at line 2098 of file gtest.cc.
Referenced by GetReservedAttributesForElement().
kReservedTestSuiteAttributes
const char* const kReservedTestSuiteAttributes[] static
Initial value:
= {
  "disabled",
  "errors",
  "failures",
  "name",
  "tests",
  "time"
}
Definition at line 2088 of file gtest.cc.
Referenced by GetReservedAttributesForElement().
kReservedTestSuitesAttributes
const char* const kReservedTestSuitesAttributes[] static
Initial value:
= {
  "disabled",
  "errors",
  "failures",
  "name",
  "random_seed",
  "tests",
  "time",
  "timestamp"
}
Definition at line 2075 of file gtest.cc.
Referenced by GetReservedAttributesForElement().
kTestShardIndex
const char kTestShardIndex[] = "GTEST_SHARD_INDEX" static
Definition at line 174 of file gtest.cc.
Referenced by UnitTestImpl::FilterTests(), PrettyUnitTestResultPrinter::OnTestIterationStart(), UnitTestImpl::RunAllTests(), and testing::internal::ShouldShard().
kTestShardStatusFile
const char kTestShardStatusFile[] = "GTEST_SHARD_STATUS_FILE" static
Definition at line 178 of file gtest.cc.
Referenced by testing::internal::WriteToShardStatusFileIfNeeded().
kTestTotalShards
const char kTestTotalShards[] = "GTEST_TOTAL_SHARDS" static
Definition at line 176 of file gtest.cc.
Referenced by UnitTestImpl::FilterTests(), PrettyUnitTestResultPrinter::OnTestIterationStart(), UnitTestImpl::RunAllTests(), and testing::internal::ShouldShard().
kUniversalFilter
const char kUniversalFilter[] = "*" static
Definition at line 168 of file gtest.cc.
Referenced by UnitTestOptions::FilterMatchesTest(), GetDefaultFilter(), and PrettyUnitTestResultPrinter::OnTestIterationStart().