Common Alogrithm: testing::operator<<
operator<<()
std::ostream & operator<< (std::ostream & os, const TestPartResult & result)
{
   return os
       << result.file_name() << ":" << result.line_number() << ": "
       << (result.type() == TestPartResult::kSuccess ? "Success" :
           result.type() == TestPartResult::kFatalFailure ? "Fatal failure" :
           "Non-fatal failure") << ":\n"
       << result.message() << std::endl;
 }
References std::endl(), TestPartResult::file_name(), TestPartResult::kFatalFailure, TestPartResult::kSuccess, TestPartResult::line_number(), TestPartResult::message(), and TestPartResult::type().