Common Alogrithm: testing::FormatTestCaseCount
FormatTestCaseCount()
static std::string testing::FormatTestCaseCount (int test_case_count) static
{
   return FormatCountableNoun(test_case_count, "test case", "test cases");
 }
References testing::FormatCountableNoun().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd(), and PrettyUnitTestResultPrinter::OnTestIterationStart().