Common Alogrithm: testing::GetReservedAttributesForElement
GetReservedAttributesForElement()
static std::vector<std::string> testing::GetReservedAttributesForElement (const std::string & xml_element) static
{
   if (xml_element == "testsuites") {
     return ArrayAsVector(kReservedTestSuitesAttributes);
   } else if (xml_element == "testsuite") {
     return ArrayAsVector(kReservedTestSuiteAttributes);
   } else if (xml_element == "testcase") {
     return ArrayAsVector(kReservedTestCaseAttributes);
   } else {
     GTEST_CHECK_(false) << "Unrecognized xml_element provided: " << xml_element;
   }
   // This code is unreachable but some compilers may not realizes that.
   return std::vector<std::string>();
 }
References testing::ArrayAsVector(), GTEST_CHECK_, testing::kReservedTestCaseAttributes, testing::kReservedTestSuiteAttributes, and testing::kReservedTestSuitesAttributes.
Referenced by XmlUnitTestResultPrinter::OutputXmlAttribute(), and TestResult::ValidateTestProperty().