Common Alogrithm: testing::ValidateTestPropertyName
ValidateTestPropertyName()
bool testing::ValidateTestPropertyName (const std::string & property_name, const std::vector< std::string > & reserved_names)
{
   if (std::find(reserved_names.begin(), reserved_names.end(), property_name) !=
           reserved_names.end()) {
     ADD_FAILURE() << "Reserved key used in RecordProperty(): " << property_name
                   << " (" << FormatWordList(reserved_names)
                   << " are reserved by " << GTEST_NAME_ << ")";
     return false;
   }
   return true;
 }
References ADD_FAILURE, vector< T >::begin(), vector< T >::end(), std::find(), testing::FormatWordList(), and GTEST_NAME_.
Referenced by TestResult::ValidateTestProperty().