Common Alogrithm: testing::internal::edit_distance::CalculateOptimalEdits
CalculateOptimalEdits() [1/2]
GTEST_API_ std::vector< EditType > CalculateOptimalEdits (const std::vector< size_t > & left, const std::vector< size_t > & right)
{
   std::vector<std::vector<double> > costs(
       left.size() + 1, std::vector<double>(right.size() + 1));
   std::vector<std::vector<EditType> > best_move(
       left.size() + 1, std::vector<EditType>(right.size() + 1));
   // Populate for empty right.
   for (size_t l_i = 0; l_i < costs.size(); ++l_i) {
     costs[l_i][0] = static_cast<double>(l_i);
     best_move[l_i][0] = kRemove;
   }
   // Populate for empty left.
   for (size_t r_i = 1; r_i < costs[0].size(); ++r_i) {
     costs[0][r_i] = static_cast<double>(r_i);
     best_move[0][r_i] = kAdd;
   }
   for (size_t l_i = 0; l_i < left.size(); ++l_i) {
     for (size_t r_i = 0; r_i < right.size(); ++r_i) {
       if (left[l_i] == right[r_i]) {
         // Found a match. Consume it.
         costs[l_i + 1][r_i + 1] = costs[l_i][r_i];
         best_move[l_i + 1][r_i + 1] = kMatch;
         continue;
       }
       const double add = costs[l_i + 1][r_i];
       const double remove = costs[l_i][r_i + 1];
       const double replace = costs[l_i][r_i];
       if (add < remove && add < replace) {
         costs[l_i + 1][r_i + 1] = add + 1;
         best_move[l_i + 1][r_i + 1] = kAdd;
       } else if (remove < add && remove < replace) {
         costs[l_i + 1][r_i + 1] = remove + 1;
         best_move[l_i + 1][r_i + 1] = kRemove;
       } else {
         // We make replace a little more expensive than add/remove to lower
         // their priority.
         costs[l_i + 1][r_i + 1] = replace + 1.00001;
         best_move[l_i + 1][r_i + 1] = kReplace;
       }
     }
   }
   // Reconstruct the best path. We do it in reverse order.
   std::vector<EditType> best_path;
   for (size_t l_i = left.size(), r_i = right.size(); l_i > 0 || r_i > 0;) {
     EditType move = best_move[l_i][r_i];
     best_path.push_back(move);
     l_i -= move != kAdd;
     r_i -= move != kRemove;
   }
   std::reverse(best_path.begin(), best_path.end());
   return best_path;
 }
References vector< T >::begin(), vector< T >::end(), testing::internal::edit_distance::kAdd, testing::internal::edit_distance::kMatch, testing::internal::edit_distance::kRemove, testing::internal::edit_distance::kReplace, testing::internal::move(), vector< T >::push_back(), std::reverse(), and vector< T >::size().
Referenced by testing::internal::edit_distance::CalculateOptimalEdits(), and testing::internal::edit_distance::CreateUnifiedDiff().