Common Alogrithm: testing::internal::edit_distance::CreateUnifiedDiff
CreateUnifiedDiff()
GTEST_API_ std::string CreateUnifiedDiff (const std::vector< std::string > & left, const std::vector< std::string > & right, size_t context)
{
   const std::vector<EditType> edits = CalculateOptimalEdits(left, right);
   size_t l_i = 0, r_i = 0, edit_i = 0;
   std::stringstream ss;
   while (edit_i < edits.size()) {
     // Find first edit.
     while (edit_i < edits.size() && edits[edit_i] == kMatch) {
       ++l_i;
       ++r_i;
       ++edit_i;
     }
     // Find the first line to include in the hunk.
     const size_t prefix_context = std::min(l_i, context);
     Hunk hunk(l_i - prefix_context + 1, r_i - prefix_context + 1);
     for (size_t i = prefix_context; i > 0; --i) {
       hunk.PushLine(' ', left[l_i - i].c_str());
     }
     // Iterate the edits until we found enough suffix for the hunk or the input
     // is over.
     size_t n_suffix = 0;
     for (; edit_i < edits.size(); ++edit_i) {
       if (n_suffix >= context) {
         // Continue only if the next hunk is very close.
         std::vector<EditType>::const_iterator it = edits.begin() + edit_i;
         while (it != edits.end() && *it == kMatch) ++it;
         if (it == edits.end() || (it - edits.begin()) - edit_i >= context) {
           // There is no next edit or it is too far away.
           break;
         }
       }
       EditType edit = edits[edit_i];
       // Reset count when a non match is found.
       n_suffix = edit == kMatch ? n_suffix + 1 : 0;
       if (edit == kMatch || edit == kRemove || edit == kReplace) {
         hunk.PushLine(edit == kMatch ? ' ' : '-', left[l_i].c_str());
       }
       if (edit == kAdd || edit == kReplace) {
         hunk.PushLine('+', right[r_i].c_str());
       }
       // Advance indices, depending on edit type.
       l_i += edit != kAdd;
       r_i += edit != kRemove;
     }
     if (!hunk.has_edits()) {
       // We are done. We don't want this hunk.
       break;
     }
     hunk.PrintTo(&ss);
   }
   return ss.str();
 }
References vector< T >::begin(), testing::internal::edit_distance::CalculateOptimalEdits(), vector< T >::end(), testing::internal::edit_distance::kAdd, testing::internal::edit_distance::kMatch, testing::internal::edit_distance::kRemove, testing::internal::edit_distance::kReplace, std::min(), vector< T >::size(), and stringstream::str().
Referenced by testing::internal::EqFailure().