Common Alogrithm: lib/googletest/test/gtest_premature_exit_test.cc File Reference
gtest_premature_exit_test.cc File Reference
(d4ab02d08ceed19dab4276c86042b1520529304b)
#include <stdio.h>
#include "gtest/gtest.h"
Classes
class PrematureExitTest
Namespaces
anonymous_namespace{gtest_premature_exit_test.cc}
Typedefs
typedef PrematureExitTest PrematureExitDeathTest
Functions
int main (int argc, char **argv)
TEST_F (PrematureExitDeathTest, FileExistsDuringExecutionOfDeathTest)
TEST_F (PrematureExitTest, PrematureExitFileExistsDuringTestExecution)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 110 of file gtest_premature_exit_test.cc.
{
   InitGoogleTest(&argc, argv);
   const int exit_code = RUN_ALL_TESTS();
   // Test that the premature-exit file is deleted upon return from
   // RUN_ALL_TESTS().
   const char* const filepath = GetEnv("TEST_PREMATURE_EXIT_FILE");
   if (filepath != NULL && *filepath != '\0') {
     if (PrematureExitTest::FileExists(filepath)) {
       printf(
           "File %s shouldn't exist after the test program finishes, but does.",
           filepath);
       return 1;
     }
   }
   return exit_code;
 }
References testing::internal::posix::GetEnv(), testing::InitGoogleTest(), and RUN_ALL_TESTS().