Common Alogrithm: Facade::MethodA
MethodA()
void MethodA ()
     {
         std::cout << "\nMethodA() ---- " << std::endl;
         one.MethodOne();
         two.MethodTwo();
         four.MethodFour();
     }
References std::endl(), four, SubSystemFour::MethodFour(), SubSystemOne::MethodOne(), SubSystemTwo::MethodTwo(), one, and two.
Referenced by main().