Common Alogrithm: Facade::MethodB
MethodB()
void MethodB ()
     {
         std::cout << "\nMethodB() ---- " << std::endl;
         two.MethodTwo();
         three.MethodThree();
     }
References std::endl(), SubSystemThree::MethodThree(), SubSystemTwo::MethodTwo(), three, and two.
Referenced by main().