Common Alogrithm: UnitTest Class Reference
UnitTest Class Reference
#include <gtest.h>
Public Member Functions
const TestResult & ad_hoc_test_result () const
const TestCase * current_test_case () const GTEST_LOCK_EXCLUDED_(mutex_)
const TestInfo * current_test_info () const GTEST_LOCK_EXCLUDED_(mutex_)
int disabled_test_count () const
TimeInMillis elapsed_time () const
bool Failed () const
int failed_test_case_count () const
int failed_test_count () const
const TestCase * GetTestCase (int i) const
TestEventListeners & listeners ()
const char * original_working_dir () const
bool Passed () const
int random_seed () const
int reportable_disabled_test_count () const
int reportable_test_count () const
int Run () GTEST_MUST_USE_RESULT_
TimeInMillis start_timestamp () const
int successful_test_case_count () const
int successful_test_count () const
int test_case_to_run_count () const
int test_to_run_count () const
int total_test_case_count () const
int total_test_count () const
Static Public Member Functions
static UnitTest * GetInstance ()
Package Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTest)
void PopGTestTrace () GTEST_LOCK_EXCLUDED_(mutex_)
void PushGTestTrace (const internal::TraceInfo &trace) GTEST_LOCK_EXCLUDED_(mutex_)
UnitTest ()
virtual ~UnitTest ()
Package Attributes
__pad0__:UnitTestImpl* impl() const { return impl_
__pad1__:UnitTestImpl* internal::GetUnitTestImpl()
__pad2__:ReportFailureInUnknownLocation(TestPartResult::Type result_type
internal::UnitTestImpl * impl_
const std::string & message
internal::Mutex mutex_
Private Member Functions
Environment * AddEnvironment (Environment *env)
void AddTestPartResult (TestPartResult::Type result_type, const char *file_name, int line_number, const std::string &message, const std::string &os_stack_trace) GTEST_LOCK_EXCLUDED_(mutex_)
TestCase * GetMutableTestCase (int i)
internal::UnitTestImpl * impl ()
void RecordProperty (const std::string &key, const std::string &value)
Friends
Environment * AddGlobalTestEnvironment (Environment *env)
class internal::AssertHelper
class internal::ScopedTrace
class internal::StreamingListenerTest
class internal::UnitTestRecordPropertyTestHelper
class Test
Detailed Description
Definition at line 1151 of file gtest.h.
Constructor & Destructor Documentation
UnitTest()
UnitTest () package
Definition at line 4299 of file gtest.cc.
                    {
   impl_ = new internal::UnitTestImpl(this);
 }
References UnitTest::impl_.
Referenced by UnitTest::GetInstance().
~UnitTest()
~UnitTest () package virtual
Definition at line 4304 of file gtest.cc.
                     {
   delete impl_;
 }
References UnitTest::impl_.
Member Function Documentation
ad_hoc_test_result()
const TestResult & ad_hoc_test_result () const
Definition at line 4069 of file gtest.cc.
{
   return *impl()->ad_hoc_test_result();
 }
References UnitTestImpl::ad_hoc_test_result(), and UnitTest::impl().
Referenced by XmlUnitTestResultPrinter::PrintXmlUnitTest().
AddEnvironment()
Environment * AddEnvironment (Environment * env) private
Definition at line 4095 of file gtest.cc.
{
   if (env == NULL) {
     return NULL;
   }
   impl_->environments().push_back(env);
   return env;
 }
References UnitTestImpl::environments(), and UnitTest::impl_.
AddTestPartResult()
void AddTestPartResult (TestPartResult::Type result_type, const char * file_name, int line_number, const std::string & message, const std::string & os_stack_trace) private
Definition at line 4108 of file gtest.cc.
{
   Message msg;
   msg << message;
   internal::MutexLock lock(&mutex_);
   if (impl_->gtest_trace_stack().size() > 0) {
     msg << "\n" << GTEST_NAME_ << " trace:";
     for (int i = static_cast<int>(impl_->gtest_trace_stack().size());
          i > 0; --i) {
       const internal::TraceInfo& trace = impl_->gtest_trace_stack()[i - 1];
       msg << "\n" << internal::FormatFileLocation(trace.file, trace.line)
           << " " << trace.message;
     }
   }
   if (os_stack_trace.c_str() != NULL && !os_stack_trace.empty()) {
     msg << internal::kStackTraceMarker << os_stack_trace;
   }
   const TestPartResult result =
     TestPartResult(result_type, file_name, line_number,
                    msg.GetString().c_str());
   impl_->GetTestPartResultReporterForCurrentThread()->
       ReportTestPartResult(result);
   if (result_type != TestPartResult::kSuccess) {
     // gtest_break_on_failure takes precedence over
     // gtest_throw_on_failure.  This allows a user to set the latter
     // in the code (perhaps in order to use Google Test assertions
     // with another testing framework) and specify the former on the
     // command line for debugging.
     if (GTEST_FLAG(break_on_failure)) {
 #if GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_PHONE && !GTEST_OS_WINDOWS_RT
       // Using DebugBreak on Windows allows gtest to still break into a debugger
       // when a failure happens and both the --gtest_break_on_failure and
       // the --gtest_catch_exceptions flags are specified.
       DebugBreak();
 #else
       // Dereference NULL through a volatile pointer to prevent the compiler
       // from removing. We use this rather than abort() or __builtin_trap() for
       // portability: Symbian doesn't implement abort() well, and some debuggers
       // don't correctly trap abort().
       *static_cast<volatile int*>(NULL) = 1;
 #endif  // GTEST_OS_WINDOWS
     } else if (GTEST_FLAG(throw_on_failure)) {
 #if GTEST_HAS_EXCEPTIONS
       throw internal::GoogleTestFailureException(result);
 #else
       // We cannot call abort() as it generates a pop-up in debug mode
       // that cannot be suppressed in VC 7.1 or below.
       exit(1);
 #endif
     }
   }
 }
References string::c_str(), TraceInfo::file, testing::internal::FormatFileLocation(), Message::GetString(), GTEST_FLAG, GTEST_NAME_, testing::internal::kStackTraceMarker, TestPartResult::kSuccess, TraceInfo::line, and TraceInfo::message.
Referenced by testing::internal::ReportFailureInUnknownLocation().
current_test_case()
const TestCase * current_test_case () const
Definition at line 4271 of file gtest.cc.
{
   internal::MutexLock lock(&mutex_);
   return impl_->current_test_case();
 }
References UnitTestImpl::current_test_case(), UnitTest::impl_, and UnitTest::mutex_.
current_test_info()
const TestInfo * current_test_info () const
Definition at line 4279 of file gtest.cc.
{
   internal::MutexLock lock(&mutex_);
   return impl_->current_test_info();
 }
References UnitTestImpl::current_test_info(), UnitTest::impl_, and UnitTest::mutex_.
disabled_test_count()
int disabled_test_count () const
Definition at line 4028 of file gtest.cc.
{
   return impl()->disabled_test_count();
 }
References UnitTestImpl::disabled_test_count(), and UnitTest::impl().
elapsed_time()
internal::TimeInMillis elapsed_time () const
Definition at line 4050 of file gtest.cc.
{
   return impl()->elapsed_time();
 }
References UnitTestImpl::elapsed_time(), and UnitTest::impl().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().
Failed()
bool Failed () const
Definition at line 4059 of file gtest.cc.
 { return impl()->Failed(); }
References UnitTestImpl::Failed(), and UnitTest::impl().
failed_test_case_count()
int failed_test_case_count () const
Definition at line 3999 of file gtest.cc.
{
   return impl()->failed_test_case_count();
 }
References UnitTestImpl::failed_test_case_count(), and UnitTest::impl().
failed_test_count()
int failed_test_count () const
Definition at line 4020 of file gtest.cc.
 { return impl()->failed_test_count(); }
References UnitTestImpl::failed_test_count(), and UnitTest::impl().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd(), PrettyUnitTestResultPrinter::PrintFailedTests(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().
GetInstance()
UnitTest * GetInstance () static
Definition at line 3972 of file gtest.cc.
{
   // When compiled with MSVC 7.1 in optimized mode, destroying the
   // UnitTest object upon exiting the program messes up the exit code,
   // causing successful tests to appear failed.  We have to use a
   // different implementation in this case to bypass the compiler bug.
   // This implementation makes the compiler happy, at the cost of
   // leaking the UnitTest object.
   // CodeGear C++Builder insists on a public destructor for the
   // default implementation.  Use this implementation to keep good OO
   // design with private destructor.
 #if (_MSC_VER == 1310 && !defined(_DEBUG)) || defined(__BORLANDC__)
   static UnitTest* const instance = new UnitTest;
   return instance;
 #else
   static UnitTest instance;
   return &instance;
 #endif  // (_MSC_VER == 1310 && !defined(_DEBUG)) || defined(__BORLANDC__)
 }
References UnitTest::UnitTest().
Referenced by UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::GetUnitTestImpl(), AssertHelper::operator=(), Test::RecordProperty(), testing::internal::ReportFailureInUnknownLocation(), TestInfo::Run(), TestCase::Run(), ScopedTrace::ScopedTrace(), and ScopedTrace::~ScopedTrace().
GetMutableTestCase()
TestCase * GetMutableTestCase (int i) private
Definition at line 4075 of file gtest.cc.
{
   return impl()->GetMutableTestCase(i);
 }
References UnitTestImpl::GetMutableTestCase(), and UnitTest::impl().
GetTestCase()
const TestCase * GetTestCase (int i) const
Definition at line 4063 of file gtest.cc.
{
   return impl()->GetTestCase(i);
 }
References UnitTestImpl::GetTestCase(), and UnitTest::impl().
Referenced by PrettyUnitTestResultPrinter::PrintFailedTests(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTest) package
impl()
internal::UnitTestImpl* impl () private
Definition at line 1287 of file gtest.h.
 { return impl_; }
Referenced by UnitTest::ad_hoc_test_result(), UnitTest::disabled_test_count(), UnitTest::elapsed_time(), UnitTest::Failed(), UnitTest::failed_test_case_count(), UnitTest::failed_test_count(), UnitTest::GetMutableTestCase(), UnitTest::GetTestCase(), testing::internal::GetUnitTestImpl(), UnitTest::listeners(), AssertHelper::operator=(), UnitTest::Passed(), UnitTest::reportable_disabled_test_count(), UnitTest::reportable_test_count(), UnitTest::Run(), UnitTest::start_timestamp(), UnitTest::successful_test_case_count(), UnitTest::successful_test_count(), UnitTest::test_case_to_run_count(), UnitTest::test_to_run_count(), UnitTest::total_test_case_count(), and UnitTest::total_test_count().
listeners()
TestEventListeners & listeners ()
Definition at line 4081 of file gtest.cc.
{
   return *impl()->listeners();
 }
References UnitTest::impl(), and UnitTestImpl::listeners().
Referenced by TestInfo::Run(), and TestCase::Run().
original_working_dir()
const char * original_working_dir () const
Definition at line 4265 of file gtest.cc.
{
   return impl_->original_working_dir_.c_str();
 }
References FilePath::c_str(), UnitTest::impl_, and UnitTestImpl::original_working_dir_.
Passed()
bool Passed () const
Definition at line 4055 of file gtest.cc.
 { return impl()->Passed(); }
References UnitTest::impl(), and UnitTestImpl::Passed().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd().
PopGTestTrace()
void PopGTestTrace () package
Definition at line 4317 of file gtest.cc.
{
   internal::MutexLock lock(&mutex_);
   impl_->gtest_trace_stack().pop_back();
 }
References UnitTestImpl::gtest_trace_stack(), UnitTest::impl_, and UnitTest::mutex_.
Referenced by ScopedTrace::~ScopedTrace().
PushGTestTrace()
void PushGTestTrace (const internal::TraceInfo & trace) package
Definition at line 4310 of file gtest.cc.
{
   internal::MutexLock lock(&mutex_);
   impl_->gtest_trace_stack().push_back(trace);
 }
Referenced by ScopedTrace::ScopedTrace().
random_seed()
int random_seed () const
Definition at line 4286 of file gtest.cc.
 { return impl_->random_seed(); }
References UnitTest::impl_, and UnitTestImpl::random_seed().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationStart(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().
RecordProperty()
void RecordProperty (const std::string & key, const std::string & value) private
Definition at line 4175 of file gtest.cc.
{
   impl_->RecordProperty(TestProperty(key, value));
 }
References UnitTest::impl_, and UnitTestImpl::RecordProperty().
Referenced by Test::RecordProperty().
reportable_disabled_test_count()
int reportable_disabled_test_count () const
Definition at line 4023 of file gtest.cc.
{
   return impl()->reportable_disabled_test_count();
 }
References UnitTest::impl(), and UnitTestImpl::reportable_disabled_test_count().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().
reportable_test_count()
int reportable_test_count () const
Definition at line 4033 of file gtest.cc.
{
   return impl()->reportable_test_count();
 }
References UnitTest::impl(), and UnitTestImpl::reportable_test_count().
Referenced by XmlUnitTestResultPrinter::PrintXmlUnitTest().
Run()
int Run ()
Definition at line 4185 of file gtest.cc.
                   {
   const bool in_death_test_child_process =
       internal::GTEST_FLAG(internal_run_death_test).length() > 0;
   // Google Test implements this protocol for catching that a test
   // program exits before returning control to Google Test:
   //
   //   1. Upon start, Google Test creates a file whose absolute path
   //      is specified by the environment variable
   //      TEST_PREMATURE_EXIT_FILE.
   //   2. When Google Test has finished its work, it deletes the file.
   //
   // This allows a test runner to set TEST_PREMATURE_EXIT_FILE before
   // running a Google-Test-based test program and check the existence
   // of the file at the end of the test execution to see if it has
   // exited prematurely.
   // If we are in the child process of a death test, don't
   // create/delete the premature exit file, as doing so is unnecessary
   // and will confuse the parent process.  Otherwise, create/delete
   // the file upon entering/leaving this function.  If the program
   // somehow exits before this function has a chance to return, the
   // premature-exit file will be left undeleted, causing a test runner
   // that understands the premature-exit-file protocol to report the
   // test as having failed.
   const internal::ScopedPrematureExitFile premature_exit_file(
       in_death_test_child_process ?
       NULL : internal::posix::GetEnv("TEST_PREMATURE_EXIT_FILE"));
   // Captures the value of GTEST_FLAG(catch_exceptions).  This value will be
   // used for the duration of the program.
   impl()->set_catch_exceptions(GTEST_FLAG(catch_exceptions));
 #if GTEST_HAS_SEH
   // Either the user wants Google Test to catch exceptions thrown by the
   // tests or this is executing in the context of death test child
   // process. In either case the user does not want to see pop-up dialogs
   // about crashes - they are expected.
   if (impl()->catch_exceptions() || in_death_test_child_process) {
 # if !GTEST_OS_WINDOWS_MOBILE && !GTEST_OS_WINDOWS_PHONE && !GTEST_OS_WINDOWS_RT
     // SetErrorMode doesn't exist on CE.
     SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOALIGNMENTFAULTEXCEPT |
                  SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
 # endif  // !GTEST_OS_WINDOWS_MOBILE
 # if (defined(_MSC_VER) || GTEST_OS_WINDOWS_MINGW) && !GTEST_OS_WINDOWS_MOBILE
     // Death test children can be terminated with _abort().  On Windows,
     // _abort() can show a dialog with a warning message.  This forces the
     // abort message to go to stderr instead.
     _set_error_mode(_OUT_TO_STDERR);
 # endif
 # if _MSC_VER >= 1400 && !GTEST_OS_WINDOWS_MOBILE
     // In the debug version, Visual Studio pops up a separate dialog
     // offering a choice to debug the aborted program. We need to suppress
     // this dialog or it will pop up for every EXPECT/ASSERT_DEATH statement
     // executed. Google Test will notify the user of any unexpected
     // failure via stderr.
     //
     // VC++ doesn't define _set_abort_behavior() prior to the version 8.0.
     // Users of prior VC versions shall suffer the agony and pain of
     // clicking through the countless debug dialogs.
     // TODO(vladl@google.com): find a way to suppress the abort dialog() in the
     // debug mode when compiled with VC 7.1 or lower.
     if (!GTEST_FLAG(break_on_failure))
       _set_abort_behavior(
           0x0,                                    // Clear the following flags:
           _WRITE_ABORT_MSG | _CALL_REPORTFAULT);  // pop-up window, core dump.
 # endif
   }
 #endif  // GTEST_HAS_SEH
   return internal::HandleExceptionsInMethodIfSupported(
       impl(),
       &internal::UnitTestImpl::RunAllTests,
       "auxiliary test code (environments or event listeners)") ? 0 : 1;
 }
References testing::internal::posix::GetEnv(), GTEST_FLAG, testing::internal::HandleExceptionsInMethodIfSupported(), UnitTest::impl(), UnitTestImpl::RunAllTests(), and UnitTestImpl::set_catch_exceptions().
start_timestamp()
internal::TimeInMillis start_timestamp () const
Definition at line 4045 of file gtest.cc.
{
     return impl()->start_timestamp();
 }
References UnitTest::impl(), and UnitTestImpl::start_timestamp().
Referenced by XmlUnitTestResultPrinter::PrintXmlUnitTest().
successful_test_case_count()
int successful_test_case_count () const
Definition at line 3994 of file gtest.cc.
{
   return impl()->successful_test_case_count();
 }
References UnitTest::impl(), and UnitTestImpl::successful_test_case_count().
successful_test_count()
int successful_test_count () const
Definition at line 4015 of file gtest.cc.
{
   return impl()->successful_test_count();
 }
References UnitTest::impl(), and UnitTestImpl::successful_test_count().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd().
test_case_to_run_count()
int test_case_to_run_count () const
Definition at line 4010 of file gtest.cc.
{
   return impl()->test_case_to_run_count();
 }
References UnitTest::impl(), and UnitTestImpl::test_case_to_run_count().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd(), and PrettyUnitTestResultPrinter::OnTestIterationStart().
test_to_run_count()
int test_to_run_count () const
Definition at line 4041 of file gtest.cc.
 { return impl()->test_to_run_count(); }
References UnitTest::impl(), and UnitTestImpl::test_to_run_count().
Referenced by PrettyUnitTestResultPrinter::OnTestIterationEnd(), and PrettyUnitTestResultPrinter::OnTestIterationStart().
total_test_case_count()
int total_test_case_count () const
Definition at line 4004 of file gtest.cc.
{
   return impl()->total_test_case_count();
 }
References UnitTest::impl(), and UnitTestImpl::total_test_case_count().
Referenced by PrettyUnitTestResultPrinter::PrintFailedTests(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().
total_test_count()
int total_test_count () const
Definition at line 4038 of file gtest.cc.
 { return impl()->total_test_count(); }
References UnitTest::impl(), and UnitTestImpl::total_test_count().
Friends And Related Function Documentation
AddGlobalTestEnvironment
Environment* AddGlobalTestEnvironment (Environment * env) friend
Definition at line 1350 of file gtest.h.
{
   return UnitTest::GetInstance()->AddEnvironment(env);
 }
internal::AssertHelper
friend class internal::AssertHelper friend
Definition at line 1293 of file gtest.h.
internal::ScopedTrace
friend class internal::ScopedTrace friend
Definition at line 1294 of file gtest.h.
internal::StreamingListenerTest
friend class internal::StreamingListenerTest friend
Definition at line 1295 of file gtest.h.
internal::UnitTestRecordPropertyTestHelper
friend class internal::UnitTestRecordPropertyTestHelper friend
Definition at line 1296 of file gtest.h.
Test
friend class Test friend
Definition at line 1292 of file gtest.h.
Member Data Documentation
__pad0__
__pad0__ package
Definition at line 1288 of file gtest.h.
__pad1__
__pad1__ package
Definition at line 1298 of file gtest.h.
__pad2__
__pad2__ package
Definition at line 1299 of file gtest.h.
impl_
internal::UnitTestImpl* impl_ package
Definition at line 1326 of file gtest.h.
Referenced by UnitTest::AddEnvironment(), UnitTest::current_test_case(), UnitTest::current_test_info(), UnitTest::original_working_dir(), UnitTest::PopGTestTrace(), UnitTest::random_seed(), UnitTest::RecordProperty(), UnitTest::UnitTest(), and UnitTest::~UnitTest().
message
const std::string& message package
Definition at line 1301 of file gtest.h.
mutex_
internal::Mutex mutex_ mutable package
Definition at line 1320 of file gtest.h.
Referenced by UnitTest::current_test_case(), UnitTest::current_test_info(), and UnitTest::PopGTestTrace().