Common Alogrithm: hash_table/hash_table_tests.h File Reference
hash_table_tests.h File Reference
(507f1dfca013d51e60369bb6d51e86175d87c82c)
#include <iostream>
#include "./hash_table.h"
Functions
void run_all_tests ()
void test_add_exists ()
void test_get ()
void test_probing ()
void test_remove ()
Function Documentation
run_all_tests()
void run_all_tests ()
Definition at line 3 of file hash_table_tests.cc.
                      {
     test_add_exists();
     test_probing();
     test_get();
     test_remove();
 }
References test_add_exists(), test_get(), test_probing(), and test_remove().
Referenced by main().
test_add_exists()
void test_add_exists ()
Definition at line 10 of file hash_table_tests.cc.
{
     common::HashTable states(100);
     common::HashObject tx;
     tx.SetKey("Texas");
     tx.SetValue("Austin");
     states.Add(&tx);
     assert(states.Exists("Texas"));
 }
References HashTable::Add(), HashTable::Exists(), HashObject::SetKey(), and HashObject::SetValue().
Referenced by run_all_tests().
test_get()
void test_get ()
Definition at line 60 of file hash_table_tests.cc.
                 {
     common::HashTable states(100);
     common::HashObject tx;
     tx.SetKey("Texas");
     tx.SetValue("Austin");
     states.Add(&tx);
     assert(states.Get("Texas") == "Austin");
 }
References HashTable::Add(), HashTable::Get(), HashObject::SetKey(), and HashObject::SetValue().
Referenced by run_all_tests().
test_probing()
void test_probing ()
Definition at line 22 of file hash_table_tests.cc.
                     {
     common::HashTable states(8);
     common::HashObject tx;
     tx.SetKey("Texas");
     tx.SetValue("Austin");
     common::HashObject ca;
     ca.SetKey("California");
     ca.SetValue("Sacramento");
     common::HashObject nm;
     nm.SetKey("New Mexico");
     nm.SetValue("Santa Fe");
     common::HashObject fl;
     fl.SetKey("Florida");
     fl.SetValue("Tallahassee");
     common::HashObject oregon;
     oregon.SetKey("Oregon");
     oregon.SetValue("Salem");
     states.Add(&tx);
     states.Add(&ca);
     states.Add(&nm);
     states.Add(&fl);
     states.Add(&oregon);
     states.PringDebug();
     assert(states.Exists("California"));
     assert(states.Exists("New Mexico"));
     assert(states.Exists("Florida"));
     assert(states.Exists("Oregon"));
 }
References HashTable::Add(), HashTable::Exists(), HashTable::PringDebug(), HashObject::SetKey(), and HashObject::SetValue().
Referenced by run_all_tests().
test_remove()
void test_remove ()
Definition at line 72 of file hash_table_tests.cc.
                    {
     common::HashTable states(3);
     common::HashObject tx;
     tx.SetKey("Texas");
     tx.SetValue("Austin");
     states.Add(&tx);
     assert(states.Exists("Texas"));
     states.Remove("Texas");
     assert(!states.Exists("Texas"));
     states.PringDebug();
 }
References HashTable::Add(), HashTable::Exists(), HashTable::PringDebug(), HashTable::Remove(), HashObject::SetKey(), and HashObject::SetValue().
Referenced by run_all_tests().