Common Alogrithm: test_probing
test_probing()
void test_probing ()
                     {
     common::HashTable states(8);
     common::HashObject tx;
     tx.SetKey("Texas");
     tx.SetValue("Austin");
     common::HashObject ca;
     ca.SetKey("California");
     ca.SetValue("Sacramento");
     common::HashObject nm;
     nm.SetKey("New Mexico");
     nm.SetValue("Santa Fe");
     common::HashObject fl;
     fl.SetKey("Florida");
     fl.SetValue("Tallahassee");
     common::HashObject oregon;
     oregon.SetKey("Oregon");
     oregon.SetValue("Salem");
     states.Add(&tx);
     states.Add(&ca);
     states.Add(&nm);
     states.Add(&fl);
     states.Add(&oregon);
     states.PringDebug();
     assert(states.Exists("California"));
     assert(states.Exists("New Mexico"));
     assert(states.Exists("Florida"));
     assert(states.Exists("Oregon"));
 }
References HashTable::Add(), HashTable::Exists(), HashTable::PringDebug(), HashObject::SetKey(), and HashObject::SetValue().
Referenced by run_all_tests().