Common Alogrithm: run_all_tests
run_all_tests()
void run_all_tests ()
                      {
     test_add_exists();
     test_probing();
     test_get();
     test_remove();
 }
References test_add_exists(), test_get(), test_probing(), and test_remove().
Referenced by main().