Common Alogrithm: testing::internal::posix Namespace Reference
testing::internal::posix Namespace Reference
Typedefs
typedef struct stat StatStruct
Functions
int ChDir (const char *dir)
int Close (int fd)
int FClose (FILE *fp)
FILE * FDOpen (int fd, const char *mode)
int FileNo (FILE *file)
FILE * FOpen (const char *path, const char *mode)
FILE * FReopen (const char *path, const char *mode, FILE *stream)
const char * GetEnv (const char *name)
GTEST_DISABLE_MSC_WARNINGS_POP_ () inline void Abort()
GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4996) inline const char *StrNCpy(char *dest
int IsATTY (int fd)
bool IsDir (const StatStruct &st)
int Read (int fd, void *buf, unsigned int count)
int RmDir (const char *dir)
int Stat (const char *path, StatStruct *buf)
int StrCaseCmp (const char *s1, const char *s2)
char * StrDup (const char *src)
const char * StrError (int errnum)
int Write (int fd, const void *buf, unsigned int count)
Constants
const char size_t n
const char * src
Typedef Documentation
StatStruct
typedef struct stat StatStruct
Definition at line 2230 of file gtest-port.h.
Function Documentation
ChDir()
int testing::internal::posix::ChDir (const char * dir)
Definition at line 2365 of file gtest-port.h.
 { return chdir(dir); }
Close()
int testing::internal::posix::Close (int fd)
Definition at line 2384 of file gtest-port.h.
 { return close(fd); }
FClose()
int testing::internal::posix::FClose (FILE * fp)
Definition at line 2376 of file gtest-port.h.
 { return fclose(fp); }
Referenced by testing::internal::GTEST_DISABLE_MSC_WARNINGS_PUSH_().
FDOpen()
FILE* testing::internal::posix::FDOpen (int fd, const char * mode)
Definition at line 2374 of file gtest-port.h.
 { return fdopen(fd, mode); }
FileNo()
int testing::internal::posix::FileNo (FILE * file)
Definition at line 2340 of file gtest-port.h.
 { return fileno(file); }
Referenced by testing::internal::ColoredPrintf().
FOpen()
FILE* testing::internal::posix::FOpen (const char * path, const char * mode)
Definition at line 2367 of file gtest-port.h.
{
   return fopen(path, mode);
 }
Referenced by testing::internal::GTEST_DISABLE_MSC_WARNINGS_PUSH_(), XmlUnitTestResultPrinter::OnTestIterationEnd(), ScopedPrematureExitFile::ScopedPrematureExitFile(), and testing::internal::WriteToShardStatusFileIfNeeded().
FReopen()
FILE* testing::internal::posix::FReopen (const char * path, const char * mode, FILE * stream)
Definition at line 2371 of file gtest-port.h.
{
   return freopen(path, mode, stream);
 }
GetEnv()
const char* testing::internal::posix::GetEnv (const char * name)
Definition at line 2387 of file gtest-port.h.
{
 #if GTEST_OS_WINDOWS_MOBILE || GTEST_OS_WINDOWS_PHONE | GTEST_OS_WINDOWS_RT
   // We are on Windows CE, which has no environment variables.
   static_cast<void>(name);  // To prevent 'unused argument' warning.
   return NULL;
 #elif defined(__BORLANDC__) || defined(__SunOS_5_8) || defined(__SunOS_5_9)
   // Environment variables which we programmatically clear will be set to the
   // empty string rather than unset (NULL).  Handle that case.
   const char* const env = getenv(name);
   return (env != NULL && env[0] != '\0') ? env : NULL;
 #else
   return getenv(name);
 #endif
 }
Referenced by testing::internal::BoolFromGTestEnv(), testing::internal::Int32FromEnvOrDie(), testing::internal::Int32FromGTestEnv(), PrettyUnitTestResultPrinter::OnTestIterationStart(), UnitTest::Run(), testing::internal::ShouldUseColor(), testing::internal::StringFromGTestEnv(), and testing::internal::WriteToShardStatusFileIfNeeded().
GTEST_DISABLE_MSC_WARNINGS_POP_()
testing::internal::posix::GTEST_DISABLE_MSC_WARNINGS_POP_ ()
Definition at line 2402 of file gtest-port.h.
                     { abort(); }
GTEST_DISABLE_MSC_WARNINGS_PUSH_()
testing::internal::posix::GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4996) const
IsATTY()
int testing::internal::posix::IsATTY (int fd)
Definition at line 2341 of file gtest-port.h.
 { return isatty(fd); }
Referenced by testing::internal::ColoredPrintf().
IsDir()
bool testing::internal::posix::IsDir (const StatStruct & st)
Definition at line 2348 of file gtest-port.h.
 { return S_ISDIR(st.st_mode); }
Referenced by FilePath::DirectoryExists().
Read()
int testing::internal::posix::Read (int fd, void * buf, unsigned int count)
Definition at line 2378 of file gtest-port.h.
{
   return static_cast<int>(read(fd, buf, count));
 }
RmDir()
int testing::internal::posix::RmDir (const char * dir)
Definition at line 2347 of file gtest-port.h.
 { return rmdir(dir); }
Stat()
int testing::internal::posix::Stat (const char * path, StatStruct * buf)
Definition at line 2342 of file gtest-port.h.
 { return stat(path, buf); }
Referenced by FilePath::DirectoryExists(), and FilePath::FileOrDirectoryExists().
StrCaseCmp()
int testing::internal::posix::StrCaseCmp (const char * s1, const char * s2)
Definition at line 2343 of file gtest-port.h.
{
   return strcasecmp(s1, s2);
 }
Referenced by String::CaseInsensitiveCStringEquals().
StrDup()
char* testing::internal::posix::StrDup (const char * src)
Definition at line 2346 of file gtest-port.h.
 { return strdup(src); }
References src.
StrError()
const char* testing::internal::posix::StrError (int errnum)
Definition at line 2385 of file gtest-port.h.
 { return strerror(errnum); }
Write()
int testing::internal::posix::Write (int fd, const void * buf, unsigned int count)
Definition at line 2381 of file gtest-port.h.
{
   return static_cast<int>(write(fd, buf, count));
 }
Constant Documentation
n
const char size_t n
Initial value:
{
  return strncpy(dest, src, n)
Definition at line 2356 of file gtest-port.h.
Referenced by GraphRepresentationList::BFS(), testing::internal::ChopLowBits(), GraphRepresentationList::ContainsCycle(), GraphRepresentationList::DFS(), and LinkedList< T >::ValueNFromEnd().
src
const char* src
Definition at line 2356 of file gtest-port.h.
Referenced by FilePath::Normalize(), and StrDup().