Common Alogrithm: TestCase Class Reference
TestCase Class Reference
#include <gtest.h>
Public Member Functions
const TestResult & ad_hoc_test_result () const
int disabled_test_count () const
TimeInMillis elapsed_time () const
bool Failed () const
int failed_test_count () const
const TestInfo * GetTestInfo (int i) const
const char * name () const
bool Passed () const
int reportable_disabled_test_count () const
int reportable_test_count () const
bool should_run () const
int successful_test_count () const
int test_to_run_count () const
TestCase (const char *name, const char *a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
int total_test_count () const
const char * type_param () const
virtual ~TestCase ()
Package Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestCase)
Package Attributes
__pad0__:scoped_ptr<const ::std::string> type_param_
TestResult ad_hoc_test_result_
TimeInMillis elapsed_time_
Test::SetUpTestCaseFunc set_up_tc_
bool should_run_
Test::TearDownTestCaseFunc tear_down_tc_
std::vector< int > test_indices_
std::vector< TestInfo * > test_info_list_
Private Member Functions
void AddTestInfo (TestInfo *test_info)
void ClearResult ()
TestInfo * GetMutableTestInfo (int i)
void Run ()
void RunSetUpTestCase ()
void RunTearDownTestCase ()
void set_should_run (bool should)
void ShuffleTests (internal::Random *random)
std::vector< TestInfo * > & test_info_list ()
const std::vector< TestInfo * > & test_info_list () const
void UnshuffleTests ()
Static Private Member Functions
static void ClearTestCaseResult (TestCase *test_case)
static bool ShouldRunTest (const TestInfo *test_info)
static bool TestDisabled (const TestInfo *test_info)
static bool TestFailed (const TestInfo *test_info)
static bool TestPassed (const TestInfo *test_info)
static bool TestReportable (const TestInfo *test_info)
static bool TestReportableDisabled (const TestInfo *test_info)
Private Attributes
std::string name_
Friends
class internal::UnitTestImpl
class Test
Detailed Description
Definition at line 778 of file gtest.h.
Constructor & Destructor Documentation
TestCase()
TestCase (const char * name, const char * a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
Definition at line 2720 of file gtest.cc.
     : name_(a_name),
       type_param_(a_type_param ? new std::string(a_type_param) : NULL),
       set_up_tc_(set_up_tc),
       tear_down_tc_(tear_down_tc),
       should_run_(false),
       elapsed_time_(0) {
 }
~TestCase()
~TestCase () virtual
Definition at line 2732 of file gtest.cc.
                     {
   // Deletes every Test in the collection.
   ForEach(test_info_list_, internal::Delete<TestInfo>);
 }
References testing::internal::ForEach(), and TestCase::test_info_list_.
Member Function Documentation
ad_hoc_test_result()
const TestResult& ad_hoc_test_result () const
Definition at line 849 of file gtest.h.
 { return ad_hoc_test_result_; }
Referenced by XmlUnitTestResultPrinter::PrintXmlTestCase().
AddTestInfo()
void AddTestInfo (TestInfo * test_info) private
Definition at line 2753 of file gtest.cc.
{
   test_info_list_.push_back(test_info);
   test_indices_.push_back(static_cast<int>(test_indices_.size()));
 }
References vector< T >::push_back(), vector< T >::size(), TestCase::test_indices_, and TestCase::test_info_list_.
ClearResult()
void ClearResult () private
Definition at line 2787 of file gtest.cc.
{
   ad_hoc_test_result_.Clear();
   ForEach(test_info_list_, TestInfo::ClearTestResult);
 }
References TestCase::ad_hoc_test_result_, TestResult::Clear(), TestInfo::ClearTestResult(), testing::internal::ForEach(), and TestCase::test_info_list_.
Referenced by TestCase::ClearTestCaseResult().
ClearTestCaseResult()
static void ClearTestCaseResult (TestCase * test_case) static private
Definition at line 878 of file gtest.h.
{
     test_case->ClearResult();
   }
References TestCase::ClearResult().
Referenced by UnitTestImpl::ClearNonAdHocTestResult().
disabled_test_count()
int disabled_test_count () const
Definition at line 2692 of file gtest.cc.
{
   return CountIf(test_info_list_, TestDisabled);
 }
References testing::internal::CountIf(), TestCase::test_info_list_, and TestCase::TestDisabled().
Referenced by UnitTestImpl::disabled_test_count().
elapsed_time()
TimeInMillis elapsed_time () const
Definition at line 841 of file gtest.h.
 { return elapsed_time_; }
Referenced by PrettyUnitTestResultPrinter::OnTestCaseEnd(), and XmlUnitTestResultPrinter::PrintXmlTestCase().
Failed()
bool Failed () const
Definition at line 838 of file gtest.h.
 { return failed_test_count() > 0; }
Referenced by testing::internal::TestCaseFailed().
failed_test_count()
int failed_test_count () const
Definition at line 2682 of file gtest.cc.
{
   return CountIf(test_info_list_, TestFailed);
 }
References testing::internal::CountIf(), TestCase::test_info_list_, and TestCase::TestFailed().
Referenced by UnitTestImpl::failed_test_count(), PrettyUnitTestResultPrinter::PrintFailedTests(), and XmlUnitTestResultPrinter::PrintXmlTestCase().
GetMutableTestInfo()
TestInfo * GetMutableTestInfo (int i) private
Definition at line 2746 of file gtest.cc.
{
   const int index = GetElementOr(test_indices_, i, -1);
   return index < 0 ? NULL : test_info_list_[index];
 }
References testing::internal::GetElementOr(), TestCase::test_indices_, and TestCase::test_info_list_.
Referenced by TestCase::Run().
GetTestInfo()
const TestInfo * GetTestInfo (int i) const
Definition at line 2739 of file gtest.cc.
{
   const int index = GetElementOr(test_indices_, i, -1);
   return index < 0 ? NULL : test_info_list_[index];
 }
References testing::internal::GetElementOr(), TestCase::test_indices_, and TestCase::test_info_list_.
Referenced by PrettyUnitTestResultPrinter::PrintFailedTests(), and XmlUnitTestResultPrinter::PrintXmlTestCase().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestCase) package
name()
const char* name () const
Definition at line 800 of file gtest.h.
 { return name_.c_str(); }
Referenced by UnitTestImpl::FilterTests(), UnitTestImpl::ListTestsMatchingFilter(), PrettyUnitTestResultPrinter::OnTestCaseEnd(), PrettyUnitTestResultPrinter::OnTestCaseStart(), TestCaseNameIs::operator()(), PrettyUnitTestResultPrinter::PrintFailedTests(), and XmlUnitTestResultPrinter::PrintXmlTestCase().
Passed()
bool Passed () const
Definition at line 835 of file gtest.h.
 { return !Failed(); }
Referenced by testing::internal::TestCasePassed().
reportable_disabled_test_count()
int reportable_disabled_test_count () const
Definition at line 2687 of file gtest.cc.
{
   return CountIf(test_info_list_, TestReportableDisabled);
 }
References testing::internal::CountIf(), TestCase::test_info_list_, and TestCase::TestReportableDisabled().
Referenced by XmlUnitTestResultPrinter::PrintXmlTestCase(), and UnitTestImpl::reportable_disabled_test_count().
reportable_test_count()
int reportable_test_count () const
Definition at line 2697 of file gtest.cc.
{
   return CountIf(test_info_list_, TestReportable);
 }
References testing::internal::CountIf(), TestCase::test_info_list_, and TestCase::TestReportable().
Referenced by XmlUnitTestResultPrinter::PrintXmlTestCase(), XmlUnitTestResultPrinter::PrintXmlUnitTest(), and UnitTestImpl::reportable_test_count().
Run()
void Run () private
Definition at line 2759 of file gtest.cc.
                    {
   if (!should_run_) return;
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   impl->set_current_test_case(this);
   TestEventListener* repeater = UnitTest::GetInstance()->listeners().repeater();
   repeater->OnTestCaseStart(*this);
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       this, &TestCase::RunSetUpTestCase, "SetUpTestCase()");
   const internal::TimeInMillis start = internal::GetTimeInMillis();
   for (int i = 0; i < total_test_count(); i++) {
     GetMutableTestInfo(i)->Run();
   }
   elapsed_time_ = internal::GetTimeInMillis() - start;
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       this, &TestCase::RunTearDownTestCase, "TearDownTestCase()");
   repeater->OnTestCaseEnd(*this);
   impl->set_current_test_case(NULL);
 }
References TestCase::elapsed_time_, UnitTest::GetInstance(), TestCase::GetMutableTestInfo(), testing::internal::GetTimeInMillis(), testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), UnitTest::listeners(), TestEventListener::OnTestCaseEnd(), TestEventListener::OnTestCaseStart(), UnitTestImpl::os_stack_trace_getter(), TestEventListeners::repeater(), TestInfo::Run(), TestCase::RunSetUpTestCase(), TestCase::RunTearDownTestCase(), UnitTestImpl::set_current_test_case(), TestCase::should_run_, TestCase::total_test_count(), and OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by UnitTestImpl::RunAllTests().
RunSetUpTestCase()
void RunSetUpTestCase () private
Definition at line 887 of file gtest.h.
 { (*set_up_tc_)(); }
Referenced by TestCase::Run().
RunTearDownTestCase()
void RunTearDownTestCase () private
Definition at line 891 of file gtest.h.
 { (*tear_down_tc_)(); }
Referenced by TestCase::Run().
set_should_run()
void set_should_run (bool should) private
Definition at line 868 of file gtest.h.
 { should_run_ = should; }
Referenced by UnitTestImpl::FilterTests().
should_run()
bool should_run () const
Definition at line 811 of file gtest.h.
 { return should_run_; }
Referenced by UnitTestImpl::FilterTests(), PrettyUnitTestResultPrinter::PrintFailedTests(), testing::internal::ShouldRunTestCase(), testing::internal::TestCaseFailed(), and testing::internal::TestCasePassed().
ShouldRunTest()
static bool ShouldRunTest (const TestInfo * test_info) static private
Definition at line 920 of file gtest.h.
{
     return test_info->should_run();
   }
References TestInfo::should_run().
Referenced by TestCase::test_to_run_count().
ShuffleTests()
void ShuffleTests (internal::Random * random) private
Definition at line 2793 of file gtest.cc.
{
   Shuffle(random, &test_indices_);
 }
References testing::internal::Shuffle(), and TestCase::test_indices_.
successful_test_count()
int successful_test_count () const
Definition at line 2677 of file gtest.cc.
{
   return CountIf(test_info_list_, TestPassed);
 }
References testing::internal::CountIf(), TestCase::test_info_list_, and TestCase::TestPassed().
Referenced by UnitTestImpl::successful_test_count().
test_info_list() [1/2]
std::vector<TestInfo*>& test_info_list () private
Definition at line 856 of file gtest.h.
 { return test_info_list_; }
Referenced by UnitTestImpl::FilterTests(), Test::HasSameFixtureClass(), and UnitTestImpl::ListTestsMatchingFilter().
test_info_list() [2/2]
const std::vector<TestInfo*>& test_info_list () const private
Definition at line 859 of file gtest.h.
{
     return test_info_list_;
   }
test_to_run_count()
int test_to_run_count () const
Definition at line 2702 of file gtest.cc.
{
   return CountIf(test_info_list_, ShouldRunTest);
 }
References testing::internal::CountIf(), TestCase::ShouldRunTest(), and TestCase::test_info_list_.
Referenced by PrettyUnitTestResultPrinter::OnTestCaseEnd(), PrettyUnitTestResultPrinter::OnTestCaseStart(), and UnitTestImpl::test_to_run_count().
TestDisabled()
static bool TestDisabled (const TestInfo * test_info) static private
Definition at line 910 of file gtest.h.
{
     return test_info->is_disabled_;
   }
References TestInfo::is_disabled_.
Referenced by TestCase::disabled_test_count().
TestFailed()
static bool TestFailed (const TestInfo * test_info) static private
Definition at line 899 of file gtest.h.
{
     return test_info->should_run() && test_info->result()->Failed();
   }
References TestResult::Failed(), TestInfo::result(), and TestInfo::should_run().
Referenced by TestCase::failed_test_count().
TestPassed()
static bool TestPassed (const TestInfo * test_info) static private
Definition at line 894 of file gtest.h.
{
     return test_info->should_run() && test_info->result()->Passed();
   }
References TestResult::Passed(), TestInfo::result(), and TestInfo::should_run().
Referenced by TestCase::successful_test_count().
TestReportable()
static bool TestReportable (const TestInfo * test_info) static private
Definition at line 915 of file gtest.h.
{
     return test_info->is_reportable();
   }
References TestInfo::is_reportable().
Referenced by TestCase::reportable_test_count().
TestReportableDisabled()
static bool TestReportableDisabled (const TestInfo * test_info) static private
Definition at line 905 of file gtest.h.
{
     return test_info->is_reportable() && test_info->is_disabled_;
   }
References TestInfo::is_disabled_, and TestInfo::is_reportable().
Referenced by TestCase::reportable_disabled_test_count().
total_test_count()
int total_test_count () const
Definition at line 2707 of file gtest.cc.
{
   return static_cast<int>(test_info_list_.size());
 }
References TestCase::test_info_list_.
Referenced by PrettyUnitTestResultPrinter::PrintFailedTests(), XmlUnitTestResultPrinter::PrintXmlTestCase(), TestCase::Run(), and UnitTestImpl::total_test_count().
type_param()
const char* type_param () const
Definition at line 804 of file gtest.h.
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
Referenced by UnitTestImpl::ListTestsMatchingFilter(), and PrettyUnitTestResultPrinter::OnTestCaseStart().
UnshuffleTests()
void UnshuffleTests () private
Definition at line 2798 of file gtest.cc.
{
   for (size_t i = 0; i < test_indices_.size(); i++) {
     test_indices_[i] = static_cast<int>(i);
   }
 }
References vector< T >::size(), and TestCase::test_indices_.
Friends And Related Function Documentation
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
Definition at line 853 of file gtest.h.
Test
friend class Test friend
Definition at line 852 of file gtest.h.
Member Data Documentation
__pad0__
__pad0__ package
Definition at line 934 of file gtest.h.
ad_hoc_test_result_
TestResult ad_hoc_test_result_ package
Definition at line 952 of file gtest.h.
Referenced by TestCase::ClearResult(), and UnitTestImpl::RecordProperty().
elapsed_time_
TimeInMillis elapsed_time_ package
Definition at line 949 of file gtest.h.
Referenced by TestCase::Run().
name_
std::string name_ private
Definition at line 931 of file gtest.h.
set_up_tc_
Test::SetUpTestCaseFunc set_up_tc_ package
Definition at line 943 of file gtest.h.
should_run_
bool should_run_ package
Definition at line 947 of file gtest.h.
Referenced by TestCase::Run().
tear_down_tc_
Test::TearDownTestCaseFunc tear_down_tc_ package
Definition at line 945 of file gtest.h.
test_indices_
std::vector<int> test_indices_ package
Definition at line 941 of file gtest.h.
Referenced by TestCase::AddTestInfo(), TestCase::GetMutableTestInfo(), TestCase::GetTestInfo(), TestCase::ShuffleTests(), and TestCase::UnshuffleTests().
test_info_list_
std::vector<TestInfo*> test_info_list_ package
Definition at line 937 of file gtest.h.
Referenced by TestCase::AddTestInfo(), TestCase::ClearResult(), TestCase::disabled_test_count(), TestCase::failed_test_count(), TestCase::GetMutableTestInfo(), TestCase::GetTestInfo(), TestCase::reportable_disabled_test_count(), TestCase::reportable_test_count(), TestCase::successful_test_count(), TestCase::test_to_run_count(), TestCase::total_test_count(), and TestCase::~TestCase().