Common Alogrithm: testing::internal::anonymous_namespace{gtest.cc} Namespace Reference
testing::internal::anonymous_namespace{gtest.cc} Namespace Reference
Classes
class ClassUniqueToAlwaysTrue
Functions
std::vector< std::string > SplitEscapedString (const std::string &str)
Class Documentation
testing::internal::anonymous_namespace{gtest.cc}::ClassUniqueToAlwaysTrue
class testing::internal::anonymous_namespace{gtest.cc}::ClassUniqueToAlwaysTrue
Definition at line 4983 of file gtest.cc.
Function Documentation
SplitEscapedString()
std::vector<std::string> testing::internal::anonymous_namespace{gtest.cc}::SplitEscapedString (const std::string & str)
Definition at line 1272 of file gtest.cc.
{
   std::vector<std::string> lines;
   size_t start = 0, end = str.size();
   if (end > 2 && str[0] == '"' && str[end - 1] == '"') {
     ++start;
     --end;
   }
   bool escaped = false;
   for (size_t i = start; i + 1 < end; ++i) {
     if (escaped) {
       escaped = false;
       if (str[i] == 'n') {
         lines.push_back(str.substr(start, i - start - 1));
         start = i + 1;
       }
     } else {
       escaped = str[i] == '\\';
     }
   }
   lines.push_back(str.substr(start, end - start));
   return lines;
 }
References vector< T >::push_back(), string::size(), and string::substr().
Referenced by testing::internal::EqFailure().