Common Alogrithm: LinkedList< T > Class Template Reference
LinkedList< T > Class Template Reference
#include <linked_list.h>
Public Member Functions
const T Back ()
bool Empty () const
void Erase (int index)
const T Front ()
void Insert (int index, T value)
LinkedList ()
LinkedList (const LinkedList &)
LinkedList & operator= (const LinkedList &)
const T PopBack ()
const T PopFront ()
void PrintDebug () const
void PushBack (T value)
void PushFront (T value)
void RemoveValue (T value)
void Reverse ()
int Size ()
const T & ValueAt (int index) const
const T ValueNFromEnd (int n)
~LinkedList ()
Private Attributes
ListElement< T > * head
Detailed Description
template<class T>
class common::LinkedList< T >
Definition at line 10 of file linked_list.h.
Constructor & Destructor Documentation
LinkedList() [1/2]
LinkedList () explicit
Definition at line 17 of file linked_list.h.
 : head(nullptr) {};
LinkedList() [2/2]
LinkedList (const LinkedList< T > &)
Definition at line 19 of file linked_list.h.
 {};
~LinkedList()
~LinkedList ()
Definition at line 22 of file linked_list.h.
                   {
         ListElement<T>* current = head;
         ListElement<T>* next = nullptr;
         while (current) {
             next = current->GetNext();
             delete current;
             current = next;
         }
     };
References ListElement< T >::GetNext(), and LinkedList< T >::head.
Member Function Documentation
Back()
const T Back
Definition at line 46 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto* current = head;
     while (current->GetNext()) {
         current = head->GetNext();
     }
     return current->GetData();
 }
References std::endl().
Empty()
bool Empty
Definition at line 145 of file linked_list.cc.
{
    return head == nullptr;
 }
Erase()
void Erase (int index)
Definition at line 213 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     ListElement<T>* prev = nullptr;
     auto * current = head;
     for (int i = 0; i < index && current != nullptr; ++i) {
         prev = current;
         current = current->GetNext();
     }
     if(current == nullptr) {
         std::cout << "Index out of bounds" << std::endl;
         exit(EXIT_FAILURE);
     }
     if (prev == nullptr) {
         head = current->GetNext();
     } else {
         prev->SetNext(current->GetNext());
         head = prev;
     }
     delete current;
 }
References std::endl().
Front()
const T Front
Definition at line 33 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     return head->GetData();
 }
References std::endl().
Insert()
void Insert (int index, T value)
Definition at line 178 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto * current = head; // asterisk (*), the dereference operator: dereference the pointer prev to access the LinkedList object it refers to
     ListElement<T> * prev = nullptr;
     int i;
     for (i = 0; i < index && current != nullptr; ++i) {
         prev = current;
         current = current->GetNext();
     }
     if(i != index) {
         std::cout << "Index out of bounds" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto * node = new ListElement<T>(value);
     if(prev == nullptr) {
         node->SetNext(head);
         head = node;
     } else {
         node->SetNext(prev->GetNext());
         prev->SetNext(node);
     }
 }
References std::endl().
operator=()
LinkedList& operator= (const LinkedList< T > &)
PopBack()
const T PopBack
Definition at line 116 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto* current = head;
     ListElement<T>* prev = nullptr;
     // Pop Back
     while (current->GetNext()) {
         prev = current;
         current = current->GetNext();
     }
     T value = current->GetData();
     if(prev == nullptr) {
         head = nullptr;
     } else {
         prev->SetNext(nullptr);
     }
     delete current;
     return value;
 }
References std::endl().
PopFront()
const T PopFront
Definition at line 77 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     ListElement<T> *node = head;
     T value = node->GetData();
     head = head->GetNext();
     delete node;
     return value;
 }
References std::endl(), and ListElement< T >::GetData().
PrintDebug()
void PrintDebug
Definition at line 330 of file linked_list.cc.
{
     auto * current = head;
     std::cout << " " << std::endl;
     while (current) {
         std::cout << current->GetData() << " ---> " ;
         current = current->GetNext();
     }
     std::cout << " " << std::endl;
 }
References std::endl().
PushBack()
void PushBack (T value)
Definition at line 95 of file linked_list.cc.
{
     auto* node = new ListElement<T>(value);
     node->SetNext(nullptr);
     if (head == nullptr) {
         head = node;
         return;
     }
     ListElement<T> * current = head;
     while (current->GetNext()) {
         current = current->GetNext();
     }
     current->SetNext(node);
 }
References ListElement< T >::GetNext(), and ListElement< T >::SetNext().
PushFront()
void PushFront (T value)
Definition at line 65 of file linked_list.cc.
{
     auto* node = new ListElement<T>(value);
     node->SetNext(head);
     head = node;
 }
RemoveValue()
void RemoveValue (T value)
Definition at line 246 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     ListElement<T>* prev = nullptr;
     auto * current = head;
     while (current) {
         if (current->GetData() == value) {
             if(prev == nullptr) {
                 head = current->GetNext();
             } else {
                 prev->SetNext(current->GetNext());
                 head = prev;
             }
             delete current;
             break;
         }
         prev = current;
         current = current->GetNext();
     }
 }
References std::endl().
Reverse()
void Reverse
Definition at line 276 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     ListElement<T>* prev = nullptr;
     auto * current = head;
     ListElement<T>* next = nullptr;
     while (current != nullptr) {
         next = current->GetNext();
         current->SetNext(prev);
         prev = current;
         current = next;
     }
     head = prev;
 }
References std::endl().
Size()
int Size
Definition at line 15 of file linked_list.cc.
{
     int size = 0;
     auto* current = head;
     while (current) {
         current = current->GetNext();
         size ++;
     }
     return size;
 }
ValueAt()
const T & ValueAt (int index) const
Definition at line 154 of file linked_list.cc.
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto * current = head;
     for (int i = 0; i < index && current != nullptr; ++i) {
         current = current->GetNext();
     }
     if(current == nullptr) {
         std::cout << "Index out of bounds" << std::endl;
         exit(EXIT_FAILURE);
     }
     return current->GetData();
 }
References std::endl().
ValueNFromEnd()
const T ValueNFromEnd (int n)
Definition at line 299 of file linked_list.cc.
{
     if( n < 1 || head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto * current = head;
     auto * match = head;
     int i;
     for (i = 0; i < n && current != nullptr ; ++i) {
         current = current->GetNext();
     }
     if(i != n) {
         std::cout << "Index out of bounds" << std::endl;
         exit(EXIT_FAILURE);
     }
     while (current) {
         match = match->GetNext();
         current = current->GetNext();
     }
     return match->GetData();
 }
References std::endl(), and testing::internal::posix::n.
Member Data Documentation
head
ListElement<T>* head private
Definition at line 13 of file linked_list.h.
Referenced by LinkedList< T >::~LinkedList().