Common Alogrithm: adapter_pattern/main.cc File Reference
main.cc File Reference
#include <iostream>
#include <string>
Classes
class Adapter
class ElectricKettle
class EuropeanSocketInterface
class Socket
class USASocketInterface
Typedefs
typedef int Cable
Functions
int main (int argc, char *argv[])
Typedef Documentation
Cable
typedef int Cable
Function Documentation
main()
int main (int argc, char * argv[])
 {
     Socket* socket = new Socket;
     Adapter* adapter = new Adapter;
     ElectricKettle* kettle = new ElectricKettle;
     /* Pluging in. */
     adapter->plugIn(socket);
     kettle->plugIn(adapter);
     /* Having coffee */
     kettle->boil();
     return 0;
 }
References ElectricKettle::boil(), Adapter::plugIn(), and ElectricKettle::plugIn().