Common Alogrithm: binary_search/main.cc File Reference
main.cc File Reference
(c53fab7feceb016938219eb2692d5fedc54dc4b9)
#include <stdlib.h>
#include "binary_search.h"
#include "binary_search.cc"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
 {
     using namespace common;
     BSTNode* root = nullptr;
     int idex;
     for (idex = 0; idex < 10; ++idex) {
         int data = rand()%100;
         root = Insert(root, data);
     }
     if (IsBinarySearchTree(root)) {
         int min = GetMin(root);
         int max = GetMax(root);
         int height = GetHeight(root);
         PrintBFS(root);
         std::cout << std::endl;
         PrintInOrder(root);
         std::cout << std::endl;
         std::cout << "Search 44 in the binary tree: "<< Search(root, 44) << std::endl;
         std::cout << "Min: " << min << std::endl;
         std::cout << "Max: " << max << std::endl;
         std::cout << "Height: " << height << std::endl;
         DeleteValue(root, 49);
         PrintInOrder(root);
         std::cout << std::endl;
         DeleteTree(root);
     }
     else
         std::cout << "The tree is not binary search tree" << std::endl;
     return 0;
 }
References common::DeleteTree(), common::DeleteValue(), common::GetHeight(), common::GetMax(), common::GetMin(), common::Insert(), common::IsBinarySearchTree(), common::PrintBFS(), common::PrintInOrder(), and common::Search().