Common Alogrithm: SubSystemTwo Class Reference
SubSystemTwo Class Reference
Public Member Functions
void MethodTwo ()
Detailed Description
Member Function Documentation
MethodTwo()
void SubSystemTwo::MethodTwo () inline
     {
         std::cout << " SubSystemTwo Method" << std::endl;
     }
References std::endl().
Referenced by Facade::MethodA(), and Facade::MethodB().