Common Alogrithm: testing::TestInfo Class Reference
testing::TestInfo Class Reference
#include <gtest.h>
Public Member Functions
const char * file () const
bool is_reportable () const
int line () const
const char * name () const
const TestResult * result () const
bool should_run () const
const char * test_case_name () const
const char * type_param () const
const char * value_param () const
~TestInfo ()
Package Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo)
int increment_death_test_count ()
void Run ()
TestInfo (const std::string &test_case_name, const std::string &name, const char *a_type_param, const char *a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase *factory)
Static Package Functions
static void ClearTestResult (TestInfo *test_info)
Package Attributes
__pad0__:MakeAndRegisterTestInfo(const char* test_case_name
__pad1__:scoped_ptr<const ::std::string> type_param_
__pad2__:scoped_ptr<const ::std::string> value_param_
__pad3__:TypeId fixture_class_id_
const char const char const char internal::CodeLocation code_location
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc Test::TearDownTestCaseFunc internal::TestFactoryBase * factory
internal::TestFactoryBase *const factory_
const char const char const char internal::CodeLocation internal::TypeId fixture_class_id
bool is_disabled_
internal::CodeLocation location_
bool matches_filter_
const char * name
const std::string name_
TestResult result_
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc set_up_tc
bool should_run_
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc Test::TearDownTestCaseFunc tear_down_tc
const std::string test_case_name_
const char const char * type_param
const char const char const char * value_param
Friends
class internal::StreamingListenerTest
class internal::UnitTestImpl
class Test
class TestCase
Detailed Description
Constructor & Destructor Documentation
~TestInfo()
testing::TestInfo::~TestInfo ()
 { delete factory_; }
References factory_.
TestInfo()
testing::TestInfo::TestInfo (const std::string & test_case_name, const std::string & name, const char * a_type_param, const char * a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase * factory) package
     : test_case_name_(a_test_case_name),
       name_(a_name),
       type_param_(a_type_param ? new std::string(a_type_param) : NULL),
       value_param_(a_value_param ? new std::string(a_value_param) : NULL),
       location_(a_code_location),
       fixture_class_id_(fixture_class_id),
       should_run_(false),
       is_disabled_(false),
       matches_filter_(false),
       factory_(factory),
       result_() {}
Member Function Documentation
ClearTestResult()
static void testing::TestInfo::ClearTestResult (TestInfo * test_info) inline static package
{
     test_info->result_.Clear();
   }
References testing::TestResult::Clear(), and result_.
Referenced by testing::TestCase::ClearResult().
file()
const char* testing::TestInfo::file () const inline
 { return location_.file.c_str(); }
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::TestInfo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo) package
increment_death_test_count()
int testing::TestInfo::increment_death_test_count () inline package
{
     return result_.increment_death_test_count();
   }
is_reportable()
bool testing::TestInfo::is_reportable () const inline
{
     // For now, the XML report includes all tests matching the filter.
     // In the future, we may trim tests that are excluded because of
     // sharding.
     return matches_filter_;
   }
Referenced by testing::internal::XmlUnitTestResultPrinter::PrintXmlTestCase(), testing::TestCase::TestReportable(), and testing::TestCase::TestReportableDisabled().
line()
int testing::TestInfo::line () const inline
 { return location_.line; }
name()
const char* testing::TestInfo::name () const inline
 { return name_.c_str(); }
result()
const TestResult* testing::TestInfo::result () const inline
 { return &result_; }
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::TestCase::TestFailed(), and testing::TestCase::TestPassed().
Run()
void testing::TestInfo::Run () package
                    {
   if (!should_run_) return;
   // Tells UnitTest where to store test result.
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   impl->set_current_test_info(this);
   TestEventListener* repeater = UnitTest::GetInstance()->listeners().repeater();
   // Notifies the unit test event listeners that a test is about to start.
   repeater->OnTestStart(*this);
   const TimeInMillis start = internal::GetTimeInMillis();
   impl->os_stack_trace_getter()->UponLeavingGTest();
   // Creates the test object.
   Test* const test = internal::HandleExceptionsInMethodIfSupported(
       factory_, &internal::TestFactoryBase::CreateTest,
       "the test fixture's constructor");
   // Runs the test only if the test object was created and its
   // constructor didn't generate a fatal failure.
   if ((test != NULL) && !Test::HasFatalFailure()) {
     // This doesn't throw as all user code that can throw are wrapped into
     // exception handling code.
     test->Run();
   }
   // Deletes the test object.
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       test, &Test::DeleteSelf_, "the test fixture's destructor");
   result_.set_elapsed_time(internal::GetTimeInMillis() - start);
   // Notifies the unit test event listener that a test has just finished.
   repeater->OnTestEnd(*this);
   // Tells UnitTest to stop associating assertion results to this
   // test.
   impl->set_current_test_info(NULL);
 }
References testing::internal::TestFactoryBase::CreateTest(), testing::Test::DeleteSelf_(), factory_, testing::UnitTest::GetInstance(), testing::internal::GetTimeInMillis(), testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), testing::Test::HasFatalFailure(), testing::UnitTest::listeners(), testing::TestEventListener::OnTestEnd(), testing::TestEventListener::OnTestStart(), testing::internal::UnitTestImpl::os_stack_trace_getter(), testing::TestEventListeners::repeater(), result_, testing::Test::Run(), testing::internal::UnitTestImpl::set_current_test_info(), testing::TestResult::set_elapsed_time(), should_run_, and testing::internal::OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by testing::TestCase::Run().
should_run()
bool testing::TestInfo::should_run () const inline
 { return should_run_; }
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::TestCase::ShouldRunTest(), testing::TestCase::TestFailed(), and testing::TestCase::TestPassed().
test_case_name()
const char* testing::TestInfo::test_case_name () const inline
 { return test_case_name_.c_str(); }
Referenced by testing::internal::UnitTestImpl::AddTestInfo(), testing::Test::HasSameFixtureClass(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), and testing::internal::PrettyUnitTestResultPrinter::OnTestStart().
type_param()
const char* testing::TestInfo::type_param () const inline
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
value_param()
const char* testing::TestInfo::value_param () const inline
{
     if (value_param_.get() != NULL)
       return value_param_->c_str();
     return NULL;
   }
Friends And Related Function Documentation
internal::StreamingListenerTest
friend class internal::StreamingListenerTest friend
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
Test
friend class Test friend
TestCase
friend class TestCase friend
Member Data Documentation
__pad0__
testing::TestInfo::__pad0__ package
__pad1__
testing::TestInfo::__pad1__ package
__pad2__
testing::TestInfo::__pad2__ package
__pad3__
testing::TestInfo::__pad3__ package
code_location
const char const char const char internal::CodeLocation testing::TestInfo::code_location package
factory
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc Test::TearDownTestCaseFunc internal::TestFactoryBase* testing::TestInfo::factory package
factory_
internal::TestFactoryBase* const testing::TestInfo::factory_ package
Referenced by Run(), and ~TestInfo().
fixture_class_id
const char const char const char internal::CodeLocation internal::TypeId testing::TestInfo::fixture_class_id package
is_disabled_
bool testing::TestInfo::is_disabled_ package
Referenced by testing::internal::UnitTestImpl::FilterTests(), testing::TestCase::TestDisabled(), and testing::TestCase::TestReportableDisabled().
location_
internal::CodeLocation testing::TestInfo::location_ package
matches_filter_
bool testing::TestInfo::matches_filter_ package
Referenced by testing::internal::UnitTestImpl::FilterTests(), and testing::internal::UnitTestImpl::ListTestsMatchingFilter().
name
const char* testing::TestInfo::name package
Referenced by testing::internal::UnitTestImpl::FilterTests(), testing::Test::HasSameFixtureClass(), testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestStart(), testing::anonymous_namespace{gtest.cc}::TestNameIs::operator()(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests().
name_
const std::string testing::TestInfo::name_ package
result_
TestResult testing::TestInfo::result_ package
Referenced by ClearTestResult(), testing::internal::UnitTestImpl::current_test_result(), testing::internal::UnitTestImpl::RecordProperty(), and Run().
set_up_tc
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc testing::TestInfo::set_up_tc package
should_run_
bool testing::TestInfo::should_run_ package
Referenced by testing::internal::UnitTestImpl::FilterTests(), and Run().
tear_down_tc
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc Test::TearDownTestCaseFunc testing::TestInfo::tear_down_tc package
test_case_name_
const std::string testing::TestInfo::test_case_name_ package
type_param
const char const char* testing::TestInfo::type_param package
Referenced by testing::internal::UnitTestImpl::AddTestInfo(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PrintFullTestCommentIfPresent().
value_param
const char const char const char* testing::TestInfo::value_param package
Referenced by testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PrintFullTestCommentIfPresent().