Common Alogrithm: Adapter Class Reference
Adapter Class Reference
Public Member Functions
Cable live ()
Cable neutral ()
void plugIn (EuropeanSocketInterface *outlet)
int voltage ()
Private Attributes
EuropeanSocketInterface * socket
Detailed Description
Member Function Documentation
live()
Cable Adapter::live () inline virtual
Implements USASocketInterface.
 { return socket->live(); }
References EuropeanSocketInterface::live(), and socket.
neutral()
Cable Adapter::neutral () inline virtual
Implements USASocketInterface.
 { return socket->neutral(); }
References EuropeanSocketInterface::neutral(), and socket.
plugIn()
void Adapter::plugIn (EuropeanSocketInterface * outlet) inline
         {
             socket = outlet;
         }
References socket.
Referenced by main().
voltage()
int Adapter::voltage () inline virtual
Implements USASocketInterface.
 { return 110; }
Member Data Documentation
socket
EuropeanSocketInterface* Adapter::socket private
Referenced by live(), neutral(), and plugIn().