Common Alogrithm: Facade Class Reference
Facade Class Reference
Public Member Functions
Facade ()
void MethodA ()
void MethodB ()
Private Attributes
SubSystemFour four
SubSystemOne one
SubSystemThree three
SubSystemTwo two
Detailed Description
Constructor & Destructor Documentation
Facade()
Facade::Facade () inline
     {
     }
Member Function Documentation
MethodA()
void Facade::MethodA () inline
     {
         std::cout << "\nMethodA() ---- " << std::endl;
         one.MethodOne();
         two.MethodTwo();
         four.MethodFour();
     }
References four, SubSystemFour::MethodFour(), SubSystemOne::MethodOne(), SubSystemTwo::MethodTwo(), one, and two.
Referenced by main().
MethodB()
void Facade::MethodB () inline
     {
         std::cout << "\nMethodB() ---- " << std::endl;
         two.MethodTwo();
         three.MethodThree();
     }
References SubSystemThree::MethodThree(), SubSystemTwo::MethodTwo(), three, and two.
Referenced by main().
Member Data Documentation
four
SubSystemFour Facade::four private
Referenced by MethodA().
one
SubSystemOne Facade::one private
Referenced by MethodA().
three
SubSystemThree Facade::three private
Referenced by MethodB().
two
SubSystemTwo Facade::two private
Referenced by MethodA(), and MethodB().