Common Alogrithm: USASocketInterface Class Reference
USASocketInterface Class Reference abstract
Public Member Functions
virtual Cable live ()=0
virtual Cable neutral ()=0
virtual int voltage ()=0
Detailed Description
Member Function Documentation
live()
virtual Cable USASocketInterface::live () pure virtual
Implemented in Adapter.
Referenced by ElectricKettle::boil().
neutral()
virtual Cable USASocketInterface::neutral () pure virtual
Implemented in Adapter.
Referenced by ElectricKettle::boil().
voltage()
virtual int USASocketInterface::voltage () pure virtual
Implemented in Adapter.
Referenced by ElectricKettle::boil().