Common Alogrithm: lib/googletest/test/gtest-unittest-api_test.cc File Reference
gtest-unittest-api_test.cc File Reference
#include "gtest/gtest.h"
#include <string.h>
#include <algorithm>
Classes
class testing::internal::FinalSuccessChecker
struct testing::internal::LessByName< T >
class testing::internal::UnitTestHelper
Namespaces
testing
testing::internal
Functions
AssertionResult testing::internal::IsNull (const char *str)
int main (int argc, char **argv)
testing::internal::TEST (ApiTest, DISABLED_Dummy1)
testing::internal::TEST (ApiTest, TestCaseDisabledAccessorsWork)
testing::internal::TEST (ApiTest, TestCaseImmutableAccessorsWork)
testing::internal::TEST (ApiTest, UnitTestImmutableAccessorsWork)
testing::internal::TEST (DISABLED_Test, Dummy2)
Constants
const int testing::internal::kTypedTestCases = 0
const int testing::internal::kTypedTests = 0
Function Documentation
main()
int main (int argc, char ** argv)
{
   InitGoogleTest(&argc, argv);
   AddGlobalTestEnvironment(new testing::internal::FinalSuccessChecker());
   return RUN_ALL_TESTS();
 }
References testing::AddGlobalTestEnvironment(), testing::InitGoogleTest(), and RUN_ALL_TESTS().