Common Alogrithm: lib/googletest/test/gtest_output_test_.cc File Reference
gtest_output_test_.cc File Reference
#include "gtest/gtest-spi.h"
#include "gtest/gtest.h"
#include "src/gtest-internal-inl.h"
#include <stdlib.h>
Classes
class BarEnvironment
class ExpectFailureTest
class FailingParamTest
class FatalFailureInFixtureConstructorTest
class FatalFailureInSetUpTest
class FooEnvironment
class foo::MixedUpTestCaseTest
class bar::MixedUpTestCaseTest
class foo::MixedUpTestCaseWithSameTestNameTest
class bar::MixedUpTestCaseWithSameTestNameTest
class NonFatalFailureInFixtureConstructorTest
class NonFatalFailureInSetUpTest
class TEST_before_TEST_F_in_same_test_case
class TEST_F_before_TEST_in_same_test_case
Namespaces
bar
foo
Macros
#define GTEST_IMPLEMENTATION_ 1
Functions
void AdHocTest ()
void FatalFailure ()
INSTANTIATE_TEST_CASE_P (PrintingFailingParams, FailingParamTest, testing::Values(2))
int main (int argc, char **argv)
int RunAllTests ()
void SubWithoutTrace (int n)
void SubWithTrace (int n)
TEST (AddFailureAtTest, MessageContainsSpecifiedFileAndLineNumber)
TEST (DisabledTestsWarningTest, DISABLED_AlsoRunDisabledTestsFlagSuppressesWarning)
TEST (ExpectFatalFailureTest, CanReferenceGlobalVariables)
TEST (ExpectFatalFailureTest, CanReferenceLocalStaticVariables)
TEST (ExpectFatalFailureTest, FailsWhenStatementReturns)
TEST (ExpectFatalFailureTest, FailsWhenThereAreTwoFatalFailures)
TEST (ExpectFatalFailureTest, FailsWhenThereIsNoFatalFailure)
TEST (ExpectFatalFailureTest, FailsWhenThereIsOneNonfatalFailure)
TEST (ExpectFatalFailureTest, SucceedsWhenThereIsOneFatalFailure)
TEST (ExpectNonfatalFailureTest, CanReferenceGlobalVariables)
TEST (ExpectNonfatalFailureTest, CanReferenceLocalVariables)
TEST (ExpectNonfatalFailureTest, FailsWhenStatementReturns)
TEST (ExpectNonfatalFailureTest, FailsWhenThereAreTwoNonfatalFailures)
TEST (ExpectNonfatalFailureTest, FailsWhenThereIsNoNonfatalFailure)
TEST (ExpectNonfatalFailureTest, FailsWhenThereIsOneFatalFailure)
TEST (ExpectNonfatalFailureTest, SucceedsWhenThereIsOneNonfatalFailure)
TEST (FatalFailureTest, FatalFailureInNestedSubroutine)
TEST (FatalFailureTest, FatalFailureInSubroutine)
TEST (FatalFailureTest, NonfatalFailureInSubroutine)
TEST (LoggingTest, InterleavingLoggingAndAssertions)
TEST (NonfatalFailureTest, DiffForLongStrings)
TEST (NonfatalFailureTest, EscapesStringOperands)
TEST (PassingTest, PassingTest1)
TEST (PassingTest, PassingTest2)
TEST (SCOPED_TRACETest, CanBeNested)
TEST (SCOPED_TRACETest, CanBeRepeated)
TEST (SCOPED_TRACETest, ObeysScopes)
TEST (SCOPED_TRACETest, WorksInLoop)
TEST (SCOPED_TRACETest, WorksInSubroutine)
TEST (TEST_before_TEST_F_in_same_test_case, DefinedUsingTEST)
TEST (TEST_F_before_TEST_in_same_test_case, DefinedUsingTESTAndShouldFail)
TEST_F (ExpectFailureTest, ExpectFatalFailure)
TEST_F (ExpectFailureTest, ExpectFatalFailureOnAllThreads)
TEST_F (ExpectFailureTest, ExpectNonFatalFailure)
TEST_F (ExpectFailureTest, ExpectNonFatalFailureOnAllThreads)
TEST_F (FatalFailureInFixtureConstructorTest, FailureInConstructor)
TEST_F (FatalFailureInSetUpTest, FailureInSetUp)
foo::TEST_F (MixedUpTestCaseTest, FirstTestFromNamespaceFoo)
foo::TEST_F (MixedUpTestCaseTest, SecondTestFromNamespaceFoo)
bar::TEST_F (MixedUpTestCaseTest, ThisShouldFail)
bar::TEST_F (MixedUpTestCaseTest, ThisShouldFailToo)
foo::TEST_F (MixedUpTestCaseWithSameTestNameTest, TheSecondTestWithThisNameShouldFail)
bar::TEST_F (MixedUpTestCaseWithSameTestNameTest, TheSecondTestWithThisNameShouldFail)
TEST_F (NonFatalFailureInFixtureConstructorTest, FailureInConstructor)
TEST_F (NonFatalFailureInSetUpTest, FailureInSetUp)
TEST_F (TEST_before_TEST_F_in_same_test_case, DefinedUsingTEST_FAndShouldFail)
TEST_F (TEST_F_before_TEST_in_same_test_case, DefinedUsingTEST_F)
TEST_P (FailingParamTest, Fails)
void TestEq1 (int x)
void TryTestSubroutine ()
Constants
int global_integer = 0
static const char kGoldenString [] = "\"Line\0 1\"\nLine 2"
Macro Definition Documentation
GTEST_IMPLEMENTATION_
#define GTEST_IMPLEMENTATION_ 1
Function Documentation
AdHocTest()
void AdHocTest ()
                  {
   printf("The non-test part of the code is expected to have 2 failures.\n\n");
   EXPECT_TRUE(false);
   EXPECT_EQ(2, 3);
 }
References EXPECT_EQ, and EXPECT_TRUE.
Referenced by RunAllTests().
FatalFailure()
void FatalFailure ()
                     {
   FAIL() << "Expected fatal failure.";
 }
References FAIL.
Referenced by TEST().
INSTANTIATE_TEST_CASE_P()
INSTANTIATE_TEST_CASE_P (PrintingFailingParams , FailingParamTest , testing::Values(2))
main()
int main (int argc, char ** argv)
{
   testing::GTEST_FLAG(print_time) = false;
   // We just run the tests, knowing some of them are intended to fail.
   // We will use a separate Python script to compare the output of
   // this program with the golden file.
   // It's hard to test InitGoogleTest() directly, as it has many
   // global side effects.  The following line serves as a sanity test
   // for it.
   testing::InitGoogleTest(&argc, argv);
   bool internal_skip_environment_and_ad_hoc_tests =
       std::count(argv, argv + argc,
                  std::string("internal_skip_environment_and_ad_hoc_tests")) > 0;
 #if GTEST_HAS_DEATH_TEST
   if (testing::internal::GTEST_FLAG(internal_run_death_test) != "") {
     // Skip the usual output capturing if we're running as the child
     // process of an threadsafe-style death test.
 # if GTEST_OS_WINDOWS
     posix::FReopen("nul:", "w", stdout);
 # else
     posix::FReopen("/dev/null", "w", stdout);
 # endif  // GTEST_OS_WINDOWS
     return RUN_ALL_TESTS();
   }
 #endif  // GTEST_HAS_DEATH_TEST
   if (internal_skip_environment_and_ad_hoc_tests)
     return RUN_ALL_TESTS();
   // Registers two global test environments.
   // The golden file verifies that they are set up in the order they
   // are registered, and torn down in the reverse order.
   testing::AddGlobalTestEnvironment(new FooEnvironment);
   testing::AddGlobalTestEnvironment(new BarEnvironment);
   return RunAllTests();
 }
References testing::AddGlobalTestEnvironment(), std::count(), testing::internal::posix::FReopen(), GTEST_FLAG, testing::InitGoogleTest(), RUN_ALL_TESTS(), and RunAllTests().
RunAllTests()
int RunAllTests ()
                   {
   AdHocTest();
   return RUN_ALL_TESTS();
 }
References AdHocTest(), and RUN_ALL_TESTS().
Referenced by main().
SubWithoutTrace()
void SubWithoutTrace (int n)
{
   EXPECT_EQ(1, n);
   ASSERT_EQ(2, n);
 }
References ASSERT_EQ, and EXPECT_EQ.
Referenced by SubWithTrace(), and TEST().
SubWithTrace()
void SubWithTrace (int n)
{
   SCOPED_TRACE(testing::Message() << "n = " << n);
   SubWithoutTrace(n);
 }
References SCOPED_TRACE, and SubWithoutTrace().
Referenced by TEST().
TEST() [1/31]
TEST (AddFailureAtTest , MessageContainsSpecifiedFileAndLineNumber)
{
   ADD_FAILURE_AT("foo.cc", 42) << "Expected failure in foo.cc";
 }
References ADD_FAILURE_AT.
TEST() [2/31]
TEST (DisabledTestsWarningTest , DISABLED_AlsoRunDisabledTestsFlagSuppressesWarning)
{
   // This test body is intentionally empty.  Its sole purpose is for
   // verifying that the --gtest_also_run_disabled_tests flag
   // suppresses the "YOU HAVE 12 DISABLED TESTS" warning at the end of
   // the test output.
 }
TEST() [3/31]
TEST (ExpectFatalFailureTest , CanReferenceGlobalVariables)
{
   global_integer = 0;
   EXPECT_FATAL_FAILURE({
     ASSERT_EQ(1, global_integer) << "Expected fatal failure.";
   }, "Expected fatal failure.");
 }
References ASSERT_EQ, EXPECT_FATAL_FAILURE, and global_integer.
TEST() [4/31]
TEST (ExpectFatalFailureTest , CanReferenceLocalStaticVariables)
{
   static int n;
   n = 1;
   EXPECT_FATAL_FAILURE({
     ASSERT_EQ(0, n) << "Expected fatal failure.";
   }, "Expected fatal failure.");
 }
References ASSERT_EQ, and EXPECT_FATAL_FAILURE.
TEST() [5/31]
TEST (ExpectFatalFailureTest , FailsWhenStatementReturns)
{
   printf("(expecting a failure)\n");
   EXPECT_FATAL_FAILURE({
     return;
   }, "");
 }
References EXPECT_FATAL_FAILURE.
TEST() [6/31]
TEST (ExpectFatalFailureTest , FailsWhenThereAreTwoFatalFailures)
{
   printf("(expecting a failure)\n");
   EXPECT_FATAL_FAILURE({
     FatalFailure();
     FatalFailure();
   }, "");
 }
References EXPECT_FATAL_FAILURE, and FatalFailure().
TEST() [7/31]
TEST (ExpectFatalFailureTest , FailsWhenThereIsNoFatalFailure)
{
   printf("(expecting a failure)\n");
   EXPECT_FATAL_FAILURE({
   }, "");
 }
References EXPECT_FATAL_FAILURE.
TEST() [8/31]
TEST (ExpectFatalFailureTest , FailsWhenThereIsOneNonfatalFailure)
{
   printf("(expecting a failure)\n");
   EXPECT_FATAL_FAILURE({
     ADD_FAILURE() << "Expected non-fatal failure.";
   }, "");
 }
References ADD_FAILURE, and EXPECT_FATAL_FAILURE.
TEST() [9/31]
TEST (ExpectFatalFailureTest , SucceedsWhenThereIsOneFatalFailure)
{
   EXPECT_FATAL_FAILURE({
     FAIL() << "Expected fatal failure.";
   }, "Expected fatal failure.");
 }
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [10/31]
TEST (ExpectNonfatalFailureTest , CanReferenceGlobalVariables)
{
   global_integer = 0;
   EXPECT_NONFATAL_FAILURE({
     EXPECT_EQ(1, global_integer) << "Expected non-fatal failure.";
   }, "Expected non-fatal failure.");
 }
References EXPECT_EQ, EXPECT_NONFATAL_FAILURE, and global_integer.
TEST() [11/31]
TEST (ExpectNonfatalFailureTest , CanReferenceLocalVariables)
{
   int m = 0;
   static int n;
   n = 1;
   EXPECT_NONFATAL_FAILURE({
     EXPECT_EQ(m, n) << "Expected non-fatal failure.";
   }, "Expected non-fatal failure.");
 }
References EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [12/31]
TEST (ExpectNonfatalFailureTest , FailsWhenStatementReturns)
{
   printf("(expecting a failure)\n");
   EXPECT_NONFATAL_FAILURE({
     return;
   }, "");
 }
References EXPECT_NONFATAL_FAILURE.
TEST() [13/31]
TEST (ExpectNonfatalFailureTest , FailsWhenThereAreTwoNonfatalFailures)
{
   printf("(expecting a failure)\n");
   EXPECT_NONFATAL_FAILURE({
     ADD_FAILURE() << "Expected non-fatal failure 1.";
     ADD_FAILURE() << "Expected non-fatal failure 2.";
   }, "");
 }
References ADD_FAILURE, and EXPECT_NONFATAL_FAILURE.
TEST() [14/31]
TEST (ExpectNonfatalFailureTest , FailsWhenThereIsNoNonfatalFailure)
{
   printf("(expecting a failure)\n");
   EXPECT_NONFATAL_FAILURE({
   }, "");
 }
References EXPECT_NONFATAL_FAILURE.
TEST() [15/31]
TEST (ExpectNonfatalFailureTest , FailsWhenThereIsOneFatalFailure)
{
   printf("(expecting a failure)\n");
   EXPECT_NONFATAL_FAILURE({
     FAIL() << "Expected fatal failure.";
   }, "");
 }
References EXPECT_NONFATAL_FAILURE, and FAIL.
TEST() [16/31]
TEST (ExpectNonfatalFailureTest , SucceedsWhenThereIsOneNonfatalFailure)
{
   EXPECT_NONFATAL_FAILURE({
     ADD_FAILURE() << "Expected non-fatal failure.";
   }, "Expected non-fatal failure.");
 }
References ADD_FAILURE, and EXPECT_NONFATAL_FAILURE.
TEST() [17/31]
TEST (FatalFailureTest , FatalFailureInNestedSubroutine)
{
   printf("(expecting a failure that x should be 1)\n");
   // Calls a subrountine that yields a fatal failure.
   TryTestSubroutine();
   // Catches the fatal failure and aborts the test.
   //
   // When calling HasFatalFailure() inside a TEST, TEST_F, or test
   // fixture, the testing::Test:: prefix is not needed.
   if (HasFatalFailure()) return;
   // If we get here, something is wrong.
   FAIL() << "This should never be reached.";
 }
References FAIL, and TryTestSubroutine().
TEST() [18/31]
TEST (FatalFailureTest , FatalFailureInSubroutine)
{
   printf("(expecting a failure that x should be 1)\n");
   TryTestSubroutine();
 }
References TryTestSubroutine().
TEST() [19/31]
TEST (FatalFailureTest , NonfatalFailureInSubroutine)
{
   printf("(expecting a failure on false)\n");
   EXPECT_TRUE(false);  // Generates a nonfatal failure
   ASSERT_FALSE(HasFatalFailure());  // This should succeed.
 }
References ASSERT_FALSE, and EXPECT_TRUE.
TEST() [20/31]
TEST (LoggingTest , InterleavingLoggingAndAssertions)
{
   static const int a[4] = {
     3, 9, 2, 6
   };
   printf("(expecting 2 failures on (3) >= (a[i]))\n");
   for (int i = 0; i < static_cast<int>(sizeof(a)/sizeof(*a)); i++) {
     printf("i == %d\n", i);
     EXPECT_GE(3, a[i]);
   }
 }
References EXPECT_GE.
TEST() [21/31]
TEST (NonfatalFailureTest , DiffForLongStrings)
{
   std::string golden_str(kGoldenString, sizeof(kGoldenString) - 1);
   EXPECT_EQ(golden_str, "Line 2");
 }
References EXPECT_EQ, and kGoldenString.
TEST() [22/31]
TEST (NonfatalFailureTest , EscapesStringOperands)
{
   std::string actual = "actual \"string\"";
   EXPECT_EQ(kGoldenString, actual);
   const char* golden = kGoldenString;
   EXPECT_EQ(golden, actual);
 }
References EXPECT_EQ, and kGoldenString.
TEST() [23/31]
TEST (PassingTest , PassingTest1)
{
 }
TEST() [24/31]
TEST (PassingTest , PassingTest2)
{
 }
TEST() [25/31]
TEST (SCOPED_TRACETest , CanBeNested)
{
   printf("(expected to fail)\n");
   SCOPED_TRACE("");  // A trace without a message.
   SubWithTrace(2);
 }
References SCOPED_TRACE, and SubWithTrace().
TEST() [26/31]
TEST (SCOPED_TRACETest , CanBeRepeated)
{
   printf("(expected to fail)\n");
   SCOPED_TRACE("A");
   ADD_FAILURE()
       << "This failure is expected, and should contain trace point A.";
   SCOPED_TRACE("B");
   ADD_FAILURE()
       << "This failure is expected, and should contain trace point A and B.";
   {
     SCOPED_TRACE("C");
     ADD_FAILURE() << "This failure is expected, and should "
                   << "contain trace point A, B, and C.";
   }
   SCOPED_TRACE("D");
   ADD_FAILURE() << "This failure is expected, and should "
                 << "contain trace point A, B, and D.";
 }
References ADD_FAILURE, and SCOPED_TRACE.
TEST() [27/31]
TEST (SCOPED_TRACETest , ObeysScopes)
{
   printf("(expected to fail)\n");
   // There should be no trace before SCOPED_TRACE() is invoked.
   ADD_FAILURE() << "This failure is expected, and shouldn't have a trace.";
   {
     SCOPED_TRACE("Expected trace");
     // After SCOPED_TRACE(), a failure in the current scope should contain
     // the trace.
     ADD_FAILURE() << "This failure is expected, and should have a trace.";
   }
   // Once the control leaves the scope of the SCOPED_TRACE(), there
   // should be no trace again.
   ADD_FAILURE() << "This failure is expected, and shouldn't have a trace.";
 }
References ADD_FAILURE, and SCOPED_TRACE.
TEST() [28/31]
TEST (SCOPED_TRACETest , WorksInLoop)
{
   printf("(expected to fail)\n");
   for (int i = 1; i <= 2; i++) {
     SCOPED_TRACE(testing::Message() << "i = " << i);
     SubWithoutTrace(i);
   }
 }
References SCOPED_TRACE, and SubWithoutTrace().
TEST() [29/31]
TEST (SCOPED_TRACETest , WorksInSubroutine)
{
   printf("(expected to fail)\n");
   SubWithTrace(1);
   SubWithTrace(2);
 }
References SubWithTrace().
TEST() [30/31]
TEST (TEST_before_TEST_F_in_same_test_case , DefinedUsingTEST)
 {}
TEST() [31/31]
TEST (TEST_F_before_TEST_in_same_test_case , DefinedUsingTESTAndShouldFail)
 {}
TEST_F() [1/10]
TEST_F (ExpectFailureTest , ExpectFatalFailure)
{
   // Expected fatal failure, but succeeds.
   printf("(expecting 1 failure)\n");
   EXPECT_FATAL_FAILURE(SUCCEED(), "Expected fatal failure.");
   // Expected fatal failure, but got a non-fatal failure.
   printf("(expecting 1 failure)\n");
   EXPECT_FATAL_FAILURE(AddFailure(NONFATAL_FAILURE), "Expected non-fatal "
                        "failure.");
   // Wrong message.
   printf("(expecting 1 failure)\n");
   EXPECT_FATAL_FAILURE(AddFailure(FATAL_FAILURE), "Some other fatal failure "
                        "expected.");
 }
References EXPECT_FATAL_FAILURE, anonymous_namespace{gtest_environment_test.cc}::FATAL_FAILURE, and SUCCEED.
TEST_F() [2/10]
TEST_F (ExpectFailureTest , ExpectFatalFailureOnAllThreads)
{
   // Expected fatal failure, but succeeds.
   printf("(expecting 1 failure)\n");
   EXPECT_FATAL_FAILURE_ON_ALL_THREADS(SUCCEED(), "Expected fatal failure.");
   // Expected fatal failure, but got a non-fatal failure.
   printf("(expecting 1 failure)\n");
   EXPECT_FATAL_FAILURE_ON_ALL_THREADS(AddFailure(NONFATAL_FAILURE),
                                       "Expected non-fatal failure.");
   // Wrong message.
   printf("(expecting 1 failure)\n");
   EXPECT_FATAL_FAILURE_ON_ALL_THREADS(AddFailure(FATAL_FAILURE),
                                       "Some other fatal failure expected.");
 }
References EXPECT_FATAL_FAILURE_ON_ALL_THREADS, anonymous_namespace{gtest_environment_test.cc}::FATAL_FAILURE, and SUCCEED.
TEST_F() [3/10]
TEST_F (ExpectFailureTest , ExpectNonFatalFailure)
{
   // Expected non-fatal failure, but succeeds.
   printf("(expecting 1 failure)\n");
   EXPECT_NONFATAL_FAILURE(SUCCEED(), "Expected non-fatal failure.");
   // Expected non-fatal failure, but got a fatal failure.
   printf("(expecting 1 failure)\n");
   EXPECT_NONFATAL_FAILURE(AddFailure(FATAL_FAILURE), "Expected fatal failure.");
   // Wrong message.
   printf("(expecting 1 failure)\n");
   EXPECT_NONFATAL_FAILURE(AddFailure(NONFATAL_FAILURE), "Some other non-fatal "
                           "failure.");
 }
References EXPECT_NONFATAL_FAILURE, anonymous_namespace{gtest_environment_test.cc}::FATAL_FAILURE, and SUCCEED.
TEST_F() [4/10]
TEST_F (ExpectFailureTest , ExpectNonFatalFailureOnAllThreads)
{
   // Expected non-fatal failure, but succeeds.
   printf("(expecting 1 failure)\n");
   EXPECT_NONFATAL_FAILURE_ON_ALL_THREADS(SUCCEED(), "Expected non-fatal "
                                          "failure.");
   // Expected non-fatal failure, but got a fatal failure.
   printf("(expecting 1 failure)\n");
   EXPECT_NONFATAL_FAILURE_ON_ALL_THREADS(AddFailure(FATAL_FAILURE),
                                          "Expected fatal failure.");
   // Wrong message.
   printf("(expecting 1 failure)\n");
   EXPECT_NONFATAL_FAILURE_ON_ALL_THREADS(AddFailure(NONFATAL_FAILURE),
                                          "Some other non-fatal failure.");
 }
References EXPECT_NONFATAL_FAILURE_ON_ALL_THREADS, anonymous_namespace{gtest_environment_test.cc}::FATAL_FAILURE, and SUCCEED.
TEST_F() [5/10]
TEST_F (FatalFailureInFixtureConstructorTest , FailureInConstructor)
{
   ADD_FAILURE() << "UNEXPECTED failure in the test body.  "
                 << "We should never get here, as the test fixture c'tor "
                 << "had a fatal failure.";
 }
References ADD_FAILURE.
TEST_F() [6/10]
TEST_F (FatalFailureInSetUpTest , FailureInSetUp)
{
   FAIL() << "UNEXPECTED failure in the test function.  "
          << "We should never get here, as SetUp() failed.";
 }
References FAIL.
TEST_F() [7/10]
TEST_F (NonFatalFailureInFixtureConstructorTest , FailureInConstructor)
{
   ADD_FAILURE() << "Expected failure #3, in the test body.";
 }
References ADD_FAILURE.
TEST_F() [8/10]
TEST_F (NonFatalFailureInSetUpTest , FailureInSetUp)
{
   FAIL() << "Expected failure #2, in the test function.";
 }
References FAIL.
TEST_F() [9/10]
TEST_F (TEST_before_TEST_F_in_same_test_case , DefinedUsingTEST_FAndShouldFail)
{
 }
TEST_F() [10/10]
TEST_F (TEST_F_before_TEST_in_same_test_case , DefinedUsingTEST_F)
 {}
TEST_P()
TEST_P (FailingParamTest , Fails)
{
   EXPECT_EQ(1, GetParam());
 }
References EXPECT_EQ.
TestEq1()
void TestEq1 (int x)
                     {
   ASSERT_EQ(1, x);
 }
References ASSERT_EQ.
Referenced by anonymous_namespace{gtest_unittest.cc}::TEST(), and TryTestSubroutine().
TryTestSubroutine()
void TryTestSubroutine ()
{
   // Calls a subrountine that yields a fatal failure.
   TestEq1(2);
   // Catches the fatal failure and aborts the test.
   //
   // The testing::Test:: prefix is necessary when calling
   // HasFatalFailure() outside of a TEST, TEST_F, or test fixture.
   if (testing::Test::HasFatalFailure()) return;
   // If we get here, something is wrong.
   FAIL() << "This should never be reached.";
 }
References FAIL, testing::Test::HasFatalFailure(), and TestEq1().
Referenced by TEST().
Variable Documentation
global_integer
int global_integer = 0
Referenced by TEST().
kGoldenString
const char kGoldenString[] = "\"Line\0 1\"\nLine 2" static
Referenced by TEST().