Common Alogrithm: lib/googletest/test/gtest-death-test_test.cc File Reference
gtest-death-test_test.cc File Reference
#include "gtest/gtest-death-test.h"
#include "gtest/gtest.h"
#include "gtest/internal/gtest-filepath.h"
Functions
void FuncWithAssert (int *n)
TEST (ConditionalDeathMacrosSyntaxDeathTest, SingleStatement)
TEST (ConditionalDeathMacrosSyntaxDeathTest, SwitchStatement)
TEST (ConditionalDeathMacrosTest, AssertDeatDoesNotReturnhIfUnsupported)
TEST (ConditionalDeathMacrosTest, WarnsWhenDeathTestsNotAvailable)
TEST (NotADeathTest, Test)
Function Documentation
FuncWithAssert()
void FuncWithAssert (int * n)
{
   ASSERT_DEATH_IF_SUPPORTED(return;, "");
   (*n)++;
 }
References ASSERT_DEATH_IF_SUPPORTED.
Referenced by TEST().
TEST() [1/5]
TEST (ConditionalDeathMacrosSyntaxDeathTest , SingleStatement)
{
   if (AlwaysFalse())
     // This would fail if executed; this is a compilation test only
     ASSERT_DEATH_IF_SUPPORTED(return, "");
   if (AlwaysTrue())
     EXPECT_DEATH_IF_SUPPORTED(_exit(1), "");
   else
     // This empty "else" branch is meant to ensure that EXPECT_DEATH
     // doesn't expand into an "if" statement without an "else"
     ;  // NOLINT
   if (AlwaysFalse())
     ASSERT_DEATH_IF_SUPPORTED(return, "") << "did not die";
   if (AlwaysFalse())
     ;  // NOLINT
   else
     EXPECT_DEATH_IF_SUPPORTED(_exit(1), "") << 1 << 2 << 3;
 }
References testing::internal::AlwaysFalse(), testing::internal::AlwaysTrue(), ASSERT_DEATH_IF_SUPPORTED, and EXPECT_DEATH_IF_SUPPORTED.
TEST() [2/5]
TEST (ConditionalDeathMacrosSyntaxDeathTest , SwitchStatement)
{
   // Microsoft compiler usually complains about switch statements without
   // case labels. We suppress that warning for this test.
   GTEST_DISABLE_MSC_WARNINGS_PUSH_(4065)
   switch (0)
     default:
       ASSERT_DEATH_IF_SUPPORTED(_exit(1), "")
           << "exit in default switch handler";
   switch (0)
     case 0:
       EXPECT_DEATH_IF_SUPPORTED(_exit(1), "") << "exit in switch case";
   GTEST_DISABLE_MSC_WARNINGS_POP_()
 }
References ASSERT_DEATH_IF_SUPPORTED, EXPECT_DEATH_IF_SUPPORTED, GTEST_DISABLE_MSC_WARNINGS_POP_, and GTEST_DISABLE_MSC_WARNINGS_PUSH_.
TEST() [3/5]
TEST (ConditionalDeathMacrosTest , AssertDeatDoesNotReturnhIfUnsupported)
{
   int n = 0;
   FuncWithAssert(&n);
   EXPECT_EQ(1, n);
 }
References EXPECT_EQ, and FuncWithAssert().
TEST() [4/5]
TEST (ConditionalDeathMacrosTest , WarnsWhenDeathTestsNotAvailable)
{
   // Empty statement will not crash, but that should not trigger a failure
   // when death tests are not supported.
   CaptureStderr();
   EXPECT_DEATH_IF_SUPPORTED(;, "");
   std::string output = GetCapturedStderr();
   ASSERT_TRUE(NULL != strstr(output.c_str(),
                              "Death tests are not supported on this platform"));
   ASSERT_TRUE(NULL != strstr(output.c_str(), ";"));
   // The streamed message should not be printed as there is no test failure.
   CaptureStderr();
   EXPECT_DEATH_IF_SUPPORTED(;, "") << "streamed message";
   output = GetCapturedStderr();
   ASSERT_TRUE(NULL == strstr(output.c_str(), "streamed message"));
   CaptureStderr();
   ASSERT_DEATH_IF_SUPPORTED(;, "");  // NOLINT
   output = GetCapturedStderr();
   ASSERT_TRUE(NULL != strstr(output.c_str(),
                              "Death tests are not supported on this platform"));
   ASSERT_TRUE(NULL != strstr(output.c_str(), ";"));
   CaptureStderr();
   ASSERT_DEATH_IF_SUPPORTED(;, "") << "streamed message";  // NOLINT
   output = GetCapturedStderr();
   ASSERT_TRUE(NULL == strstr(output.c_str(), "streamed message"));
 }
References ASSERT_DEATH_IF_SUPPORTED, ASSERT_TRUE, testing::internal::CaptureStderr(), EXPECT_DEATH_IF_SUPPORTED, testing::internal::GetCapturedStderr(), and gtest_output_test::output.
TEST() [5/5]
TEST (NotADeathTest , Test)
{
   SUCCEED();
 }
References SUCCEED.