Common Alogrithm: common Namespace Reference
common Namespace Reference
Classes
struct BSTNode
Functions
void DeleteTree (BSTNode *node)
BSTNode * DeleteValue (BSTNode *node, int value)
int GetHeight (BSTNode *node)
int GetMax (BSTNode *node)
BSTNode * GetMaxNode (BSTNode *node)
int GetMin (BSTNode *node)
BSTNode * GetMinNode (BSTNode *node)
BSTNode * GetNewNode (int value)
BSTNode * Insert (BSTNode *node, int value)
bool IsBetween (BSTNode *node, int min, int max)
bool IsBinarySearchTree (BSTNode *node)
void PrintBFS (BSTNode *node)
void PrintInOrder (BSTNode *node)
bool Search (BSTNode *node, int value)
Class Documentation
common::BSTNode
struct common::BSTNode
Class Members
int data
BSTNode * left
BSTNode * right
Function Documentation
DeleteTree()
void common::DeleteTree (BSTNode * node)
{
     if (node == nullptr) return;
     if (node->left != nullptr) DeleteTree(node->left);
     if (node->right != nullptr) DeleteTree(node->right);
     delete node;
 }
References common::BSTNode::left, and common::BSTNode::right.
Referenced by main().
DeleteValue()
BSTNode * common::DeleteValue (BSTNode * node, int value)
{
     if (node == nullptr) return nullptr;
     if (value < node->data)
         node->left = DeleteValue(node->left, value);
     else if (value > node->data)
         node->right = DeleteValue(node->right, value);
     else {
         // Delete the matching value
         if (node->left == nullptr && node->right == nullptr) {
             delete node;
             node = nullptr;
         } else if (node->left == nullptr) {
             BSTNode* temp = node;
             node = node->right;
             delete temp;
         } else if (node->right == nullptr) {
             BSTNode* temp = node;
             node = node->left;
             delete temp;
         } else {
             BSTNode* temp = GetMinNode(node->right);
             node->data = temp->data; // replace min data in the right node with deleted value
             node->right = DeleteValue(node->right, temp->data); // reconstruct binary tree
         }
     }
     return node;
 }
References common::BSTNode::data, GetMinNode(), common::BSTNode::left, and common::BSTNode::right.
Referenced by main().
GetHeight()
int common::GetHeight (BSTNode * node)
{
     if (node == nullptr) return 0;
     return 1 + std::max(GetHeight(node->left), GetHeight(node->right));
 }
References common::BSTNode::left, std::max(), and common::BSTNode::right.
Referenced by main().
GetMax()
int common::GetMax (BSTNode * node)
{
     if (node == nullptr) return -1;
     if (node->right == nullptr)
         return node->data;
     return GetMax(node->right);
 }
References common::BSTNode::data, and common::BSTNode::right.
Referenced by main().
GetMaxNode()
BSTNode * common::GetMaxNode (BSTNode * node)
{
     if (node == nullptr) return nullptr;
     if (node->right == nullptr)
         return node;
     return GetMaxNode(node->right);
 }
References common::BSTNode::right.
GetMin()
int common::GetMin (BSTNode * node)
{
     if (node == nullptr) return -1;
     if (node->left == nullptr)
         return node->data;
     return GetMin(node->left);
 }
References common::BSTNode::data, and common::BSTNode::left.
Referenced by main().
GetMinNode()
BSTNode * common::GetMinNode (BSTNode * node)
{
     if (node == nullptr) return nullptr;
     if(node->left == nullptr)
         return node;
     return GetMinNode(node->left);
 }
References common::BSTNode::left.
Referenced by DeleteValue().
GetNewNode()
BSTNode * common::GetNewNode (int value)
{
     BSTNode* node = new BSTNode;
     node->data = value;
     node->left = nullptr;
     node->right = nullptr;
     return node;
 }
References common::BSTNode::data, common::BSTNode::left, and common::BSTNode::right.
Referenced by Insert().
Insert()
BSTNode * common::Insert (BSTNode * node, int value)
{
     // First Node
     if (node == nullptr) {
         node = GetNewNode(value);
         return node;
     }
     if (value < node->data) {
         node->left = Insert(node->left, value);
     } else if (value > node->data) {
         node->right = Insert(node->right, value);
     }
     return node;
 }
References common::BSTNode::data, GetNewNode(), common::BSTNode::left, and common::BSTNode::right.
Referenced by main().
IsBetween()
bool common::IsBetween (BSTNode * node, int min, int max)
{
     if (node == nullptr) return true;
     if (node->data > min && node->data < max &&
         IsBetween(node->left, min, node->data) &&
         IsBetween(node->right, node->data, max))
         return true;
     else
         return false;
 }
References common::BSTNode::data, common::BSTNode::left, and common::BSTNode::right.
Referenced by IsBinarySearchTree().
IsBinarySearchTree()
bool common::IsBinarySearchTree (BSTNode * node)
{
     return IsBetween(node, INT_MIN, INT_MAX);
 }
References IsBetween().
Referenced by main().
PrintBFS()
void common::PrintBFS (BSTNode * node)
{
     std::queue<BSTNode*> node_queue;
     BSTNode* current;
     node_queue.push(node);
     while (! node_queue.empty()) {
         current = node_queue.front();
         node_queue.pop();
         if (current != nullptr) {
             std::cout << current->data << " ";
             if (current->left != nullptr) node_queue.push(current->left);
             if (current->right != nullptr) node_queue.push(current->right);
         }
     }
 }
References common::BSTNode::data, std::queue< T >::empty(), std::queue< T >::front(), common::BSTNode::left, std::queue< T >::pop(), std::queue< T >::push(), and common::BSTNode::right.
Referenced by main().
PrintInOrder()
void common::PrintInOrder (BSTNode * node)
{
     if (node == nullptr) return;
     if (node->left != nullptr) PrintInOrder(node->left);
     std::cout << node->data << " ";
     if (node->right != nullptr) PrintInOrder(node->right);
 }
References common::BSTNode::data, common::BSTNode::left, and common::BSTNode::right.
Referenced by main().
Search()
bool common::Search (BSTNode * node, int value)
{
     if (node == nullptr) return false;
     if (value < node->data) {
         return Search(node->left, value);
     } else if (value > node->data) {
         return Search(node->right, value);
     } else {
         return true;
     }
 }
References common::BSTNode::data, common::BSTNode::left, and common::BSTNode::right.
Referenced by main().