Common Alogrithm: EnqueueTest Class Reference
EnqueueTest Class Reference abstract
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
Package Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test)
virtual Setup_should_be_spelled_SetUp * Setup ()
Static Package Functions
static bool HasFailure ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
Package Attributes
__pad0__:SetUpTestCaseFunc SetUpTestCaseFunc
__pad1__:TearDownTestCaseFunc TearDownTestCaseFunc
__pad2__:scoped_ptr< GTEST_FLAG_SAVER_ > gtest_flag_saver_
Private Member Functions
void DeleteSelf_ ()
void Run ()
virtual void TestBody ()=0
Static Private Member Functions
static bool HasSameFixtureClass ()
Detailed Description
Definition at line 7 of file queue_linked_list_unit_test.cc.
Member Function Documentation
DeleteSelf_()
void DeleteSelf_ () private inherited
Definition at line 453 of file gtest.h.
 { delete this; }
Referenced by TestInfo::Run().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test) package inherited
HasFailure()
static bool HasFailure () static package inherited
Definition at line 407 of file gtest.h.
 { return HasFatalFailure() || HasNonfatalFailure(); }
HasFatalFailure()
bool HasFatalFailure () static package inherited
Definition at line 2487 of file gtest.cc.
{
   return internal::GetUnitTestImpl()->current_test_result()->HasFatalFailure();
 }
References UnitTestImpl::current_test_result(), testing::internal::GetUnitTestImpl(), and TestResult::HasFatalFailure().
Referenced by TestInfo::Run(), and UnitTestImpl::RunAllTests().
HasNonfatalFailure()
bool HasNonfatalFailure () static package inherited
Definition at line 2492 of file gtest.cc.
{
   return internal::GetUnitTestImpl()->current_test_result()->
       HasNonfatalFailure();
 }
References UnitTestImpl::current_test_result(), and testing::internal::GetUnitTestImpl().
HasSameFixtureClass()
bool HasSameFixtureClass () static private inherited
Definition at line 2269 of file gtest.cc.
{
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   const TestCase* const test_case = impl->current_test_case();
   // Info about the first test in the current test case.
   const TestInfo* const first_test_info = test_case->test_info_list()[0];
   const internal::TypeId first_fixture_id = first_test_info->fixture_class_id_;
   const char* const first_test_name = first_test_info->name();
   // Info about the current test.
   const TestInfo* const this_test_info = impl->current_test_info();
   const internal::TypeId this_fixture_id = this_test_info->fixture_class_id_;
   const char* const this_test_name = this_test_info->name();
   if (this_fixture_id != first_fixture_id) {
     // Is the first test defined using TEST?
     const bool first_is_TEST = first_fixture_id == internal::GetTestTypeId();
     // Is this test defined using TEST?
     const bool this_is_TEST = this_fixture_id == internal::GetTestTypeId();
     if (first_is_TEST || this_is_TEST) {
       // Both TEST and TEST_F appear in same test case, which is incorrect.
       // Tell the user how to fix this.
       // Gets the name of the TEST and the name of the TEST_F.  Note
       // that first_is_TEST and this_is_TEST cannot both be true, as
       // the fixture IDs are different for the two tests.
       const char* const TEST_name =
           first_is_TEST ? first_test_name : this_test_name;
       const char* const TEST_F_name =
           first_is_TEST ? this_test_name : first_test_name;
       ADD_FAILURE()
           << "All tests in the same test case must use the same test fixture\n"
           << "class, so mixing TEST_F and TEST in the same test case is\n"
           << "illegal.  In test case " << this_test_info->test_case_name()
           << ",\n"
           << "test " << TEST_F_name << " is defined using TEST_F but\n"
           << "test " << TEST_name << " is defined using TEST.  You probably\n"
           << "want to change the TEST to TEST_F or move it to another test\n"
           << "case.";
     } else {
       // Two fixture classes with the same name appear in two different
       // namespaces, which is not allowed. Tell the user how to fix this.
       ADD_FAILURE()
           << "All tests in the same test case must use the same test fixture\n"
           << "class.  However, in test case "
           << this_test_info->test_case_name() << ",\n"
           << "you defined test " << first_test_name
           << " and test " << this_test_name << "\n"
           << "using two different test fixture classes.  This can happen if\n"
           << "the two classes are from different namespaces or translation\n"
           << "units and have the same name.  You should probably rename one\n"
           << "of the classes to put the tests into different test cases.";
     }
     return false;
   }
   return true;
 }
References ADD_FAILURE, UnitTestImpl::current_test_case(), UnitTestImpl::current_test_info(), testing::internal::GetTestTypeId(), testing::internal::GetUnitTestImpl(), TestInfo::name, TestInfo::test_case_name(), and TestCase::test_info_list().
RecordProperty() [1/2]
void RecordProperty (const std::string & key, const std::string & value) static package inherited
Definition at line 2237 of file gtest.cc.
{
   UnitTest::GetInstance()->RecordProperty(key, value);
 }
References UnitTest::GetInstance(), and UnitTest::RecordProperty().
Referenced by Test::RecordProperty().
RecordProperty() [2/2]
void RecordProperty (const std::string & key, int value) static package inherited
Definition at line 2242 of file gtest.cc.
{
   Message value_message;
   value_message << value;
   RecordProperty(key, value_message.GetString().c_str());
 }
References string::c_str(), Message::GetString(), and Test::RecordProperty().
Run()
void Run () private inherited
Definition at line 2465 of file gtest.cc.
                {
   if (!HasSameFixtureClass()) return;
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(this, &Test::SetUp, "SetUp()");
   // We will run the test only if SetUp() was successful.
   if (!HasFatalFailure()) {
     impl->os_stack_trace_getter()->UponLeavingGTest();
     internal::HandleExceptionsInMethodIfSupported(
         this, &Test::TestBody, "the test body");
   }
   // However, we want to clean up as much as possible.  Hence we will
   // always call TearDown(), even if SetUp() or the test body has
   // failed.
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       this, &Test::TearDown, "TearDown()");
 }
References testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), UnitTestImpl::os_stack_trace_getter(), and OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by TestInfo::Run().
SetUp()
void SetUp () protected virtual inherited
Definition at line 2227 of file gtest.cc.
                  {
 }
Setup()
virtual Setup_should_be_spelled_SetUp* Setup () package virtual inherited
Definition at line 474 of file gtest.h.
 { return NULL; }
SetUpTestCase()
static void SetUpTestCase () static package inherited
Definition at line 389 of file gtest.h.
 {}
TearDown()
void TearDown () protected virtual inherited
Definition at line 2233 of file gtest.cc.
                     {
 }
TearDownTestCase()
static void TearDownTestCase () static package inherited
Definition at line 397 of file gtest.h.
 {}
TestBody()
virtual void TestBody () private pure virtual inherited
Member Data Documentation
__pad0__
__pad0__ package inherited
Definition at line 377 of file gtest.h.
__pad1__
__pad1__ package inherited
Definition at line 378 of file gtest.h.
__pad2__
__pad2__ package inherited
Definition at line 455 of file gtest.h.