Common Alogrithm: TestProperty Class Reference
TestProperty Class Reference
#include <gtest.h>
Public Member Functions
const char * key () const
void SetValue (const std::string &new_value)
TestProperty (const std::string &a_key, const std::string &a_value)
const char * value () const
Private Attributes
std::string key_
std::string value_
Detailed Description
Definition at line 486 of file gtest.h.
Constructor & Destructor Documentation
TestProperty()
TestProperty (const std::string & a_key, const std::string & a_value)
Definition at line 491 of file gtest.h.
                                                                  :
     key_(a_key), value_(a_value) {
   }
Member Function Documentation
key()
const char* key () const
Definition at line 496 of file gtest.h.
{
     return key_.c_str();
   }
References string::c_str(), and TestProperty::key_.
Referenced by TestPropertyKeyIs::operator()(), TestResult::RecordProperty(), and TestResult::ValidateTestProperty().
SetValue()
void SetValue (const std::string & new_value)
Definition at line 506 of file gtest.h.
{
     value_ = new_value;
   }
References TestProperty::value_.
value()
const char* value () const
Definition at line 501 of file gtest.h.
{
     return value_.c_str();
   }
References string::c_str(), and TestProperty::value_.
Referenced by TestResult::RecordProperty().
Member Data Documentation
key_
std::string key_ private
Definition at line 512 of file gtest.h.
Referenced by TestProperty::key().
value_
std::string value_ private
Definition at line 514 of file gtest.h.
Referenced by TestProperty::SetValue(), and TestProperty::value().