Common Alogrithm: TestPartResultArray Class Reference
TestPartResultArray Class Reference
#include <gtest-test-part.h>
Public Member Functions
void Append (const TestPartResult &result)
const TestPartResult & GetTestPartResult (int index) const
int size () const
TestPartResultArray ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestPartResultArray)
Private Attributes
std::vector< TestPartResult > array_
Detailed Description
Definition at line 126 of file gtest-test-part.h.
Constructor & Destructor Documentation
TestPartResultArray()
TestPartResultArray ()
Definition at line 128 of file gtest-test-part.h.
 {}
Member Function Documentation
Append()
void Append (const TestPartResult & result)
Definition at line 68 of file gtest-test-part.cc.
{
   array_.push_back(result);
 }
References TestPartResultArray::array_.
Referenced by ScopedFakeTestPartResultReporter::ReportTestPartResult().
GetTestPartResult()
const TestPartResult & GetTestPartResult (int index) const
Definition at line 73 of file gtest-test-part.cc.
{
   if (index < 0 || index >= size()) {
     printf("\nInvalid index (%d) into TestPartResultArray.\n", index);
     internal::posix::Abort();
   }
   return array_[index];
 }
References TestPartResultArray::array_, and TestPartResultArray::size().
Referenced by testing::internal::HasOneFailure().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestPartResultArray) private
size()
int size () const
Definition at line 83 of file gtest-test-part.cc.
{
   return static_cast<int>(array_.size());
 }
References TestPartResultArray::array_.
Referenced by TestPartResultArray::GetTestPartResult(), and testing::internal::HasOneFailure().
Member Data Documentation
array_
std::vector<TestPartResult> array_ private
Definition at line 140 of file gtest-test-part.h.
Referenced by TestPartResultArray::Append(), TestPartResultArray::GetTestPartResult(), and TestPartResultArray::size().