Common Alogrithm: stdlib_experiments
stdlib_experiments()
void stdlib_experiments ()
 {
     std::unordered_map<std::string, std::string> states;
     states["Texas"] = "Austin";
     states["Florida"] = "Tallahassee";
     states["Washington"] = "Olympia";
     for (auto it = states.begin(); it != states.end(); ++it) {
         std::cout << "The capital of " << it->first << " is " << it->second << std::endl;
     }
     auto iter = states.find("Oregon");
     if (iter == states.end()) {
         std::cout << "Oregon not found" << std::endl;
     }
     for (int i = 0; i < states.bucket_count(); ++i) {
         std::cout << "Size of bucket " << i << ": " << states.bucket_size(i) << std::endl;
     }
 }
References unordered_map< K, T >::begin(), unordered_map< K, T >::bucket_count(), unordered_map< K, T >::bucket_size(), unordered_map< K, T >::end(), std::endl(), and unordered_map< K, T >::find().
Referenced by main().