Common Alogrithm: hash_table/main.cc File Reference
main.cc File Reference
(507f1dfca013d51e60369bb6d51e86175d87c82c)
#include "./hash_table.h"
#include "./hash_table_tests.h"
#include <unordered_map>
Functions
int main (int argc, char *argv[])
void stdlib_experiments ()
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 28 of file main.cc.
 {
     run_all_tests();
     stdlib_experiments();
     return 0;
 }
References run_all_tests(), and stdlib_experiments().
stdlib_experiments()
void stdlib_experiments ()
Definition at line 6 of file main.cc.
 {
     std::unordered_map<std::string, std::string> states;
     states["Texas"] = "Austin";
     states["Florida"] = "Tallahassee";
     states["Washington"] = "Olympia";
     for (auto it = states.begin(); it != states.end(); ++it) {
         std::cout << "The capital of " << it->first << " is " << it->second << std::endl;
     }
     auto iter = states.find("Oregon");
     if (iter == states.end()) {
         std::cout << "Oregon not found" << std::endl;
     }
     for (int i = 0; i < states.bucket_count(); ++i) {
         std::cout << "Size of bucket " << i << ": " << states.bucket_size(i) << std::endl;
     }
 }
References unordered_map< K, T >::begin(), unordered_map< K, T >::bucket_count(), unordered_map< K, T >::bucket_size(), unordered_map< K, T >::end(), std::endl(), and unordered_map< K, T >::find().
Referenced by main().