Common Alogrithm: common::BinarySearch::PrintBFS
PrintBFS()
void PrintBFS (BSTNode * node)
{
     std::queue<BSTNode*> node_queue;
     BSTNode* current;
     node_queue.push(node);
     while (! node_queue.empty()) {
         current = node_queue.front();
         node_queue.pop();
         if (current != nullptr) {
             std::cout << current->data << " ";
             if (current->left != nullptr) node_queue.push(current->left);
             if (current->right != nullptr) node_queue.push(current->right);
         }
     }
 }
References BSTNode::data, queue< T >::empty(), queue< T >::front(), BSTNode::left, queue< T >::pop(), queue< T >::push(), and BSTNode::right.