Common Alogrithm: TestInfo Class Reference
TestInfo Class Reference
#include <gtest.h>
Public Member Functions
const char * file () const
bool is_reportable () const
int line () const
const char * name () const
const TestResult * result () const
bool should_run () const
const char * test_case_name () const
const char * type_param () const
const char * value_param () const
~TestInfo ()
Package Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo)
int increment_death_test_count ()
void Run ()
TestInfo (const std::string &test_case_name, const std::string &name, const char *a_type_param, const char *a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase *factory)
Static Package Functions
static void ClearTestResult (TestInfo *test_info)
Package Attributes
__pad0__:MakeAndRegisterTestInfo(const char* test_case_name
__pad1__:scoped_ptr<const ::std::string> type_param_
__pad2__:scoped_ptr<const ::std::string> value_param_
__pad3__:TypeId fixture_class_id_
const char const char const char internal::CodeLocation code_location
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc Test::TearDownTestCaseFunc internal::TestFactoryBase * factory
internal::TestFactoryBase *const factory_
const char const char const char internal::CodeLocation internal::TypeId fixture_class_id
bool is_disabled_
internal::CodeLocation location_
bool matches_filter_
const char * name
const std::string name_
TestResult result_
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc set_up_tc
bool should_run_
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc Test::TearDownTestCaseFunc tear_down_tc
const std::string test_case_name_
const char const char * type_param
const char const char const char * value_param
Friends
class internal::StreamingListenerTest
class internal::UnitTestImpl
class Test
class TestCase
Detailed Description
Definition at line 644 of file gtest.h.
Constructor & Destructor Documentation
~TestInfo()
~TestInfo ()
Definition at line 2521 of file gtest.cc.
 { delete factory_; }
References TestInfo::factory_.
TestInfo()
TestInfo (const std::string & test_case_name, const std::string & name, const char * a_type_param, const char * a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase * factory) package
Definition at line 2501 of file gtest.cc.
     : test_case_name_(a_test_case_name),
       name_(a_name),
       type_param_(a_type_param ? new std::string(a_type_param) : NULL),
       value_param_(a_value_param ? new std::string(a_value_param) : NULL),
       location_(a_code_location),
       fixture_class_id_(fixture_class_id),
       should_run_(false),
       is_disabled_(false),
       matches_filter_(false),
       factory_(factory),
       result_() {}
Member Function Documentation
ClearTestResult()
static void ClearTestResult (TestInfo * test_info) static package
Definition at line 746 of file gtest.h.
{
     test_info->result_.Clear();
   }
References TestResult::Clear(), and TestInfo::result_.
Referenced by TestCase::ClearResult().
file()
const char* file () const
Definition at line 673 of file gtest.h.
 { return location_.file.c_str(); }
GTEST_DISALLOW_COPY_AND_ASSIGN_()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo) package
increment_death_test_count()
int increment_death_test_count () package
Definition at line 738 of file gtest.h.
{
     return result_.increment_death_test_count();
   }
is_reportable()
bool is_reportable () const
Definition at line 697 of file gtest.h.
{
     // For now, the XML report includes all tests matching the filter.
     // In the future, we may trim tests that are excluded because of
     // sharding.
     return matches_filter_;
   }
Referenced by XmlUnitTestResultPrinter::PrintXmlTestCase(), TestCase::TestReportable(), and TestCase::TestReportableDisabled().
line()
int line () const
Definition at line 676 of file gtest.h.
 { return location_.line; }
name()
const char* name () const
Definition at line 654 of file gtest.h.
 { return name_.c_str(); }
result()
const TestResult* result () const
Definition at line 705 of file gtest.h.
 { return &result_; }
Referenced by PrettyUnitTestResultPrinter::OnTestEnd(), XmlUnitTestResultPrinter::OutputXmlTestInfo(), PrettyUnitTestResultPrinter::PrintFailedTests(), TestCase::TestFailed(), and TestCase::TestPassed().
Run()
void Run () package
Definition at line 2630 of file gtest.cc.
                    {
   if (!should_run_) return;
   // Tells UnitTest where to store test result.
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   impl->set_current_test_info(this);
   TestEventListener* repeater = UnitTest::GetInstance()->listeners().repeater();
   // Notifies the unit test event listeners that a test is about to start.
   repeater->OnTestStart(*this);
   const TimeInMillis start = internal::GetTimeInMillis();
   impl->os_stack_trace_getter()->UponLeavingGTest();
   // Creates the test object.
   Test* const test = internal::HandleExceptionsInMethodIfSupported(
       factory_, &internal::TestFactoryBase::CreateTest,
       "the test fixture's constructor");
   // Runs the test only if the test object was created and its
   // constructor didn't generate a fatal failure.
   if ((test != NULL) && !Test::HasFatalFailure()) {
     // This doesn't throw as all user code that can throw are wrapped into
     // exception handling code.
     test->Run();
   }
   // Deletes the test object.
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       test, &Test::DeleteSelf_, "the test fixture's destructor");
   result_.set_elapsed_time(internal::GetTimeInMillis() - start);
   // Notifies the unit test event listener that a test has just finished.
   repeater->OnTestEnd(*this);
   // Tells UnitTest to stop associating assertion results to this
   // test.
   impl->set_current_test_info(NULL);
 }
References TestFactoryBase::CreateTest(), Test::DeleteSelf_(), TestInfo::factory_, UnitTest::GetInstance(), testing::internal::GetTimeInMillis(), testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), Test::HasFatalFailure(), UnitTest::listeners(), TestEventListener::OnTestEnd(), TestEventListener::OnTestStart(), UnitTestImpl::os_stack_trace_getter(), TestEventListeners::repeater(), TestInfo::result_, Test::Run(), UnitTestImpl::set_current_test_info(), TestResult::set_elapsed_time(), TestInfo::should_run_, and OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by TestCase::Run().
should_run()
bool should_run () const
Definition at line 694 of file gtest.h.
 { return should_run_; }
Referenced by XmlUnitTestResultPrinter::OutputXmlTestInfo(), PrettyUnitTestResultPrinter::PrintFailedTests(), TestCase::ShouldRunTest(), TestCase::TestFailed(), and TestCase::TestPassed().
test_case_name()
const char* test_case_name () const
Definition at line 651 of file gtest.h.
 { return test_case_name_.c_str(); }
Referenced by UnitTestImpl::AddTestInfo(), Test::HasSameFixtureClass(), PrettyUnitTestResultPrinter::OnTestEnd(), and PrettyUnitTestResultPrinter::OnTestStart().
type_param()
const char* type_param () const
Definition at line 658 of file gtest.h.
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
value_param()
const char* value_param () const
Definition at line 666 of file gtest.h.
{
     if (value_param_.get() != NULL)
       return value_param_->c_str();
     return NULL;
   }
Friends And Related Function Documentation
internal::StreamingListenerTest
friend class internal::StreamingListenerTest friend
Definition at line 714 of file gtest.h.
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
Definition at line 713 of file gtest.h.
Test
friend class Test friend
Definition at line 711 of file gtest.h.
TestCase
friend class TestCase friend
Definition at line 712 of file gtest.h.
Member Data Documentation
__pad0__
__pad0__ package
Definition at line 715 of file gtest.h.
__pad1__
__pad1__ package
Definition at line 755 of file gtest.h.
__pad2__
__pad2__ package
Definition at line 758 of file gtest.h.
__pad3__
__pad3__ package
Definition at line 760 of file gtest.h.
code_location
const char const char const char internal::CodeLocation code_location package
Definition at line 720 of file gtest.h.
factory
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc Test::TearDownTestCaseFunc internal::TestFactoryBase* factory package
Definition at line 724 of file gtest.h.
factory_
internal::TestFactoryBase* const factory_ package
Definition at line 765 of file gtest.h.
Referenced by TestInfo::Run(), and TestInfo::~TestInfo().
fixture_class_id
const char const char const char internal::CodeLocation internal::TypeId fixture_class_id package
Definition at line 721 of file gtest.h.
is_disabled_
bool is_disabled_ package
Definition at line 762 of file gtest.h.
Referenced by UnitTestImpl::FilterTests(), TestCase::TestDisabled(), and TestCase::TestReportableDisabled().
location_
internal::CodeLocation location_ package
Definition at line 759 of file gtest.h.
matches_filter_
bool matches_filter_ package
Definition at line 763 of file gtest.h.
Referenced by UnitTestImpl::FilterTests(), and UnitTestImpl::ListTestsMatchingFilter().
name
const char* name package
Definition at line 717 of file gtest.h.
Referenced by UnitTestImpl::FilterTests(), Test::HasSameFixtureClass(), UnitTestImpl::ListTestsMatchingFilter(), PrettyUnitTestResultPrinter::OnTestEnd(), PrettyUnitTestResultPrinter::OnTestStart(), TestNameIs::operator()(), XmlUnitTestResultPrinter::OutputXmlTestInfo(), and PrettyUnitTestResultPrinter::PrintFailedTests().
name_
const std::string name_ package
Definition at line 752 of file gtest.h.
result_
TestResult result_ package
Definition at line 770 of file gtest.h.
Referenced by TestInfo::ClearTestResult(), UnitTestImpl::current_test_result(), UnitTestImpl::RecordProperty(), and TestInfo::Run().
set_up_tc
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc set_up_tc package
Definition at line 722 of file gtest.h.
should_run_
bool should_run_ package
Definition at line 761 of file gtest.h.
Referenced by UnitTestImpl::FilterTests(), and TestInfo::Run().
tear_down_tc
const char const char const char internal::CodeLocation internal::TypeId Test::SetUpTestCaseFunc Test::TearDownTestCaseFunc tear_down_tc package
Definition at line 723 of file gtest.h.
test_case_name_
const std::string test_case_name_ package
Definition at line 751 of file gtest.h.
type_param
const char const char* type_param package
Definition at line 718 of file gtest.h.
Referenced by UnitTestImpl::AddTestInfo(), XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PrintFullTestCommentIfPresent().
value_param
const char const char const char* value_param package
Definition at line 719 of file gtest.h.
Referenced by UnitTestImpl::ListTestsMatchingFilter(), XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PrintFullTestCommentIfPresent().