Common Alogrithm: Facade Class Reference
Facade Class Reference
Public Member Functions
Facade ()
void MethodA ()
void MethodB ()
Private Attributes
SubSystemFour four
SubSystemOne one
SubSystemThree three
SubSystemTwo two
Detailed Description
Definition at line 47 of file main.cc.
Constructor & Destructor Documentation
Facade()
Facade ()
Definition at line 55 of file main.cc.
     {
     }
Member Function Documentation
MethodA()
void MethodA ()
Definition at line 59 of file main.cc.
     {
         std::cout << "\nMethodA() ---- " << std::endl;
         one.MethodOne();
         two.MethodTwo();
         four.MethodFour();
     }
References std::endl(), four, SubSystemFour::MethodFour(), SubSystemOne::MethodOne(), SubSystemTwo::MethodTwo(), one, and two.
Referenced by main().
MethodB()
void MethodB ()
Definition at line 66 of file main.cc.
     {
         std::cout << "\nMethodB() ---- " << std::endl;
         two.MethodTwo();
         three.MethodThree();
     }
References std::endl(), SubSystemThree::MethodThree(), SubSystemTwo::MethodTwo(), three, and two.
Referenced by main().
Member Data Documentation
four
SubSystemFour four private
Definition at line 52 of file main.cc.
Referenced by MethodA().
one
SubSystemOne one private
Definition at line 49 of file main.cc.
Referenced by MethodA().
three
SubSystemThree three private
Definition at line 51 of file main.cc.
Referenced by MethodB().
two
SubSystemTwo two private
Definition at line 50 of file main.cc.
Referenced by MethodA(), and MethodB().