Common Alogrithm: testing::internal::UniversalPrint
UniversalPrint()
void UniversalPrint (const T & value, ::std::ostream * os)
{
   // A workarond for the bug in VC++ 7.1 that prevents us from instantiating
   // UniversalPrinter with T directly.
   typedef T T1;
   UniversalPrinter<T1>::Print(value, os);
 }
References UniversalPrinter< T >::Print().
Referenced by testing::internal::DefaultPrintTo(), UniversalTersePrinter< const char * >::Print(), UniversalPrinter< T & >::Print(), UniversalTersePrinter< T >::Print(), UniversalTersePrinter< T & >::Print(), and testing::internal::PrintRawArrayTo().