Common Alogrithm: testing::internal::IsPathSeparator
IsPathSeparator()
static bool testing::internal::IsPathSeparator (char c) static
{
 #if GTEST_HAS_ALT_PATH_SEP_
   return (c == kPathSeparator) || (c == kAlternatePathSeparator);
 #else
   return c == kPathSeparator;
 #endif
 }
References testing::internal::kPathSeparator.
Referenced by FilePath::IsAbsolutePath(), FilePath::IsDirectory(), FilePath::IsRootDirectory(), and FilePath::Normalize().