Common Alogrithm: testing::internal::FormatFileLocation
FormatFileLocation()
GTEST_API_::std::string FormatFileLocation (const char * file, int line)
{
   const std::string file_name(file == NULL ? kUnknownFile : file);
   if (line < 0) {
     return file_name + ":";
   }
 #ifdef _MSC_VER
   return file_name + "(" + StreamableToString(line) + "):";
 #else
   return file_name + ":" + StreamableToString(line) + ":";
 #endif  // _MSC_VER
 }
References testing::internal::kUnknownFile, and testing::internal::StreamableToString().
Referenced by UnitTest::AddTestPartResult(), GTestLog::GTestLog(), and testing::internal::PrintTestPartResultToString().