Common Alogrithm: testing::internal::GetUnitTestImpl
GetUnitTestImpl()
class UnitTestImpl * GetUnitTestImpl ()
{
   return UnitTest::GetInstance()->impl();
 }
References UnitTest::GetInstance(), and UnitTest::impl().
Referenced by testing::internal::GetCurrentOsStackTraceExceptTop(), testing::internal::HandleExceptionsInMethodIfSupported(), Test::HasFatalFailure(), HasNewFatalFailureHelper::HasNewFatalFailureHelper(), Test::HasNonfatalFailure(), Test::HasSameFixtureClass(), ScopedFakeTestPartResultReporter::Init(), testing::internal::InitGoogleTestImpl(), testing::internal::MakeAndRegisterTestInfo(), Test::Run(), TestInfo::Run(), TestCase::Run(), HasNewFatalFailureHelper::~HasNewFatalFailureHelper(), and ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().