Common Alogrithm: testing::internal::EqFailure
EqFailure()
GTEST_API_ AssertionResult EqFailure (const char * lhs_expression, const char * rhs_expression, const std::string & lhs_value, const std::string & rhs_value, bool ignoring_case)
{
   Message msg;
   msg << "      Expected: " << lhs_expression;
   if (lhs_value != lhs_expression) {
     msg << "\n      Which is: " << lhs_value;
   }
   msg << "\nTo be equal to: " << rhs_expression;
   if (rhs_value != rhs_expression) {
     msg << "\n      Which is: " << rhs_value;
   }
   if (ignoring_case) {
     msg << "\nIgnoring case";
   }
   if (!lhs_value.empty() && !rhs_value.empty()) {
     const std::vector<std::string> lhs_lines =
         SplitEscapedString(lhs_value);
     const std::vector<std::string> rhs_lines =
         SplitEscapedString(rhs_value);
     if (lhs_lines.size() > 1 || rhs_lines.size() > 1) {
       msg << "\nWith diff:\n"
           << edit_distance::CreateUnifiedDiff(lhs_lines, rhs_lines);
     }
   }
   return AssertionFailure() << msg;
 }
References testing::AssertionFailure(), testing::internal::edit_distance::CreateUnifiedDiff(), string::empty(), vector< T >::size(), and testing::internal::anonymous_namespace{gtest.cc}::SplitEscapedString().
Referenced by testing::internal::CmpHelperEQ(), testing::internal::CmpHelperEQFailure(), testing::internal::CmpHelperFloatingPointEQ(), testing::internal::CmpHelperSTRCASEEQ(), and testing::internal::CmpHelperSTREQ().