Common Alogrithm: testing::internal::AppendUserMessage
AppendUserMessage()
GTEST_API_ std::string AppendUserMessage (const std::string & gtest_msg, const Message & user_msg)
{
   // Appends the user message if it's non-empty.
   const std::string user_msg_string = user_msg.GetString();
   if (user_msg_string.empty()) {
     return gtest_msg;
   }
   return gtest_msg + "\n" + user_msg_string;
 }
References string::empty(), and Message::GetString().
Referenced by AssertHelper::operator=().