Common Alogrithm: testing::internal::ReportFailureInUnknownLocation
ReportFailureInUnknownLocation()
void ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string & message)
{
   // This function is a friend of UnitTest and as such has access to
   // AddTestPartResult.
   UnitTest::GetInstance()->AddTestPartResult(
       result_type,
       NULL,  // No info about the source file where the exception occurred.
       -1,    // We have no info on which line caused the exception.
       message,
       "");   // No stack trace, either.
 }
References UnitTest::AddTestPartResult(), and UnitTest::GetInstance().
Referenced by testing::internal::HandleExceptionsInMethodIfSupported(), and testing::internal::HandleSehExceptionsInMethodIfSupported().