Common Alogrithm: testing::internal::CountIf
CountIf()
int testing::internal::CountIf (const Container & c, Predicate predicate)
{
   // Implemented as an explicit loop since std::count_if() in libCstd on
   // Solaris has a non-standard signature.
   int count = 0;
   for (typename Container::const_iterator it = c.begin(); it != c.end(); ++it) {
     if (predicate(*it))
       ++count;
   }
   return count;
 }
Referenced by TestCase::disabled_test_count(), UnitTestImpl::failed_test_case_count(), TestCase::failed_test_count(), TestResult::HasFatalFailure(), TestResult::HasNonfatalFailure(), TestCase::reportable_disabled_test_count(), TestCase::reportable_test_count(), UnitTestImpl::successful_test_case_count(), TestCase::successful_test_count(), UnitTestImpl::test_case_to_run_count(), and TestCase::test_to_run_count().