Common Alogrithm: testing::internal::StringFromGTestEnv
StringFromGTestEnv()
std::string StringFromGTestEnv (const char * flag, const char * default_value)
{
 #if defined(GTEST_GET_STRING_FROM_ENV_)
   return GTEST_GET_STRING_FROM_ENV_(flag, default_value);
 #endif  // defined(GTEST_GET_STRING_FROM_ENV_)
   const std::string env_var = FlagToEnvVar(flag);
   const char* value = posix::GetEnv(env_var.c_str());
   if (value != NULL) {
     return value;
   }
   // As a special case for the 'output' flag, if GTEST_OUTPUT is not
   // set, we look for XML_OUTPUT_FILE, which is set by the Bazel build
   // system.  The value of XML_OUTPUT_FILE is a filename without the
   // "xml:" prefix of GTEST_OUTPUT.
   //
   // The net priority order after flag processing is thus:
   //   --gtest_output command line flag
   //   GTEST_OUTPUT environment variable
   //   XML_OUTPUT_FILE environment variable
   //   'default_value'
   if (strcmp(flag, "output") == 0) {
     value = posix::GetEnv("XML_OUTPUT_FILE");
     if (value != NULL) {
       return std::string("xml:") + value;
     }
   }
   return default_value;
 }
References string::c_str(), testing::internal::FlagToEnvVar(), and testing::internal::posix::GetEnv().