Common Alogrithm: testing::internal::CmpHelperSTRNE
CmpHelperSTRNE() [2/2]
GTEST_API_ AssertionResult CmpHelperSTRNE (const char * s1_expression, const char * s2_expression, const wchar_t * s1, const wchar_t * s2)
{
   if (!String::WideCStringEquals(s1, s2)) {
     return AssertionSuccess();
   }
   return AssertionFailure() << "Expected: (" << s1_expression << ") != ("
                             << s2_expression << "), actual: "
                             << PrintToString(s1)
                             << " vs " << PrintToString(s2);
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::PrintToString(), and String::WideCStringEquals().