Common Alogrithm: testing::internal::ParseGoogleTestFlagsOnlyImpl
ParseGoogleTestFlagsOnlyImpl()
void testing::internal::ParseGoogleTestFlagsOnlyImpl (int * argc, CharType ** argv)
{
   for (int i = 1; i < *argc; i++) {
     const std::string arg_string = StreamableToString(argv[i]);
     const char* const arg = arg_string.c_str();
     using internal::ParseBoolFlag;
     using internal::ParseInt32Flag;
     using internal::ParseStringFlag;
     bool remove_flag = false;
     if (ParseGoogleTestFlag(arg)) {
       remove_flag = true;
 #if GTEST_USE_OWN_FLAGFILE_FLAG_
     } else if (ParseStringFlag(arg, kFlagfileFlag, &GTEST_FLAG(flagfile))) {
       LoadFlagsFromFile(GTEST_FLAG(flagfile));
       remove_flag = true;
 #endif  // GTEST_USE_OWN_FLAGFILE_FLAG_
     } else if (arg_string == "--help" || arg_string == "-h" ||
                arg_string == "-?" || arg_string == "/?" ||
                HasGoogleTestFlagPrefix(arg)) {
       // Both help flag and unrecognized Google Test flags (excluding
       // internal ones) trigger help display.
       g_help_flag = true;
     }
     if (remove_flag) {
       // Shift the remainder of the argv list left by one.  Note
       // that argv has (*argc + 1) elements, the last one always being
       // NULL.  The following loop moves the trailing NULL element as
       // well.
       for (int j = i; j != *argc; j++) {
         argv[j] = argv[j + 1];
       }
       // Decrements the argument count.
       (*argc)--;
       // We also need to decrement the iterator as we just removed
       // an element.
       i--;
     }
   }
   if (g_help_flag) {
     // We print the help here instead of in RUN_ALL_TESTS(), as the
     // latter may not be called at all if the user is using Google
     // Test with another testing framework.
     PrintColorEncoded(kColorEncodedHelpMessage);
   }
 }
References string::c_str(), testing::internal::g_help_flag, GTEST_FLAG, testing::internal::HasGoogleTestFlagPrefix(), testing::internal::kColorEncodedHelpMessage, testing::internal::kFlagfileFlag, testing::internal::ParseBoolFlag(), testing::internal::ParseGoogleTestFlag(), testing::internal::ParseInt32Flag(), testing::internal::ParseStringFlag(), testing::internal::PrintColorEncoded(), and testing::internal::StreamableToString().
Referenced by testing::internal::ParseGoogleTestFlagsOnly().