Common Alogrithm: testing::internal::Int32FromEnvOrDie
Int32FromEnvOrDie()
Int32 Int32FromEnvOrDie (const char * env_var, Int32 default_val)
{
   const char* str_val = posix::GetEnv(var);
   if (str_val == NULL) {
     return default_val;
   }
   Int32 result;
   if (!ParseInt32(Message() << "The value of environment variable " << var,
                   str_val, &result)) {
     exit(EXIT_FAILURE);
   }
   return result;
 }
References testing::internal::posix::GetEnv(), and testing::internal::ParseInt32().
Referenced by UnitTestImpl::FilterTests(), PrettyUnitTestResultPrinter::OnTestIterationStart(), and testing::internal::ShouldShard().