Common Alogrithm: testing::internal::ParseInt32Flag
ParseInt32Flag()
bool ParseInt32Flag (const char * str, const char * flag, Int32 * value)
{
   // Gets the value of the flag as a string.
   const char* const value_str = ParseFlagValue(str, flag, false);
   // Aborts if the parsing failed.
   if (value_str == NULL) return false;
   // Sets *value to the value of the flag.
   return ParseInt32(Message() << "The value of flag --" << flag,
                     value_str, value);
 }
References testing::internal::ParseFlagValue(), and testing::internal::ParseInt32().
Referenced by testing::internal::ParseGoogleTestFlag(), and testing::internal::ParseGoogleTestFlagsOnlyImpl().