Common Alogrithm: testing::internal::ForEach
ForEach()
void testing::internal::ForEach (const Container & c, Functor functor)
{
   std::for_each(c.begin(), c.end(), functor);
 }
References std::for_each().
Referenced by UnitTestImpl::ClearNonAdHocTestResult(), TestCase::ClearResult(), UnitTestImpl::RunAllTests(), TestCase::~TestCase(), TestEventRepeater::~TestEventRepeater(), and UnitTestImpl::~UnitTestImpl().