Common Alogrithm: testing::internal::GetCurrentExecutableName
GetCurrentExecutableName()
FilePath GetCurrentExecutableName ()
{
   FilePath result;
 #if GTEST_OS_WINDOWS
   result.Set(FilePath(GetArgvs()[0]).RemoveExtension("exe"));
 #else
   result.Set(FilePath(GetArgvs()[0]));
 #endif  // GTEST_OS_WINDOWS
   return result.RemoveDirectoryName();
 }
References testing::internal::GetArgvs(), FilePath::RemoveDirectoryName(), and FilePath::Set().
Referenced by UnitTestOptions::GetAbsolutePathToOutputFile().