Common Alogrithm: testing::internal::PrintCharsAsStringTo
PrintCharsAsStringTo()
GTEST_ATTRIBUTE_NO_SANITIZE_MEMORY_ GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_ static GTEST_ATTRIBUTE_NO_SANITIZE_THREAD_ void testing::internal::PrintCharsAsStringTo (const CharType * begin, size_t len, ostream * os) static
{
   const char* const kQuoteBegin = sizeof(CharType) == 1 ? "\"" : "L\"";
   *os << kQuoteBegin;
   bool is_previous_hex = false;
   for (size_t index = 0; index < len; ++index) {
     const CharType cur = begin[index];
     if (is_previous_hex && IsXDigit(cur)) {
       // Previous character is of '\x..' form and this character can be
       // interpreted as another hexadecimal digit in its number. Break string to
       // disambiguate.
       *os << "\" " << kQuoteBegin;
     }
     is_previous_hex = PrintAsStringLiteralTo(cur, os) == kHexEscape;
   }
   *os << "\"";
 }
References testing::internal::IsXDigit(), testing::internal::kHexEscape, and testing::internal::PrintAsStringLiteralTo().
Referenced by testing::internal::PrintStringTo(), testing::internal::PrintTo(), and testing::internal::UniversalPrintCharArray().