Common Alogrithm: testing::internal::ParseGoogleTestFlag
ParseGoogleTestFlag()
bool testing::internal::ParseGoogleTestFlag (const char *const arg)
{
   return ParseBoolFlag(arg, kAlsoRunDisabledTestsFlag,
                        &GTEST_FLAG(also_run_disabled_tests)) ||
       ParseBoolFlag(arg, kBreakOnFailureFlag,
                     &GTEST_FLAG(break_on_failure)) ||
       ParseBoolFlag(arg, kCatchExceptionsFlag,
                     &GTEST_FLAG(catch_exceptions)) ||
       ParseStringFlag(arg, kColorFlag, &GTEST_FLAG(color)) ||
       ParseStringFlag(arg, kDeathTestStyleFlag,
                       &GTEST_FLAG(death_test_style)) ||
       ParseBoolFlag(arg, kDeathTestUseFork,
                     &GTEST_FLAG(death_test_use_fork)) ||
       ParseStringFlag(arg, kFilterFlag, &GTEST_FLAG(filter)) ||
       ParseStringFlag(arg, kInternalRunDeathTestFlag,
                       &GTEST_FLAG(internal_run_death_test)) ||
       ParseBoolFlag(arg, kListTestsFlag, &GTEST_FLAG(list_tests)) ||
       ParseStringFlag(arg, kOutputFlag, &GTEST_FLAG(output)) ||
       ParseBoolFlag(arg, kPrintTimeFlag, &GTEST_FLAG(print_time)) ||
       ParseInt32Flag(arg, kRandomSeedFlag, &GTEST_FLAG(random_seed)) ||
       ParseInt32Flag(arg, kRepeatFlag, &GTEST_FLAG(repeat)) ||
       ParseBoolFlag(arg, kShuffleFlag, &GTEST_FLAG(shuffle)) ||
       ParseInt32Flag(arg, kStackTraceDepthFlag,
                      &GTEST_FLAG(stack_trace_depth)) ||
       ParseStringFlag(arg, kStreamResultToFlag,
                       &GTEST_FLAG(stream_result_to)) ||
       ParseBoolFlag(arg, kThrowOnFailureFlag,
                     &GTEST_FLAG(throw_on_failure));
 }
References GTEST_FLAG, testing::internal::kAlsoRunDisabledTestsFlag, testing::internal::kBreakOnFailureFlag, testing::internal::kCatchExceptionsFlag, testing::internal::kColorFlag, testing::internal::kDeathTestStyleFlag, testing::internal::kDeathTestUseFork, testing::internal::kFilterFlag, testing::internal::kInternalRunDeathTestFlag, testing::internal::kListTestsFlag, testing::internal::kOutputFlag, testing::internal::kPrintTimeFlag, testing::internal::kRandomSeedFlag, testing::internal::kRepeatFlag, testing::internal::kShuffleFlag, testing::internal::kStackTraceDepthFlag, testing::internal::kStreamResultToFlag, testing::internal::kThrowOnFailureFlag, testing::internal::ParseBoolFlag(), testing::internal::ParseInt32Flag(), and testing::internal::ParseStringFlag().
Referenced by testing::internal::ParseGoogleTestFlagsOnlyImpl().