Common Alogrithm: testing::internal::ParseFlagValue
ParseFlagValue()
const char* testing::internal::ParseFlagValue (const char * str, const char * flag, bool def_optional)
{
   // str and flag must not be NULL.
   if (str == NULL || flag == NULL) return NULL;
   // The flag must start with "--" followed by GTEST_FLAG_PREFIX_.
   const std::string flag_str = std::string("--") + GTEST_FLAG_PREFIX_ + flag;
   const size_t flag_len = flag_str.length();
   if (strncmp(str, flag_str.c_str(), flag_len) != 0) return NULL;
   // Skips the flag name.
   const char* flag_end = str + flag_len;
   // When def_optional is true, it's OK to not have a "=value" part.
   if (def_optional && (flag_end[0] == '\0')) {
     return flag_end;
   }
   // If def_optional is true and there are more characters after the
   // flag name, or if def_optional is false, there must be a '=' after
   // the flag name.
   if (flag_end[0] != '=') return NULL;
   // Returns the string after "=".
   return flag_end + 1;
 }
References string::c_str(), GTEST_FLAG_PREFIX_, and string::length().
Referenced by testing::internal::ParseBoolFlag(), testing::internal::ParseInt32Flag(), and testing::internal::ParseStringFlag().