Common Alogrithm: testing::internal::FormatTimeInMillisAsSeconds
FormatTimeInMillisAsSeconds()
std::string FormatTimeInMillisAsSeconds (TimeInMillis ms)
{
   ::std::stringstream ss;
   ss << (static_cast<double>(ms) * 1e-3);
   return ss.str();
 }
References stringstream::str().
Referenced by XmlUnitTestResultPrinter::OutputXmlTestInfo(), XmlUnitTestResultPrinter::PrintXmlTestCase(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().