Common Alogrithm: testing::internal::ParseStringFlag
ParseStringFlag()
bool testing::internal::ParseStringFlag (const char * str, const char * flag, std::string * value)
{
   // Gets the value of the flag as a string.
   const char* const value_str = ParseFlagValue(str, flag, false);
   // Aborts if the parsing failed.
   if (value_str == NULL) return false;
   // Sets *value to the value of the flag.
   *value = value_str;
   return true;
 }
References testing::internal::ParseFlagValue().
Referenced by testing::internal::ParseGoogleTestFlag(), and testing::internal::ParseGoogleTestFlagsOnlyImpl().