Common Alogrithm: testing::internal::BoolFromGTestEnv
BoolFromGTestEnv()
bool BoolFromGTestEnv (const char * flag, bool default_value)
{
 #if defined(GTEST_GET_BOOL_FROM_ENV_)
   return GTEST_GET_BOOL_FROM_ENV_(flag, default_value);
 #endif  // defined(GTEST_GET_BOOL_FROM_ENV_)
   const std::string env_var = FlagToEnvVar(flag);
   const char* const string_value = posix::GetEnv(env_var.c_str());
   return string_value == NULL ?
       default_value : strcmp(string_value, "0") != 0;
 }
References string::c_str(), testing::internal::FlagToEnvVar(), and testing::internal::posix::GetEnv().