Common Alogrithm: testing::internal::ParseBoolFlag
ParseBoolFlag()
bool testing::internal::ParseBoolFlag (const char * str, const char * flag, bool * value)
{
   // Gets the value of the flag as a string.
   const char* const value_str = ParseFlagValue(str, flag, true);
   // Aborts if the parsing failed.
   if (value_str == NULL) return false;
   // Converts the string value to a bool.
   *value = !(*value_str == '0' || *value_str == 'f' || *value_str == 'F');
   return true;
 }
References testing::internal::ParseFlagValue().
Referenced by testing::internal::ParseGoogleTestFlag(), and testing::internal::ParseGoogleTestFlagsOnlyImpl().