Common Alogrithm: testing::internal::WriteToShardStatusFileIfNeeded
WriteToShardStatusFileIfNeeded()
void WriteToShardStatusFileIfNeeded ()
{
   const char* const test_shard_file = posix::GetEnv(kTestShardStatusFile);
   if (test_shard_file != NULL) {
     FILE* const file = posix::FOpen(test_shard_file, "w");
     if (file == NULL) {
       ColoredPrintf(COLOR_RED,
                     "Could not write to the test shard status file \"%s\" "
                     "specified by the %s environment variable.\n",
                     test_shard_file, kTestShardStatusFile);
       fflush(stdout);
       exit(EXIT_FAILURE);
     }
     fclose(file);
   }
 }
References testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::internal::posix::FOpen(), testing::internal::posix::GetEnv(), and testing::kTestShardStatusFile.
Referenced by UnitTestImpl::RunAllTests().