Common Alogrithm: testing::internal::SplitString
SplitString()
void testing::internal::SplitString (const ::std::string & str, char delimiter, ::std::vector< ::std::string > * dest)
{
   ::std::vector< ::std::string> parsed;
   ::std::string::size_type pos = 0;
   while (::testing::internal::AlwaysTrue()) {
     const ::std::string::size_type colon = str.find(delimiter, pos);
     if (colon == ::std::string::npos) {
       parsed.push_back(str.substr(pos));
       break;
     } else {
       parsed.push_back(str.substr(pos, colon - pos));
       pos = colon + 1;
     }
   }
   dest->swap(parsed);
 }
References testing::internal::AlwaysTrue(), vector< T >::push_back(), and vector< T >::swap().