Common Alogrithm: testing::internal::WideStringToUtf8
WideStringToUtf8()
std::string WideStringToUtf8 (const wchar_t * str, int num_chars)
{
   if (num_chars == -1)
     num_chars = static_cast<int>(wcslen(str));
   ::std::stringstream stream;
   for (int i = 0; i < num_chars; ++i) {
     UInt32 unicode_code_point;
     if (str[i] == L'\0') {
       break;
     } else if (i + 1 < num_chars && IsUtf16SurrogatePair(str[i], str[i + 1])) {
       unicode_code_point = CreateCodePointFromUtf16SurrogatePair(str[i],
                                                                  str[i + 1]);
       i++;
     } else {
       unicode_code_point = static_cast<UInt32>(str[i]);
     }
     stream << CodePointToUtf8(unicode_code_point);
   }
   return StringStreamToString(&stream);
 }
References testing::internal::CodePointToUtf8(), testing::internal::CreateCodePointFromUtf16SurrogatePair(), testing::internal::IsUtf16SurrogatePair(), and testing::internal::StringStreamToString().
Referenced by String::ShowWideCString().