Common Alogrithm: testing::internal Namespace Reference
testing::internal Namespace Reference
Namespaces
anonymous_namespace{gtest.cc}
edit_distance
posix
Classes
struct IteratorTraits< const T * >
class String
class TypeWithSize
class TypeWithSize< 4 >
class TypeWithSize< 8 >
Typedefs
typedef long long BiggestInt
typedef FloatingPoint< double > Double
typedef bool_constant< false > false_type
typedef FloatingPoint< float > Float
typedef TypeWithSize< 4 >::Int Int32
typedef TypeWithSize< 8 >::Int Int64
typedef int IsContainer
typedef char IsNotContainer
typedef GTestMutexLock MutexLock
typedef void(* SetUpTestCaseFunc) ()
typedef ::std::string string
typedef ::std::vector< string > Strings
typedef void(* TearDownTestCaseFunc) ()
typedef TypeWithSize< 8 >::Int TimeInMillis
typedef bool_constant< true > true_type
typedef const void * TypeId
typedef TypeWithSize< 4 >::UInt UInt32
typedef TypeWithSize< 8 >::UInt UInt64
typedef ::std::wstring wstring
Enumerations
enum CharFormat { kAsIs , kHexEscape , kSpecialEscape }
enum GTestColor { COLOR_DEFAULT , COLOR_RED , COLOR_GREEN , COLOR_YELLOW }
enum GTestLogSeverity { GTEST_INFO , GTEST_WARNING , GTEST_ERROR , GTEST_FATAL }
Functions
bool AlwaysFalse ()
bool AlwaysTrue ()
std::string AppendUserMessage (const std::string &gtest_msg, const Message &user_msg)
template<typename Iter , typename Element >
Iter ArrayAwareFind (Iter begin, Iter end, const Element &elem)
template<typename T , typename U >
bool ArrayEq (const T &lhs, const U &rhs)
template<typename T , typename U >
bool ArrayEq (const T *lhs, size_t size, const U *rhs)
template<typename T , typename U , size_t N>
bool ArrayEq (const T(&lhs)[N], const U(&rhs)[N])
bool BoolFromGTestEnv (const char *flag, bool default_value)
GTEST_API_ void CaptureStderr ()
GTEST_API_ void CaptureStdout ()
template<class Derived , class Base >
Derived * CheckedDowncastToActualType (Base *base)
UInt32 ChopLowBits (UInt32 *bits, int n)
AssertionResult CmpHelperEQ (const char *lhs_expression, const char *rhs_expression, BiggestInt lhs, BiggestInt rhs)
template<typename T1 , typename T2 >
AssertionResult CmpHelperEQ (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)
template<typename T1 , typename T2 >
AssertionResult CmpHelperEQFailure (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)
template<typename RawType >
AssertionResult CmpHelperFloatingPointEQ (const char *lhs_expression, const char *rhs_expression, RawType lhs_value, RawType rhs_value)
template<typename T1 , typename T2 >
AssertionResult CmpHelperOpFailure (const char *expr1, const char *expr2, const T1 &val1, const T2 &val2, const char *op)
GTEST_API_ AssertionResult CmpHelperSTRCASEEQ (const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
GTEST_API_ AssertionResult CmpHelperSTRCASENE (const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
AssertionResult CmpHelperSTREQ (const char *lhs_expression, const char *rhs_expression, const wchar_t *lhs, const wchar_t *rhs)
GTEST_API_ AssertionResult CmpHelperSTREQ (const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
GTEST_API_ AssertionResult CmpHelperSTRNE (const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
AssertionResult CmpHelperSTRNE (const char *s1_expression, const char *s2_expression, const wchar_t *s1, const wchar_t *s2)
GTEST_API_ std::string CodePointToUtf8 (UInt32 code_point)
void ColoredPrintf (GTestColor color, const char *fmt,...)
template<typename T , typename U >
void CopyArray (const T &from, U *to)
template<typename T , typename U >
void CopyArray (const T *from, size_t size, U *to)
template<typename T , typename U , size_t N>
void CopyArray (const T(&from)[N], U(*to)[N])
template<class Container , typename Predicate >
int CountIf (const Container &c, Predicate predicate)
UInt32 CreateCodePointFromUtf16SurrogatePair (wchar_t first, wchar_t second)
template<typename C >
void DefaultPrintTo (IsContainer, false_type, const C &container, ::std::ostream *os)
template<typename T >
void DefaultPrintTo (IsNotContainer, false_type, const T &value, ::std::ostream *os)
template<typename T >
void DefaultPrintTo (IsNotContainer, true_type, T *p, ::std::ostream *os)
template<typename T >
static void Delete (T *x)
GTEST_API_ std::string DiffStrings (const std::string &left, const std::string &right, size_t *total_line_count)
AssertionResult DoubleNearPredFormat (const char *expr1, const char *expr2, const char *abs_error_expr, double val1, double val2, double abs_error)
template<typename To , typename From >
To DownCast_ (From *f)
AssertionResult EqFailure (const char *lhs_expression, const char *rhs_expression, const std::string &lhs_value, const std::string &rhs_value, bool ignoring_case)
static std::string FlagToEnvVar (const char *flag)
template<typename RawType >
AssertionResult FloatingPointLE (const char *expr1, const char *expr2, RawType val1, RawType val2)
void FlushInfoLog ()
template<class Container , typename Functor >
void ForEach (const Container &c, Functor functor)
GTEST_API_ ::std::string FormatCompilerIndependentFileLocation (const char *file, int line)
GTEST_API_ std::string FormatEpochTimeInMillisAsIso8601 (TimeInMillis ms)
GTEST_API_ ::std::string FormatFileLocation (const char *file, int line)
template<typename T1 , typename T2 >
std::string FormatForComparisonFailureMessage (const T1 &value, const T2 &)
GTEST_API_ std::string FormatTimeInMillisAsSeconds (TimeInMillis ms)
const char * GetAnsiColorCode (GTestColor color)
const ::std::vector< testing::internal::string > & GetArgvs ()
std::string GetBoolAssertionFailureMessage (const AssertionResult &assertion_result, const char *expression_text, const char *actual_predicate_value, const char *expected_predicate_value)
GTEST_API_ std::string GetCapturedStderr ()
GTEST_API_ std::string GetCapturedStdout ()
GTEST_API_ FilePath GetCurrentExecutableName ()
std::string GetCurrentOsStackTraceExceptTop (UnitTest *, int skip_count)
template<typename E >
E GetElementOr (const std::vector< E > &v, int i, E default_value)
size_t GetFileSize (FILE *file)
int GetNextRandomSeed (int seed)
int GetRandomSeedFromFlag (Int32 random_seed_flag)
TypeId GetTestTypeId ()
size_t GetThreadCount ()
GTEST_API_ TimeInMillis GetTimeInMillis ()
template<typename T >
TypeId GetTypeId ()
template<typename T >
std::string GetTypeName ()
UnitTestImpl * GetUnitTestImpl ()
GTEST_API_ GTEST_DECLARE_STATIC_MUTEX_ (g_linked_ptr_mutex)
GTEST_DECLARE_string_ (internal_run_death_test)
GTEST_API_ GTEST_DEFINE_STATIC_MUTEX_ (g_linked_ptr_mutex)
GTEST_DEFINE_string_ (internal_run_death_test, "", "Indicates the file, line number, temporal index of " "the single death test to run, and a file descriptor to " "which a success code may be sent, all separated by " "the '|' characters. This flag is specified if and only if the current " "process is a sub-process launched for running a thread-safe " "death test. FOR INTERNAL USE ONLY.")
GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4996) std
GTEST_IMPL_CMP_HELPER_ (GE, >=)
GTEST_IMPL_CMP_HELPER_ (GT, >)
GTEST_IMPL_CMP_HELPER_ (LE,<=)
GTEST_IMPL_CMP_HELPER_ (LT,<)
GTEST_IMPL_CMP_HELPER_ (NE, !=) GTEST_IMPL_CMP_HELPER_(LE
GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_ (char)
GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_ (wchar_t)
GTEST_IMPL_FORMAT_C_STRING_AS_STRING_ (char, ::std::string)
UnitTest GTEST_REPEATER_METHOD_ (OnTestCaseStart, TestCase) GTEST_REPEATER_METHOD_(OnTestStart
UnitTest TestInfo GTEST_REPEATER_METHOD_ (OnTestPartResult, TestPartResult) GTEST_REPEATER_METHOD_(OnEnvironmentsTearDownStart
GTEST_REPEATER_METHOD_ (OnTestProgramStart, UnitTest) GTEST_REPEATER_METHOD_(OnEnvironmentsSetUpStart
UnitTest TestInfo UnitTest GTEST_REVERSE_REPEATER_METHOD_ (OnEnvironmentsSetUpEnd, UnitTest) GTEST_REVERSE_REPEATER_METHOD_(OnEnvironmentsTearDownEnd
UnitTest TestInfo UnitTest UnitTest GTEST_REVERSE_REPEATER_METHOD_ (OnTestEnd, TestInfo) GTEST_REVERSE_REPEATER_METHOD_(OnTestCaseEnd
UnitTest TestInfo UnitTest UnitTest TestCase GTEST_REVERSE_REPEATER_METHOD_ (OnTestProgramEnd, UnitTest) void TestEventRepeater
static bool GTestIsInitialized ()
template<class T , typename Result >
Result HandleExceptionsInMethodIfSupported (T *object, Result(T::*method)(), const char *location)
template<class T , typename Result >
Result HandleSehExceptionsInMethodIfSupported (T *object, Result(T::*method)(), const char *location)
static bool HasGoogleTestFlagPrefix (const char *str)
AssertionResult HasOneFailure (const char *, const char *, const char *, const TestPartResultArray &results, TestPartResult::Type type, const string &substr)
template<typename To >
To ImplicitCast_ (To x)
template<typename CharType >
void InitGoogleTestImpl (int *argc, CharType **argv)
GTEST_API_ Int32 Int32FromEnvOrDie (const char *env_var, Int32 default_val)
Int32 Int32FromGTestEnv (const char *flag, Int32 default_value)
bool IsAlNum (char ch)
bool IsAlpha (char ch)
template<class C >
IsContainer IsContainerTest (int, typename C::iterator *=NULL, typename C::const_iterator *=NULL)
template<class C >
IsNotContainer IsContainerTest (long)
bool IsDigit (char ch)
bool IsLower (char ch)
char(& IsNullLiteralHelper (...))[2]
char IsNullLiteralHelper (Secret *p)
static bool IsPathSeparator (char c)
bool IsPrintableAscii (wchar_t c)
bool IsSpace (char ch)
bool IsTrue (bool condition)
bool IsUpper (char ch)
bool IsUtf16SurrogatePair (wchar_t first, wchar_t second)
bool IsXDigit (char ch)
bool IsXDigit (wchar_t ch)
void LogToStderr ()
template<typename T >
linked_ptr< T > make_linked_ptr (T *ptr)
TestInfo * MakeAndRegisterTestInfo (const char *test_case_name, const char *name, const char *type_param, const char *value_param, CodeLocation code_location, TypeId fixture_class_id, SetUpTestCaseFunc set_up_tc, TearDownTestCaseFunc tear_down_tc, TestFactoryBase *factory)
template<typename T >
const T & move (const T &t)
template<typename T >
bool operator!= (T *ptr, const linked_ptr< T > &x)
template<typename T >
bool operator== (T *ptr, const linked_ptr< T > &x)
bool ParseBoolFlag (const char *str, const char *flag, bool *value)
const char * ParseFlagValue (const char *str, const char *flag, bool def_optional)
bool ParseGoogleTestFlag (const char *const arg)
GTEST_API_ void ParseGoogleTestFlagsOnly (int *argc, char **argv)
GTEST_API_ void ParseGoogleTestFlagsOnly (int *argc, wchar_t **argv)
template<typename CharType >
void ParseGoogleTestFlagsOnlyImpl (int *argc, CharType **argv)
bool ParseInt32 (const Message &src_text, const char *str, Int32 *value)
GTEST_API_ bool ParseInt32Flag (const char *str, const char *flag, Int32 *value)
bool ParseStringFlag (const char *str, const char *flag, std::string *value)
static bool PortableLocaltime (time_t seconds, struct tm *out)
template<typename UnsignedChar , typename Char >
static CharFormat PrintAsCharLiteralTo (Char c, ostream *os)
static CharFormat PrintAsStringLiteralTo (char c, ostream *os)
static CharFormat PrintAsStringLiteralTo (wchar_t c, ostream *os)
template<typename UnsignedChar , typename Char >
void PrintCharAndCodeTo (Char c, ostream *os)
template<typename CharType >
GTEST_ATTRIBUTE_NO_SANITIZE_MEMORY_ GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_ static GTEST_ATTRIBUTE_NO_SANITIZE_THREAD_ void PrintCharsAsStringTo (const CharType *begin, size_t len, ostream *os)
static void PrintColorEncoded (const char *str)
void PrintFullTestCommentIfPresent (const TestInfo &test_info)
static void PrintOnOneLine (const char *str, int max_length)
template<typename T >
void PrintRawArrayTo (const T a[], size_t count, ::std::ostream *os)
GTEST_API_ void PrintStringTo (const ::std::string &s, ::std::ostream *os)
void PrintStringTo (const ::std::string &s, ostream *os)
static void PrintTestPartResult (const TestPartResult &test_part_result)
static std::string PrintTestPartResultToString (const TestPartResult &test_part_result)
void PrintTo (bool x, ::std::ostream *os)
void PrintTo (char *s, ::std::ostream *os)
void PrintTo (char c, ::std::ostream *os)
template<typename T1 , typename T2 >
void PrintTo (const ::std::pair< T1, T2 > &value, ::std::ostream *os)
void PrintTo (const ::std::string &s, ::std::ostream *os)
GTEST_API_ void PrintTo (const char *s, ::std::ostream *os)
void PrintTo (const char *s, ostream *os)
void PrintTo (const signed char *s, ::std::ostream *os)
template<typename T >
void PrintTo (const T &value, ::std::ostream *os)
void PrintTo (const unsigned char *s, ::std::ostream *os)
GTEST_API_ void PrintTo (const wchar_t *s, ::std::ostream *os)
void PrintTo (const wchar_t *s, ostream *os)
void PrintTo (signed char *s, ::std::ostream *os)
void PrintTo (signed char c, ::std::ostream *os)
void PrintTo (unsigned char *s, ::std::ostream *os)
void PrintTo (unsigned char c, ::std::ostream *os)
void PrintTo (wchar_t *s, ::std::ostream *os)
GTEST_API_ void PrintTo (wchar_t wc, ::std::ostream *os)
void PrintTo (wchar_t wc, ostream *os)
std::string ReadEntireFile (FILE *file)
void ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string &message)
static void SetUpEnvironment (Environment *env)
static bool ShouldRunTestCase (const TestCase *test_case)
GTEST_API_ bool ShouldRunTestOnShard (int total_shards, int shard_index, int test_id)
GTEST_API_ bool ShouldShard (const char *total_shards_str, const char *shard_index_str, bool in_subprocess_for_death_test)
GTEST_API_ bool ShouldUseColor (bool stdout_is_tty)
template<typename E >
void Shuffle (internal::Random *random, std::vector< E > *v)
template<typename E >
void ShuffleRange (internal::Random *random, int begin, int end, std::vector< E > *v)
bool SkipPrefix (const char *prefix, const char **pstr)
void SplitString (const ::std::string &str, char delimiter, ::std::vector< ::std::string > *dest)
template<typename T >
std::string StreamableToString (const T &streamable)
std::string StringFromGTestEnv (const char *flag, const char *default_value)
std::string StringStreamToString (::std::stringstream *ss)
std::string StripTrailingSpaces (std::string str)
static int SumOverTestCaseList (const std::vector< TestCase * > &case_list, int(TestCase::*method)() const)
static void TearDownEnvironment (Environment *env)
GTEST_API_ std::string TempDir ()
static bool TestCaseFailed (const TestCase *test_case)
static bool TestCasePassed (const TestCase *test_case)
char ToLower (char ch)
char ToUpper (char ch)
template<typename T >
void UniversalPrint (const T &value, ::std::ostream *os)
GTEST_API_ void UniversalPrintArray (const char *begin, size_t len, ::std::ostream *os)
void UniversalPrintArray (const char *begin, size_t len, ostream *os)
template<typename T >
void UniversalPrintArray (const T *begin, size_t len, ::std::ostream *os)
GTEST_API_ void UniversalPrintArray (const wchar_t *begin, size_t len, ::std::ostream *os)
void UniversalPrintArray (const wchar_t *begin, size_t len, ostream *os)
template<typename CharType >
GTEST_ATTRIBUTE_NO_SANITIZE_MEMORY_ GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_ static GTEST_ATTRIBUTE_NO_SANITIZE_THREAD_ void UniversalPrintCharArray (const CharType *begin, size_t len, ostream *os)
template<typename T >
void UniversalTersePrint (const T &value, ::std::ostream *os)
GTEST_API_ std::string WideStringToUtf8 (const wchar_t *str, int num_chars)
void WriteToShardStatusFileIfNeeded ()
Constants
::std::vector< testing::internal::string > g_argvs
GTEST_API_ bool g_help_flag = false
class testing::internal::GTestFlagSaver GTEST_ATTRIBUTE_UNUSED_
const char kAlsoRunDisabledTestsFlag [] = "also_run_disabled_tests"
const char kBreakOnFailureFlag [] = "break_on_failure"
const char kCatchExceptionsFlag [] = "catch_exceptions"
static const char kColorEncodedHelpMessage []
const char kColorFlag [] = "color"
const char kCurrentDirectoryString [] = "./"
const char kDeathTestStyleFlag [] = "death_test_style"
const char kDeathTestUseFork [] = "death_test_use_fork"
const char kFilterFlag [] = "filter"
const char kFlagfileFlag [] = "flagfile"
const char kInternalRunDeathTestFlag [] = "internal_run_death_test"
const char kListTestsFlag [] = "list_tests"
const BiggestInt kMaxBiggestInt
const UInt32 kMaxCodePoint1 = (static_cast<UInt32>(1) << 7) - 1
const UInt32 kMaxCodePoint2 = (static_cast<UInt32>(1) << (5 + 6)) - 1
const UInt32 kMaxCodePoint3 = (static_cast<UInt32>(1) << (4 + 2*6)) - 1
const UInt32 kMaxCodePoint4 = (static_cast<UInt32>(1) << (3 + 3*6)) - 1
const int kMaxRandomSeed = 99999
const char kOutputFlag [] = "output"
const char kPathSeparator = '/'
const char kPrintTimeFlag [] = "print_time"
const char kRandomSeedFlag [] = "random_seed"
const char kRepeatFlag [] = "repeat"
const char kShuffleFlag [] = "shuffle"
const char kStackTraceDepthFlag [] = "stack_trace_depth"
const char kStackTraceMarker [] = "\nStack trace:\n"
const int kStdErrFileno = STDERR_FILENO
const int kStdOutFileno = STDOUT_FILENO
const char kStreamResultToFlag [] = "stream_result_to"
GTEST_API_ const TypeId kTestTypeIdInGoogleTest = GetTestTypeId()
const char kThrowOnFailureFlag [] = "throw_on_failure"
static const char kTypeParamLabel [] = "TypeParam"
const char kUnknownFile [] = "unknown file"
static const char kValueParamLabel [] = "GetParam()"
Class Documentation
testing::internal::IteratorTraits< const T * >
struct testing::internal::IteratorTraits< const T * >
template<typename T>
struct testing::internal::IteratorTraits< const T * >
Definition at line 2229 of file gtest-port.h.
Class Members
typedef T value_type
testing::internal::TypeWithSize
class testing::internal::TypeWithSize
template<size_t size>
class testing::internal::TypeWithSize< size >
Definition at line 2461 of file gtest-port.h.
Class Members
typedef void UInt
testing::internal::TypeWithSize< 4 >
class testing::internal::TypeWithSize< 4 >
Definition at line 2470 of file gtest-port.h.
Class Members
typedef int Int
typedef unsigned int UInt
testing::internal::TypeWithSize< 8 >
class testing::internal::TypeWithSize< 8 >
Definition at line 2482 of file gtest-port.h.
Class Members
typedef long long Int
typedef unsigned long long UInt
Typedef Documentation
BiggestInt
typedef long long BiggestInt
Definition at line 2241 of file gtest-port.h.
Double
typedef FloatingPoint<double> Double
Definition at line 421 of file gtest-internal.h.
false_type
typedef bool_constant<false> false_type
Definition at line 2209 of file gtest-port.h.
Float
typedef FloatingPoint<float> Float
Definition at line 420 of file gtest-internal.h.
Int32
typedef TypeWithSize<4>::Int Int32
Definition at line 2494 of file gtest-port.h.
Int64
typedef TypeWithSize<8>::Int Int64
Definition at line 2496 of file gtest-port.h.
IsContainer
typedef int IsContainer
Definition at line 930 of file gtest-internal.h.
IsNotContainer
typedef char IsNotContainer
Definition at line 938 of file gtest-internal.h.
MutexLock
typedef GTestMutexLock MutexLock
Definition at line 2159 of file gtest-port.h.
SetUpTestCaseFunc
typedef void(* SetUpTestCaseFunc) ()
Definition at line 501 of file gtest-internal.h.
string
typedef ::std::string string
Definition at line 1097 of file gtest-port.h.
Strings
typedef ::std::vector<string> Strings
Definition at line 859 of file gtest-printers.h.
TearDownTestCaseFunc
typedef void(* TearDownTestCaseFunc) ()
Definition at line 502 of file gtest-internal.h.
TimeInMillis
typedef TypeWithSize<8>::Int TimeInMillis
Definition at line 2498 of file gtest-port.h.
true_type
typedef bool_constant<true> true_type
Definition at line 2210 of file gtest-port.h.
TypeId
typedef const void* TypeId
Definition at line 429 of file gtest-internal.h.
UInt32
typedef TypeWithSize<4>::UInt UInt32
Definition at line 2495 of file gtest-port.h.
UInt64
typedef TypeWithSize<8>::UInt UInt64
Definition at line 2497 of file gtest-port.h.
wstring
typedef ::std::wstring wstring
Definition at line 1103 of file gtest-port.h.
Enumeration Type Documentation
CharFormat
enum CharFormat
Enumerator
kAsIs
kHexEscape
kSpecialEscape
Definition at line 128 of file gtest-printers.cc.
                 {
   kAsIs,
   kHexEscape,
   kSpecialEscape
 };
GTestColor
enum GTestColor
Enumerator
COLOR_DEFAULT
COLOR_RED
COLOR_GREEN
COLOR_YELLOW
Definition at line 2880 of file gtest.cc.
                 {
   COLOR_DEFAULT,
   COLOR_RED,
   COLOR_GREEN,
   COLOR_YELLOW
 };
GTestLogSeverity
enum GTestLogSeverity
Enumerator
GTEST_INFO
GTEST_WARNING
GTEST_ERROR
GTEST_FATAL
Definition at line 1244 of file gtest-port.h.
                       {
   GTEST_INFO,
   GTEST_WARNING,
   GTEST_ERROR,
   GTEST_FATAL
 };
Function Documentation
AlwaysFalse()
bool testing::internal::AlwaysFalse ()
Definition at line 736 of file gtest-internal.h.
 { return !AlwaysTrue(); }
References AlwaysTrue().
Referenced by ColoredPrintf().
AlwaysTrue()
GTEST_API_ bool AlwaysTrue ()
Definition at line 4988 of file gtest.cc.
                   {
 #if GTEST_HAS_EXCEPTIONS
   // This condition is always false so AlwaysTrue() never actually throws,
   // but it makes the compiler think that it may throw.
   if (IsTrue(false))
     throw ClassUniqueToAlwaysTrue();
 #endif  // GTEST_HAS_EXCEPTIONS
   return true;
 }
References IsTrue().
Referenced by AlwaysFalse(), and SplitString().
AppendUserMessage()
GTEST_API_ std::string AppendUserMessage (const std::string & gtest_msg, const Message & user_msg)
Definition at line 2001 of file gtest.cc.
{
   // Appends the user message if it's non-empty.
   const std::string user_msg_string = user_msg.GetString();
   if (user_msg_string.empty()) {
     return gtest_msg;
   }
   return gtest_msg + "\n" + user_msg_string;
 }
References string::empty(), and Message::GetString().
Referenced by AssertHelper::operator=().
ArrayAwareFind()
Iter testing::internal::ArrayAwareFind (Iter begin, Iter end, const Element & elem)
Definition at line 983 of file gtest-internal.h.
{
   for (Iter it = begin; it != end; ++it) {
     if (internal::ArrayEq(*it, elem))
       return it;
   }
   return end;
 }
References ArrayEq().
ArrayEq() [1/3]
bool testing::internal::ArrayEq (const T & lhs, const U & rhs)
Definition at line 960 of file gtest-internal.h.
 { return lhs == rhs; }
ArrayEq() [2/3]
bool ArrayEq (const T * lhs, size_t size, const U * rhs)
Definition at line 972 of file gtest-internal.h.
{
   for (size_t i = 0; i != size; i++) {
     if (!internal::ArrayEq(lhs[i], rhs[i]))
       return false;
   }
   return true;
 }
Referenced by ArrayAwareFind(), ArrayEq(), and NativeArray< Element >::operator==().
ArrayEq() [3/3]
bool testing::internal::ArrayEq (const T(&) lhs[N], const U(&) rhs[N])
Definition at line 964 of file gtest-internal.h.
{
   return internal::ArrayEq(lhs, N, rhs);
 }
References ArrayEq().
BoolFromGTestEnv()
bool BoolFromGTestEnv (const char * flag, bool default_value)
Definition at line 1191 of file gtest-port.cc.
{
 #if defined(GTEST_GET_BOOL_FROM_ENV_)
   return GTEST_GET_BOOL_FROM_ENV_(flag, default_value);
 #endif  // defined(GTEST_GET_BOOL_FROM_ENV_)
   const std::string env_var = FlagToEnvVar(flag);
   const char* const string_value = posix::GetEnv(env_var.c_str());
   return string_value == NULL ?
       default_value : strcmp(string_value, "0") != 0;
 }
References string::c_str(), FlagToEnvVar(), and testing::internal::posix::GetEnv().
CaptureStderr()
GTEST_API_ void testing::internal::CaptureStderr ()
CaptureStdout()
GTEST_API_ void testing::internal::CaptureStdout ()
CheckedDowncastToActualType()
Derived* testing::internal::CheckedDowncastToActualType (Base * base)
Definition at line 1392 of file gtest-port.h.
{
 #if GTEST_HAS_RTTI
   GTEST_CHECK_(typeid(*base) == typeid(Derived));
 #endif
 #if GTEST_HAS_DOWNCAST_
   return ::down_cast<Derived*>(base);
 #elif GTEST_HAS_RTTI
   return dynamic_cast<Derived*>(base);  // NOLINT
 #else
   return static_cast<Derived*>(base);  // Poor man's downcast.
 #endif
 }
References GTEST_CHECK_.
ChopLowBits()
UInt32 testing::internal::ChopLowBits (UInt32 * bits, int n)
Definition at line 1747 of file gtest.cc.
{
   const UInt32 low_bits = *bits & ((static_cast<UInt32>(1) << n) - 1);
   *bits >>= n;
   return low_bits;
 }
References testing::internal::posix::n.
Referenced by CodePointToUtf8().
CmpHelperEQ() [1/2]
GTEST_API_ AssertionResult CmpHelperEQ (const char * lhs_expression, const char * rhs_expression, BiggestInt lhs, BiggestInt rhs)
Definition at line 1437 of file gtest.cc.
{
   if (lhs == rhs) {
     return AssertionSuccess();
   }
   return EqFailure(lhs_expression,
                    rhs_expression,
                    FormatForComparisonFailureMessage(lhs, rhs),
                    FormatForComparisonFailureMessage(rhs, lhs),
                    false);
 }
References testing::AssertionSuccess(), EqFailure(), and FormatForComparisonFailureMessage().
CmpHelperEQ() [2/2]
AssertionResult testing::internal::CmpHelperEQ (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs)
Definition at line 1387 of file gtest.h.
{
 GTEST_DISABLE_MSC_WARNINGS_PUSH_(4389 /* signed/unsigned mismatch */)
   if (lhs == rhs) {
     return AssertionSuccess();
   }
 GTEST_DISABLE_MSC_WARNINGS_POP_()
   return CmpHelperEQFailure(lhs_expression, rhs_expression, lhs, rhs);
 }
References testing::AssertionSuccess(), CmpHelperEQFailure(), GTEST_DISABLE_MSC_WARNINGS_POP_, and GTEST_DISABLE_MSC_WARNINGS_PUSH_.
Referenced by EqHelper< lhs_is_null_literal >::Compare(), and EqHelper< true >::Compare().
CmpHelperEQFailure()
AssertionResult testing::internal::CmpHelperEQFailure (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs)
Definition at line 1375 of file gtest.h.
{
   return EqFailure(lhs_expression,
                    rhs_expression,
                    FormatForComparisonFailureMessage(lhs, rhs),
                    FormatForComparisonFailureMessage(rhs, lhs),
                    false);
 }
References EqFailure(), and FormatForComparisonFailureMessage().
Referenced by CmpHelperEQ().
CmpHelperFloatingPointEQ()
AssertionResult testing::internal::CmpHelperFloatingPointEQ (const char * lhs_expression, const char * rhs_expression, RawType lhs_value, RawType rhs_value)
Definition at line 1631 of file gtest.h.
{
   const FloatingPoint<RawType> lhs(lhs_value), rhs(rhs_value);
   if (lhs.AlmostEquals(rhs)) {
     return AssertionSuccess();
   }
   ::std::stringstream lhs_ss;
   lhs_ss << std::setprecision(std::numeric_limits<RawType>::digits10 + 2)
          << lhs_value;
   ::std::stringstream rhs_ss;
   rhs_ss << std::setprecision(std::numeric_limits<RawType>::digits10 + 2)
          << rhs_value;
   return EqFailure(lhs_expression,
                    rhs_expression,
                    StringStreamToString(&lhs_ss),
                    StringStreamToString(&rhs_ss),
                    false);
 }
References testing::AssertionSuccess(), EqFailure(), std::setprecision(), and StringStreamToString().
CmpHelperOpFailure()
AssertionResult testing::internal::CmpHelperOpFailure (const char * expr1, const char * expr2, const T1 & val1, const T2 & val2, const char * op)
Definition at line 1486 of file gtest.h.
{
   return AssertionFailure()
          << "Expected: (" << expr1 << ") " << op << " (" << expr2
          << "), actual: " << FormatForComparisonFailureMessage(val1, val2)
          << " vs " << FormatForComparisonFailureMessage(val2, val1);
 }
References testing::AssertionFailure(), and FormatForComparisonFailureMessage().
CmpHelperSTRCASEEQ()
GTEST_API_ AssertionResult testing::internal::CmpHelperSTRCASEEQ (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
CmpHelperSTRCASENE()
GTEST_API_ AssertionResult testing::internal::CmpHelperSTRCASENE (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
CmpHelperSTREQ() [1/2]
GTEST_API_ AssertionResult CmpHelperSTREQ (const char * lhs_expression, const char * rhs_expression, const wchar_t * lhs, const wchar_t * rhs)
Definition at line 1869 of file gtest.cc.
{
   if (String::WideCStringEquals(lhs, rhs)) {
     return AssertionSuccess();
   }
   return EqFailure(lhs_expression,
                    rhs_expression,
                    PrintToString(lhs),
                    PrintToString(rhs),
                    false);
 }
References testing::AssertionSuccess(), EqFailure(), testing::PrintToString(), and String::WideCStringEquals().
CmpHelperSTREQ() [2/2]
GTEST_API_ AssertionResult testing::internal::CmpHelperSTREQ (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
CmpHelperSTRNE() [1/2]
GTEST_API_ AssertionResult testing::internal::CmpHelperSTRNE (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
CmpHelperSTRNE() [2/2]
GTEST_API_ AssertionResult CmpHelperSTRNE (const char * s1_expression, const char * s2_expression, const wchar_t * s1, const wchar_t * s2)
Definition at line 1885 of file gtest.cc.
{
   if (!String::WideCStringEquals(s1, s2)) {
     return AssertionSuccess();
   }
   return AssertionFailure() << "Expected: (" << s1_expression << ") != ("
                             << s2_expression << "), actual: "
                             << PrintToString(s1)
                             << " vs " << PrintToString(s2);
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::PrintToString(), and String::WideCStringEquals().
CodePointToUtf8()
std::string CodePointToUtf8 (UInt32 code_point)
Definition at line 1759 of file gtest.cc.
{
   if (code_point > kMaxCodePoint4) {
     return "(Invalid Unicode 0x" + String::FormatHexInt(code_point) + ")";
   }
   char str[5];  // Big enough for the largest valid code point.
   if (code_point <= kMaxCodePoint1) {
     str[1] = '\0';
     str[0] = static_cast<char>(code_point);                          // 0xxxxxxx
   } else if (code_point <= kMaxCodePoint2) {
     str[2] = '\0';
     str[1] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[0] = static_cast<char>(0xC0 | code_point);                   // 110xxxxx
   } else if (code_point <= kMaxCodePoint3) {
     str[3] = '\0';
     str[2] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[1] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[0] = static_cast<char>(0xE0 | code_point);                   // 1110xxxx
   } else {  // code_point <= kMaxCodePoint4
     str[4] = '\0';
     str[3] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[2] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[1] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[0] = static_cast<char>(0xF0 | code_point);                   // 11110xxx
   }
   return str;
 }
References ChopLowBits(), String::FormatHexInt(), kMaxCodePoint1, kMaxCodePoint2, kMaxCodePoint3, and kMaxCodePoint4.
Referenced by WideStringToUtf8().
ColoredPrintf()
void testing::internal::ColoredPrintf (GTestColor color, const char * fmt, ...)
Definition at line 2956 of file gtest.cc.
{
   va_list args;
   va_start(args, fmt);
 #if GTEST_OS_WINDOWS_MOBILE || GTEST_OS_SYMBIAN || GTEST_OS_ZOS || \
     GTEST_OS_IOS || GTEST_OS_WINDOWS_PHONE || GTEST_OS_WINDOWS_RT
   const bool use_color = AlwaysFalse();
 #else
   static const bool in_color_mode =
       ShouldUseColor(posix::IsATTY(posix::FileNo(stdout)) != 0);
   const bool use_color = in_color_mode && (color != COLOR_DEFAULT);
 #endif  // GTEST_OS_WINDOWS_MOBILE || GTEST_OS_SYMBIAN || GTEST_OS_ZOS
   // The '!= 0' comparison is necessary to satisfy MSVC 7.1.
   if (!use_color) {
     vprintf(fmt, args);
     va_end(args);
     return;
   }
 #if GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_MOBILE && \
     !GTEST_OS_WINDOWS_PHONE && !GTEST_OS_WINDOWS_RT
   const HANDLE stdout_handle = GetStdHandle(STD_OUTPUT_HANDLE);
   // Gets the current text color.
   CONSOLE_SCREEN_BUFFER_INFO buffer_info;
   GetConsoleScreenBufferInfo(stdout_handle, &buffer_info);
   const WORD old_color_attrs = buffer_info.wAttributes;
   // We need to flush the stream buffers into the console before each
   // SetConsoleTextAttribute call lest it affect the text that is already
   // printed but has not yet reached the console.
   fflush(stdout);
   SetConsoleTextAttribute(stdout_handle,
                           GetColorAttribute(color) | FOREGROUND_INTENSITY);
   vprintf(fmt, args);
   fflush(stdout);
   // Restores the text color.
   SetConsoleTextAttribute(stdout_handle, old_color_attrs);
 #else
   printf("\033[0;3%sm", GetAnsiColorCode(color));
   vprintf(fmt, args);
   printf("\033[m");  // Resets the terminal to default.
 #endif  // GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_MOBILE
   va_end(args);
 }
References AlwaysFalse(), COLOR_DEFAULT, testing::internal::posix::FileNo(), GetAnsiColorCode(), testing::internal::posix::IsATTY(), and ShouldUseColor().
Referenced by PrettyUnitTestResultPrinter::OnEnvironmentsSetUpStart(), PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), PrettyUnitTestResultPrinter::OnTestCaseEnd(), PrettyUnitTestResultPrinter::OnTestCaseStart(), PrettyUnitTestResultPrinter::OnTestEnd(), PrettyUnitTestResultPrinter::OnTestIterationEnd(), PrettyUnitTestResultPrinter::OnTestIterationStart(), PrettyUnitTestResultPrinter::OnTestStart(), PrintColorEncoded(), PrettyUnitTestResultPrinter::PrintFailedTests(), ShouldShard(), and WriteToShardStatusFileIfNeeded().
CopyArray() [1/3]
void testing::internal::CopyArray (const T & from, U * to)
Definition at line 1000 of file gtest-internal.h.
 { *to = from; }
CopyArray() [2/3]
void CopyArray (const T * from, size_t size, U * to)
Definition at line 1012 of file gtest-internal.h.
{
   for (size_t i = 0; i != size; i++) {
     internal::CopyArray(from[i], to + i);
   }
 }
Referenced by CopyArray(), and NativeArray< Element >::InitCopy().
CopyArray() [3/3]
void testing::internal::CopyArray (const T(&) from[N], U(*) to[N])
Definition at line 1004 of file gtest-internal.h.
{
   internal::CopyArray(from, N, *to);
 }
References CopyArray().
CountIf()
int testing::internal::CountIf (const Container & c, Predicate predicate)
Definition at line 283 of file gtest-internal-inl.h.
{
   // Implemented as an explicit loop since std::count_if() in libCstd on
   // Solaris has a non-standard signature.
   int count = 0;
   for (typename Container::const_iterator it = c.begin(); it != c.end(); ++it) {
     if (predicate(*it))
       ++count;
   }
   return count;
 }
Referenced by TestCase::disabled_test_count(), UnitTestImpl::failed_test_case_count(), TestCase::failed_test_count(), TestResult::HasFatalFailure(), TestResult::HasNonfatalFailure(), TestCase::reportable_disabled_test_count(), TestCase::reportable_test_count(), UnitTestImpl::successful_test_case_count(), TestCase::successful_test_count(), UnitTestImpl::test_case_to_run_count(), and TestCase::test_to_run_count().
CreateCodePointFromUtf16SurrogatePair()
UInt32 testing::internal::CreateCodePointFromUtf16SurrogatePair (wchar_t first, wchar_t second)
Definition at line 1800 of file gtest.cc.
{
   const UInt32 mask = (1 << 10) - 1;
   return (sizeof(wchar_t) == 2) ?
       (((first & mask) << 10) | (second & mask)) + 0x10000 :
       // This function should not be called when the condition is
       // false, but we provide a sensible default in case it is.
       static_cast<UInt32>(first);
 }
Referenced by WideStringToUtf8().
DefaultPrintTo() [1/3]
void testing::internal::DefaultPrintTo (IsContainer , false_type , const C & container, ::std::ostream * os)
Definition at line 370 of file gtest-printers.h.
{
   const size_t kMaxCount = 32;  // The maximum number of elements to print.
   *os << '{';
   size_t count = 0;
   for (typename C::const_iterator it = container.begin();
        it != container.end(); ++it, ++count) {
     if (count > 0) {
       *os << ',';
       if (count == kMaxCount) {  // Enough has been printed.
         *os << " ...";
         break;
       }
     }
     *os << ' ';
     // We cannot call PrintTo(*it, os) here as PrintTo() doesn't
     // handle *it being a native array.
     internal::UniversalPrint(*it, os);
   }
   if (count > 0) {
     *os << ' ';
   }
   *os << '}';
 }
References UniversalPrint().
Referenced by PrintTo().
DefaultPrintTo() [2/3]
void testing::internal::DefaultPrintTo (IsNotContainer , false_type , const T & value, ::std::ostream * os)
Definition at line 436 of file gtest-printers.h.
{
   ::testing_internal::DefaultPrintNonContainerTo(value, os);
 }
References testing_internal::DefaultPrintNonContainerTo().
DefaultPrintTo() [3/3]
void testing::internal::DefaultPrintTo (IsNotContainer , true_type , T * p, ::std::ostream * os)
Definition at line 404 of file gtest-printers.h.
{
   if (p == NULL) {
     *os << "NULL";
   } else {
     // C++ doesn't allow casting from a function pointer to any object
     // pointer.
     //
     // IsTrue() silences warnings: "Condition is always true",
     // "unreachable code".
     if (IsTrue(ImplicitlyConvertible<T*, const void*>::value)) {
       // T is not a function type.  We just call << to print p,
       // relying on ADL to pick up user-defined << for their pointer
       // types, if any.
       *os << p;
     } else {
       // T is a function type, so '*os << p' doesn't do what we want
       // (it just prints p as bool).  We want to print p as a const
       // void*.  However, we cannot cast it to const void* directly,
       // even using reinterpret_cast, as earlier versions of gcc
       // (e.g. 3.4.5) cannot compile the cast when p is a function
       // pointer.  Casting to UInt64 first solves the problem.
       *os << reinterpret_cast<const void*>(
           reinterpret_cast<internal::UInt64>(p));
     }
   }
 }
References IsTrue().
Delete()
static void testing::internal::Delete (T * x) static
Definition at line 340 of file gtest-internal-inl.h.
{
   delete x;
 }
DiffStrings()
GTEST_API_ std::string testing::internal::DiffStrings (const std::string & left, const std::string & right, size_t * total_line_count)
DoubleNearPredFormat()
GTEST_API_ AssertionResult DoubleNearPredFormat (const char * expr1, const char * expr2, const char * abs_error_expr, double val1, double val2, double abs_error)
Definition at line 1362 of file gtest.cc.
{
   const double diff = fabs(val1 - val2);
   if (diff <= abs_error) return AssertionSuccess();
   // TODO(wan): do not print the value of an expression if it's
   // already a literal.
   return AssertionFailure()
       << "The difference between " << expr1 << " and " << expr2
       << " is " << diff << ", which exceeds " << abs_error_expr << ", where\n"
       << expr1 << " evaluates to " << val1 << ",\n"
       << expr2 << " evaluates to " << val2 << ", and\n"
       << abs_error_expr << " evaluates to " << abs_error << ".";
 }
References testing::AssertionFailure(), and testing::AssertionSuccess().
DownCast_()
To testing::internal::DownCast_ (From * f)
Definition at line 1367 of file gtest-port.h.
                              {  // so we only accept pointers
   // Ensures that To is a sub-type of From *.  This test is here only
   // for compile-time type checking, and has no overhead in an
   // optimized build at run-time, as it will be optimized away
   // completely.
   GTEST_INTENTIONAL_CONST_COND_PUSH_()
   if (false) {
   GTEST_INTENTIONAL_CONST_COND_POP_()
     const To to = NULL;
     ::testing::internal::ImplicitCast_<From*>(to);
   }
 #if GTEST_HAS_RTTI
   // RTTI: debug mode only!
   GTEST_CHECK_(f == NULL || dynamic_cast<To>(f) != NULL);
 #endif
   return static_cast<To>(f);
 }
References GTEST_CHECK_, GTEST_INTENTIONAL_CONST_COND_POP_, and GTEST_INTENTIONAL_CONST_COND_PUSH_.
EqFailure()
GTEST_API_ AssertionResult EqFailure (const char * lhs_expression, const char * rhs_expression, const std::string & lhs_value, const std::string & rhs_value, bool ignoring_case)
Definition at line 1312 of file gtest.cc.
{
   Message msg;
   msg << "      Expected: " << lhs_expression;
   if (lhs_value != lhs_expression) {
     msg << "\n      Which is: " << lhs_value;
   }
   msg << "\nTo be equal to: " << rhs_expression;
   if (rhs_value != rhs_expression) {
     msg << "\n      Which is: " << rhs_value;
   }
   if (ignoring_case) {
     msg << "\nIgnoring case";
   }
   if (!lhs_value.empty() && !rhs_value.empty()) {
     const std::vector<std::string> lhs_lines =
         SplitEscapedString(lhs_value);
     const std::vector<std::string> rhs_lines =
         SplitEscapedString(rhs_value);
     if (lhs_lines.size() > 1 || rhs_lines.size() > 1) {
       msg << "\nWith diff:\n"
           << edit_distance::CreateUnifiedDiff(lhs_lines, rhs_lines);
     }
   }
   return AssertionFailure() << msg;
 }
References testing::AssertionFailure(), testing::internal::edit_distance::CreateUnifiedDiff(), string::empty(), vector< T >::size(), and testing::internal::anonymous_namespace{gtest.cc}::SplitEscapedString().
Referenced by CmpHelperEQ(), CmpHelperEQFailure(), CmpHelperFloatingPointEQ(), CmpHelperSTREQ(), and GTEST_IMPL_CMP_HELPER_().
FlagToEnvVar()
static std::string testing::internal::FlagToEnvVar (const char * flag) static
Definition at line 1134 of file gtest-port.cc.
{
   const std::string full_flag =
       (Message() << GTEST_FLAG_PREFIX_ << flag).GetString();
   Message env_var;
   for (size_t i = 0; i != full_flag.length(); i++) {
     env_var << ToUpper(full_flag.c_str()[i]);
   }
   return env_var.GetString();
 }
References string::c_str(), Message::GetString(), GTEST_FLAG_PREFIX_, string::length(), and ToUpper().
Referenced by BoolFromGTestEnv(), Int32FromGTestEnv(), and StringFromGTestEnv().
FloatingPointLE()
AssertionResult testing::internal::FloatingPointLE (const char * expr1, const char * expr2, RawType val1, RawType val2)
Definition at line 1384 of file gtest.cc.
{
   // Returns success if val1 is less than val2,
   if (val1 < val2) {
     return AssertionSuccess();
   }
   // or if val1 is almost equal to val2.
   const FloatingPoint<RawType> lhs(val1), rhs(val2);
   if (lhs.AlmostEquals(rhs)) {
     return AssertionSuccess();
   }
   // Note that the above two checks will both fail if either val1 or
   // val2 is NaN, as the IEEE floating-point standard requires that
   // any predicate involving a NaN must return false.
   ::std::stringstream val1_ss;
   val1_ss << std::setprecision(std::numeric_limits<RawType>::digits10 + 2)
           << val1;
   ::std::stringstream val2_ss;
   val2_ss << std::setprecision(std::numeric_limits<RawType>::digits10 + 2)
           << val2;
   return AssertionFailure()
       << "Expected: (" << expr1 << ") <= (" << expr2 << ")\n"
       << "  Actual: " << StringStreamToString(&val1_ss) << " vs "
       << StringStreamToString(&val2_ss);
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), std::setprecision(), and StringStreamToString().
FlushInfoLog()
void testing::internal::FlushInfoLog ()
Definition at line 1276 of file gtest-port.h.
 { fflush(NULL); }
ForEach()
void testing::internal::ForEach (const Container & c, Functor functor)
Definition at line 296 of file gtest-internal-inl.h.
{
   std::for_each(c.begin(), c.end(), functor);
 }
References std::for_each().
Referenced by UnitTestImpl::ClearNonAdHocTestResult(), TestCase::ClearResult(), UnitTestImpl::RunAllTests(), TestCase::~TestCase(), TestEventRepeater::~TestEventRepeater(), and UnitTestImpl::~UnitTestImpl().
FormatCompilerIndependentFileLocation()
GTEST_API_::std::string FormatCompilerIndependentFileLocation (const char * file, int line)
Definition at line 898 of file gtest-port.cc.
{
   const std::string file_name(file == NULL ? kUnknownFile : file);
   if (line < 0)
     return file_name;
   else
     return file_name + ":" + StreamableToString(line);
 }
References kUnknownFile, and StreamableToString().
Referenced by XmlUnitTestResultPrinter::OutputXmlTestInfo().
FormatEpochTimeInMillisAsIso8601()
std::string FormatEpochTimeInMillisAsIso8601 (TimeInMillis ms)
Definition at line 3574 of file gtest.cc.
{
   struct tm time_struct;
   if (!PortableLocaltime(static_cast<time_t>(ms / 1000), &time_struct))
     return "";
   // YYYY-MM-DDThh:mm:ss
   return StreamableToString(time_struct.tm_year + 1900) + "-" +
       String::FormatIntWidth2(time_struct.tm_mon + 1) + "-" +
       String::FormatIntWidth2(time_struct.tm_mday) + "T" +
       String::FormatIntWidth2(time_struct.tm_hour) + ":" +
       String::FormatIntWidth2(time_struct.tm_min) + ":" +
       String::FormatIntWidth2(time_struct.tm_sec);
 }
References String::FormatIntWidth2(), PortableLocaltime(), and StreamableToString().
Referenced by XmlUnitTestResultPrinter::PrintXmlUnitTest().
FormatFileLocation()
GTEST_API_::std::string FormatFileLocation (const char * file, int line)
Definition at line 880 of file gtest-port.cc.
{
   const std::string file_name(file == NULL ? kUnknownFile : file);
   if (line < 0) {
     return file_name + ":";
   }
 #ifdef _MSC_VER
   return file_name + "(" + StreamableToString(line) + "):";
 #else
   return file_name + ":" + StreamableToString(line) + ":";
 #endif  // _MSC_VER
 }
References kUnknownFile, and StreamableToString().
Referenced by UnitTest::AddTestPartResult(), GTestLog::GTestLog(), and PrintTestPartResultToString().
FormatForComparisonFailureMessage()
std::string testing::internal::FormatForComparisonFailureMessage (const T1 & value, const T2 &)
Definition at line 349 of file gtest-printers.h.
{
   return FormatForComparison<T1, T2>::Format(value);
 }
References FormatForComparison< ToPrint, OtherOperand >::Format().
Referenced by CmpHelperEQ(), CmpHelperEQFailure(), and CmpHelperOpFailure().
FormatTimeInMillisAsSeconds()
std::string FormatTimeInMillisAsSeconds (TimeInMillis ms)
Definition at line 3550 of file gtest.cc.
{
   ::std::stringstream ss;
   ss << (static_cast<double>(ms) * 1e-3);
   return ss.str();
 }
References stringstream::str().
Referenced by XmlUnitTestResultPrinter::OutputXmlTestInfo(), XmlUnitTestResultPrinter::PrintXmlTestCase(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().
GetAnsiColorCode()
const char* testing::internal::GetAnsiColorCode (GTestColor color)
Definition at line 2904 of file gtest.cc.
{
   switch (color) {
     case COLOR_RED:     return "1";
     case COLOR_GREEN:   return "2";
     case COLOR_YELLOW:  return "3";
     default:            return NULL;
   };
 }
References COLOR_GREEN, COLOR_RED, and COLOR_YELLOW.
Referenced by ColoredPrintf().
GetArgvs()
GTEST_API_ const ::std::vector< testing::internal::string > & GetArgvs ()
Definition at line 389 of file gtest.cc.
{
 #if defined(GTEST_CUSTOM_GET_ARGVS_)
   return GTEST_CUSTOM_GET_ARGVS_();
 #else  // defined(GTEST_CUSTOM_GET_ARGVS_)
   return g_argvs;
 #endif  // defined(GTEST_CUSTOM_GET_ARGVS_)
 }
References g_argvs.
Referenced by GetCurrentExecutableName(), and GTestIsInitialized().
GetBoolAssertionFailureMessage()
GTEST_API_ std::string GetBoolAssertionFailureMessage (const AssertionResult & assertion_result, const char * expression_text, const char * actual_predicate_value, const char * expected_predicate_value)
Definition at line 1346 of file gtest.cc.
{
   const char* actual_message = assertion_result.message();
   Message msg;
   msg << "Value of: " << expression_text
       << "\n  Actual: " << actual_predicate_value;
   if (actual_message[0] != '\0')
     msg << " (" << actual_message << ")";
   msg << "\nExpected: " << expected_predicate_value;
   return msg.GetString();
 }
References Message::GetString(), and AssertionResult::message().
GetCapturedStderr()
GTEST_API_ std::string testing::internal::GetCapturedStderr ()
GetCapturedStdout()
GTEST_API_ std::string testing::internal::GetCapturedStdout ()
GetCurrentExecutableName()
FilePath GetCurrentExecutableName ()
Definition at line 399 of file gtest.cc.
{
   FilePath result;
 #if GTEST_OS_WINDOWS
   result.Set(FilePath(GetArgvs()[0]).RemoveExtension("exe"));
 #else
   result.Set(FilePath(GetArgvs()[0]));
 #endif  // GTEST_OS_WINDOWS
   return result.RemoveDirectoryName();
 }
References GetArgvs(), FilePath::RemoveDirectoryName(), and FilePath::Set().
Referenced by UnitTestOptions::GetAbsolutePathToOutputFile().
GetCurrentOsStackTraceExceptTop()
GTEST_API_ std::string GetCurrentOsStackTraceExceptTop (UnitTest * , int skip_count)
Definition at line 4973 of file gtest.cc.
{
   // We pass skip_count + 1 to skip this wrapper function in addition
   // to what the user really wants to skip.
   return GetUnitTestImpl()->CurrentOsStackTraceExceptTop(skip_count + 1);
 }
References UnitTestImpl::CurrentOsStackTraceExceptTop(), and GetUnitTestImpl().
GetElementOr()
E testing::internal::GetElementOr (const std::vector< E > & v, int i, E default_value)
Definition at line 303 of file gtest-internal-inl.h.
{
   return (i < 0 || i >= static_cast<int>(v.size())) ? default_value : v[i];
 }
References vector< T >::size().
Referenced by UnitTestImpl::GetMutableTestCase(), TestCase::GetMutableTestInfo(), UnitTestImpl::GetTestCase(), and TestCase::GetTestInfo().
GetFileSize()
GTEST_API_ size_t GetFileSize (FILE * file)
Definition at line 1076 of file gtest-port.cc.
{
   fseek(file, 0, SEEK_END);
   return static_cast<size_t>(ftell(file));
 }
Referenced by ReadEntireFile().
GetNextRandomSeed()
int testing::internal::GetNextRandomSeed (int seed)
Definition at line 152 of file gtest-internal-inl.h.
{
   GTEST_CHECK_(1 <= seed && seed <= kMaxRandomSeed)
       << "Invalid random seed " << seed << " - must be in [1, "
       << kMaxRandomSeed << "].";
   const int next_seed = seed + 1;
   return (next_seed > kMaxRandomSeed) ? 1 : next_seed;
 }
References GTEST_CHECK_, and kMaxRandomSeed.
Referenced by UnitTestImpl::RunAllTests().
GetRandomSeedFromFlag()
int testing::internal::GetRandomSeedFromFlag (Int32 random_seed_flag)
Definition at line 136 of file gtest-internal-inl.h.
{
   const unsigned int raw_seed = (random_seed_flag == 0) ?
       static_cast<unsigned int>(GetTimeInMillis()) :
       static_cast<unsigned int>(random_seed_flag);
   // Normalizes the actual seed to range [1, kMaxRandomSeed] such that
   // it's easy to type.
   const int normalized_seed =
       static_cast<int>((raw_seed - 1U) %
                        static_cast<unsigned int>(kMaxRandomSeed)) + 1;
   return normalized_seed;
 }
References GetTimeInMillis(), and kMaxRandomSeed.
Referenced by UnitTestImpl::RunAllTests().
GetTestTypeId()
GTEST_API_ TypeId GetTestTypeId ()
Definition at line 620 of file gtest.cc.
{
   return GetTypeId<Test>();
 }
Referenced by Test::HasSameFixtureClass().
GetThreadCount()
GTEST_API_ size_t GetThreadCount ()
Definition at line 169 of file gtest-port.cc.
{
   // There's no portable way to detect the number of threads, so we just
   // return 0 to indicate that we cannot detect it.
   return 0;
 }
GetTimeInMillis()
TimeInMillis GetTimeInMillis ()
Definition at line 806 of file gtest.cc.
{
 #if GTEST_OS_WINDOWS_MOBILE || defined(__BORLANDC__)
   // Difference between 1970-01-01 and 1601-01-01 in milliseconds.
   // http://analogous.blogspot.com/2005/04/epoch.html
   const TimeInMillis kJavaEpochToWinFileTimeDelta =
     static_cast<TimeInMillis>(116444736UL) * 100000UL;
   const DWORD kTenthMicrosInMilliSecond = 10000;
   SYSTEMTIME now_systime;
   FILETIME now_filetime;
   ULARGE_INTEGER now_int64;
   // TODO(kenton@google.com): Shouldn't this just use
   //   GetSystemTimeAsFileTime()?
   GetSystemTime(&now_systime);
   if (SystemTimeToFileTime(&now_systime, &now_filetime)) {
     now_int64.LowPart = now_filetime.dwLowDateTime;
     now_int64.HighPart = now_filetime.dwHighDateTime;
     now_int64.QuadPart = (now_int64.QuadPart / kTenthMicrosInMilliSecond) -
       kJavaEpochToWinFileTimeDelta;
     return now_int64.QuadPart;
   }
   return 0;
 #elif GTEST_OS_WINDOWS && !GTEST_HAS_GETTIMEOFDAY_
   __timeb64 now;
   // MSVC 8 deprecates _ftime64(), so we want to suppress warning 4996
   // (deprecated function) there.
   // TODO(kenton@google.com): Use GetTickCount()?  Or use
   //   SystemTimeToFileTime()
   GTEST_DISABLE_MSC_WARNINGS_PUSH_(4996)
   _ftime64(&now);
   GTEST_DISABLE_MSC_WARNINGS_POP_()
   return static_cast<TimeInMillis>(now.time) * 1000 + now.millitm;
 #elif GTEST_HAS_GETTIMEOFDAY_
   struct timeval now;
   gettimeofday(&now, NULL);
   return static_cast<TimeInMillis>(now.tv_sec) * 1000 + now.tv_usec / 1000;
 #else
 # error "Don't know how to get the current time on your system."
 #endif
 }
References GTEST_DISABLE_MSC_WARNINGS_POP_, GTEST_DISABLE_MSC_WARNINGS_PUSH_(), and GTEST_HAS_GETTIMEOFDAY_.
Referenced by GetRandomSeedFromFlag(), TestInfo::Run(), TestCase::Run(), and UnitTestImpl::RunAllTests().
GetTypeId()
TypeId testing::internal::GetTypeId ()
Definition at line 447 of file gtest-internal.h.
                    {
   // The compiler is required to allocate a different
   // TypeIdHelper<T>::dummy_ variable for each T used to instantiate
   // the template.  Therefore, the address of dummy_ is guaranteed to
   // be unique.
   return &(TypeIdHelper<T>::dummy_);
 }
GetTypeName()
std::string testing::internal::GetTypeName ()
Definition at line 64 of file gtest-type-util.h.
{
 # if GTEST_HAS_RTTI
   const char* const name = typeid(T).name();
 #  if GTEST_HAS_CXXABI_H_ || defined(__HP_aCC)
   int status = 0;
   // gcc's implementation of typeid(T).name() mangles the type name,
   // so we have to demangle it.
 #   if GTEST_HAS_CXXABI_H_
   using abi::__cxa_demangle;
 #   endif  // GTEST_HAS_CXXABI_H_
   char* const readable_name = __cxa_demangle(name, 0, 0, &status);
   const std::string name_str(status == 0 ? readable_name : name);
   free(readable_name);
   return name_str;
 #  else
   return name;
 #  endif  // GTEST_HAS_CXXABI_H_ || __HP_aCC
 # else
   return "<type>";
 # endif  // GTEST_HAS_RTTI
 }
GetUnitTestImpl()
class UnitTestImpl * GetUnitTestImpl ()
Definition at line 927 of file gtest-internal-inl.h.
{
   return UnitTest::GetInstance()->impl();
 }
References UnitTest::GetInstance(), and UnitTest::impl().
Referenced by GetCurrentOsStackTraceExceptTop(), HandleExceptionsInMethodIfSupported(), Test::HasFatalFailure(), HasNewFatalFailureHelper::HasNewFatalFailureHelper(), Test::HasNonfatalFailure(), Test::HasSameFixtureClass(), ScopedFakeTestPartResultReporter::Init(), InitGoogleTestImpl(), MakeAndRegisterTestInfo(), Test::Run(), TestInfo::Run(), TestCase::Run(), HasNewFatalFailureHelper::~HasNewFatalFailureHelper(), and ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().
GTEST_DECLARE_STATIC_MUTEX_()
GTEST_API_ testing::internal::GTEST_DECLARE_STATIC_MUTEX_ (g_linked_ptr_mutex)
GTEST_DECLARE_string_()
testing::internal::GTEST_DECLARE_string_ (internal_run_death_test)
GTEST_DEFINE_STATIC_MUTEX_()
GTEST_API_ testing::internal::GTEST_DEFINE_STATIC_MUTEX_ (g_linked_ptr_mutex)
GTEST_DEFINE_string_()
testing::internal::GTEST_DEFINE_string_ (internal_run_death_test , "" , "Indicates the file, line number, temporal index of " "the single death test to run, and a file descriptor to " "which a success code may be sent, all separated by " "the '|' characters. This flag is specified if and only if the current " "process is a sub-process launched for running a thread-safe " "death test. FOR INTERNAL USE ONLY.")
GTEST_DISABLE_MSC_WARNINGS_PUSH_()
testing::internal::GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4996)
Definition at line 928 of file gtest-port.cc.
                      {
  public:
   // The ctor redirects the stream to a temporary file.
   explicit CapturedStream(int fd) : fd_(fd), uncaptured_fd_(dup(fd)) {
 # if GTEST_OS_WINDOWS
     char temp_dir_path[MAX_PATH + 1] = { '\0' };  // NOLINT
     char temp_file_path[MAX_PATH + 1] = { '\0' };  // NOLINT
     ::GetTempPathA(sizeof(temp_dir_path), temp_dir_path);
     const UINT success = ::GetTempFileNameA(temp_dir_path,
                                             "gtest_redir",
                                             0,  // Generate unique file name.
                                             temp_file_path);
     GTEST_CHECK_(success != 0)
         << "Unable to create a temporary file in " << temp_dir_path;
     const int captured_fd = creat(temp_file_path, _S_IREAD | _S_IWRITE);
     GTEST_CHECK_(captured_fd != -1) << "Unable to open temporary file "
                                     << temp_file_path;
     filename_ = temp_file_path;
 # else
     // There's no guarantee that a test has write access to the current
     // directory, so we create the temporary file in the /tmp directory
     // instead. We use /tmp on most systems, and /sdcard on Android.
     // That's because Android doesn't have /tmp.
 #  if GTEST_OS_LINUX_ANDROID
     // Note: Android applications are expected to call the framework's
     // Context.getExternalStorageDirectory() method through JNI to get
     // the location of the world-writable SD Card directory. However,
     // this requires a Context handle, which cannot be retrieved
     // globally from native code. Doing so also precludes running the
     // code as part of a regular standalone executable, which doesn't
     // run in a Dalvik process (e.g. when running it through 'adb shell').
     //
     // The location /sdcard is directly accessible from native code
     // and is the only location (unofficially) supported by the Android
     // team. It's generally a symlink to the real SD Card mount point
     // which can be /mnt/sdcard, /mnt/sdcard0, /system/media/sdcard, or
     // other OEM-customized locations. Never rely on these, and always
     // use /sdcard.
     char name_template[] = "/sdcard/gtest_captured_stream.XXXXXX";
 #  else
     char name_template[] = "/tmp/captured_stream.XXXXXX";
 #  endif  // GTEST_OS_LINUX_ANDROID
     const int captured_fd = mkstemp(name_template);
     filename_ = name_template;
 # endif  // GTEST_OS_WINDOWS
     fflush(NULL);
     dup2(captured_fd, fd_);
     close(captured_fd);
   }
   ~CapturedStream() {
     remove(filename_.c_str());
   }
   std::string GetCapturedString() {
     if (uncaptured_fd_ != -1) {
       // Restores the original stream.
       fflush(NULL);
       dup2(uncaptured_fd_, fd_);
       close(uncaptured_fd_);
       uncaptured_fd_ = -1;
     }
     FILE* const file = posix::FOpen(filename_.c_str(), "r");
     const std::string content = ReadEntireFile(file);
     posix::FClose(file);
     return content;
   }
  private:
   const int fd_;  // A stream to capture.
   int uncaptured_fd_;
   // Name of the temporary file holding the stderr output.
   ::std::string filename_;
   GTEST_DISALLOW_COPY_AND_ASSIGN_(CapturedStream);
 };
 GTEST_DISABLE_MSC_WARNINGS_POP_()
 static CapturedStream* g_captured_stderr = NULL;
 static CapturedStream* g_captured_stdout = NULL;
 // Starts capturing an output stream (stdout/stderr).
 void CaptureStream(int fd, const char* stream_name, CapturedStream** stream) {
   if (*stream != NULL) {
     GTEST_LOG_(FATAL) << "Only one " << stream_name
                       << " capturer can exist at a time.";
   }
   *stream = new CapturedStream(fd);
 }
 // Stops capturing the output stream and returns the captured string.
 std::string GetCapturedStream(CapturedStream** captured_stream) {
   const std::string content = (*captured_stream)->GetCapturedString();
   delete *captured_stream;
   *captured_stream = NULL;
   return content;
 }
 // Starts capturing stdout.
 void CaptureStdout() {
   CaptureStream(kStdOutFileno, "stdout", &g_captured_stdout);
 }
 // Starts capturing stderr.
 void CaptureStderr() {
   CaptureStream(kStdErrFileno, "stderr", &g_captured_stderr);
 }
 // Stops capturing stdout and returns the captured string.
 std::string GetCapturedStdout() {
   return GetCapturedStream(&g_captured_stdout);
 }
 // Stops capturing stderr and returns the captured string.
 std::string GetCapturedStderr() {
   return GetCapturedStream(&g_captured_stderr);
 }
 #endif  // GTEST_HAS_STREAM_REDIRECTION
 std::string TempDir() {
 #if GTEST_OS_WINDOWS_MOBILE
   return "\\temp\\";
 #elif GTEST_OS_WINDOWS
   const char* temp_dir = posix::GetEnv("TEMP");
   if (temp_dir == NULL || temp_dir[0] == '\0')
     return "\\temp\\";
   else if (temp_dir[strlen(temp_dir) - 1] == '\\')
     return temp_dir;
   else
     return std::string(temp_dir) + "\\";
 #elif GTEST_OS_LINUX_ANDROID
   return "/sdcard/";
 #else
   return "/tmp/";
 #endif  // GTEST_OS_WINDOWS_MOBILE
 }
References testing::internal::posix::FClose(), testing::internal::posix::FOpen(), GTEST_CHECK_, GTEST_DISALLOW_COPY_AND_ASSIGN_, and ReadEntireFile().
Referenced by GetTimeInMillis().
GTEST_IMPL_CMP_HELPER_() [1/5]
testing::internal::GTEST_IMPL_CMP_HELPER_ (GE , >=)
GTEST_IMPL_CMP_HELPER_() [2/5]
testing::internal::GTEST_IMPL_CMP_HELPER_ (GT)
GTEST_IMPL_CMP_HELPER_() [3/5]
testing::internal::GTEST_IMPL_CMP_HELPER_ (LE , <=)
GTEST_IMPL_CMP_HELPER_() [4/5]
testing::internal::GTEST_IMPL_CMP_HELPER_ (LT)
GTEST_IMPL_CMP_HELPER_() [5/5]
GTEST_IMPL_CMP_HELPER_ (NE , !)
References testing::AssertionSuccess(), String::CStringEquals(), EqFailure(), and testing::PrintToString().
GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_() [1/2]
GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_ (char)
GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_() [2/2]
GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_ (wchar_t)
GTEST_IMPL_FORMAT_C_STRING_AS_STRING_()
GTEST_IMPL_FORMAT_C_STRING_AS_STRING_ (char , ::std::string)
GTEST_REPEATER_METHOD_() [1/3]
UnitTest testing::internal::GTEST_REPEATER_METHOD_ (OnTestCaseStart , TestCase)
GTEST_REPEATER_METHOD_() [2/3]
UnitTest TestInfo testing::internal::GTEST_REPEATER_METHOD_ (OnTestPartResult , TestPartResult)
GTEST_REPEATER_METHOD_() [3/3]
testing::internal::GTEST_REPEATER_METHOD_ (OnTestProgramStart , UnitTest)
GTEST_REVERSE_REPEATER_METHOD_() [1/3]
UnitTest TestInfo UnitTest testing::internal::GTEST_REVERSE_REPEATER_METHOD_ (OnEnvironmentsSetUpEnd , UnitTest)
GTEST_REVERSE_REPEATER_METHOD_() [2/3]
UnitTest TestInfo UnitTest UnitTest testing::internal::GTEST_REVERSE_REPEATER_METHOD_ (OnTestEnd , TestInfo)
GTEST_REVERSE_REPEATER_METHOD_() [3/3]
UnitTest TestInfo UnitTest UnitTest TestCase testing::internal::GTEST_REVERSE_REPEATER_METHOD_ (OnTestProgramEnd , UnitTest)
Definition at line 3323 of file gtest.cc.
{
   if (forwarding_enabled_) {
     for (size_t i = 0; i < listeners_.size(); i++) {
       listeners_[i]->OnTestIterationStart(unit_test, iteration);
     }
   }
 }
References TestEventRepeater::forwarding_enabled_, and TestEventRepeater::listeners_.
GTestIsInitialized()
static bool testing::internal::GTestIsInitialized () static
Definition at line 330 of file gtest.cc.
 { return GetArgvs().size() > 0; }
References GetArgvs().
Referenced by InitGoogleTestImpl(), and UnitTestImpl::RunAllTests().
HandleExceptionsInMethodIfSupported()
Result testing::internal::HandleExceptionsInMethodIfSupported (T * object, Result(T::*)() method, const char * location)
Definition at line 2410 of file gtest.cc.
{
   // NOTE: The user code can affect the way in which Google Test handles
   // exceptions by setting GTEST_FLAG(catch_exceptions), but only before
   // RUN_ALL_TESTS() starts. It is technically possible to check the flag
   // after the exception is caught and either report or re-throw the
   // exception based on the flag's value:
   //
   // try {
   //   // Perform the test method.
   // } catch (...) {
   //   if (GTEST_FLAG(catch_exceptions))
   //     // Report the exception as failure.
   //   else
   //     throw;  // Re-throws the original exception.
   // }
   //
   // However, the purpose of this flag is to allow the program to drop into
   // the debugger when the exception is thrown. On most platforms, once the
   // control enters the catch block, the exception origin information is
   // lost and the debugger will stop the program at the point of the
   // re-throw in this function -- instead of at the point of the original
   // throw statement in the code under test.  For this reason, we perform
   // the check early, sacrificing the ability to affect Google Test's
   // exception handling in the method where the exception is thrown.
   if (internal::GetUnitTestImpl()->catch_exceptions()) {
 #if GTEST_HAS_EXCEPTIONS
     try {
       return HandleSehExceptionsInMethodIfSupported(object, method, location);
     } catch (const internal::GoogleTestFailureException&) {  // NOLINT
       // This exception type can only be thrown by a failed Google
       // Test assertion with the intention of letting another testing
       // framework catch it.  Therefore we just re-throw it.
       throw;
     } catch (const std::exception& e) {  // NOLINT
       internal::ReportFailureInUnknownLocation(
           TestPartResult::kFatalFailure,
           FormatCxxExceptionMessage(e.what(), location));
     } catch (...) {  // NOLINT
       internal::ReportFailureInUnknownLocation(
           TestPartResult::kFatalFailure,
           FormatCxxExceptionMessage(NULL, location));
     }
     return static_cast<Result>(0);
 #else
     return HandleSehExceptionsInMethodIfSupported(object, method, location);
 #endif  // GTEST_HAS_EXCEPTIONS
   } else {
     return (object->*method)();
   }
 }
References GetUnitTestImpl(), HandleSehExceptionsInMethodIfSupported(), TestPartResult::kFatalFailure, ReportFailureInUnknownLocation(), and exception::what().
Referenced by Test::Run(), TestInfo::Run(), TestCase::Run(), and UnitTest::Run().
HandleSehExceptionsInMethodIfSupported()
Result testing::internal::HandleSehExceptionsInMethodIfSupported (T * object, Result(T::*)() method, const char * location)
Definition at line 2383 of file gtest.cc.
{
 #if GTEST_HAS_SEH
   __try {
     return (object->*method)();
   } __except (internal::UnitTestOptions::GTestShouldProcessSEH(  // NOLINT
       GetExceptionCode())) {
     // We create the exception message on the heap because VC++ prohibits
     // creation of objects with destructors on stack in functions using __try
     // (see error C2712).
     std::string* exception_message = FormatSehExceptionMessage(
         GetExceptionCode(), location);
     internal::ReportFailureInUnknownLocation(TestPartResult::kFatalFailure,
                                              *exception_message);
     delete exception_message;
     return static_cast<Result>(0);
   }
 #else
   (void)location;
   return (object->*method)();
 #endif  // GTEST_HAS_SEH
 }
References TestPartResult::kFatalFailure, and ReportFailureInUnknownLocation().
Referenced by HandleExceptionsInMethodIfSupported().
HasGoogleTestFlagPrefix()
static bool testing::internal::HasGoogleTestFlagPrefix (const char * str) static
Definition at line 5105 of file gtest.cc.
{
   return (SkipPrefix("--", &str) ||
           SkipPrefix("-", &str) ||
           SkipPrefix("/", &str)) &&
          !SkipPrefix(GTEST_FLAG_PREFIX_ "internal_", &str) &&
          (SkipPrefix(GTEST_FLAG_PREFIX_, &str) ||
           SkipPrefix(GTEST_FLAG_PREFIX_DASH_, &str));
 }
References GTEST_FLAG_PREFIX_, GTEST_FLAG_PREFIX_DASH_, and SkipPrefix().
Referenced by ParseGoogleTestFlagsOnlyImpl().
HasOneFailure()
AssertionResult testing::internal::HasOneFailure (const char * , const char * , const char * , const TestPartResultArray & results, TestPartResult::Type type, const string & substr)
Definition at line 631 of file gtest.cc.
{
   const std::string expected(type == TestPartResult::kFatalFailure ?
                         "1 fatal failure" :
                         "1 non-fatal failure");
   Message msg;
   if (results.size() != 1) {
     msg << "Expected: " << expected << "\n"
         << "  Actual: " << results.size() << " failures";
     for (int i = 0; i < results.size(); i++) {
       msg << "\n" << results.GetTestPartResult(i);
     }
     return AssertionFailure() << msg;
   }
   const TestPartResult& r = results.GetTestPartResult(0);
   if (r.type() != type) {
     return AssertionFailure() << "Expected: " << expected << "\n"
                               << "  Actual:\n"
                               << r;
   }
   if (strstr(r.message(), substr.c_str()) == NULL) {
     return AssertionFailure() << "Expected: " << expected << " containing \""
                               << substr << "\"\n"
                               << "  Actual:\n"
                               << r;
   }
   return AssertionSuccess();
 }
References testing::AssertionFailure(), testing::AssertionSuccess(), string::c_str(), TestPartResultArray::GetTestPartResult(), TestPartResult::kFatalFailure, TestPartResult::message(), TestPartResultArray::size(), and TestPartResult::type().
Referenced by SingleFailureChecker::~SingleFailureChecker().
ImplicitCast_()
To testing::internal::ImplicitCast_ (To x)
Definition at line 1343 of file gtest-port.h.
 { return x; }
InitGoogleTestImpl()
void testing::internal::InitGoogleTestImpl (int * argc, CharType ** argv)
Definition at line 5344 of file gtest.cc.
{
   // We don't want to run the initialization code twice.
   if (GTestIsInitialized()) return;
   if (*argc <= 0) return;
   g_argvs.clear();
   for (int i = 0; i != *argc; i++) {
     g_argvs.push_back(StreamableToString(argv[i]));
   }
   ParseGoogleTestFlagsOnly(argc, argv);
   GetUnitTestImpl()->PostFlagParsingInit();
 }
References g_argvs, GetUnitTestImpl(), GTestIsInitialized(), ParseGoogleTestFlagsOnly(), UnitTestImpl::PostFlagParsingInit(), and StreamableToString().
Referenced by testing::InitGoogleTest().
Int32FromEnvOrDie()
Int32 Int32FromEnvOrDie (const char * env_var, Int32 default_val)
Definition at line 4760 of file gtest.cc.
{
   const char* str_val = posix::GetEnv(var);
   if (str_val == NULL) {
     return default_val;
   }
   Int32 result;
   if (!ParseInt32(Message() << "The value of environment variable " << var,
                   str_val, &result)) {
     exit(EXIT_FAILURE);
   }
   return result;
 }
References testing::internal::posix::GetEnv(), and ParseInt32().
Referenced by UnitTestImpl::FilterTests(), PrettyUnitTestResultPrinter::OnTestIterationStart(), and ShouldShard().
Int32FromGTestEnv()
GTEST_API_ Int32 Int32FromGTestEnv (const char * flag, Int32 default_value)
Definition at line 1204 of file gtest-port.cc.
{
 #if defined(GTEST_GET_INT32_FROM_ENV_)
   return GTEST_GET_INT32_FROM_ENV_(flag, default_value);
 #endif  // defined(GTEST_GET_INT32_FROM_ENV_)
   const std::string env_var = FlagToEnvVar(flag);
   const char* const string_value = posix::GetEnv(env_var.c_str());
   if (string_value == NULL) {
     // The environment variable is not set.
     return default_value;
   }
   Int32 result = default_value;
   if (!ParseInt32(Message() << "Environment variable " << env_var,
                   string_value, &result)) {
     printf("The default value %s is used.\n",
            (Message() << default_value).GetString().c_str());
     fflush(stdout);
     return default_value;
   }
   return result;
 }
References string::c_str(), FlagToEnvVar(), testing::internal::posix::GetEnv(), and ParseInt32().
IsAlNum()
bool testing::internal::IsAlNum (char ch)
Definition at line 2254 of file gtest-port.h.
{
   return isalnum(static_cast<unsigned char>(ch)) != 0;
 }
IsAlpha()
bool testing::internal::IsAlpha (char ch)
Definition at line 2251 of file gtest-port.h.
{
   return isalpha(static_cast<unsigned char>(ch)) != 0;
 }
IsContainerTest() [1/2]
IsContainer testing::internal::IsContainerTest (int , typename C::iterator * = NULL, typename C::const_iterator * = NULL)
Definition at line 932 of file gtest-internal.h.
{
   return 0;
 }
IsContainerTest() [2/2]
IsNotContainer testing::internal::IsContainerTest (long)
Definition at line 940 of file gtest-internal.h.
 { return '\0'; }
IsDigit()
bool testing::internal::IsDigit (char ch)
Definition at line 2257 of file gtest-port.h.
{
   return isdigit(static_cast<unsigned char>(ch)) != 0;
 }
IsLower()
bool testing::internal::IsLower (char ch)
Definition at line 2260 of file gtest-port.h.
{
   return islower(static_cast<unsigned char>(ch)) != 0;
 }
IsNullLiteralHelper() [1/2]
char(& testing::internal::IsNullLiteralHelper (...))[2]
IsNullLiteralHelper() [2/2]
char testing::internal::IsNullLiteralHelper (Secret * p)
IsPathSeparator()
static bool testing::internal::IsPathSeparator (char c) static
Definition at line 90 of file gtest-filepath.cc.
{
 #if GTEST_HAS_ALT_PATH_SEP_
   return (c == kPathSeparator) || (c == kAlternatePathSeparator);
 #else
   return c == kPathSeparator;
 #endif
 }
References kPathSeparator.
Referenced by FilePath::IsAbsolutePath(), FilePath::IsDirectory(), FilePath::IsRootDirectory(), and FilePath::Normalize().
IsPrintableAscii()
bool testing::internal::IsPrintableAscii (wchar_t c)
Definition at line 137 of file gtest-printers.cc.
{
   return 0x20 <= c && c <= 0x7E;
 }
Referenced by PrintAsCharLiteralTo().
IsSpace()
bool testing::internal::IsSpace (char ch)
Definition at line 2263 of file gtest-port.h.
{
   return isspace(static_cast<unsigned char>(ch)) != 0;
 }
Referenced by StripTrailingSpaces().
IsTrue()
GTEST_API_ bool IsTrue (bool condition)
Definition at line 4986 of file gtest.cc.
 { return condition; }
Referenced by AlwaysTrue(), DefaultPrintTo(), and scoped_ptr< T >::reset().
IsUpper()
bool testing::internal::IsUpper (char ch)
Definition at line 2266 of file gtest-port.h.
{
   return isupper(static_cast<unsigned char>(ch)) != 0;
 }
IsUtf16SurrogatePair()
bool testing::internal::IsUtf16SurrogatePair (wchar_t first, wchar_t second)
Definition at line 1794 of file gtest.cc.
{
   return sizeof(wchar_t) == 2 &&
       (first & 0xFC00) == 0xD800 && (second & 0xFC00) == 0xDC00;
 }
Referenced by WideStringToUtf8().
IsXDigit() [1/2]
bool testing::internal::IsXDigit (char ch)
Definition at line 2269 of file gtest-port.h.
{
   return isxdigit(static_cast<unsigned char>(ch)) != 0;
 }
Referenced by PrintCharsAsStringTo().
IsXDigit() [2/2]
bool testing::internal::IsXDigit (wchar_t ch)
Definition at line 2272 of file gtest-port.h.
{
   const unsigned char low_byte = static_cast<unsigned char>(ch);
   return ch == low_byte && isxdigit(low_byte) != 0;
 }
LogToStderr()
void testing::internal::LogToStderr ()
Definition at line 1275 of file gtest-port.h.
 {}
make_linked_ptr()
linked_ptr<T> testing::internal::make_linked_ptr (T * ptr)
Definition at line 236 of file gtest-linked_ptr.h.
{
   return linked_ptr<T>(ptr);
 }
MakeAndRegisterTestInfo()
GTEST_API_ TestInfo * MakeAndRegisterTestInfo (const char * test_case_name, const char * name, const char * type_param, const char * value_param, CodeLocation code_location, TypeId fixture_class_id, SetUpTestCaseFunc set_up_tc, TearDownTestCaseFunc tear_down_tc, TestFactoryBase * factory)
Definition at line 2543 of file gtest.cc.
{
   TestInfo* const test_info =
       new TestInfo(test_case_name, name, type_param, value_param,
                    code_location, fixture_class_id, factory);
   GetUnitTestImpl()->AddTestInfo(set_up_tc, tear_down_tc, test_info);
   return test_info;
 }
References UnitTestImpl::AddTestInfo(), and GetUnitTestImpl().
move()
const T& testing::internal::move (const T & t)
Definition at line 1317 of file gtest-port.h.
{
   return t;
 }
Referenced by testing::internal::edit_distance::CalculateOptimalEdits().
operator!=()
bool testing::internal::operator!= (T * ptr, const linked_ptr< T > & x)
Definition at line 228 of file gtest-linked_ptr.h.
{
   return ptr != x.get();
 }
References linked_ptr< T >::get().
operator==()
bool testing::internal::operator== (T * ptr, const linked_ptr< T > & x)
Definition at line 223 of file gtest-linked_ptr.h.
{
   return ptr == x.get();
 }
References linked_ptr< T >::get().
ParseBoolFlag()
bool testing::internal::ParseBoolFlag (const char * str, const char * flag, bool * value)
Definition at line 5053 of file gtest.cc.
{
   // Gets the value of the flag as a string.
   const char* const value_str = ParseFlagValue(str, flag, true);
   // Aborts if the parsing failed.
   if (value_str == NULL) return false;
   // Converts the string value to a bool.
   *value = !(*value_str == '0' || *value_str == 'f' || *value_str == 'F');
   return true;
 }
References ParseFlagValue().
Referenced by ParseGoogleTestFlag(), and ParseGoogleTestFlagsOnlyImpl().
ParseFlagValue()
const char* testing::internal::ParseFlagValue (const char * str, const char * flag, bool def_optional)
Definition at line 5015 of file gtest.cc.
{
   // str and flag must not be NULL.
   if (str == NULL || flag == NULL) return NULL;
   // The flag must start with "--" followed by GTEST_FLAG_PREFIX_.
   const std::string flag_str = std::string("--") + GTEST_FLAG_PREFIX_ + flag;
   const size_t flag_len = flag_str.length();
   if (strncmp(str, flag_str.c_str(), flag_len) != 0) return NULL;
   // Skips the flag name.
   const char* flag_end = str + flag_len;
   // When def_optional is true, it's OK to not have a "=value" part.
   if (def_optional && (flag_end[0] == '\0')) {
     return flag_end;
   }
   // If def_optional is true and there are more characters after the
   // flag name, or if def_optional is false, there must be a '=' after
   // the flag name.
   if (flag_end[0] != '=') return NULL;
   // Returns the string after "=".
   return flag_end + 1;
 }
References string::c_str(), GTEST_FLAG_PREFIX_, and string::length().
Referenced by ParseBoolFlag(), ParseInt32Flag(), and ParseStringFlag().
ParseGoogleTestFlag()
bool testing::internal::ParseGoogleTestFlag (const char *const arg)
Definition at line 5223 of file gtest.cc.
{
   return ParseBoolFlag(arg, kAlsoRunDisabledTestsFlag,
                        &GTEST_FLAG(also_run_disabled_tests)) ||
       ParseBoolFlag(arg, kBreakOnFailureFlag,
                     &GTEST_FLAG(break_on_failure)) ||
       ParseBoolFlag(arg, kCatchExceptionsFlag,
                     &GTEST_FLAG(catch_exceptions)) ||
       ParseStringFlag(arg, kColorFlag, &GTEST_FLAG(color)) ||
       ParseStringFlag(arg, kDeathTestStyleFlag,
                       &GTEST_FLAG(death_test_style)) ||
       ParseBoolFlag(arg, kDeathTestUseFork,
                     &GTEST_FLAG(death_test_use_fork)) ||
       ParseStringFlag(arg, kFilterFlag, &GTEST_FLAG(filter)) ||
       ParseStringFlag(arg, kInternalRunDeathTestFlag,
                       &GTEST_FLAG(internal_run_death_test)) ||
       ParseBoolFlag(arg, kListTestsFlag, &GTEST_FLAG(list_tests)) ||
       ParseStringFlag(arg, kOutputFlag, &GTEST_FLAG(output)) ||
       ParseBoolFlag(arg, kPrintTimeFlag, &GTEST_FLAG(print_time)) ||
       ParseInt32Flag(arg, kRandomSeedFlag, &GTEST_FLAG(random_seed)) ||
       ParseInt32Flag(arg, kRepeatFlag, &GTEST_FLAG(repeat)) ||
       ParseBoolFlag(arg, kShuffleFlag, &GTEST_FLAG(shuffle)) ||
       ParseInt32Flag(arg, kStackTraceDepthFlag,
                      &GTEST_FLAG(stack_trace_depth)) ||
       ParseStringFlag(arg, kStreamResultToFlag,
                       &GTEST_FLAG(stream_result_to)) ||
       ParseBoolFlag(arg, kThrowOnFailureFlag,
                     &GTEST_FLAG(throw_on_failure));
 }
References GTEST_FLAG, kAlsoRunDisabledTestsFlag, kBreakOnFailureFlag, kCatchExceptionsFlag, kColorFlag, kDeathTestStyleFlag, kDeathTestUseFork, kFilterFlag, kInternalRunDeathTestFlag, kListTestsFlag, kOutputFlag, kPrintTimeFlag, kRandomSeedFlag, kRepeatFlag, kShuffleFlag, kStackTraceDepthFlag, kStreamResultToFlag, kThrowOnFailureFlag, ParseBoolFlag(), ParseInt32Flag(), and ParseStringFlag().
Referenced by ParseGoogleTestFlagsOnlyImpl().
ParseGoogleTestFlagsOnly() [1/2]
void ParseGoogleTestFlagsOnly (int * argc, char ** argv)
Definition at line 5332 of file gtest.cc.
{
   ParseGoogleTestFlagsOnlyImpl(argc, argv);
 }
References ParseGoogleTestFlagsOnlyImpl().
Referenced by InitGoogleTestImpl().
ParseGoogleTestFlagsOnly() [2/2]
void ParseGoogleTestFlagsOnly (int * argc, wchar_t ** argv)
Definition at line 5335 of file gtest.cc.
{
   ParseGoogleTestFlagsOnlyImpl(argc, argv);
 }
References ParseGoogleTestFlagsOnlyImpl().
ParseGoogleTestFlagsOnlyImpl()
void testing::internal::ParseGoogleTestFlagsOnlyImpl (int * argc, CharType ** argv)
Definition at line 5279 of file gtest.cc.
{
   for (int i = 1; i < *argc; i++) {
     const std::string arg_string = StreamableToString(argv[i]);
     const char* const arg = arg_string.c_str();
     using internal::ParseBoolFlag;
     using internal::ParseInt32Flag;
     using internal::ParseStringFlag;
     bool remove_flag = false;
     if (ParseGoogleTestFlag(arg)) {
       remove_flag = true;
 #if GTEST_USE_OWN_FLAGFILE_FLAG_
     } else if (ParseStringFlag(arg, kFlagfileFlag, &GTEST_FLAG(flagfile))) {
       LoadFlagsFromFile(GTEST_FLAG(flagfile));
       remove_flag = true;
 #endif  // GTEST_USE_OWN_FLAGFILE_FLAG_
     } else if (arg_string == "--help" || arg_string == "-h" ||
                arg_string == "-?" || arg_string == "/?" ||
                HasGoogleTestFlagPrefix(arg)) {
       // Both help flag and unrecognized Google Test flags (excluding
       // internal ones) trigger help display.
       g_help_flag = true;
     }
     if (remove_flag) {
       // Shift the remainder of the argv list left by one.  Note
       // that argv has (*argc + 1) elements, the last one always being
       // NULL.  The following loop moves the trailing NULL element as
       // well.
       for (int j = i; j != *argc; j++) {
         argv[j] = argv[j + 1];
       }
       // Decrements the argument count.
       (*argc)--;
       // We also need to decrement the iterator as we just removed
       // an element.
       i--;
     }
   }
   if (g_help_flag) {
     // We print the help here instead of in RUN_ALL_TESTS(), as the
     // latter may not be called at all if the user is using Google
     // Test with another testing framework.
     PrintColorEncoded(kColorEncodedHelpMessage);
   }
 }
References string::c_str(), g_help_flag, GTEST_FLAG, HasGoogleTestFlagPrefix(), kColorEncodedHelpMessage, kFlagfileFlag, ParseBoolFlag(), ParseGoogleTestFlag(), ParseInt32Flag(), ParseStringFlag(), PrintColorEncoded(), and StreamableToString().
Referenced by ParseGoogleTestFlagsOnly().
ParseInt32()
bool ParseInt32 (const Message & src_text, const char * str, Int32 * value)
Definition at line 1149 of file gtest-port.cc.
{
   // Parses the environment variable as a decimal integer.
   char* end = NULL;
   const long long_value = strtol(str, &end, 10);  // NOLINT
   // Has strtol() consumed all characters in the string?
   if (*end != '\0') {
     // No - an invalid character was encountered.
     Message msg;
     msg << "WARNING: " << src_text
         << " is expected to be a 32-bit integer, but actually"
         << " has value \"" << str << "\".\n";
     printf("%s", msg.GetString().c_str());
     fflush(stdout);
     return false;
   }
   // Is the parsed value in the range of an Int32?
   const Int32 result = static_cast<Int32>(long_value);
   if (long_value == LONG_MAX || long_value == LONG_MIN ||
       // The parsed value overflows as a long.  (strtol() returns
       // LONG_MAX or LONG_MIN when the input overflows.)
       result != long_value
       // The parsed value overflows as an Int32.
       ) {
     Message msg;
     msg << "WARNING: " << src_text
         << " is expected to be a 32-bit integer, but actually"
         << " has value " << str << ", which overflows.\n";
     printf("%s", msg.GetString().c_str());
     fflush(stdout);
     return false;
   }
   *value = result;
   return true;
 }
References string::c_str(), and Message::GetString().
Referenced by Int32FromEnvOrDie(), Int32FromGTestEnv(), and ParseInt32Flag().
ParseInt32Flag()
bool ParseInt32Flag (const char * str, const char * flag, Int32 * value)
Definition at line 5070 of file gtest.cc.
{
   // Gets the value of the flag as a string.
   const char* const value_str = ParseFlagValue(str, flag, false);
   // Aborts if the parsing failed.
   if (value_str == NULL) return false;
   // Sets *value to the value of the flag.
   return ParseInt32(Message() << "The value of flag --" << flag,
                     value_str, value);
 }
References ParseFlagValue(), and ParseInt32().
Referenced by ParseGoogleTestFlag(), and ParseGoogleTestFlagsOnlyImpl().
ParseStringFlag()
bool testing::internal::ParseStringFlag (const char * str, const char * flag, std::string * value)
Definition at line 5087 of file gtest.cc.
{
   // Gets the value of the flag as a string.
   const char* const value_str = ParseFlagValue(str, flag, false);
   // Aborts if the parsing failed.
   if (value_str == NULL) return false;
   // Sets *value to the value of the flag.
   *value = value_str;
   return true;
 }
References ParseFlagValue().
Referenced by ParseGoogleTestFlag(), and ParseGoogleTestFlagsOnlyImpl().
PortableLocaltime()
static bool testing::internal::PortableLocaltime (time_t seconds, struct tm * out) static
Definition at line 3556 of file gtest.cc.
{
 #if defined(_MSC_VER)
   return localtime_s(out, &seconds) == 0;
 #elif defined(__MINGW32__) || defined(__MINGW64__)
   // MINGW <time.h> provides neither localtime_r nor localtime_s, but uses
   // Windows' localtime(), which has a thread-local tm buffer.
   struct tm* tm_ptr = localtime(&seconds);  // NOLINT
   if (tm_ptr == NULL)
     return false;
   *out = *tm_ptr;
   return true;
 #else
   return localtime_r(&seconds, out) != NULL;
 #endif
 }
Referenced by FormatEpochTimeInMillisAsIso8601().
PrintAsCharLiteralTo()
static CharFormat testing::internal::PrintAsCharLiteralTo (Char c, ostream * os) static
Definition at line 146 of file gtest-printers.cc.
{
   switch (static_cast<wchar_t>(c)) {
     case L'\0':
       *os << "\\0";
       break;
     case L'\'':
       *os << "\\'";
       break;
     case L'\\':
       *os << "\\\\";
       break;
     case L'\a':
       *os << "\\a";
       break;
     case L'\b':
       *os << "\\b";
       break;
     case L'\f':
       *os << "\\f";
       break;
     case L'\n':
       *os << "\\n";
       break;
     case L'\r':
       *os << "\\r";
       break;
     case L'\t':
       *os << "\\t";
       break;
     case L'\v':
       *os << "\\v";
       break;
     default:
       if (IsPrintableAscii(c)) {
         *os << static_cast<char>(c);
         return kAsIs;
       } else {
         *os << "\\x" + String::FormatHexInt(static_cast<UnsignedChar>(c));
         return kHexEscape;
       }
   }
   return kSpecialEscape;
 }
References String::FormatHexInt(), IsPrintableAscii(), kAsIs, kHexEscape, and kSpecialEscape.
PrintAsStringLiteralTo() [1/2]
static CharFormat testing::internal::PrintAsStringLiteralTo (char c, ostream * os) static
Definition at line 207 of file gtest-printers.cc.
{
   return PrintAsStringLiteralTo(
       static_cast<wchar_t>(static_cast<unsigned char>(c)), os);
 }
References PrintAsStringLiteralTo().
PrintAsStringLiteralTo() [2/2]
static CharFormat testing::internal::PrintAsStringLiteralTo (wchar_t c, ostream * os) static
Definition at line 192 of file gtest-printers.cc.
{
   switch (c) {
     case L'\'':
       *os << "'";
       return kAsIs;
     case L'"':
       *os << "\\\"";
       return kSpecialEscape;
     default:
       return PrintAsCharLiteralTo<wchar_t>(c, os);
   }
 }
References kAsIs, and kSpecialEscape.
Referenced by PrintAsStringLiteralTo(), and PrintCharsAsStringTo().
PrintCharAndCodeTo()
void testing::internal::PrintCharAndCodeTo (Char c, ostream * os)
Definition at line 217 of file gtest-printers.cc.
{
   // First, print c as a literal in the most readable form we can find.
   *os << ((sizeof(c) > 1) ? "L'" : "'");
   const CharFormat format = PrintAsCharLiteralTo<UnsignedChar>(c, os);
   *os << "'";
   // To aid user debugging, we also print c's code in decimal, unless
   // it's 0 (in which case c was printed as '\\0', making the code
   // obvious).
   if (c == 0)
     return;
   *os << " (" << static_cast<int>(c);
   // For more convenience, we print c's code again in hexidecimal,
   // unless c was already printed in the form '\x##' or the code is in
   // [1, 9].
   if (format == kHexEscape || (1 <= c && c <= 9)) {
     // Do nothing.
   } else {
     *os << ", 0x" << String::FormatHexInt(static_cast<UnsignedChar>(c));
   }
   *os << ")";
 }
References String::FormatHexInt(), and kHexEscape.
PrintCharsAsStringTo()
GTEST_ATTRIBUTE_NO_SANITIZE_MEMORY_ GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_ static GTEST_ATTRIBUTE_NO_SANITIZE_THREAD_ void testing::internal::PrintCharsAsStringTo (const CharType * begin, size_t len, ostream * os) static
Definition at line 262 of file gtest-printers.cc.
{
   const char* const kQuoteBegin = sizeof(CharType) == 1 ? "\"" : "L\"";
   *os << kQuoteBegin;
   bool is_previous_hex = false;
   for (size_t index = 0; index < len; ++index) {
     const CharType cur = begin[index];
     if (is_previous_hex && IsXDigit(cur)) {
       // Previous character is of '\x..' form and this character can be
       // interpreted as another hexadecimal digit in its number. Break string to
       // disambiguate.
       *os << "\" " << kQuoteBegin;
     }
     is_previous_hex = PrintAsStringLiteralTo(cur, os) == kHexEscape;
   }
   *os << "\"";
 }
References IsXDigit(), kHexEscape, and PrintAsStringLiteralTo().
Referenced by PrintStringTo(), PrintTo(), and UniversalPrintCharArray().
PrintColorEncoded()
static void testing::internal::PrintColorEncoded (const char * str) static
Definition at line 5125 of file gtest.cc.
{
   GTestColor color = COLOR_DEFAULT;  // The current color.
   // Conceptually, we split the string into segments divided by escape
   // sequences.  Then we print one segment at a time.  At the end of
   // each iteration, the str pointer advances to the beginning of the
   // next segment.
   for (;;) {
     const char* p = strchr(str, '@');
     if (p == NULL) {
       ColoredPrintf(color, "%s", str);
       return;
     }
     ColoredPrintf(color, "%s", std::string(str, p).c_str());
     const char ch = p[1];
     str = p + 2;
     if (ch == '@') {
       ColoredPrintf(color, "@");
     } else if (ch == 'D') {
       color = COLOR_DEFAULT;
     } else if (ch == 'R') {
       color = COLOR_RED;
     } else if (ch == 'G') {
       color = COLOR_GREEN;
     } else if (ch == 'Y') {
       color = COLOR_YELLOW;
     } else {
       --str;
     }
   }
 }
References COLOR_DEFAULT, COLOR_GREEN, COLOR_RED, COLOR_YELLOW, and ColoredPrintf().
Referenced by ParseGoogleTestFlagsOnlyImpl().
PrintFullTestCommentIfPresent()
void testing::internal::PrintFullTestCommentIfPresent (const TestInfo & test_info)
Definition at line 3009 of file gtest.cc.
{
   const char* const type_param = test_info.type_param();
   const char* const value_param = test_info.value_param();
   if (type_param != NULL || value_param != NULL) {
     printf(", where ");
     if (type_param != NULL) {
       printf("%s = %s", kTypeParamLabel, type_param);
       if (value_param != NULL)
         printf(" and ");
     }
     if (value_param != NULL) {
       printf("%s = %s", kValueParamLabel, value_param);
     }
   }
 }
References kTypeParamLabel, kValueParamLabel, TestInfo::type_param, and TestInfo::value_param.
Referenced by PrettyUnitTestResultPrinter::OnTestEnd(), and PrettyUnitTestResultPrinter::PrintFailedTests().
PrintOnOneLine()
static void testing::internal::PrintOnOneLine (const char * str, int max_length) static
Definition at line 4846 of file gtest.cc.
{
   if (str != NULL) {
     for (int i = 0; *str != '\0'; ++str) {
       if (i >= max_length) {
         printf("...");
         break;
       }
       if (*str == '\n') {
         printf("\\n");
         i += 2;
       } else {
         printf("%c", *str);
         ++i;
       }
     }
   }
 }
Referenced by UnitTestImpl::ListTestsMatchingFilter().
PrintRawArrayTo()
void testing::internal::PrintRawArrayTo (const T a[], size_t count, ::std::ostream * os)
Definition at line 548 of file gtest-printers.h.
{
   UniversalPrint(a[0], os);
   for (size_t i = 1; i != count; i++) {
     *os << ", ";
     UniversalPrint(a[i], os);
   }
 }
References UniversalPrint().
Referenced by UniversalPrintArray().
PrintStringTo() [1/2]
GTEST_API_ void testing::internal::PrintStringTo (const ::std::string & s, ::std::ostream * os)
PrintStringTo() [2/2]
void testing::internal::PrintStringTo (const ::std::string & s, ostream * os)
Definition at line 354 of file gtest-printers.cc.
{
   PrintCharsAsStringTo(s.data(), s.size(), os);
 }
References PrintCharsAsStringTo().
Referenced by PrintTo().
PrintTestPartResult()
static void testing::internal::PrintTestPartResult (const TestPartResult & test_part_result) static
Definition at line 2860 of file gtest.cc.
{
   const std::string& result =
       PrintTestPartResultToString(test_part_result);
   printf("%s\n", result.c_str());
   fflush(stdout);
   // If the test program runs in Visual Studio or a debugger, the
   // following statements add the test part result message to the Output
   // window such that the user can double-click on it to jump to the
   // corresponding source code location; otherwise they do nothing.
 #if GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_MOBILE
   // We don't call OutputDebugString*() on Windows Mobile, as printing
   // to stdout is done by OutputDebugString() there already - we don't
   // want the same message printed twice.
   ::OutputDebugStringA(result.c_str());
   ::OutputDebugStringA("\n");
 #endif
 }
References string::c_str(), and PrintTestPartResultToString().
Referenced by PrettyUnitTestResultPrinter::OnTestPartResult().
PrintTestPartResultToString()
static std::string testing::internal::PrintTestPartResultToString (const TestPartResult & test_part_result) static
Definition at line 2850 of file gtest.cc.
{
   return (Message()
           << internal::FormatFileLocation(test_part_result.file_name(),
                                           test_part_result.line_number())
           << " " << TestPartResultTypeToString(test_part_result.type())
           << test_part_result.message()).GetString();
 }
References TestPartResult::file_name(), FormatFileLocation(), TestPartResult::line_number(), TestPartResult::message(), testing::TestPartResultTypeToString(), and TestPartResult::type().
Referenced by PrintTestPartResult().
PrintTo() [1/19]
void testing::internal::PrintTo (bool x, ::std::ostream * os)
Definition at line 495 of file gtest-printers.h.
{
   *os << (x ? "true" : "false");
 }
PrintTo() [2/19]
void testing::internal::PrintTo (char * s, ::std::ostream * os)
Definition at line 510 of file gtest-printers.h.
{
   PrintTo(ImplicitCast_<const char*>(s), os);
 }
References PrintTo().
PrintTo() [3/19]
void testing::internal::PrintTo (char c, ::std::ostream * os)
Definition at line 487 of file gtest-printers.h.
{
   // When printing a plain char, we always treat it as unsigned.  This
   // way, the output won't be affected by whether the compiler thinks
   // char is signed or not.
   PrintTo(static_cast<unsigned char>(c), os);
 }
References PrintTo().
PrintTo() [4/19]
void testing::internal::PrintTo (const ::std::pair< T1, T2 > & value, ::std::ostream * os)
Definition at line 676 of file gtest-printers.h.
{
   *os << '(';
   // We cannot use UniversalPrint(value.first, os) here, as T1 may be
   // a reference type.  The same for printing value.second.
   UniversalPrinter<T1>::Print(value.first, os);
   *os << ", ";
   UniversalPrinter<T2>::Print(value.second, os);
   *os << ')';
 }
PrintTo() [5/19]
void testing::internal::PrintTo (const ::std::string & s, ::std::ostream * os)
Definition at line 565 of file gtest-printers.h.
{
   PrintStringTo(s, os);
 }
References PrintStringTo().
PrintTo() [6/19]
GTEST_API_ void testing::internal::PrintTo (const char * s, ::std::ostream * os)
PrintTo() [7/19]
void testing::internal::PrintTo (const char * s, ostream * os)
Definition at line 320 of file gtest-printers.cc.
{
   if (s == NULL) {
     *os << "NULL";
   } else {
     *os << ImplicitCast_<const void*>(s) << " pointing to ";
     PrintCharsAsStringTo(s, strlen(s), os);
   }
 }
References PrintCharsAsStringTo().
PrintTo() [8/19]
void testing::internal::PrintTo (const signed char * s, ::std::ostream * os)
Definition at line 516 of file gtest-printers.h.
{
   PrintTo(ImplicitCast_<const void*>(s), os);
 }
References PrintTo().
PrintTo() [9/19]
void testing::internal::PrintTo (const T & value, ::std::ostream * os)
Definition at line 454 of file gtest-printers.h.
{
   // DefaultPrintTo() is overloaded.  The type of its first two
   // arguments determine which version will be picked.  If T is an
   // STL-style container, the version for container will be called; if
   // T is a pointer, the pointer version will be called; otherwise the
   // generic version will be called.
   //
   // Note that we check for container types here, prior to we check
   // for protocol message types in our operator<<.  The rationale is:
   //
   // For protocol messages, we want to give people a chance to
   // override Google Mock's format by defining a PrintTo() or
   // operator<<.  For STL containers, other formats can be
   // incompatible with Google Mock's format for the container
   // elements; therefore we check for container types here to ensure
   // that our format is used.
   //
   // The second argument of DefaultPrintTo() is needed to bypass a bug
   // in Symbian's C++ compiler that prevents it from picking the right
   // overload between:
   //
   //   PrintTo(const T& x, ...);
   //   PrintTo(T* x, ...);
   DefaultPrintTo(IsContainerTest<T>(0), is_pointer<T>(), value, os);
 }
References DefaultPrintTo().
PrintTo() [10/19]
void testing::internal::PrintTo (const unsigned char * s, ::std::ostream * os)
Definition at line 522 of file gtest-printers.h.
{
   PrintTo(ImplicitCast_<const void*>(s), os);
 }
References PrintTo().
PrintTo() [11/19]
GTEST_API_ void testing::internal::PrintTo (const wchar_t * s, ::std::ostream * os)
PrintTo() [12/19]
void testing::internal::PrintTo (const wchar_t * s, ostream * os)
Definition at line 337 of file gtest-printers.cc.
{
   if (s == NULL) {
     *os << "NULL";
   } else {
     *os << ImplicitCast_<const void*>(s) << " pointing to ";
     PrintCharsAsStringTo(s, std::wcslen(s), os);
   }
 }
References PrintCharsAsStringTo(), and std::wcslen().
PrintTo() [13/19]
void testing::internal::PrintTo (signed char * s, ::std::ostream * os)
Definition at line 519 of file gtest-printers.h.
{
   PrintTo(ImplicitCast_<const void*>(s), os);
 }
References PrintTo().
PrintTo() [14/19]
GTEST_API_ void PrintTo (signed char c, ::std::ostream * os)
Definition at line 244 of file gtest-printers.cc.
{
   PrintCharAndCodeTo<unsigned char>(c, os);
 }
PrintTo() [15/19]
void testing::internal::PrintTo (unsigned char * s, ::std::ostream * os)
Definition at line 525 of file gtest-printers.h.
{
   PrintTo(ImplicitCast_<const void*>(s), os);
 }
References PrintTo().
PrintTo() [16/19]
GTEST_API_ void PrintTo (unsigned char c, ::std::ostream * os)
Definition at line 241 of file gtest-printers.cc.
{
   PrintCharAndCodeTo<unsigned char>(c, os);
 }
Referenced by PrintTo().
PrintTo() [17/19]
void testing::internal::PrintTo (wchar_t * s, ::std::ostream * os)
Definition at line 537 of file gtest-printers.h.
{
   PrintTo(ImplicitCast_<const wchar_t*>(s), os);
 }
References PrintTo().
PrintTo() [18/19]
GTEST_API_ void testing::internal::PrintTo (wchar_t wc, ::std::ostream * os)
PrintTo() [19/19]
void testing::internal::PrintTo (wchar_t wc, ostream * os)
Definition at line 250 of file gtest-printers.cc.
{
   PrintCharAndCodeTo<wchar_t>(wc, os);
 }
ReadEntireFile()
GTEST_API_ std::string ReadEntireFile (FILE * file)
Definition at line 1081 of file gtest-port.cc.
{
   const size_t file_size = GetFileSize(file);
   char* const buffer = new char[file_size];
   size_t bytes_last_read = 0;  // # of bytes read in the last fread()
   size_t bytes_read = 0;       // # of bytes read so far
   fseek(file, 0, SEEK_SET);
   // Keeps reading the file until we cannot read further or the
   // pre-determined file size is reached.
   do {
     bytes_last_read = fread(buffer+bytes_read, 1, file_size-bytes_read, file);
     bytes_read += bytes_last_read;
   } while (bytes_last_read > 0 && bytes_read < file_size);
   const std::string content(buffer, bytes_read);
   delete[] buffer;
   return content;
 }
References GetFileSize().
Referenced by GTEST_DISABLE_MSC_WARNINGS_PUSH_().
ReportFailureInUnknownLocation()
void ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string & message)
Definition at line 2250 of file gtest.cc.
{
   // This function is a friend of UnitTest and as such has access to
   // AddTestPartResult.
   UnitTest::GetInstance()->AddTestPartResult(
       result_type,
       NULL,  // No info about the source file where the exception occurred.
       -1,    // We have no info on which line caused the exception.
       message,
       "");   // No stack trace, either.
 }
References UnitTest::AddTestPartResult(), and UnitTest::GetInstance().
Referenced by HandleExceptionsInMethodIfSupported(), and HandleSehExceptionsInMethodIfSupported().
SetUpEnvironment()
static void testing::internal::SetUpEnvironment (Environment * env) static
Definition at line 4539 of file gtest.cc.
 { env->SetUp(); }
References Environment::SetUp().
Referenced by UnitTestImpl::RunAllTests().
ShouldRunTestCase()
static bool testing::internal::ShouldRunTestCase (const TestCase * test_case) static
Definition at line 356 of file gtest.cc.
{
   return test_case->should_run();
 }
References TestCase::should_run().
Referenced by UnitTestImpl::test_case_to_run_count().
ShouldRunTestOnShard()
bool ShouldRunTestOnShard (int total_shards, int shard_index, int test_id)
Definition at line 4778 of file gtest.cc.
{
   return (test_id % total_shards) == shard_index;
 }
Referenced by UnitTestImpl::FilterTests().
ShouldShard()
bool ShouldShard (const char * total_shards_str, const char * shard_index_str, bool in_subprocess_for_death_test)
Definition at line 4715 of file gtest.cc.
{
   if (in_subprocess_for_death_test) {
     return false;
   }
   const Int32 total_shards = Int32FromEnvOrDie(total_shards_env, -1);
   const Int32 shard_index = Int32FromEnvOrDie(shard_index_env, -1);
   if (total_shards == -1 && shard_index == -1) {
     return false;
   } else if (total_shards == -1 && shard_index != -1) {
     const Message msg = Message()
       << "Invalid environment variables: you have "
       << kTestShardIndex << " = " << shard_index
       << ", but have left " << kTestTotalShards << " unset.\n";
     ColoredPrintf(COLOR_RED, msg.GetString().c_str());
     fflush(stdout);
     exit(EXIT_FAILURE);
   } else if (total_shards != -1 && shard_index == -1) {
     const Message msg = Message()
       << "Invalid environment variables: you have "
       << kTestTotalShards << " = " << total_shards
       << ", but have left " << kTestShardIndex << " unset.\n";
     ColoredPrintf(COLOR_RED, msg.GetString().c_str());
     fflush(stdout);
     exit(EXIT_FAILURE);
   } else if (shard_index < 0 || shard_index >= total_shards) {
     const Message msg = Message()
       << "Invalid environment variables: we require 0 <= "
       << kTestShardIndex << " < " << kTestTotalShards
       << ", but you have " << kTestShardIndex << "=" << shard_index
       << ", " << kTestTotalShards << "=" << total_shards << ".\n";
     ColoredPrintf(COLOR_RED, msg.GetString().c_str());
     fflush(stdout);
     exit(EXIT_FAILURE);
   }
   return total_shards > 1;
 }
References string::c_str(), COLOR_RED, ColoredPrintf(), Message::GetString(), Int32FromEnvOrDie(), testing::kTestShardIndex, and testing::kTestTotalShards.
Referenced by PrettyUnitTestResultPrinter::OnTestIterationStart(), and UnitTestImpl::RunAllTests().
ShouldUseColor()
bool ShouldUseColor (bool stdout_is_tty)
Definition at line 2916 of file gtest.cc.
{
   const char* const gtest_color = GTEST_FLAG(color).c_str();
   if (String::CaseInsensitiveCStringEquals(gtest_color, "auto")) {
 #if GTEST_OS_WINDOWS
     // On Windows the TERM variable is usually not set, but the
     // console there does support colors.
     return stdout_is_tty;
 #else
     // On non-Windows platforms, we rely on the TERM variable.
     const char* const term = posix::GetEnv("TERM");
     const bool term_supports_color =
         String::CStringEquals(term, "xterm") ||
         String::CStringEquals(term, "xterm-color") ||
         String::CStringEquals(term, "xterm-256color") ||
         String::CStringEquals(term, "screen") ||
         String::CStringEquals(term, "screen-256color") ||
         String::CStringEquals(term, "tmux") ||
         String::CStringEquals(term, "tmux-256color") ||
         String::CStringEquals(term, "rxvt-unicode") ||
         String::CStringEquals(term, "rxvt-unicode-256color") ||
         String::CStringEquals(term, "linux") ||
         String::CStringEquals(term, "cygwin");
     return stdout_is_tty && term_supports_color;
 #endif  // GTEST_OS_WINDOWS
   }
   return String::CaseInsensitiveCStringEquals(gtest_color, "yes") ||
       String::CaseInsensitiveCStringEquals(gtest_color, "true") ||
       String::CaseInsensitiveCStringEquals(gtest_color, "t") ||
       String::CStringEquals(gtest_color, "1");
   // We take "yes", "true", "t", and "1" as meaning "yes".  If the
   // value is neither one of these nor "auto", we treat it as "no" to
   // be conservative.
 }
References String::CaseInsensitiveCStringEquals(), String::CStringEquals(), testing::internal::posix::GetEnv(), and GTEST_FLAG.
Referenced by ColoredPrintf().
Shuffle()
void testing::internal::Shuffle (internal::Random * random, std::vector< E > * v)
Definition at line 333 of file gtest-internal-inl.h.
{
   ShuffleRange(random, 0, static_cast<int>(v->size()), v);
 }
References ShuffleRange(), and vector< T >::size().
Referenced by TestCase::ShuffleTests().
ShuffleRange()
void testing::internal::ShuffleRange (internal::Random * random, int begin, int end, std::vector< E > * v)
Definition at line 312 of file gtest-internal-inl.h.
{
   const int size = static_cast<int>(v->size());
   GTEST_CHECK_(0 <= begin && begin <= size)
       << "Invalid shuffle range start " << begin << ": must be in range [0, "
       << size << "].";
   GTEST_CHECK_(begin <= end && end <= size)
       << "Invalid shuffle range finish " << end << ": must be in range ["
       << begin << ", " << size << "].";
   // Fisher-Yates shuffle, from
   // http://en.wikipedia.org/wiki/Fisher-Yates_shuffle
   for (int range_width = end - begin; range_width >= 2; range_width--) {
     const int last_in_range = begin + range_width - 1;
     const int selected = begin + random->Generate(range_width);
     std::swap((*v)[selected], (*v)[last_in_range]);
   }
 }
References Random::Generate(), GTEST_CHECK_, vector< T >::size(), and std::swap().
Referenced by Shuffle(), and UnitTestImpl::ShuffleTests().
SkipPrefix()
GTEST_API_ bool SkipPrefix (const char * prefix, const char ** pstr)
Definition at line 5001 of file gtest.cc.
{
   const size_t prefix_len = strlen(prefix);
   if (strncmp(*pstr, prefix, prefix_len) == 0) {
     *pstr += prefix_len;
     return true;
   }
   return false;
 }
Referenced by HasGoogleTestFlagPrefix().
SplitString()
void testing::internal::SplitString (const ::std::string & str, char delimiter, ::std::vector< ::std::string > * dest)
Definition at line 922 of file gtest.cc.
{
   ::std::vector< ::std::string> parsed;
   ::std::string::size_type pos = 0;
   while (::testing::internal::AlwaysTrue()) {
     const ::std::string::size_type colon = str.find(delimiter, pos);
     if (colon == ::std::string::npos) {
       parsed.push_back(str.substr(pos));
       break;
     } else {
       parsed.push_back(str.substr(pos, colon - pos));
       pos = colon + 1;
     }
   }
   dest->swap(parsed);
 }
References AlwaysTrue(), vector< T >::push_back(), and vector< T >::swap().
StreamableToString()
std::string testing::internal::StreamableToString (const T & streamable)
Definition at line 243 of file gtest-message.h.
{
   return (Message() << streamable).GetString();
 }
Referenced by FormatCompilerIndependentFileLocation(), testing::FormatCountableNoun(), FormatEpochTimeInMillisAsIso8601(), FormatFileLocation(), InitGoogleTestImpl(), FilePath::MakeFileName(), PrettyUnitTestResultPrinter::OnTestCaseEnd(), PrettyUnitTestResultPrinter::OnTestEnd(), PrettyUnitTestResultPrinter::OnTestIterationEnd(), ParseGoogleTestFlagsOnlyImpl(), XmlUnitTestResultPrinter::PrintXmlTestCase(), and XmlUnitTestResultPrinter::PrintXmlUnitTest().
StringFromGTestEnv()
std::string StringFromGTestEnv (const char * flag, const char * default_value)
Definition at line 1229 of file gtest-port.cc.
{
 #if defined(GTEST_GET_STRING_FROM_ENV_)
   return GTEST_GET_STRING_FROM_ENV_(flag, default_value);
 #endif  // defined(GTEST_GET_STRING_FROM_ENV_)
   const std::string env_var = FlagToEnvVar(flag);
   const char* value = posix::GetEnv(env_var.c_str());
   if (value != NULL) {
     return value;
   }
   // As a special case for the 'output' flag, if GTEST_OUTPUT is not
   // set, we look for XML_OUTPUT_FILE, which is set by the Bazel build
   // system.  The value of XML_OUTPUT_FILE is a filename without the
   // "xml:" prefix of GTEST_OUTPUT.
   //
   // The net priority order after flag processing is thus:
   //   --gtest_output command line flag
   //   GTEST_OUTPUT environment variable
   //   XML_OUTPUT_FILE environment variable
   //   'default_value'
   if (strcmp(flag, "output") == 0) {
     value = posix::GetEnv("XML_OUTPUT_FILE");
     if (value != NULL) {
       return std::string("xml:") + value;
     }
   }
   return default_value;
 }
References string::c_str(), FlagToEnvVar(), and testing::internal::posix::GetEnv().
StringStreamToString()
GTEST_API_ std::string StringStreamToString (::std::stringstream * ss)
Definition at line 1982 of file gtest.cc.
{
   const ::std::string& str = ss->str();
   const char* const start = str.c_str();
   const char* const end = start + str.length();
   std::string result;
   result.reserve(2 * (end - start));
   for (const char* ch = start; ch != end; ++ch) {
     if (*ch == '\0') {
       result += "\\0";  // Replaces NUL with "\\0";
     } else {
       result += *ch;
     }
   }
   return result;
 }
References string::reserve(), and stringstream::str().
Referenced by CmpHelperFloatingPointEQ(), FloatingPointLE(), Message::GetString(), XmlUnitTestResultPrinter::OnTestIterationEnd(), and WideStringToUtf8().
StripTrailingSpaces()
std::string testing::internal::StripTrailingSpaces (std::string str)
Definition at line 2284 of file gtest-port.h.
{
   std::string::iterator it = str.end();
   while (it != str.begin() && IsSpace(*--it))
     it = str.erase(it);
   return str;
 }
References string::begin(), string::end(), string::erase(), and IsSpace().
SumOverTestCaseList()
static int testing::internal::SumOverTestCaseList (const std::vector< TestCase * > & case_list, int(TestCase::*)() const method) static
Definition at line 335 of file gtest.cc.
{
   int sum = 0;
   for (size_t i = 0; i < case_list.size(); i++) {
     sum += (case_list[i]->*method)();
   }
   return sum;
 }
References vector< T >::size().
Referenced by UnitTestImpl::disabled_test_count(), UnitTestImpl::failed_test_count(), UnitTestImpl::reportable_disabled_test_count(), UnitTestImpl::reportable_test_count(), UnitTestImpl::successful_test_count(), UnitTestImpl::test_to_run_count(), and UnitTestImpl::total_test_count().
TearDownEnvironment()
static void testing::internal::TearDownEnvironment (Environment * env) static
Definition at line 4540 of file gtest.cc.
 { env->TearDown(); }
References Environment::TearDown().
Referenced by UnitTestImpl::RunAllTests().
TempDir()
GTEST_API_ std::string testing::internal::TempDir ()
TestCaseFailed()
static bool testing::internal::TestCaseFailed (const TestCase * test_case) static
Definition at line 350 of file gtest.cc.
{
   return test_case->should_run() && test_case->Failed();
 }
References TestCase::Failed(), and TestCase::should_run().
Referenced by UnitTestImpl::failed_test_case_count().
TestCasePassed()
static bool testing::internal::TestCasePassed (const TestCase * test_case) static
Definition at line 345 of file gtest.cc.
{
   return test_case->should_run() && test_case->Passed();
 }
References TestCase::Passed(), and TestCase::should_run().
Referenced by UnitTestImpl::successful_test_case_count().
ToLower()
char testing::internal::ToLower (char ch)
Definition at line 2277 of file gtest-port.h.
{
   return static_cast<char>(tolower(static_cast<unsigned char>(ch)));
 }
ToUpper()
char testing::internal::ToUpper (char ch)
Definition at line 2280 of file gtest-port.h.
{
   return static_cast<char>(toupper(static_cast<unsigned char>(ch)));
 }
Referenced by FlagToEnvVar().
UniversalPrint()
void UniversalPrint (const T & value, ::std::ostream * os)
Definition at line 852 of file gtest-printers.h.
{
   // A workarond for the bug in VC++ 7.1 that prevents us from instantiating
   // UniversalPrinter with T directly.
   typedef T T1;
   UniversalPrinter<T1>::Print(value, os);
 }
Referenced by DefaultPrintTo(), UniversalTersePrinter< const char * >::Print(), UniversalTersePrinter< T >::Print(), UniversalTersePrinter< T & >::Print(), and PrintRawArrayTo().
UniversalPrintArray() [1/5]
GTEST_API_ void testing::internal::UniversalPrintArray (const char * begin, size_t len, ::std::ostream * os)
UniversalPrintArray() [2/5]
void testing::internal::UniversalPrintArray (const char * begin, size_t len, ostream * os)
Definition at line 309 of file gtest-printers.cc.
{
   UniversalPrintCharArray(begin, len, os);
 }
References UniversalPrintCharArray().
Referenced by UniversalPrinter< T[N]>::Print().
UniversalPrintArray() [3/5]
void testing::internal::UniversalPrintArray (const T * begin, size_t len, ::std::ostream * os)
Definition at line 716 of file gtest-printers.h.
{
   if (len == 0) {
     *os << "{}";
   } else {
     *os << "{ ";
     const size_t kThreshold = 18;
     const size_t kChunkSize = 8;
     // If the array has more than kThreshold elements, we'll have to
     // omit some details by printing only the first and the last
     // kChunkSize elements.
     // TODO(wan@google.com): let the user control the threshold using a flag.
     if (len <= kThreshold) {
       PrintRawArrayTo(begin, len, os);
     } else {
       PrintRawArrayTo(begin, kChunkSize, os);
       *os << ", ..., ";
       PrintRawArrayTo(begin + len - kChunkSize, kChunkSize, os);
     }
     *os << " }";
   }
 }
References PrintRawArrayTo().
UniversalPrintArray() [4/5]
GTEST_API_ void testing::internal::UniversalPrintArray (const wchar_t * begin, size_t len, ::std::ostream * os)
UniversalPrintArray() [5/5]
void testing::internal::UniversalPrintArray (const wchar_t * begin, size_t len, ostream * os)
Definition at line 315 of file gtest-printers.cc.
{
   UniversalPrintCharArray(begin, len, os);
 }
References UniversalPrintCharArray().
UniversalPrintCharArray()
GTEST_ATTRIBUTE_NO_SANITIZE_MEMORY_ GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_ static GTEST_ATTRIBUTE_NO_SANITIZE_THREAD_ void testing::internal::UniversalPrintCharArray (const CharType * begin, size_t len, ostream * os) static
Definition at line 286 of file gtest-printers.cc.
{
   // The code
   //   const char kFoo[] = "foo";
   // generates an array of 4, not 3, elements, with the last one being '\0'.
   //
   // Therefore when printing a char array, we don't print the last element if
   // it's '\0', such that the output matches the string literal as it's
   // written in the source code.
   if (len > 0 && begin[len - 1] == '\0') {
     PrintCharsAsStringTo(begin, len - 1, os);
     return;
   }
   // If, however, the last element in the array is not '\0', e.g.
   //    const char kFoo[] = { 'f', 'o', 'o' };
   // we must print the entire array.  We also print a message to indicate
   // that the array is not NUL-terminated.
   PrintCharsAsStringTo(begin, len, os);
   *os << " (no terminating NUL)";
 }
References PrintCharsAsStringTo().
Referenced by UniversalPrintArray().
UniversalTersePrint()
void testing::internal::UniversalTersePrint (const T & value, ::std::ostream * os)
Definition at line 843 of file gtest-printers.h.
{
   UniversalTersePrinter<T>::Print(value, os);
 }
References UniversalTersePrinter< T >::Print().
WideStringToUtf8()
std::string WideStringToUtf8 (const wchar_t * str, int num_chars)
Definition at line 1823 of file gtest.cc.
{
   if (num_chars == -1)
     num_chars = static_cast<int>(wcslen(str));
   ::std::stringstream stream;
   for (int i = 0; i < num_chars; ++i) {
     UInt32 unicode_code_point;
     if (str[i] == L'\0') {
       break;
     } else if (i + 1 < num_chars && IsUtf16SurrogatePair(str[i], str[i + 1])) {
       unicode_code_point = CreateCodePointFromUtf16SurrogatePair(str[i],
                                                                  str[i + 1]);
       i++;
     } else {
       unicode_code_point = static_cast<UInt32>(str[i]);
     }
     stream << CodePointToUtf8(unicode_code_point);
   }
   return StringStreamToString(&stream);
 }
References CodePointToUtf8(), CreateCodePointFromUtf16SurrogatePair(), IsUtf16SurrogatePair(), and StringStreamToString().
Referenced by String::ShowWideCString().
WriteToShardStatusFileIfNeeded()
void WriteToShardStatusFileIfNeeded ()
Definition at line 4693 of file gtest.cc.
{
   const char* const test_shard_file = posix::GetEnv(kTestShardStatusFile);
   if (test_shard_file != NULL) {
     FILE* const file = posix::FOpen(test_shard_file, "w");
     if (file == NULL) {
       ColoredPrintf(COLOR_RED,
                     "Could not write to the test shard status file \"%s\" "
                     "specified by the %s environment variable.\n",
                     test_shard_file, kTestShardStatusFile);
       fflush(stdout);
       exit(EXIT_FAILURE);
     }
     fclose(file);
   }
 }
References COLOR_RED, ColoredPrintf(), testing::internal::posix::FOpen(), testing::internal::posix::GetEnv(), and testing::kTestShardStatusFile.
Referenced by UnitTestImpl::RunAllTests().
Constant Documentation
g_argvs
::std::vector<testing::internal::string> g_argvs
Definition at line 387 of file gtest.cc.
Referenced by GetArgvs(), and InitGoogleTestImpl().
g_help_flag
bool g_help_flag = false
Definition at line 188 of file gtest.cc.
Referenced by ParseGoogleTestFlagsOnlyImpl(), and UnitTestImpl::RunAllTests().
GTEST_ATTRIBUTE_UNUSED_
class GTEST_API_ testing::internal::ScopedTrace GTEST_ATTRIBUTE_UNUSED_
kAlsoRunDisabledTestsFlag
const char kAlsoRunDisabledTestsFlag[] = "also_run_disabled_tests"
Definition at line 89 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kBreakOnFailureFlag
const char kBreakOnFailureFlag[] = "break_on_failure"
Definition at line 90 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kCatchExceptionsFlag
const char kCatchExceptionsFlag[] = "catch_exceptions"
Definition at line 91 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kColorEncodedHelpMessage
const char kColorEncodedHelpMessage[] static
Definition at line 5159 of file gtest.cc.
Referenced by ParseGoogleTestFlagsOnlyImpl().
kColorFlag
const char kColorFlag[] = "color"
Definition at line 92 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kCurrentDirectoryString
const char kCurrentDirectoryString[] = "./"
Definition at line 86 of file gtest-filepath.cc.
Referenced by FilePath::GetCurrentDir(), and FilePath::RemoveFileName().
kDeathTestStyleFlag
const char kDeathTestStyleFlag[] = "death_test_style"
Definition at line 50 of file gtest-death-test-internal.h.
Referenced by ParseGoogleTestFlag().
kDeathTestUseFork
const char kDeathTestUseFork[] = "death_test_use_fork"
Definition at line 51 of file gtest-death-test-internal.h.
Referenced by ParseGoogleTestFlag().
kFilterFlag
const char kFilterFlag[] = "filter"
Definition at line 93 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kFlagfileFlag
const char kFlagfileFlag[] = "flagfile"
Definition at line 103 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlagsOnlyImpl().
kInternalRunDeathTestFlag
const char kInternalRunDeathTestFlag[] = "internal_run_death_test"
Definition at line 52 of file gtest-death-test-internal.h.
Referenced by ParseGoogleTestFlag().
kListTestsFlag
const char kListTestsFlag[] = "list_tests"
Definition at line 94 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kMaxBiggestInt
const BiggestInt kMaxBiggestInt
Initial value:
=
    ~(static_cast<BiggestInt>(1) << (8*sizeof(BiggestInt) - 1))
Definition at line 2439 of file gtest-port.h.
kMaxCodePoint1
const UInt32 kMaxCodePoint1 = (static_cast<UInt32>(1) << 7) - 1
Definition at line 1733 of file gtest.cc.
Referenced by CodePointToUtf8().
kMaxCodePoint2
const UInt32 kMaxCodePoint2 = (static_cast<UInt32>(1) << (5 + 6)) - 1
Definition at line 1736 of file gtest.cc.
Referenced by CodePointToUtf8().
kMaxCodePoint3
const UInt32 kMaxCodePoint3 = (static_cast<UInt32>(1) << (4 + 2*6)) - 1
Definition at line 1739 of file gtest.cc.
Referenced by CodePointToUtf8().
kMaxCodePoint4
const UInt32 kMaxCodePoint4 = (static_cast<UInt32>(1) << (3 + 3*6)) - 1
Definition at line 1742 of file gtest.cc.
Referenced by CodePointToUtf8().
kMaxRandomSeed
const int kMaxRandomSeed = 99999
Definition at line 106 of file gtest-internal-inl.h.
Referenced by GetNextRandomSeed(), and GetRandomSeedFromFlag().
kOutputFlag
const char kOutputFlag[] = "output"
Definition at line 95 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kPathSeparator
const char kPathSeparator = '/'
Definition at line 85 of file gtest-filepath.cc.
Referenced by FilePath::ConcatPaths(), FilePath::FindLastPathSeparator(), IsPathSeparator(), and FilePath::Normalize().
kPrintTimeFlag
const char kPrintTimeFlag[] = "print_time"
Definition at line 96 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kRandomSeedFlag
const char kRandomSeedFlag[] = "random_seed"
Definition at line 97 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kRepeatFlag
const char kRepeatFlag[] = "repeat"
Definition at line 98 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kShuffleFlag
const char kShuffleFlag[] = "shuffle"
Definition at line 99 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kStackTraceDepthFlag
const char kStackTraceDepthFlag[] = "stack_trace_depth"
Definition at line 100 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kStackTraceMarker
GTEST_API_ const char kStackTraceMarker = "\nStack trace:\n"
Definition at line 184 of file gtest.cc.
Referenced by UnitTest::AddTestPartResult(), and TestPartResult::ExtractSummary().
kStdErrFileno
const int kStdErrFileno = STDERR_FILENO
Definition at line 89 of file gtest-port.cc.
kStdOutFileno
const int kStdOutFileno = STDOUT_FILENO
Definition at line 88 of file gtest-port.cc.
kStreamResultToFlag
const char kStreamResultToFlag[] = "stream_result_to"
Definition at line 101 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kTestTypeIdInGoogleTest
const TypeId kTestTypeIdInGoogleTest = GetTestTypeId() extern
Definition at line 626 of file gtest.cc.
kThrowOnFailureFlag
const char kThrowOnFailureFlag[] = "throw_on_failure"
Definition at line 102 of file gtest-internal-inl.h.
Referenced by ParseGoogleTestFlag().
kTypeParamLabel
const char kTypeParamLabel[] = "TypeParam" static
Definition at line 3006 of file gtest.cc.
Referenced by UnitTestImpl::ListTestsMatchingFilter(), PrettyUnitTestResultPrinter::OnTestCaseStart(), and PrintFullTestCommentIfPresent().
kUnknownFile
const char kUnknownFile[] = "unknown file"
Definition at line 876 of file gtest-port.cc.
Referenced by FormatCompilerIndependentFileLocation(), and FormatFileLocation().
kValueParamLabel
const char kValueParamLabel[] = "GetParam()" static
Definition at line 3007 of file gtest.cc.
Referenced by UnitTestImpl::ListTestsMatchingFilter(), and PrintFullTestCommentIfPresent().