Common Alogrithm: testing::internal::CodePointToUtf8
CodePointToUtf8()
std::string CodePointToUtf8 (UInt32 code_point)
{
   if (code_point > kMaxCodePoint4) {
     return "(Invalid Unicode 0x" + String::FormatHexInt(code_point) + ")";
   }
   char str[5];  // Big enough for the largest valid code point.
   if (code_point <= kMaxCodePoint1) {
     str[1] = '\0';
     str[0] = static_cast<char>(code_point);                          // 0xxxxxxx
   } else if (code_point <= kMaxCodePoint2) {
     str[2] = '\0';
     str[1] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[0] = static_cast<char>(0xC0 | code_point);                   // 110xxxxx
   } else if (code_point <= kMaxCodePoint3) {
     str[3] = '\0';
     str[2] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[1] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[0] = static_cast<char>(0xE0 | code_point);                   // 1110xxxx
   } else {  // code_point <= kMaxCodePoint4
     str[4] = '\0';
     str[3] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[2] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[1] = static_cast<char>(0x80 | ChopLowBits(&code_point, 6));  // 10xxxxxx
     str[0] = static_cast<char>(0xF0 | code_point);                   // 11110xxx
   }
   return str;
 }
References testing::internal::ChopLowBits(), String::FormatHexInt(), testing::internal::kMaxCodePoint1, testing::internal::kMaxCodePoint2, testing::internal::kMaxCodePoint3, and testing::internal::kMaxCodePoint4.
Referenced by testing::internal::WideStringToUtf8().