Common Alogrithm: testing::internal::FlagToEnvVar
FlagToEnvVar()
static std::string testing::internal::FlagToEnvVar (const char * flag) static
{
   const std::string full_flag =
       (Message() << GTEST_FLAG_PREFIX_ << flag).GetString();
   Message env_var;
   for (size_t i = 0; i != full_flag.length(); i++) {
     env_var << ToUpper(full_flag.c_str()[i]);
   }
   return env_var.GetString();
 }
References string::c_str(), Message::GetString(), GTEST_FLAG_PREFIX_, string::length(), and testing::internal::ToUpper().
Referenced by testing::internal::BoolFromGTestEnv(), testing::internal::Int32FromGTestEnv(), and testing::internal::StringFromGTestEnv().