Common Alogrithm: testing::internal::StringStreamToString
StringStreamToString()
GTEST_API_ std::string StringStreamToString (::std::stringstream * ss)
{
   const ::std::string& str = ss->str();
   const char* const start = str.c_str();
   const char* const end = start + str.length();
   std::string result;
   result.reserve(2 * (end - start));
   for (const char* ch = start; ch != end; ++ch) {
     if (*ch == '\0') {
       result += "\\0";  // Replaces NUL with "\\0";
     } else {
       result += *ch;
     }
   }
   return result;
 }
References string::reserve(), and stringstream::str().
Referenced by testing::internal::CmpHelperFloatingPointEQ(), testing::internal::FloatingPointLE(), Message::GetString(), XmlUnitTestResultPrinter::OnTestIterationEnd(), and testing::internal::WideStringToUtf8().