Common Alogrithm: testing::internal::ArrayEq
ArrayEq() [2/3]
bool ArrayEq (const T * lhs, size_t size, const U * rhs)
{
   for (size_t i = 0; i != size; i++) {
     if (!internal::ArrayEq(lhs[i], rhs[i]))
       return false;
   }
   return true;
 }
Referenced by testing::internal::ArrayAwareFind(), testing::internal::ArrayEq(), and NativeArray< Element >::operator==().