Common Alogrithm: testing::internal::InitGoogleTestImpl
InitGoogleTestImpl()
void testing::internal::InitGoogleTestImpl (int * argc, CharType ** argv)
{
   // We don't want to run the initialization code twice.
   if (GTestIsInitialized()) return;
   if (*argc <= 0) return;
   g_argvs.clear();
   for (int i = 0; i != *argc; i++) {
     g_argvs.push_back(StreamableToString(argv[i]));
   }
   ParseGoogleTestFlagsOnly(argc, argv);
   GetUnitTestImpl()->PostFlagParsingInit();
 }
References testing::internal::g_argvs, testing::internal::GetUnitTestImpl(), testing::internal::GTestIsInitialized(), testing::internal::ParseGoogleTestFlagsOnly(), UnitTestImpl::PostFlagParsingInit(), and testing::internal::StreamableToString().
Referenced by testing::InitGoogleTest().