Common Alogrithm: googletest Namespace Reference
googletest Namespace Reference
Classes
class BackTest
class EmptyTest
class EnqueueTest
class EraseTest
class FrontTest
class PopBackTest
class PopFrontTest
class RemoveValueTest
class ReverseTest
class SizeTest
class SolutionsTest
class ValueAtTest
class ValueNFromEndTest
Functions
TEST_F (BackTest, Back)
TEST_F (EmptyTest, Empty)
TEST_F (EnqueueTest, Enqueue)
TEST_F (EraseTest, Erase)
TEST_F (FrontTest, Front)
TEST_F (PopBackTest, PopBack)
TEST_F (PopFrontTest, PopFront)
TEST_F (RemoveValueTest, RemoveValue)
TEST_F (ReverseTest, Reverse)
TEST_F (SizeTest, Size)
TEST_F (SizeTest, SizeEmpty)
TEST_F (SolutionsTest, largestKTest)
TEST_F (SolutionsTest, minDeletionsTest)
TEST_F (SolutionsTest, minStpesTest)
TEST_F (SolutionsTest, MinSwapTest)
TEST_F (SolutionsTest, ShortestDistanceTest)
TEST_F (SolutionsTest, TwoSumTest)
TEST_F (ValueAtTest, ValueAt)
TEST_F (ValueNFromEndTest, ValueNFromEnd)
Function Documentation
TEST_F() [1/19]
googletest::TEST_F (BackTest , Back)
Definition at line 37 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     int golden_value = 100;
     lists.PushBack(golden_value);
     EXPECT_EQ(golden_value,lists.Back());
 }
References LinkedList< T >::Back(), EXPECT_EQ, and LinkedList< T >::PushBack().
TEST_F() [2/19]
googletest::TEST_F (EmptyTest , Empty)
Definition at line 23 of file queue_linked_list_unit_test.cc.
 {
     /* Declare the Unit Test object */
     common::QueueLinkedList<int> queue_lists;
     EXPECT_TRUE(queue_lists.Empty());
 }
References QueueLinkedList< T >::Empty(), and EXPECT_TRUE.
TEST_F() [3/19]
googletest::TEST_F (EnqueueTest , Enqueue)
Definition at line 9 of file queue_linked_list_unit_test.cc.
 {
     /* Declare the Unit Test object */
     common::QueueLinkedList<int> queue_lists;
     queue_lists.Enqueue(10);
     queue_lists.Enqueue(20);
     EXPECT_EQ(10,queue_lists.Dequeue());
     EXPECT_EQ(20,queue_lists.Dequeue());
 }
References QueueLinkedList< T >::Dequeue(), QueueLinkedList< T >::Enqueue(), and EXPECT_EQ.
TEST_F() [4/19]
googletest::TEST_F (EraseTest , Erase)
Definition at line 86 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     lists.PushFront(10);
     lists.Erase(0);
     EXPECT_EQ(0,lists.Size());
 }
References LinkedList< T >::Erase(), EXPECT_EQ, LinkedList< T >::PushFront(), and LinkedList< T >::Size().
TEST_F() [5/19]
googletest::TEST_F (FrontTest , Front)
Definition at line 26 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     int golden_value = 100;
     lists.PushFront(golden_value);
     EXPECT_EQ(golden_value, lists.Front());
 }
References EXPECT_EQ, LinkedList< T >::Front(), and LinkedList< T >::PushFront().
TEST_F() [6/19]
googletest::TEST_F (PopBackTest , PopBack)
Definition at line 60 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
      common::LinkedList<int> lists;
      int golden_value = 100;
      lists.PushFront(golden_value);
      EXPECT_EQ(golden_value,lists.PopBack());
 }
References EXPECT_EQ, LinkedList< T >::PopBack(), and LinkedList< T >::PushFront().
TEST_F() [7/19]
googletest::TEST_F (PopFrontTest , PopFront)
Definition at line 48 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     int golden_value = 100;
     lists.PushFront(golden_value);
     EXPECT_EQ(golden_value,lists.PopFront());
 }
References EXPECT_EQ, LinkedList< T >::PopFront(), and LinkedList< T >::PushFront().
TEST_F() [8/19]
googletest::TEST_F (RemoveValueTest , RemoveValue)
Definition at line 97 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     lists.PushFront(6);
     lists.RemoveValue(6);
     EXPECT_EQ(0,lists.Size());
 }
References EXPECT_EQ, LinkedList< T >::PushFront(), LinkedList< T >::RemoveValue(), and LinkedList< T >::Size().
TEST_F() [9/19]
googletest::TEST_F (ReverseTest , Reverse)
Definition at line 109 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     lists.PushFront(10);
     lists.PushFront(11);
     lists.PushFront(12);
 //     lists.PrintDebug();
     lists.Reverse();
 //     lists.PrintDebug();
     EXPECT_EQ(10,lists.PopFront());
     EXPECT_EQ(11,lists.PopFront());
     EXPECT_EQ(12,lists.PopFront());
 }
References EXPECT_EQ, LinkedList< T >::PopFront(), LinkedList< T >::PushFront(), and LinkedList< T >::Reverse().
TEST_F() [10/19]
googletest::TEST_F (SizeTest , Size)
Definition at line 15 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     lists.PushFront(3);
     lists.PushFront(2);
     EXPECT_EQ(2,lists.Size());
 }
References EXPECT_EQ, LinkedList< T >::PushFront(), and LinkedList< T >::Size().
TEST_F() [11/19]
googletest::TEST_F (SizeTest , SizeEmpty)
Definition at line 8 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     EXPECT_EQ(0,lists.Size());
 }
References EXPECT_EQ, and LinkedList< T >::Size().
TEST_F() [12/19]
googletest::TEST_F (SolutionsTest , largestKTest)
Definition at line 59 of file leetcode_unit_test.cc.
 {
     /* Declare the Unit Test object */
     leetcode::Solutions solutions;
     std::vector<int> array = {-41,3,2,5,41 };
     int expected_value = 41, result_value = solutions.largestK(array);
     EXPECT_EQ(expected_value,result_value);
 }
References EXPECT_EQ, and Solutions::largestK().
TEST_F() [13/19]
googletest::TEST_F (SolutionsTest , minDeletionsTest)
Definition at line 8 of file leetcode_unit_test.cc.
 {
     /* Declare the Unit Test object */
     leetcode::Solutions solutions;
     std::string input = "aaabbccdddtt";
     EXPECT_EQ(6, solutions.minDeletions(input));
 }
References EXPECT_EQ, and Solutions::minDeletions().
TEST_F() [14/19]
googletest::TEST_F (SolutionsTest , minStpesTest)
Definition at line 48 of file leetcode_unit_test.cc.
 {
     /* Declare the Unit Test object */
     leetcode::Solutions solutions;
     std::vector<int> piles = {1, 2, 2, 3, 3, 4};
     int minsteps = 9;
     EXPECT_EQ(minsteps, solutions.minStpes(piles));
 }
References EXPECT_EQ, and Solutions::minStpes().
TEST_F() [15/19]
googletest::TEST_F (SolutionsTest , MinSwapTest)
Definition at line 16 of file leetcode_unit_test.cc.
 {
     /* Declare the Unit Test object */
     leetcode::Solutions solutions;
     std::string input = "mamad";
     EXPECT_EQ(3, solutions.minSwaps(input));
 }
References EXPECT_EQ, and Solutions::minSwaps().
TEST_F() [16/19]
googletest::TEST_F (SolutionsTest , ShortestDistanceTest)
Definition at line 38 of file leetcode_unit_test.cc.
 {
     /* Declare the Unit Test object */
     leetcode::Solutions solutions;
     std::vector< std::vector<int> > grid = {{1, 0, 2, 0 ,1}, {0, 0, 0, 0, 0}, {0, 0, 1, 0, 0}};
     EXPECT_EQ( 7, solutions.shortestDistance(grid));
 }
References EXPECT_EQ, and Solutions::shortestDistance().
TEST_F() [17/19]
googletest::TEST_F (SolutionsTest , TwoSumTest)
Definition at line 25 of file leetcode_unit_test.cc.
 {
     /* Declare the Unit Test object */
     leetcode::Solutions solutions;
     std::vector<int> nums = {2, 7, 11, 15};
     int target = 9;
     std::vector<int> output = {0, 1};
     for (int i = 0; i < solutions.twoSum(nums, target).capacity(); ++i) {
         EXPECT_EQ(output[i], solutions.twoSum(nums, target)[i]);
     }
 }
References EXPECT_EQ, and Solutions::twoSum().
TEST_F() [18/19]
googletest::TEST_F (ValueAtTest , ValueAt)
Definition at line 71 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     lists.PushFront(100);
     lists.PushFront(200);
     lists.Insert(2, 300);
 //     lists.PrintDebug();
     EXPECT_EQ(200,lists.ValueAt(0));
     EXPECT_EQ(300,lists.ValueAt(2));
 }
References EXPECT_EQ, LinkedList< T >::Insert(), LinkedList< T >::PushFront(), and LinkedList< T >::ValueAt().
TEST_F() [19/19]
googletest::TEST_F (ValueNFromEndTest , ValueNFromEnd)
Definition at line 128 of file linkedlists_unit_test.cc.
{
     /* Declare the Unit Test object */
     common::LinkedList<int> lists;
     lists.PushBack(1);
     lists.PushBack(2);
     lists.PushBack(3);
     lists.PrintDebug();
     EXPECT_EQ(3,lists.ValueNFromEnd(1));
     EXPECT_EQ(2,lists.ValueNFromEnd(2));
     EXPECT_EQ(1,lists.ValueNFromEnd(3));
 }
References EXPECT_EQ, LinkedList< T >::PrintDebug(), LinkedList< T >::PushBack(), and LinkedList< T >::ValueNFromEnd().