Common Alogrithm: common::ListElement< T > Class Template Reference
common::ListElement< T > Class Template Reference
#include <list_element.h>
Public Member Functions
const T & GetData () const
ListElement< T > * GetNext () const
ListElement (const ListElement &)
ListElement (const T &value)
ListElement & operator= (const ListElement &)
void SetData (const T &datain)
void SetNext (ListElement< T > *elem)
virtual ~ListElement ()
Private Attributes
T data
ListElement< T > * next
Detailed Description
template<class T>
class common::ListElement< T >
Constructor & Destructor Documentation
ListElement() [1/2]
template<class T > common::ListElement< T >::ListElement (const T & value)
 : next(nullptr), data(value) {};
ListElement() [2/2]
template<class T > common::ListElement< T >::ListElement (const ListElement< T > &)
 {};
~ListElement()
template<class T > virtual common::ListElement< T >::~ListElement () virtual
 {};
Member Function Documentation
GetData()
template<class T > const T& common::ListElement< T >::GetData () const
 { return data; };
References common::ListElement< T >::data.
Referenced by common::LinkedList< T >::PopFront().
GetNext()
template<class T > ListElement<T>* common::ListElement< T >::GetNext () const
 { return next; };
References common::ListElement< T >::next.
Referenced by common::LinkedList< T >::PushBack(), and common::LinkedList< T >::~LinkedList().
operator=()
template<class T > ListElement& common::ListElement< T >::operator= (const ListElement< T > &)
SetData()
template<class T > void common::ListElement< T >::SetData (const T & datain)
 { data = datain; };
References common::ListElement< T >::data.
SetNext()
template<class T > void common::ListElement< T >::SetNext (ListElement< T > * elem)
 { next = elem; };
References common::ListElement< T >::next.
Referenced by common::LinkedList< T >::PushBack().
Member Data Documentation
data
template<class T > T common::ListElement< T >::data private
Referenced by common::ListElement< T >::GetData(), and common::ListElement< T >::SetData().
next
template<class T > ListElement<T>* common::ListElement< T >::next private
Referenced by common::ListElement< T >::GetNext(), and common::ListElement< T >::SetNext().