Common Alogrithm: testing::TestResult Class Reference
testing::TestResult Class Reference
#include <gtest.h>
Public Member Functions
TimeInMillis elapsed_time () const
bool Failed () const
const TestPartResult & GetTestPartResult (int i) const
const TestProperty & GetTestProperty (int i) const
bool HasFatalFailure () const
bool HasNonfatalFailure () const
bool Passed () const
int test_property_count () const
TestResult ()
int total_part_count () const
~TestResult ()
Private Member Functions
void AddTestPartResult (const TestPartResult &test_part_result)
void Clear ()
void ClearTestPartResults ()
int death_test_count () const
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult)
int increment_death_test_count ()
void RecordProperty (const std::string &xml_element, const TestProperty &test_property)
void set_elapsed_time (TimeInMillis elapsed)
const std::vector< TestPartResult > & test_part_results () const
const std::vector< TestProperty > & test_properties () const
Static Private Member Functions
static bool ValidateTestProperty (const std::string &xml_element, const TestProperty &test_property)
Private Attributes
int death_test_count_
TimeInMillis elapsed_time_
std::vector< TestPartResult > test_part_results_
internal::Mutex test_properites_mutex_
std::vector< TestProperty > test_properties_
Friends
class internal::DefaultGlobalTestPartResultReporter
class internal::ExecDeathTest
class internal::TestResultAccessor
class internal::UnitTestImpl
class internal::WindowsDeathTest
class TestCase
class TestInfo
class UnitTest
Detailed Description
Constructor & Destructor Documentation
TestResult()
testing::TestResult::TestResult ()
     : death_test_count_(0),
       elapsed_time_(0) {
 }
~TestResult()
testing::TestResult::~TestResult ()
{
 }
Member Function Documentation
AddTestPartResult()
void testing::TestResult::AddTestPartResult (const TestPartResult & test_part_result) private
{
   test_part_results_.push_back(test_part_result);
 }
References test_part_results_.
Referenced by testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult().
Clear()
void testing::TestResult::Clear () private
{
   test_part_results_.clear();
   test_properties_.clear();
   death_test_count_ = 0;
   elapsed_time_ = 0;
 }
References death_test_count_, elapsed_time_, test_part_results_, and test_properties_.
Referenced by testing::TestCase::ClearResult(), and testing::TestInfo::ClearTestResult().
ClearTestPartResults()
void testing::TestResult::ClearTestPartResults () private
{
   test_part_results_.clear();
 }
References test_part_results_.
Referenced by testing::internal::TestResultAccessor::ClearTestPartResults().
death_test_count()
int testing::TestResult::death_test_count () const private
 { return death_test_count_; }
elapsed_time()
TimeInMillis testing::TestResult::elapsed_time () const
 { return elapsed_time_; }
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), and testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo().
Failed()
bool testing::TestResult::Failed () const
{
   for (int i = 0; i < total_part_count(); ++i) {
     if (GetTestPartResult(i).failed())
       return true;
   }
   return false;
 }
References testing::TestPartResult::failed(), GetTestPartResult(), and total_part_count().
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), and testing::TestCase::TestFailed().
GetTestPartResult()
const TestPartResult & testing::TestResult::GetTestPartResult (int i) const
{
   if (i < 0 || i >= total_part_count())
     internal::posix::Abort();
   return test_part_results_.at(i);
 }
References testing::internal::posix::Abort(), test_part_results_, and total_part_count().
Referenced by Failed(), and testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo().
GetTestProperty()
const TestProperty & testing::TestResult::GetTestProperty (int i) const
{
   if (i < 0 || i >= test_property_count())
     internal::posix::Abort();
   return test_properties_.at(i);
 }
References testing::internal::posix::Abort(), test_properties_, and test_property_count().
Referenced by testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::TestResult::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult) private
HasFatalFailure()
bool testing::TestResult::HasFatalFailure () const
{
   return CountIf(test_part_results_, TestPartFatallyFailed) > 0;
 }
References testing::internal::CountIf(), test_part_results_, and testing::TestPartFatallyFailed().
Referenced by testing::Test::HasFatalFailure().
HasNonfatalFailure()
bool testing::TestResult::HasNonfatalFailure () const
{
   return CountIf(test_part_results_, TestPartNonfatallyFailed) > 0;
 }
References testing::internal::CountIf(), test_part_results_, and testing::TestPartNonfatallyFailed().
increment_death_test_count()
int testing::TestResult::increment_death_test_count () private
 { return ++death_test_count_; }
Passed()
bool testing::TestResult::Passed () const
 { return !Failed(); }
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), and testing::TestCase::TestPassed().
RecordProperty()
void testing::TestResult::RecordProperty (const std::string & xml_element, const TestProperty & test_property) private
{
   if (!ValidateTestProperty(xml_element, test_property)) {
     return;
   }
   internal::MutexLock lock(&test_properites_mutex_);
   const std::vector<TestProperty>::iterator property_with_matching_key =
       std::find_if(test_properties_.begin(), test_properties_.end(),
                    internal::TestPropertyKeyIs(test_property.key()));
   if (property_with_matching_key == test_properties_.end()) {
     test_properties_.push_back(test_property);
     return;
   }
   property_with_matching_key->SetValue(test_property.value());
 }
References std::find_if(), testing::TestProperty::key(), test_properites_mutex_, test_properties_, ValidateTestProperty(), and testing::TestProperty::value().
Referenced by testing::internal::UnitTestImpl::RecordProperty(), and testing::internal::TestResultAccessor::RecordProperty().
set_elapsed_time()
void testing::TestResult::set_elapsed_time (TimeInMillis elapsed) private
 { elapsed_time_ = elapsed; }
Referenced by testing::TestInfo::Run().
test_part_results()
const std::vector<TestPartResult>& testing::TestResult::test_part_results () const private
{
     return test_part_results_;
   }
Referenced by testing::internal::TestResultAccessor::test_part_results().
test_properties()
const std::vector<TestProperty>& testing::TestResult::test_properties () const private
{
     return test_properties_;
   }
test_property_count()
int testing::TestResult::test_property_count () const
{
   return static_cast<int>(test_properties_.size());
 }
References test_properties_.
Referenced by GetTestProperty(), and testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
total_part_count()
int testing::TestResult::total_part_count () const
{
   return static_cast<int>(test_part_results_.size());
 }
References test_part_results_.
Referenced by Failed(), GetTestPartResult(), and testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo().
ValidateTestProperty()
bool testing::TestResult::ValidateTestProperty (const std::string & xml_element, const TestProperty & test_property) static private
{
   return ValidateTestPropertyName(test_property.key(),
                                   GetReservedAttributesForElement(xml_element));
 }
References testing::GetReservedAttributesForElement(), testing::TestProperty::key(), and testing::ValidateTestPropertyName().
Referenced by RecordProperty().
Friends And Related Function Documentation
internal::DefaultGlobalTestPartResultReporter
friend class internal::DefaultGlobalTestPartResultReporter friend
internal::ExecDeathTest
friend class internal::ExecDeathTest friend
internal::TestResultAccessor
friend class internal::TestResultAccessor friend
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
internal::WindowsDeathTest
friend class internal::WindowsDeathTest friend
TestCase
friend class TestCase friend
TestInfo
friend class TestInfo friend
UnitTest
friend class UnitTest friend
Member Data Documentation
death_test_count_
int testing::TestResult::death_test_count_ private
Referenced by Clear().
elapsed_time_
TimeInMillis testing::TestResult::elapsed_time_ private
Referenced by Clear().
test_part_results_
std::vector<TestPartResult> testing::TestResult::test_part_results_ private
Referenced by AddTestPartResult(), Clear(), ClearTestPartResults(), GetTestPartResult(), HasFatalFailure(), HasNonfatalFailure(), and total_part_count().
test_properites_mutex_
internal::Mutex testing::TestResult::test_properites_mutex_ private
Referenced by RecordProperty().
test_properties_
std::vector<TestProperty> testing::TestResult::test_properties_ private
Referenced by Clear(), GetTestProperty(), RecordProperty(), and test_property_count().