Common Alogrithm: PriorityQueue Class Reference
PriorityQueue Class Reference
#include <priority_queue.h>
Public Member Functions
PQElement * ExtractMax ()
PQElement * GetMax ()
int GetSize ()
void Insert (const int key, const std::string value)
bool IsEmpty ()
PriorityQueue & operator= (const PriorityQueue &)=delete
void PrintDebug ()
PriorityQueue (const int size)
PriorityQueue (const PriorityQueue &)=delete
void Remove (int index)
virtual ~PriorityQueue ()
Private Member Functions
void SiftDown (int index)
Brief function description here.
void SiftUp (int index)
Brief function description here.
void Swap (const int index1, const int index2)
Private Attributes
int capacity_queue = 0
PQElement * pelement
int size = 0
Detailed Description
Definition at line 13 of file priority_queue.h.
Constructor & Destructor Documentation
PriorityQueue() [1/2]
PriorityQueue (const int size) explicit
Definition at line 5 of file priority_queue.cc.
                                           : capacity_queue(size)
 {
     assert(size > 0 && size < INT_MAX);
     pelement = new PQElement[size];
 }
References PriorityQueue::pelement, and PriorityQueue::size.
PriorityQueue() [2/2]
PriorityQueue (const PriorityQueue &) delete
~PriorityQueue()
~PriorityQueue () virtual
Definition at line 12 of file priority_queue.cc.
 { delete [] pelement; };
References PriorityQueue::pelement.
Member Function Documentation
ExtractMax()
PQElement * ExtractMax ()
Definition at line 54 of file priority_queue.cc.
 {
     assert(size >0);
     PQElement* max = new PQElement;
     max->key = pelement[0].key;
     max->value = pelement[0].value;
     Swap(0 , size -1);
     -- size;
     SiftDown(0);
     return max;
 }
References PriorityQueueElement::key, PriorityQueue::pelement, PriorityQueue::SiftDown(), PriorityQueue::size, PriorityQueue::Swap(), and PriorityQueueElement::value.
Referenced by main().
GetMax()
PQElement * GetMax ()
Definition at line 46 of file priority_queue.cc.
 {
     assert(size > 0);
     return & pelement[0];
 }
References PriorityQueue::pelement, and PriorityQueue::size.
GetSize()
int GetSize ()
Definition at line 36 of file priority_queue.cc.
 {
     return size;
 }
References PriorityQueue::size.
Referenced by main().
Insert()
void Insert (const int key, const std::string value)
Definition at line 14 of file priority_queue.cc.
 {
     assert(size < capacity_queue);
     pelement[size].key = key;
     pelement[size].value = value;
     ++size;
     SiftUp(size - 1);
 }
References PriorityQueue::capacity_queue, PriorityQueueElement::key, PriorityQueue::pelement, PriorityQueue::SiftUp(), PriorityQueue::size, and PriorityQueueElement::value.
Referenced by main().
IsEmpty()
bool IsEmpty ()
Definition at line 41 of file priority_queue.cc.
 {
     return size == 0;
 }
References PriorityQueue::size.
Referenced by main().
operator=()
PriorityQueue& operator= (const PriorityQueue &) delete
PrintDebug()
void PrintDebug ()
Definition at line 69 of file priority_queue.cc.
 {
     for (int i = 0; i < size; ++i) {
         std::cout << i << ": " << pelement[i].key << ":" << pelement[i].value  << std::endl;
     }
     std::cout << "------------" << std::endl;
 }
References std::endl(), PriorityQueueElement::key, PriorityQueue::pelement, PriorityQueue::size, and PriorityQueueElement::value.
Referenced by main().
Remove()
void Remove (int index)
Definition at line 26 of file priority_queue.cc.
 {
     assert(index > 0 && index < size);
     Swap(index, size -1);
     --size;
     SiftDown(index);
 }
References PriorityQueue::SiftDown(), PriorityQueue::size, and PriorityQueue::Swap().
SiftDown()
void SiftDown (int index) private
Brief function description here.
SiftDown swaps a node that is too small with its largest child (thereby moving it down) until it is at least as large as both nodes below it.
Parameters
Parameter Parameter description
Returns
Return parameter description
Definition at line 124 of file priority_queue.cc.
 {
     assert(index < capacity_queue);
     while (index *2 + 1 < size ) {
         int left_child_index = index*2 + 1;
         int right_child_index = index*2 + 2;
         bool has_left_child_index = left_child_index < size;
         bool has_right_child_index = right_child_index < size;
         int swap_index = index;
         if (has_right_child_index && has_left_child_index) {
             if(pelement[left_child_index].key > pelement[right_child_index].key) {
                 swap_index = left_child_index;
             } else {
                 swap_index = right_child_index;
             }
         } else if (has_left_child_index) {
             swap_index = left_child_index;
         } else if (has_right_child_index) {
             swap_index = right_child_index;
         } else {
             break;
         }
         if(pelement[swap_index].key > pelement[index].key) {
             Swap(swap_index, index);
         } else {
             break;
         }
         index = swap_index;
     }
 }
References PriorityQueue::capacity_queue, PriorityQueue::pelement, PriorityQueue::size, and PriorityQueue::Swap().
Referenced by PriorityQueue::ExtractMax(), and PriorityQueue::Remove().
SiftUp()
void SiftUp (int index) private
Brief function description here.
SiftUp swaps a node that is too large with its parent (thereby moving it up) until it is no larger than the node above it.
Parameters
Parameter Parameter description
Returns
Return parameter description
Definition at line 87 of file priority_queue.cc.
 {
    assert(index < capacity_queue);
    while (index > 0) {
     // Quick sorting
     int parent = (index - 1)/2;
     if (pelement[parent].key < pelement[index].key) {
         Swap(parent, index);
     } else {
         break;
     }
     index = parent;
    }
 }
References PriorityQueue::capacity_queue, PriorityQueue::pelement, and PriorityQueue::Swap().
Referenced by PriorityQueue::Insert().
Swap()
void Swap (const int index1, const int index2) private
Definition at line 104 of file priority_queue.cc.
 {
     int tmp_key = pelement[index1].key;
     std::string tmp_value = pelement[index1].value;
     pelement[index1].key = pelement[index2].key;
     pelement[index1].value = pelement[index2].value;
     pelement[index2].key = tmp_key;
     pelement[index2].value = tmp_value;
 }
References PriorityQueueElement::key, PriorityQueue::pelement, and PriorityQueueElement::value.
Referenced by PriorityQueue::ExtractMax(), PriorityQueue::Remove(), PriorityQueue::SiftDown(), and PriorityQueue::SiftUp().
Member Data Documentation
capacity_queue
int capacity_queue = 0 private
Definition at line 17 of file priority_queue.h.
Referenced by PriorityQueue::Insert(), PriorityQueue::SiftDown(), and PriorityQueue::SiftUp().
pelement
PQElement* pelement private
Definition at line 18 of file priority_queue.h.
Referenced by PriorityQueue::ExtractMax(), PriorityQueue::GetMax(), PriorityQueue::Insert(), PriorityQueue::PrintDebug(), PriorityQueue::PriorityQueue(), PriorityQueue::SiftDown(), PriorityQueue::SiftUp(), PriorityQueue::Swap(), and PriorityQueue::~PriorityQueue().
size
int size = 0 private
Definition at line 16 of file priority_queue.h.
Referenced by PriorityQueue::ExtractMax(), PriorityQueue::GetMax(), PriorityQueue::GetSize(), PriorityQueue::Insert(), PriorityQueue::IsEmpty(), PriorityQueue::PrintDebug(), PriorityQueue::PriorityQueue(), PriorityQueue::Remove(), and PriorityQueue::SiftDown().