Common Alogrithm: testing::anonymous_namespace{gtest-printers.cc} Namespace Reference
testing::anonymous_namespace{gtest-printers.cc} Namespace Reference
Functions
GTEST_ATTRIBUTE_NO_SANITIZE_MEMORY_ GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_ GTEST_ATTRIBUTE_NO_SANITIZE_THREAD_ void PrintByteSegmentInObjectTo (const unsigned char *obj_bytes, size_t start, size_t count, ostream *os)
void PrintBytesInObjectToImpl (const unsigned char *obj_bytes, size_t count, ostream *os)
Function Documentation
PrintByteSegmentInObjectTo()
GTEST_ATTRIBUTE_NO_SANITIZE_MEMORY_ GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_ GTEST_ATTRIBUTE_NO_SANITIZE_THREAD_ void testing::anonymous_namespace{gtest-printers.cc}::PrintByteSegmentInObjectTo (const unsigned char * obj_bytes, size_t start, size_t count, ostream * os)
Definition at line 63 of file gtest-printers.cc.
{
   char text[5] = "";
   for (size_t i = 0; i != count; i++) {
     const size_t j = start + i;
     if (i != 0) {
       // Organizes the bytes into groups of 2 for easy parsing by
       // human.
       if ((j % 2) == 0)
         *os << ' ';
       else
         *os << '-';
     }
     GTEST_SNPRINTF_(text, sizeof(text), "%02X", obj_bytes[j]);
     *os << text;
   }
 }
References GTEST_SNPRINTF_.
Referenced by PrintBytesInObjectToImpl().
PrintBytesInObjectToImpl()
void testing::anonymous_namespace{gtest-printers.cc}::PrintBytesInObjectToImpl (const unsigned char * obj_bytes, size_t count, ostream * os)
Definition at line 82 of file gtest-printers.cc.
{
   // Tells the user how big the object is.
   *os << count << "-byte object <";
   const size_t kThreshold = 132;
   const size_t kChunkSize = 64;
   // If the object size is bigger than kThreshold, we'll have to omit
   // some details by printing only the first and the last kChunkSize
   // bytes.
   // TODO(wan): let the user control the threshold using a flag.
   if (count < kThreshold) {
     PrintByteSegmentInObjectTo(obj_bytes, 0, count, os);
   } else {
     PrintByteSegmentInObjectTo(obj_bytes, 0, kChunkSize, os);
     *os << " ... ";
     // Rounds up to 2-byte boundary.
     const size_t resume_pos = (count - kChunkSize + 1)/2*2;
     PrintByteSegmentInObjectTo(obj_bytes, resume_pos, count - resume_pos, os);
   }
   *os << ">";
 }
References PrintByteSegmentInObjectTo().
Referenced by testing::internal2::PrintBytesInObjectTo().