Common Alogrithm: Solutions Class Reference
Solutions Class Reference
#include <solutions.h>
Public Member Functions
int minDeletions (std::string s)
leetcode 1647 Minimum Deletions to Make Character Frequencies Unique
Solutions ()
virtual ~Solutions ()
Detailed Description
Definition at line 7 of file solutions.h.
Constructor & Destructor Documentation
Solutions()
Solutions ()
Definition at line 13 of file solutions.h.
 {};
~Solutions()
virtual ~Solutions () virtual
Definition at line 14 of file solutions.h.
 {};
Member Function Documentation
minDeletions()
int minDeletions (std::string s)
leetcode 1647 Minimum Deletions to Make Character Frequencies Unique
A string s is called good if there are no two different characters in s that have the same frequency. Given a string s, return the minimum number of characters you need to delete to make s good. The frequency of a character in a string is the number of times it appears in the string. For example, in the string "aab", the frequency of 'a' is 2, while the freqnency of 'b' is 1.
Returns
the minmum number of characters you need tp delete to make s good
Definition at line 15 of file solutions.cc.
 {
     std::vector<int> v(26);
     for (auto it : s) {
         v[it - 'a'] ++;
     }
     // Count the frequencies of elements
     std::map<int, int> mp;
     for (int i = 0; i < 26; ++i) {
         mp[v[i]] ++;
     }
     int ans = 0;
     // Traverse map from backwards
     for (auto it = mp.rbegin();  it!=mp.rend() ; ++it) {
         int key = it->first;
         int val = it->second;
         std::cout << "key: " << key  << " value: " << val << std::endl;
         // not frequencies of elements
         if (key == 0 || val == 1) {
             continue;
         }
         // increase the freqnency count after delete characters
         int new_val = val - 1;
         mp[key -1] += new_val;
         ans += new_val;
     }
     return ans;
 }
References std::endl(), map< K, T >::rbegin(), and map< K, T >::rend().
Referenced by main().