Common Alogrithm: Solutions Class Reference
Solutions Class Reference
#include <solutions.h>
Public Member Functions
int minDeletions (std::string s)
Minimum Deletions to Make Character Frequencies Unique.
int minSwaps (std::string s)
Minimum Adjacent Swaps to Make Palindrome.
Solutions ()
std::vector< int > twoSum (std::vector< int > &num, int target)
Two Sum.
virtual ~Solutions ()
Private Member Functions
bool isPalindrome (std::string s)
bool isValidChar (char c)
bool isValidString (std::string s)
Detailed Description
Definition at line 11 of file solutions.h.
Constructor & Destructor Documentation
Solutions()
Solutions ()
Definition at line 20 of file solutions.h.
 {};
~Solutions()
virtual ~Solutions () virtual
Definition at line 21 of file solutions.h.
 {};
Member Function Documentation
isPalindrome()
bool isPalindrome (std::string s) private
Definition at line 5 of file solutions.cc.
 {
     int start = 0, end = s.length() - 1;
     while (start < end) {
         if (isValidChar(s[start]) && isValidChar(s[end])) {
             if (s[start] == s[end]) {
                 start ++;
                 end --;
             } else {
                 return false;
             }
         } else if (isValidChar(s[start])) {
             ++start;
             continue;
         } else if (isValidChar(s[end])) {
             ++end;
             continue;
         } else {
             continue;
         }
     }
     return true;
 }
References Solutions::isValidChar(), and string::length().
Referenced by Solutions::minSwaps().
isValidChar()
bool isValidChar (char c) private
Definition at line 31 of file solutions.cc.
 {
     return ((c - 'a' >= 0 && c - 'z' <= 0) || (c - 'A' >= 0 && c - 'Z' <= 0));
 }
Referenced by Solutions::isPalindrome().
isValidString()
bool isValidString (std::string s) private
Definition at line 36 of file solutions.cc.
 {
     for (auto elem : s) {
         if ((elem - 'a' >= 0 && elem - 'z' <= 0 ) || (elem - 'A' >= 0 && elem - 'Z' <= 0)){
             continue;
         }
         else return false;
         std::cout << "va" << std::endl;
     }
     return true;
 }
References std::endl().
Referenced by Solutions::minSwaps().
minDeletions()
int minDeletions (std::string s)
Minimum Deletions to Make Character Frequencies Unique.
A string s is called good if there are no two different characters in s that have the same frequency.
Given a string s, return the minimum number of characters you need to delete to make s good.
The frequency of a character in a string is the number of times it appears in the string.
For example, in the string "aab", the frequency of 'a' is 2, while the freqnency of 'b' is 1.
Returns
the minmum number of characters you need tp delete to make s good
Definition at line 61 of file solutions.cc.
 {
     std::vector<int> v(26, 0);
     for (auto it : s) v[it - 'a'] ++;
     // Count the frequencies of elements
     std::map<int, int> mp;
     for (int i = 0; i < 26; ++i) mp[v[i]] ++;
     int ans = 0;
     // Traverse map from backwards
     for (auto it = mp.rbegin();  it!=mp.rend() ; ++it) {
         int key = it->first;
         int val = it->second;
 //         std::cout << "key: " << key  << " value: " << val << std::endl;
         // not frequencies of elements
         if (key == 0 || val == 1) {
             continue;
         }
         // increase the freqnency count after delete characters
         int new_val = val - 1;
         mp[key -1] += new_val;
         ans += new_val;
     }
     return ans;
 }
References map< K, T >::rbegin(), and map< K, T >::rend().
minSwaps()
int minSwaps (std::string s)
Minimum Adjacent Swaps to Make Palindrome.
Given a string, what is the minimum number of adjacent swaps required to convert a string into a palindrome. If not possibl, return -1.
Returns
the minimum number of adjust required
Definition at line 98 of file solutions.cc.
 {
     int start = 0, end = s.length() - 1, ans = 0;
     if (isValidString(s)) {
         while (start < s.length()/2) {
             // Palindrome
             if (s[start] == s[end - start]){
                 ++ start;
                 continue;
             }
             //  Core begins
             //  track of the left and right points and compare
             int left_index, right_index;
             for (left_index = start + 1; left_index <= end - start && s[left_index] != s[end - start]; ++left_index);
             for (right_index = end - start - 1; right_index >= start && s[right_index] != s[start]; --right_index);
             // choose minimum distance between left side or right side
             ans += std::min(left_index - start, end - start - right_index);
             if (left_index - start < end - start - right_index) {
                 for (int p = left_index; p > start; --p) {
                     std::swap(s[p], s[p-1]);
                 }
             } else {
                 for (int p = right_index; p < end - start; ++p) {
                      std::swap(s[p], s[p+1]);
                 }
             }
             ++start;
         }
         if (!isPalindrome(s)) return -1;
     } else {
         return -1;
     }
     return ans;
 }
References Solutions::isPalindrome(), Solutions::isValidString(), string::length(), std::min(), and std::swap().
twoSum()
std::vector< int > twoSum (std::vector< int > & num, int target)
Two Sum.
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
Returns
indices of the two numbers such that they add up to target
Definition at line 148 of file solutions.cc.
 {
     std::vector<int> indices_two_sum;
     indices_two_sum.clear();
     // O(n^2)
     /*
     for (int i = 0; i < num.capacity(); ++i) {
         for (int j = i + 1; j < num.capacity(); ++j) {
             if( (num[i] + num[j]) == target) {
                 indices_two_sum.push_back(i);
                 indices_two_sum.push_back(j);
             }
         }
     }
     */
     // O(n)
     std::map<int, int> hashmap;
     hashmap.clear();
     for (int i = 0; i < num.capacity() ; i++)
     {
         const int diff = target - num[i];
         if ( hashmap.count(diff)) {
             indices_two_sum.push_back(hashmap[diff]);
             indices_two_sum.push_back(i);
             return indices_two_sum;
         }
         hashmap.insert( { num[i], i } );
     }
     return indices_two_sum;
 }
References vector< T >::capacity(), map< K, T >::clear(), vector< T >::clear(), map< K, T >::count(), map< K, T >::insert(), and vector< T >::push_back().