Common Alogrithm: ListElement< T > Class Template Reference
ListElement< T > Class Template Reference
#include <list_element.h>
Public Member Functions
const T & GetData () const
const T & GetData () const
ListElement< T > * GetNext () const
ListElement< T > * GetNext () const
ListElement (const ListElement &)
ListElement (const ListElement &)=delete
ListElement (const T &value)
ListElement (const T &value)
ListElement & operator= (const ListElement &)
ListElement & operator= (const ListElement &)=delete
void SetData (const T &datain)
void SetData (const T &inputdata)
void SetNext (ListElement< T > *elem)
void SetNext (ListElement< T > *elem)
virtual ~ListElement ()
virtual ~ListElement ()
Private Attributes
T data
ListElement< T > * next
Detailed Description
template<class T>
class common::ListElement< T >
Definition at line 8 of file list_element.h.
Constructor & Destructor Documentation
ListElement() [1/4]
ListElement (const T & value)
Definition at line 15 of file list_element.h.
 : next(nullptr), data(value) {};
ListElement() [2/4]
ListElement (const ListElement< T > &) delete
~ListElement() [1/2]
virtual ~ListElement () virtual
Definition at line 18 of file list_element.h.
 {};
ListElement() [3/4]
ListElement (const T & value)
Definition at line 17 of file list_element.h.
 : next(nullptr), data(value) {};
ListElement() [4/4]
ListElement (const ListElement< T > &)
Definition at line 18 of file list_element.h.
 {};
~ListElement() [2/2]
virtual ~ListElement () virtual
Definition at line 20 of file list_element.h.
 {};
Member Function Documentation
GetData() [1/2]
const T& GetData () const
Definition at line 22 of file list_element.h.
 { return data; };
References ListElement< T >::data.
GetData() [2/2]
const T& GetData () const
Definition at line 20 of file list_element.h.
 { return data; };
References ListElement< T >::data.
Referenced by LinkedList< T >::PopFront(), and QueueLinkedList< T >::PrintDebug().
GetNext() [1/2]
ListElement<T>* GetNext () const
Definition at line 23 of file list_element.h.
 { return next; };
References ListElement< T >::next.
GetNext() [2/2]
ListElement<T>* GetNext () const
Definition at line 21 of file list_element.h.
 {return next;};
References ListElement< T >::next.
Referenced by QueueLinkedList< T >::Dequeue(), QueueLinkedList< T >::PrintDebug(), LinkedList< T >::PushBack(), LinkedList< T >::~LinkedList(), and QueueLinkedList< T >::~QueueLinkedList().
operator=() [1/2]
ListElement& operator= (const ListElement< T > &)
operator=() [2/2]
ListElement& operator= (const ListElement< T > &) delete
SetData() [1/2]
void SetData (const T & datain)
Definition at line 25 of file list_element.h.
 { data = datain; };
References ListElement< T >::data.
SetData() [2/2]
void SetData (const T & inputdata)
Definition at line 22 of file list_element.h.
 { data = inputdata; };
References ListElement< T >::data.
SetNext() [1/2]
void SetNext (ListElement< T > * elem)
Definition at line 26 of file list_element.h.
 { next = elem; };
References ListElement< T >::next.
SetNext() [2/2]
void SetNext (ListElement< T > * elem)
Definition at line 23 of file list_element.h.
 { next = elem; };
References ListElement< T >::next.
Referenced by LinkedList< T >::PushBack().
Member Data Documentation
data
T data private
Definition at line 12 of file list_element.h.
Referenced by ListElement< T >::GetData(), and ListElement< T >::SetData().
next
ListElement< T > * next private
Definition at line 11 of file list_element.h.
Referenced by ListElement< T >::GetNext(), and ListElement< T >::SetNext().