Common Alogrithm: common::LinkedList< T > Class Template Reference
common::LinkedList< T > Class Template Reference
#include <linked_list.h>
Public Member Functions
const T Back ()
bool Empty () const
void Erase (int index)
const T Front ()
void Insert (int index, T value)
LinkedList ()
LinkedList (const LinkedList &)
LinkedList & operator= (const LinkedList &)
const T PopBack ()
const T PopFront ()
void PrintDebug () const
void PushBack (T value)
void PushFront (T value)
void RemoveValue (T value)
void Reverse ()
int Size ()
const T & ValueAt (int index) const
const T ValueNFromEnd (int n)
~LinkedList ()
Private Attributes
ListElement< T > * head
Detailed Description
template<class T>
class common::LinkedList< T >
Constructor & Destructor Documentation
LinkedList() [1/2]
template<class T > common::LinkedList< T >::LinkedList () explicit
 : head(nullptr) {};
LinkedList() [2/2]
template<class T > common::LinkedList< T >::LinkedList (const LinkedList< T > &)
 {};
~LinkedList()
template<class T > common::LinkedList< T >::~LinkedList ()
                   {
         ListElement<T>* current = head;
         ListElement<T>* next = nullptr;
         while (current) {
             next = current->GetNext();
             delete current;
             current = next;
         }
     };
References common::ListElement< T >::GetNext(), and common::LinkedList< T >::head.
Member Function Documentation
Back()
template<class T > const T common::LinkedList< T >::Back
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto* current = head;
     while (current->GetNext()) {
         current = head->GetNext();
     }
     return current->GetData();
 }
References std::endl().
Empty()
template<class T > bool common::LinkedList< T >::Empty
{
    return head == nullptr;
 }
Erase()
template<class T > void common::LinkedList< T >::Erase (int index)
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     ListElement<T>* prev = nullptr;
     auto * current = head;
     for (int i = 0; i < index && current != nullptr; ++i) {
         prev = current;
         current = current->GetNext();
     }
     if(current == nullptr) {
         std::cout << "Index out of bounds" << std::endl;
         exit(EXIT_FAILURE);
     }
     if (prev == nullptr) {
         head = current->GetNext();
     } else {
         prev->SetNext(current->GetNext());
         head = prev;
     }
     delete current;
 }
References std::endl().
Front()
template<class T > const T common::LinkedList< T >::Front
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     return head->GetData();
 }
References std::endl().
Insert()
template<class T > void common::LinkedList< T >::Insert (int index, T value)
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto * current = head; // asterisk (*), the dereference operator: dereference the pointer prev to access the LinkedList object it refers to
     ListElement<T> * prev = nullptr;
     int i;
     for (i = 0; i < index && current != nullptr; ++i) {
         prev = current;
         current = current->GetNext();
     }
     if(i != index) {
         std::cout << "Index out of bounds" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto * node = new ListElement<T>(value);
     if(prev == nullptr) {
         node->SetNext(head);
         head = node;
     } else {
         node->SetNext(prev->GetNext());
         prev->SetNext(node);
     }
 }
References std::endl().
operator=()
template<class T > LinkedList& common::LinkedList< T >::operator= (const LinkedList< T > &)
PopBack()
template<class T > const T common::LinkedList< T >::PopBack
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto* current = head;
     ListElement<T>* prev = nullptr;
     // Pop Back
     while (current->GetNext()) {
         prev = current;
         current = current->GetNext();
     }
     T value = current->GetData();
     if(prev == nullptr) {
         head = nullptr;
     } else {
         prev->SetNext(nullptr);
     }
     delete current;
     return value;
 }
References std::endl().
PopFront()
template<class T > const T common::LinkedList< T >::PopFront
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     ListElement<T> *node = head;
     T value = node->GetData();
     head = head->GetNext();
     delete node;
     return value;
 }
References std::endl(), and common::ListElement< T >::GetData().
PrintDebug()
template<class T > void common::LinkedList< T >::PrintDebug
{
     auto * current = head;
     std::cout << " " << std::endl;
     while (current) {
         std::cout << current->GetData() << " ---> " ;
         current = current->GetNext();
     }
     std::cout << " " << std::endl;
 }
References std::endl().
PushBack()
template<class T > void common::LinkedList< T >::PushBack (T value)
{
     auto* node = new ListElement<T>(value);
     node->SetNext(nullptr);
     if (head == nullptr) {
         head = node;
         return;
     }
     ListElement<T> * current = head;
     while (current->GetNext()) {
         current = current->GetNext();
     }
     current->SetNext(node);
 }
References common::ListElement< T >::GetNext(), and common::ListElement< T >::SetNext().
PushFront()
template<class T > void common::LinkedList< T >::PushFront (T value)
{
     auto* node = new ListElement<T>(value);
     node->SetNext(head);
     head = node;
 }
RemoveValue()
template<class T > void common::LinkedList< T >::RemoveValue (T value)
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     ListElement<T>* prev = nullptr;
     auto * current = head;
     while (current) {
         if (current->GetData() == value) {
             if(prev == nullptr) {
                 head = current->GetNext();
             } else {
                 prev->SetNext(current->GetNext());
                 head = prev;
             }
             delete current;
             break;
         }
         prev = current;
         current = current->GetNext();
     }
 }
References std::endl().
Reverse()
template<class T > void common::LinkedList< T >::Reverse
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     ListElement<T>* prev = nullptr;
     auto * current = head;
     ListElement<T>* next = nullptr;
     while (current != nullptr) {
         next = current->GetNext();
         current->SetNext(prev);
         prev = current;
         current = next;
     }
     head = prev;
 }
References std::endl().
Size()
template<class T > int common::LinkedList< T >::Size
{
     int size = 0;
     auto* current = head;
     while (current) {
         current = current->GetNext();
         size ++;
     }
     return size;
 }
ValueAt()
template<class T > const T & common::LinkedList< T >::ValueAt (int index) const
{
     if(head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto * current = head;
     for (int i = 0; i < index && current != nullptr; ++i) {
         current = current->GetNext();
     }
     if(current == nullptr) {
         std::cout << "Index out of bounds" << std::endl;
         exit(EXIT_FAILURE);
     }
     return current->GetData();
 }
References std::endl().
ValueNFromEnd()
template<class T > const T common::LinkedList< T >::ValueNFromEnd (int n)
{
     if( n < 1 || head == nullptr) {
         std::cout << "List is empty" << std::endl;
         exit(EXIT_FAILURE);
     }
     auto * current = head;
     auto * match = head;
     int i;
     for (i = 0; i < n && current != nullptr ; ++i) {
         current = current->GetNext();
     }
     if(i != n) {
         std::cout << "Index out of bounds" << std::endl;
         exit(EXIT_FAILURE);
     }
     while (current) {
         match = match->GetNext();
         current = current->GetNext();
     }
     return match->GetData();
 }
References std::endl().
Member Data Documentation
head
template<class T > ListElement<T>* common::LinkedList< T >::head private
Referenced by common::LinkedList< T >::~LinkedList().