Common Alogrithm: common::HashObject::SetValue
SetValue()
void SetValue (const std::string value)
 { value_ = value;};
References HashObject::value_.
Referenced by HashTable::Add(), HashTable::Remove(), test_add_exists(), test_get(), test_probing(), and test_remove().