Common Alogrithm: testing::Test Class Reference
testing::Test Class Reference abstract
#include <gtest.h>
Classes
struct Setup_should_be_spelled_SetUp
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
Test ()
Package Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test)
virtual Setup_should_be_spelled_SetUp * Setup ()
virtual ~Test ()
Static Package Functions
static bool HasFailure ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
Package Attributes
__pad0__:SetUpTestCaseFunc SetUpTestCaseFunc
__pad1__:TearDownTestCaseFunc TearDownTestCaseFunc
__pad2__:scoped_ptr< GTEST_FLAG_SAVER_ > gtest_flag_saver_
Private Member Functions
void DeleteSelf_ ()
void Run ()
virtual void TestBody ()=0
Static Private Member Functions
static bool HasSameFixtureClass ()
Friends
class TestInfo
Detailed Description
Class Documentation
testing::Test::Setup_should_be_spelled_SetUp
struct testing::Test::Setup_should_be_spelled_SetUp
Constructor & Destructor Documentation
~Test()
testing::Test::~Test () package virtual
             {
 }
Test()
testing::Test::Test () protected
     : gtest_flag_saver_(new GTEST_FLAG_SAVER_) {
 }
Member Function Documentation
DeleteSelf_()
void testing::Test::DeleteSelf_ () private
 { delete this; }
Referenced by testing::TestInfo::Run().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::Test::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test) package
HasFailure()
static bool testing::Test::HasFailure () static package
 { return HasFatalFailure() || HasNonfatalFailure(); }
HasFatalFailure()
bool testing::Test::HasFatalFailure () static package
{
   return internal::GetUnitTestImpl()->current_test_result()->HasFatalFailure();
 }
References testing::internal::UnitTestImpl::current_test_result(), testing::internal::GetUnitTestImpl(), and testing::TestResult::HasFatalFailure().
Referenced by testing::TestInfo::Run(), and testing::internal::UnitTestImpl::RunAllTests().
HasNonfatalFailure()
bool testing::Test::HasNonfatalFailure () static package
{
   return internal::GetUnitTestImpl()->current_test_result()->
       HasNonfatalFailure();
 }
References testing::internal::UnitTestImpl::current_test_result(), and testing::internal::GetUnitTestImpl().
HasSameFixtureClass()
bool testing::Test::HasSameFixtureClass () static private
{
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   const TestCase* const test_case = impl->current_test_case();
   // Info about the first test in the current test case.
   const TestInfo* const first_test_info = test_case->test_info_list()[0];
   const internal::TypeId first_fixture_id = first_test_info->fixture_class_id_;
   const char* const first_test_name = first_test_info->name();
   // Info about the current test.
   const TestInfo* const this_test_info = impl->current_test_info();
   const internal::TypeId this_fixture_id = this_test_info->fixture_class_id_;
   const char* const this_test_name = this_test_info->name();
   if (this_fixture_id != first_fixture_id) {
     // Is the first test defined using TEST?
     const bool first_is_TEST = first_fixture_id == internal::GetTestTypeId();
     // Is this test defined using TEST?
     const bool this_is_TEST = this_fixture_id == internal::GetTestTypeId();
     if (first_is_TEST || this_is_TEST) {
       // Both TEST and TEST_F appear in same test case, which is incorrect.
       // Tell the user how to fix this.
       // Gets the name of the TEST and the name of the TEST_F.  Note
       // that first_is_TEST and this_is_TEST cannot both be true, as
       // the fixture IDs are different for the two tests.
       const char* const TEST_name =
           first_is_TEST ? first_test_name : this_test_name;
       const char* const TEST_F_name =
           first_is_TEST ? this_test_name : first_test_name;
       ADD_FAILURE()
           << "All tests in the same test case must use the same test fixture\n"
           << "class, so mixing TEST_F and TEST in the same test case is\n"
           << "illegal.  In test case " << this_test_info->test_case_name()
           << ",\n"
           << "test " << TEST_F_name << " is defined using TEST_F but\n"
           << "test " << TEST_name << " is defined using TEST.  You probably\n"
           << "want to change the TEST to TEST_F or move it to another test\n"
           << "case.";
     } else {
       // Two fixture classes with the same name appear in two different
       // namespaces, which is not allowed. Tell the user how to fix this.
       ADD_FAILURE()
           << "All tests in the same test case must use the same test fixture\n"
           << "class.  However, in test case "
           << this_test_info->test_case_name() << ",\n"
           << "you defined test " << first_test_name
           << " and test " << this_test_name << "\n"
           << "using two different test fixture classes.  This can happen if\n"
           << "the two classes are from different namespaces or translation\n"
           << "units and have the same name.  You should probably rename one\n"
           << "of the classes to put the tests into different test cases.";
     }
     return false;
   }
   return true;
 }
References ADD_FAILURE, testing::internal::UnitTestImpl::current_test_case(), testing::internal::UnitTestImpl::current_test_info(), testing::internal::GetTestTypeId(), testing::internal::GetUnitTestImpl(), testing::TestInfo::name, testing::TestInfo::test_case_name(), and testing::TestCase::test_info_list().
RecordProperty() [1/2]
void testing::Test::RecordProperty (const std::string & key, const std::string & value) static package
{
   UnitTest::GetInstance()->RecordProperty(key, value);
 }
References testing::UnitTest::GetInstance(), and testing::UnitTest::RecordProperty().
Referenced by RecordProperty().
RecordProperty() [2/2]
void testing::Test::RecordProperty (const std::string & key, int value) static package
{
   Message value_message;
   value_message << value;
   RecordProperty(key, value_message.GetString().c_str());
 }
References std::string::c_str(), testing::Message::GetString(), and RecordProperty().
Run()
void testing::Test::Run () private
                {
   if (!HasSameFixtureClass()) return;
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(this, &Test::SetUp, "SetUp()");
   // We will run the test only if SetUp() was successful.
   if (!HasFatalFailure()) {
     impl->os_stack_trace_getter()->UponLeavingGTest();
     internal::HandleExceptionsInMethodIfSupported(
         this, &Test::TestBody, "the test body");
   }
   // However, we want to clean up as much as possible.  Hence we will
   // always call TearDown(), even if SetUp() or the test body has
   // failed.
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       this, &Test::TearDown, "TearDown()");
 }
References testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), testing::internal::UnitTestImpl::os_stack_trace_getter(), and testing::internal::OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by testing::TestInfo::Run().
SetUp()
void testing::Test::SetUp () protected virtual
                  {
 }
Setup()
virtual Setup_should_be_spelled_SetUp* testing::Test::Setup () package virtual
 { return NULL; }
SetUpTestCase()
static void testing::Test::SetUpTestCase () static package
 {}
TearDown()
void testing::Test::TearDown () protected virtual
                     {
 }
TearDownTestCase()
static void testing::Test::TearDownTestCase () static package
 {}
TestBody()
virtual void testing::Test::TestBody () private pure virtual
Friends And Related Function Documentation
TestInfo
friend class TestInfo friend
Member Data Documentation
__pad0__
testing::Test::__pad0__ package
__pad1__
testing::Test::__pad1__ package
__pad2__
testing::Test::__pad2__ package