Common Alogrithm: design_pattern/adapter_pattern/main.cc File Reference
main.cc File Reference
(d4ab02d08ceed19dab4276c86042b1520529304b)
#include <iostream>
#include <string>
Classes
class Adapter
class ElectricKettle
class EuropeanSocketInterface
class Socket
class USASocketInterface
Typedefs
typedef int Cable
Functions
int main (int argc, char *argv[])
Typedef Documentation
Cable
typedef int Cable
Definition at line 19 of file main.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 95 of file main.cc.
 {
     Socket* socket = new Socket;
     Adapter* adapter = new Adapter;
     ElectricKettle* kettle = new ElectricKettle;
     /* Pluging in. */
     adapter->plugIn(socket);
     kettle->plugIn(adapter);
     /* Having coffee */
     kettle->boil();
     return 0;
 }
References ElectricKettle::boil(), Adapter::plugIn(), and ElectricKettle::plugIn().