Common Alogrithm: main
main()
int main (int argc, char * argv[])
 {
     Socket* socket = new Socket;
     Adapter* adapter = new Adapter;
     ElectricKettle* kettle = new ElectricKettle;
     /* Pluging in. */
     adapter->plugIn(socket);
     kettle->plugIn(adapter);
     /* Having coffee */
     kettle->boil();
     return 0;
 }
References ElectricKettle::boil(), Adapter::plugIn(), and ElectricKettle::plugIn().