Common Alogrithm: test_remove
test_remove()
void test_remove ()
                    {
     common::HashTable states(3);
     common::HashObject tx;
     tx.SetKey("Texas");
     tx.SetValue("Austin");
     states.Add(&tx);
     assert(states.Exists("Texas"));
     states.Remove("Texas");
     assert(!states.Exists("Texas"));
     states.PringDebug();
 }
References HashTable::Add(), HashTable::Exists(), HashTable::PringDebug(), HashTable::Remove(), HashObject::SetKey(), and HashObject::SetValue().
Referenced by run_all_tests().