Common Alogrithm: test_get
test_get()
void test_get ()
                 {
     common::HashTable states(100);
     common::HashObject tx;
     tx.SetKey("Texas");
     tx.SetValue("Austin");
     states.Add(&tx);
     assert(states.Get("Texas") == "Austin");
 }
References HashTable::Add(), HashTable::Get(), HashObject::SetKey(), and HashObject::SetValue().
Referenced by run_all_tests().