Common Alogrithm: Microsoft_interview/main.cc File Reference
main.cc File Reference
#include <iostream>
#include <memory>
#include "./exam.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 5 of file main.cc.
 {
     Exam exam;
     exam.Debug();
     // Interview
     std::cout << "Manager: "<< exam.ReportManager("Alice") << std::endl;
     exam.ReportCommonManager("Alice", "Bob");
     // Practice smart pointer unique_ptr
     exam.SmartPointer();
     exam.SmartPointerMakeUnique();
     exam.SmartPointerSharedPtr();
     exam.SmartPointerWeakPtr();
 }
References Exam::Debug(), std::endl(), Exam::ReportCommonManager(), Exam::ReportManager(), Exam::SmartPointer(), Exam::SmartPointerMakeUnique(), Exam::SmartPointerSharedPtr(), and Exam::SmartPointerWeakPtr().