Common Alogrithm: ScopedFakeTestPartResultReporter Class Reference
ScopedFakeTestPartResultReporter Class Reference
#include <gtest-spi.h>
Public Types
enum InterceptMode { INTERCEPT_ONLY_CURRENT_THREAD , INTERCEPT_ALL_THREADS }
Public Member Functions
virtual void ReportTestPartResult (const TestPartResult &result)
ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray *result)
ScopedFakeTestPartResultReporter (TestPartResultArray *result)
virtual ~ScopedFakeTestPartResultReporter ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter)
void Init ()
Private Attributes
const InterceptMode intercept_mode_
TestPartResultReporterInterface * old_reporter_
TestPartResultArray *const result_
Detailed Description
Definition at line 51 of file gtest-spi.h.
Member Enumeration Documentation
InterceptMode
enum InterceptMode
Enumerator
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
Definition at line 55 of file gtest-spi.h.
                      {
     INTERCEPT_ONLY_CURRENT_THREAD,  // Intercepts only thread local failures.
     INTERCEPT_ALL_THREADS           // Intercepts all failures.
   };
Constructor & Destructor Documentation
ScopedFakeTestPartResultReporter() [1/2]
ScopedFakeTestPartResultReporter (TestPartResultArray * result) explicit
Definition at line 563 of file gtest.cc.
     : intercept_mode_(INTERCEPT_ONLY_CURRENT_THREAD),
       result_(result) {
   Init();
 }
References ScopedFakeTestPartResultReporter::Init().
ScopedFakeTestPartResultReporter() [2/2]
ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray * result)
Definition at line 573 of file gtest.cc.
     : intercept_mode_(intercept_mode),
       result_(result) {
   Init();
 }
References ScopedFakeTestPartResultReporter::Init().
~ScopedFakeTestPartResultReporter()
~ScopedFakeTestPartResultReporter () virtual
Definition at line 593 of file gtest.cc.
{
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   if (intercept_mode_ == INTERCEPT_ALL_THREADS) {
     impl->SetGlobalTestPartResultReporter(old_reporter_);
   } else {
     impl->SetTestPartResultReporterForCurrentThread(old_reporter_);
   }
 }
References testing::internal::GetUnitTestImpl(), ScopedFakeTestPartResultReporter::INTERCEPT_ALL_THREADS, ScopedFakeTestPartResultReporter::intercept_mode_, ScopedFakeTestPartResultReporter::old_reporter_, UnitTestImpl::SetGlobalTestPartResultReporter(), and UnitTestImpl::SetTestPartResultReporterForCurrentThread().
Member Function Documentation
GTEST_DISALLOW_COPY_AND_ASSIGN_()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter) private
Init()
void Init () private
Definition at line 580 of file gtest.cc.
{
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   if (intercept_mode_ == INTERCEPT_ALL_THREADS) {
     old_reporter_ = impl->GetGlobalTestPartResultReporter();
     impl->SetGlobalTestPartResultReporter(this);
   } else {
     old_reporter_ = impl->GetTestPartResultReporterForCurrentThread();
     impl->SetTestPartResultReporterForCurrentThread(this);
   }
 }
References UnitTestImpl::GetGlobalTestPartResultReporter(), UnitTestImpl::GetTestPartResultReporterForCurrentThread(), testing::internal::GetUnitTestImpl(), ScopedFakeTestPartResultReporter::INTERCEPT_ALL_THREADS, ScopedFakeTestPartResultReporter::intercept_mode_, ScopedFakeTestPartResultReporter::old_reporter_, UnitTestImpl::SetGlobalTestPartResultReporter(), and UnitTestImpl::SetTestPartResultReporterForCurrentThread().
Referenced by ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter().
ReportTestPartResult()
void ReportTestPartResult (const TestPartResult & result) virtual
Implements TestPartResultReporterInterface.
Definition at line 604 of file gtest.cc.
{
   result_->Append(result);
 }
References TestPartResultArray::Append(), and ScopedFakeTestPartResultReporter::result_.
Member Data Documentation
intercept_mode_
const InterceptMode intercept_mode_ private
Definition at line 82 of file gtest-spi.h.
Referenced by ScopedFakeTestPartResultReporter::Init(), and ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().
old_reporter_
TestPartResultReporterInterface* old_reporter_ private
Definition at line 83 of file gtest-spi.h.
Referenced by ScopedFakeTestPartResultReporter::Init(), and ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().
result_
TestPartResultArray* const result_ private
Definition at line 84 of file gtest-spi.h.
Referenced by ScopedFakeTestPartResultReporter::ReportTestPartResult().