Common Alogrithm: TestResult Class Reference
TestResult Class Reference
#include <gtest.h>
Public Member Functions
TimeInMillis elapsed_time () const
bool Failed () const
const TestPartResult & GetTestPartResult (int i) const
const TestProperty & GetTestProperty (int i) const
bool HasFatalFailure () const
bool HasNonfatalFailure () const
bool Passed () const
int test_property_count () const
TestResult ()
int total_part_count () const
~TestResult ()
Private Member Functions
void AddTestPartResult (const TestPartResult &test_part_result)
void Clear ()
void ClearTestPartResults ()
int death_test_count () const
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult)
int increment_death_test_count ()
void RecordProperty (const std::string &xml_element, const TestProperty &test_property)
void set_elapsed_time (TimeInMillis elapsed)
const std::vector< TestPartResult > & test_part_results () const
const std::vector< TestProperty > & test_properties () const
Static Private Member Functions
static bool ValidateTestProperty (const std::string &xml_element, const TestProperty &test_property)
Private Attributes
int death_test_count_
TimeInMillis elapsed_time_
std::vector< TestPartResult > test_part_results_
internal::Mutex test_properites_mutex_
std::vector< TestProperty > test_properties_
Friends
class internal::DefaultGlobalTestPartResultReporter
class internal::ExecDeathTest
class internal::TestResultAccessor
class internal::UnitTestImpl
class internal::WindowsDeathTest
class TestCase
class TestInfo
class UnitTest
Detailed Description
Definition at line 523 of file gtest.h.
Constructor & Destructor Documentation
TestResult()
TestResult ()
Definition at line 2017 of file gtest.cc.
     : death_test_count_(0),
       elapsed_time_(0) {
 }
~TestResult()
~TestResult ()
Definition at line 2023 of file gtest.cc.
{
 }
Member Function Documentation
AddTestPartResult()
void AddTestPartResult (const TestPartResult & test_part_result) private
Definition at line 2050 of file gtest.cc.
{
   test_part_results_.push_back(test_part_result);
 }
References TestResult::test_part_results_.
Referenced by DefaultGlobalTestPartResultReporter::ReportTestPartResult().
Clear()
void Clear () private
Definition at line 2162 of file gtest.cc.
{
   test_part_results_.clear();
   test_properties_.clear();
   death_test_count_ = 0;
   elapsed_time_ = 0;
 }
References TestResult::death_test_count_, TestResult::elapsed_time_, TestResult::test_part_results_, and TestResult::test_properties_.
Referenced by TestCase::ClearResult(), and TestInfo::ClearTestResult().
ClearTestPartResults()
void ClearTestPartResults () private
Definition at line 2045 of file gtest.cc.
{
   test_part_results_.clear();
 }
References TestResult::test_part_results_.
Referenced by TestResultAccessor::ClearTestPartResults().
death_test_count()
int death_test_count () const private
Definition at line 605 of file gtest.h.
 { return death_test_count_; }
elapsed_time()
TimeInMillis elapsed_time () const
Definition at line 551 of file gtest.h.
 { return elapsed_time_; }
Referenced by PrettyUnitTestResultPrinter::OnTestEnd(), and XmlUnitTestResultPrinter::OutputXmlTestInfo().
Failed()
bool Failed () const
Definition at line 2170 of file gtest.cc.
{
   for (int i = 0; i < total_part_count(); ++i) {
     if (GetTestPartResult(i).failed())
       return true;
   }
   return false;
 }
References TestPartResult::failed(), TestResult::GetTestPartResult(), and TestResult::total_part_count().
Referenced by PrettyUnitTestResultPrinter::OnTestEnd(), and TestCase::TestFailed().
GetTestPartResult()
const TestPartResult & GetTestPartResult (int i) const
Definition at line 2029 of file gtest.cc.
{
   if (i < 0 || i >= total_part_count())
     internal::posix::Abort();
   return test_part_results_.at(i);
 }
References TestResult::test_part_results_, and TestResult::total_part_count().
Referenced by TestResult::Failed(), and XmlUnitTestResultPrinter::OutputXmlTestInfo().
GetTestProperty()
const TestProperty & GetTestProperty (int i) const
Definition at line 2038 of file gtest.cc.
{
   if (i < 0 || i >= test_property_count())
     internal::posix::Abort();
   return test_properties_.at(i);
 }
References TestResult::test_properties_, and TestResult::test_property_count().
Referenced by XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult) private
HasFatalFailure()
bool HasFatalFailure () const
Definition at line 2184 of file gtest.cc.
{
   return CountIf(test_part_results_, TestPartFatallyFailed) > 0;
 }
References testing::internal::CountIf(), TestResult::test_part_results_, and testing::TestPartFatallyFailed().
Referenced by Test::HasFatalFailure().
HasNonfatalFailure()
bool HasNonfatalFailure () const
Definition at line 2194 of file gtest.cc.
{
   return CountIf(test_part_results_, TestPartNonfatallyFailed) > 0;
 }
References testing::internal::CountIf(), TestResult::test_part_results_, and testing::TestPartNonfatallyFailed().
increment_death_test_count()
int increment_death_test_count () private
Definition at line 608 of file gtest.h.
 { return ++death_test_count_; }
Passed()
bool Passed () const
Definition at line 539 of file gtest.h.
 { return !Failed(); }
Referenced by PrettyUnitTestResultPrinter::OnTestEnd(), PrettyUnitTestResultPrinter::PrintFailedTests(), and TestCase::TestPassed().
RecordProperty()
void RecordProperty (const std::string & xml_element, const TestProperty & test_property) private
Definition at line 2057 of file gtest.cc.
{
   if (!ValidateTestProperty(xml_element, test_property)) {
     return;
   }
   internal::MutexLock lock(&test_properites_mutex_);
   const std::vector<TestProperty>::iterator property_with_matching_key =
       std::find_if(test_properties_.begin(), test_properties_.end(),
                    internal::TestPropertyKeyIs(test_property.key()));
   if (property_with_matching_key == test_properties_.end()) {
     test_properties_.push_back(test_property);
     return;
   }
   property_with_matching_key->SetValue(test_property.value());
 }
References std::find_if(), TestProperty::key(), TestResult::test_properites_mutex_, TestResult::test_properties_, TestResult::ValidateTestProperty(), and TestProperty::value().
Referenced by UnitTestImpl::RecordProperty(), and TestResultAccessor::RecordProperty().
set_elapsed_time()
void set_elapsed_time (TimeInMillis elapsed) private
Definition at line 584 of file gtest.h.
 { elapsed_time_ = elapsed; }
Referenced by TestInfo::Run().
test_part_results()
const std::vector<TestPartResult>& test_part_results () const private
Definition at line 574 of file gtest.h.
{
     return test_part_results_;
   }
Referenced by TestResultAccessor::test_part_results().
test_properties()
const std::vector<TestProperty>& test_properties () const private
Definition at line 579 of file gtest.h.
{
     return test_properties_;
   }
test_property_count()
int test_property_count () const
Definition at line 2205 of file gtest.cc.
{
   return static_cast<int>(test_properties_.size());
 }
References TestResult::test_properties_.
Referenced by TestResult::GetTestProperty(), and XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
total_part_count()
int total_part_count () const
Definition at line 2200 of file gtest.cc.
{
   return static_cast<int>(test_part_results_.size());
 }
References TestResult::test_part_results_.
Referenced by TestResult::Failed(), TestResult::GetTestPartResult(), and XmlUnitTestResultPrinter::OutputXmlTestInfo().
ValidateTestProperty()
bool ValidateTestProperty (const std::string & xml_element, const TestProperty & test_property) static private
Definition at line 2155 of file gtest.cc.
{
   return ValidateTestPropertyName(test_property.key(),
                                   GetReservedAttributesForElement(xml_element));
 }
References testing::GetReservedAttributesForElement(), TestProperty::key(), and testing::ValidateTestPropertyName().
Referenced by TestResult::RecordProperty().
Friends And Related Function Documentation
internal::DefaultGlobalTestPartResultReporter
friend class internal::DefaultGlobalTestPartResultReporter friend
Definition at line 567 of file gtest.h.
internal::ExecDeathTest
friend class internal::ExecDeathTest friend
Definition at line 568 of file gtest.h.
internal::TestResultAccessor
friend class internal::TestResultAccessor friend
Definition at line 569 of file gtest.h.
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
Definition at line 570 of file gtest.h.
internal::WindowsDeathTest
friend class internal::WindowsDeathTest friend
Definition at line 571 of file gtest.h.
TestCase
friend class TestCase friend
Definition at line 565 of file gtest.h.
TestInfo
friend class TestInfo friend
Definition at line 564 of file gtest.h.
UnitTest
friend class UnitTest friend
Definition at line 566 of file gtest.h.
Member Data Documentation
death_test_count_
int death_test_count_ private
Definition at line 625 of file gtest.h.
Referenced by TestResult::Clear().
elapsed_time_
TimeInMillis elapsed_time_ private
Definition at line 627 of file gtest.h.
Referenced by TestResult::Clear().
test_part_results_
std::vector<TestPartResult> test_part_results_ private
Definition at line 621 of file gtest.h.
Referenced by TestResult::AddTestPartResult(), TestResult::Clear(), TestResult::ClearTestPartResults(), TestResult::GetTestPartResult(), TestResult::HasFatalFailure(), TestResult::HasNonfatalFailure(), and TestResult::total_part_count().
test_properites_mutex_
internal::Mutex test_properites_mutex_ private
Definition at line 618 of file gtest.h.
Referenced by TestResult::RecordProperty().
test_properties_
std::vector<TestProperty> test_properties_ private
Definition at line 623 of file gtest.h.
Referenced by TestResult::Clear(), TestResult::GetTestProperty(), TestResult::RecordProperty(), and TestResult::test_property_count().