Common Alogrithm: Message Class Reference
Message Class Reference
#include <gtest-message.h>
Public Member Functions
std::string GetString () const
Message ()
Message (const char *str)
Message (const Message &msg)
Message & operator<< (BasicNarrowIoManip val)
Message & operator<< (bool b)
template<typename T >
Message & operator<< (const T &val)
Message & operator<< (const wchar_t *wide_c_str)
template<typename T >
Message & operator<< (T *const &pointer)
Message & operator<< (wchar_t *wide_c_str)
Package Functions
void operator= (const Message &)
Package Attributes
__pad0__:scoped_ptr< ::std::stringstream> ss_
Private Types
typedef std::ostream &(* BasicNarrowIoManip) (std::ostream &)
Detailed Description
Definition at line 85 of file gtest-message.h.
Member Typedef Documentation
BasicNarrowIoManip
typedef std::ostream&(* BasicNarrowIoManip) (std::ostream &) private
Definition at line 89 of file gtest-message.h.
Constructor & Destructor Documentation
Message() [1/3]
Message ()
Definition at line 946 of file gtest.cc.
                  : ss_(new ::std::stringstream) {
   // By default, we want there to be enough precision when printing
   // a double to a Message.
   *ss_ << std::setprecision(std::numeric_limits<double>::digits10 + 2);
 }
References std::setprecision().
Message() [2/3]
Message (const Message & msg)
Definition at line 96 of file gtest-message.h.
                               : ss_(new ::std::stringstream) {  // NOLINT
     *ss_ << msg.GetString();
   }
References Message::GetString().
Message() [3/3]
Message (const char * str) explicit
Definition at line 101 of file gtest-message.h.
                                     : ss_(new ::std::stringstream) {
     *ss_ << str;
   }
Member Function Documentation
GetString()
std::string GetString () const
Definition at line 981 of file gtest.cc.
{
   return internal::StringStreamToString(ss_.get());
 }
References testing::internal::StringStreamToString().
Referenced by UnitTest::AddTestPartResult(), AssertionResult::AppendMessage(), testing::internal::AppendUserMessage(), XmlUnitTestResultPrinter::EscapeXml(), testing::internal::FlagToEnvVar(), testing::FormatWordList(), testing::internal::GetBoolAssertionFailureMessage(), Message::Message(), testing::operator<<(), testing::internal::ParseInt32(), Test::RecordProperty(), testing::internal::ShouldShard(), and XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
operator<<() [1/6]
Message& operator<< (BasicNarrowIoManip val)
Definition at line 165 of file gtest-message.h.
{
     *ss_ << val;
     return *this;
   }
operator<<() [2/6]
Message& operator<< (bool b)
Definition at line 171 of file gtest-message.h.
{
     return *this << (b ? "true" : "false");
   }
operator<<() [3/6]
Message& operator<< (const T & val)
Definition at line 115 of file gtest-message.h.
{
     // Some libraries overload << for STL containers.  These
     // overloads are defined in the global namespace instead of ::std.
     //
     // C++'s symbol lookup rule (i.e. Koenig lookup) says that these
     // overloads are visible in either the std namespace or the global
     // namespace, but not other namespaces, including the testing
     // namespace which Google Test's Message class is in.
     //
     // To allow STL containers (and other types that has a << operator
     // defined in the global namespace) to be used in Google Test
     // assertions, testing::Message must access the custom << operator
     // from the global namespace.  With this using declaration,
     // overloads of << defined in the global namespace and those
     // visible via Koenig lookup are both exposed in this function.
     using ::operator <<;
     *ss_ << val;
     return *this;
   }
operator<<() [4/6]
Message & operator<< (const wchar_t * wide_c_str)
Definition at line 954 of file gtest.cc.
{
   return *this << internal::String::ShowWideCString(wide_c_str);
 }
References String::ShowWideCString().
operator<<() [5/6]
Message& operator<< (T *const & pointer)
Definition at line 149 of file gtest-message.h.
                                                  {  // NOLINT
     if (pointer == NULL) {
       *ss_ << "(null)";
     } else {
       *ss_ << pointer;
     }
     return *this;
   }
operator<<() [6/6]
Message & operator<< (wchar_t * wide_c_str)
Definition at line 957 of file gtest.cc.
{
   return *this << internal::String::ShowWideCString(wide_c_str);
 }
References String::ShowWideCString().
operator=()
void operator= (const Message &) package
Member Data Documentation
__pad0__
__pad0__ package
Definition at line 224 of file gtest-message.h.